ui/CHANGELOG.md
ui/js/component/file-actions.js
ui/js/component/file-tile.js
ui/js/jsonrpc.js
ui/js/lbry.js
ui/js/lighthouse.js
ui/js/main.js
ui/js/page/discover.js
ui/js/page/file-list.js
ui/js/page/show.js
ui/js/page/watch.js

- Refactoring throughout JSON-RPC, lbrynet and Lighthouse logic
- Move JSON-RPC stuff into its own module
- Add ability to directly call API methods on the lbry and lighthouse modules, e.g. `lbry.file_list({name: 'what'})`
- New-style API calls use promises instead of callbacks.
- Converted some lbrynet calls and all Lighthouse calls to use the new style

Revamp API wrapper code

---

app/menu/context-menu.js
ui/js/component/drawer.js
ui/js/main.js

Has Cut, Copy, Paste, and when in developer mode there's also Inspect Element
Also adds Command-Shift-Click as an alternative shortcut to get to Developer Settings, now that Ctrl-Shift is used for context menu on Mac

Add context menu

---

app/main.js
ui/CHANGELOG.md
ui/dist/upgrade.html
ui/js/app.js
ui/js/component/modal.js
ui/js/page/developer.js

- Now asks the daemon to close, even if it wasn't started by the same app
- Improved UX during upgrade process (cancel buttons, final dialog where you approve the update, etc.)
- Saves updates in temp directory, closes app and launches the installer
Todo (none of these are blocking merge):
- Force kill the existing daemon if it doesn't stop
- Improve visuals
- Don't upgrade to RCs

Real update system

---

CHANGELOG.md
app/main.js
ui/js/app.js
ui/js/component/drawer.js
ui/js/component/file-actions.js
ui/js/component/file-tile.js
ui/js/lbry.js
ui/js/page/file-list.js
ui/js/page/help.js
ui/js/page/show.js
ui/js/page/wallet.js
ui/scss/component/_load-screen.scss

This started as simply wanting to catch click events and re-draw the app inside of app.js without a full reload of index.html and all assets. However, it turned out to require adding a subscription feature for balances and fixing a few other areas where we were not unsubscribing/unmounting properly.

make page changes fast

---

CHANGELOG.md
app/main.js
ui/js/app.js
ui/js/component/drawer.js
ui/js/component/file-actions.js
ui/js/component/file-tile.js
ui/js/lbry.js
ui/js/page/file-list.js
ui/js/page/help.js
ui/js/page/show.js
ui/js/page/wallet.js
ui/js/utils.js
ui/scss/component/_load-screen.scss

Uses a client side cache to simulate entries in the file manager and  claims list.
Also adds new utility functions for using Local Storage.

Make publishes appear immediately in My Files

---

README.md

Someone seems to have forgotten a dot in the URL.

Fix .appveyor.yml link in README.md

---

ui/js/page/wallet.js

wallet.js did not compile with .bind after the lambda function, and after talking in #dev in Gitter we came to the conclusion to just remove the bind as it's not necessary

Removed .bind() from lambda

---

app/main.js

In #30 we're still getting some reports of an error box after LBRY is closed. I suspect that's just because some people are running 0.9.x and the problem went away in 0.10.0. But this bug could cause a similar looking error in certain edge cases (user closes window before upgrade check finishes, or the upgrade connection gets stuck open somehow and only ends when LBRY is closing).

Don't try to send version info to render process if window isn't open

---

CHANGELOG.md
ui/js/app.js
ui/js/component/modal.js

Was not passing in the generic modal-overlay class. (ExpandableModal doesn't provide it automatically so you can omit it and make a totally custom overlay if you want.)

Make error modals display full screen properly

---

app/main.js
package.json
ui/js/app.js
ui/js/main.js

Implements opening LBRY URIs using Electron's built-in support.
Electron only has very basic support for this: on Mac it works well, but on Windows it can only pass the URI in as a command line argument (i.e. you can't launch URIs in an app that's already running), and there's no Linux support at all yet.
I'm thinking we'd be best off to use the built-in functionality like this, and then eventually hack on improvements for Win and Linux. [Here are some ideas](https://github.com/electron/electron/issues/4857#issuecomment-201124281) about how to do it in Linux.

URI handling (WIP)

---

ui/js/actions/content.js
ui/js/component/fileTile/index.js
ui/js/component/fileTile/view.jsx
ui/js/component/fileTileStream/view.jsx
ui/js/page/search/view.jsx

Fixes exact search matching and search results HTML @kauffj.
I have no idea why default thumbnails aren't resolving any more or when that stopped working :(
I think in order for this to be mergable to master we need to:
- fix default thumbnails
- store file info in the state by `sd_hash` rather than URI and then fix the downloaded/published pages (right now published appear in downloaded after you loaded both and it starts throwing errors)
- do a test run to make sure rewards is still working
We'd need to then lookup files by first selecting the claim for a URI, then running a selector that iterates all files in the state and grabs the one with the matching outpoint. It seems to make sense to store files by `sd_hash` though, as claim and outpoint can sometimes be `null`, in the case of …

Make FileTile resolve URIs (fixes exact search matching)

---

package.json

Still left to do: get single-instance app mode working on Linux.
In theory, it should work the same as Windows without any changes. The problem is that `app.makeSingleInstance()` is always returning true on Linux, meaning "this is the not the original process and the app should close." Probably an Electron bug, but there might be a workaround, and the worst case is that we implement a similar system from scratch.

Linux URI handling (WIP)

---

CHANGELOG.md
ui/js/component/file-selector.js
ui/js/component/form.js
ui/js/page/developer.js
ui/js/page/settings.js
ui/scss/all.scss
ui/scss/component/_file-selector.scss

This will make it much easier to customize look and feel, and allows extra features like pre-populating with an existing file. This also updates the Settings page to use the new directory selector.

Convert file fields to use native Electron dialog + add directory selector field

---

package.json

#122 was merged into the original URIs branch instead of master.

Linux URI handling (again)

---

ui/webpack.config.js

So we don't have redux logs in releases.

set ENV to production webpack.config.js

---

app/main.js
ui/js/actions/app.js
ui/js/reducers/app.js
ui/js/selectors/app.js

Fixes several recent problems with upgrades:
- After the Redux refactor, we ended up opening the directory instead of the file
- The file names changed on Windows and Mac but the source code wasn't updated (we didn't catch it because we were just opening the folder anyway)
- On Windows, we weren't spawning the installer inside a shell, so it couldn't show the "this app wants elevated permissions" box and the `child_process.spawn()` call was silently throwing an error. Beats me why it worked before.

Upgrades fixes

---

ui/js/actions/app.js
ui/js/actions/content.js
ui/js/component/fileActions/index.js
ui/js/component/fileActions/view.jsx
ui/js/component/video/index.js
ui/js/component/video/view.jsx
ui/js/lbry.js
ui/js/page/filePage/view.jsx

A couple of things in this PR @kauffj 
Small tweaks:
- Scroll to the top of the page when changing path. This was really irritating me.
- Syncing up the loading status between the file actions and the video player. Can't click download on file actions when you're already loading from player and vice versa.
Big change:
- Use render-media to also render images and audio files (should also be able to do documents at some point too). I think it might be cool to rename all the `Video` stuff to `Media` soon too.
Images have a folder icon which renders on click. Audio renders an HTML5 audio tag below the thumbnail image. Not all audio types are seekable.
Perhaps we could render a waveform style player instead later on, and maybe an audio visualization instead of the thumbnail.
I think it would …

Play more file types

---

app/main.js

request() didn't hit the callback sometimes
fixes #19
fixes #188
Timeout is currently set to 1000 ms, please choose an optimal number

Add timeout for jayson client requests

---

ui/js/component/video/view.jsx
ui/js/page/filePage/view.jsx
ui/scss/page/_show.scss

I've added all the other types that `render-media` can play @kauffj.
It renders documents into an iframe. This could be a security vulnerability. I tried adding some HTML with JS and couldn't get anything to run, but looking at the `render-media` source, it seems that it does allow scripts somehow https://github.com/feross/render-media/blob/master/index.js#L282.

Render all file types that render-media can handle

---

ui/js/component/walletSend/view.jsx

This commit fixes the missing _ in one of the y18n translation labels.
fixes #198

Quick fix for Issue #198 , not being able to go to SEND/RECEIVE page

---

app/package-lock.json
package-lock.json
package.json
ui/package-lock.json

Just upgrade to NPM 5 and it now generates these `package-lock` files. I think that's backwards compatible. Would be good if someone with a lower NPM version could double check. If not I'll try downgrading my local version in 8-10 hours.

Some package tweaks for npm 5x

---

ui/js/page/help/view.jsx

This commit fixes the version in the help page.
Before it displayed the last remote version, now it displays the "localVersion".

Fixed the local version in help

---

ui/js/component/video/internal/loading-screen.jsx
ui/js/component/video/internal/play-button.jsx
ui/js/component/video/internal/player.jsx
ui/js/component/video/view.jsx
ui/scss/component/_video.scss

The goal of this is to add a slightly better-looking video player loading screen and set a folder tree structure for internal components. In this PR I have created a folder called `internal` inside of the `video` component folder. Currently, the components are separated by name into folders, but they only have a single `.jsx` file for the main component, as well as any other internal components needed to build the main component.
This leads to huge React files with many components which can make it hard to follow the component tree. I think we should set a style now and try to adhere to it as components grow.
The structure added in this PR is:
```
component/
...
video/
internal/
some-internal-comp.jsx // some component that is imported by view.jsx
view.jsx // the base component
index.js …
```

Update video player loading screen

---

CHANGELOG.md
app/menu/main-menu.js
ui/js/main.js

fixing issue of Help menu force reloading the app.
- use ipcRenderer as bridge for communication between electron and ui app
- add changelog
reference: 
- issue https://github.com/lbryio/lbry-app/issues/226

Fix loading help menu

---

ui/js/actions/file_info.js
ui/js/component/fileList/view.jsx
ui/js/component/fileTile/view.jsx
ui/js/lbry.js
ui/js/page/fileListDownloaded/view.jsx
ui/js/page/fileListPublished/view.jsx

This fixes published files not appearing until restart
- Always refresh the claim list when loading published/downloaded pages.
- Remove caching happening inside of `lbry.js` (this is what stops the URI ever being solved again until restart)

Always refresh claims/file info on downloaded/published pages

---

ui/js/component/file-selector.js

For https://github.com/lbryio/lbry-app/issues/234
Add `createDirectory` property to the `showOpenDialog` call

allow user to create new directory when choosing download directory

---

ui/js/actions/app.js
ui/js/page/settings/index.js
ui/js/page/settings/view.jsx
ui/js/store.js

In anticipation of caching problems. Not sure if there's a nicer way to reload. We need to do a full page load though, otherwise the store will just get synced back into the cache again and nothing will have changed.

Add a way for users to clear their own cache

---

ui/js/actions/app.js

We were loading the Discover page at the end of the launch screen. That meant that if a user started with LBRY closed and started it by clicking on a lbry:// link, it would load during the launch screen but then get overridden by the Discover page as soon as the launch screen finished.
Fortunately, this load was redundant anyway as the necessary state is already being set in the default state for the App component:
https://github.com/lbryio/lbry-app/blob/902fb96878c175d480be9ed11207a21bedd61713/ui/js/reducers/app.js#L7

Make URLs load correctly after clicking a lbry:// link with the app closed

---

ui/js/component/fileList/view.jsx

Not sure if this is what is required here? Added the claim ID to the URIs in file lists. This way, when you click through to the show page, the URI in the wunderbar is now the full version which can be copied and distributed.

Add claim ids to urls in downloaded/published files

---

ui/js/component/transactionList/view.jsx

Looks like URLs changed slightly with the new block explorer.

Fix links from transactions to block explorer

---

ui/js/actions/app.js

Without this the app does a full refresh sometimes when you keep clicking back.

Don't call history.back when there is no previous history

---

ui/js/main.js

Currently the app blows up if the window isn't focused as it loads or during a refresh. Also, old focused listeners are left around and pollute the logs with errors.

Teardown old window event listeners and don't blow up when window isn't focused

---

ui/js/component/video/internal/player.jsx

This hides the menu when a video enters full screen mode on Windows. I added the win32 platform check in the `webkitfullscreenchange` event handler since I was unable to reproduce the issue on Linux (Ubuntu 16.04), so I assumed it's probably Windows-specific.

Issue #308 hide menu in fullscreen mode on Windows

---

ui/js/component/video/view.jsx

Fix for switching between audio and video media types after playback has started.
I had to set the state's `isPlaying` property directly in the `componentWillReceiveProps` method, since I tried to make use of `setState` which resulted in a no-op error: `Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.`

Issue #333 media switch fix

---

ui/js/page/filePage/index.js

The download cards in page were not obscured when opening a link
directly(e.g. lbry://jacki2).

A quick fix for oscuring cards for nsfw content.

---

CHANGELOG.md
ui/js/actions/content.js
ui/js/actions/file_info.js
ui/js/component/modalRemoveFile/index.js
ui/js/reducers/file_info.js
ui/js/selectors/file_info.js

Now we have one unique place to track downloading files, instead of by URI. This fixes files in the downloaded file list not showing download progress along with some other downloading weirdness.

Track downloading files by outpoint

---

CHANGELOG.md
ui/js/component/fileActions/view.jsx

Seems to be a problem where some files start to download but never receive any data. Then the "open" link appears when viewing them after the app has been restarted. This switches it to display the download link still.

Display the download button for files that are not downloading and have 0 progress

---

CHANGELOG.md
ui/js/actions/content.js
ui/js/component/fileActions/index.js
ui/js/component/fileActions/view.jsx

A better download fix. Now the app will start monitoring downloads again between restarts.

Restart download monitoring in redux for pending downloads after restart

---

ui/js/page/settings/view.jsx

Currently reloading the settings page blows up the app trying to access `daemonSettings.max_key_fee.amount` before the settings have been loaded.

Settings fix

---

ui/js/component/fileActions/view.jsx

Will move restart download to callback after file_list when I get some more time.

Quick fix to stop an infinite loop

---

ui/scss/component/_modal.scss

@kauffj `word-break: break-word` is Webkit-specific which gracefully handles long overflowing text and doesn't split regular words in the middle like `break-all` does. You can refer to https://miketaylr.com/posts/2014/01/word-break-break-word.html for more details about this property.

Issue #255 purchase confirmation dialog css fix

---

ui/scss/component/_card.scss

Replaced translate3d with translateX in CSS since the cards only need to shift on the x-axis (horizontally). More details at https://stackoverflow.com/questions/8024061/webkit-blurry-text-with-css-scale-translate3d.

Fix for blurry text and image on hover

---

ui/scss/component/_video.scss

The real problem is not the alignment but the the width of the `video` element. 
~Since it's using a container there is no need for `position: absolute`,~
setting the width to `100% `  should do the trick :smile: 
Fix: https://github.com/lbryio/lbry-app/issues/419
Prevent regression:  #295

Fix video width

---

ui/js/page/channel/view.jsx
ui/scss/component/_pagination.scss

> Pagination in channels is not displaying properly at the bottom of the page. Also, should we have this at the top of the page as well? Just a thought.
Fix for https://github.com/lbryio/lbry-app/issues/416

Fix pagination break

---

app/package.json
build/DAEMON_URL
build/build.ps1
build/build.sh
build/release.py

Now both the daemon URL template and the daemon version are stored in `app/package.json`. Also fixes a couple of places that were still using the old `DAEMON_URL` file.

Fix build and release system to store all daemon version settings in app/package.json

---

.bumpversion.cfg

Before, it was matching *any* instance of the current app version string, so if the daemon version configured in app/package.json happened to match the app version, it would get bumped.
This updates the bumpversion config to only update the line containing the package version itself.

Configure bumpversion to avoid modifying daemon version in package.json

---

ui/js/reducers/claims.js

It should fix all of #384 as it was being caused by the function taking the last claim info, if there were many with the same claim id, now it only takes the claims into accounts(not supports or channels).

Fix for broken published links in published tab

---

CHANGELOG.md
ui/js/component/fileList/view.jsx

FIx for #460. Now the channel's claim_id is appended in after the channel_name in the URI.

Return proper URI when channel name is present.

---

CHANGELOG.md
ui/js/component/fileList/view.jsx

This is a temporary fix, but I think the daemon should return consistent result whether it be `file_list` or `claim_list_mine`.

Fixed regression in #501

---

ui/js/actions/settings.js
ui/js/app.js

In the internationalization code it is assumed that the app directory is in the current working directory.
This causes problems when the current working directory is not where it is expected. Before some of the internationalization code was temporarily disabled (a return was inserted at the begging of the doDownloadLanguages function), on startup it would get stuck and display a pure cyan screen. In the background it would start the daemon and everything, but it would not display anything but the cyan background. This was reported by me in #516.
This PR proposes that instead of assuming that the app folder for the application is in our current working directory, we grab the path of the app folder directly from Electron itself. We grab this directory by using Electron's remote module, …

Get the app directory via an absolute path instead of a relative one.

---

ui/js/component/form.js
ui/js/component/inviteNew/view.jsx
ui/js/component/publishForm/view.jsx
ui/js/component/userEmailNew/view.jsx
ui/js/component/userEmailVerify/view.jsx
ui/js/component/walletSend/view.jsx
ui/scss/_gui.scss
ui/scss/component/_button.scss

> If you try to use the Enter key to send credits on the Send screen or send an invite on the Invites screen, the page reloads and nothing happens
- Implement form component.
- Implement submit component.
- Fix weird behavior in wallet send.
- Prevent refresh on enter key.
- Submit form on enter key in `Send`, and `Invite` page.

Form component

---

README.md

-add step to download git for Windows
-I had to manually extract the last SDK to install on Windows 10
-add step to build windows-build-tools, otherwise it fails on keytar install
-fix xcopy  - /E includes directories
-fix syntax to run app

update windows build instructions

---

ui/js/page/rewards/view.jsx

This message appears when a user's account is manually disabled (rewards abuse, etc).  We don't reach out to them via email, so we should ask them to reach out if they are actually legitimate users.

update disabled reward text

---

ui/js/page/rewards/view.jsx

Change failed message to: "There are no rewards available at this time, please check back later."
This scenario happens when all rewards are claimed. Not sure if it can be encountered any other time.

change message if all rewards redeemed

---

ui/js/component/app/view.jsx

> Home page menu bar shows index.html.  
If no title is set, it would always show the current file path (`./index.html`)
Display the application name as default title.

Better title for menu bar

---

CHANGELOG.md
ui/js/lbryuri.js

Should be a fix for #689 and I think this was the only reference to the length of channel name.

Fixed parsing of channel names of length < 4

---

app/main.js
app/menu/main-menu.js

> Allow access to Developer Tools / Reload functionality #672 
> Copy-paste keyboard hotkeys into and out of app UI #685 
- Toggle `menuBar` visibility ( hidden by default )
- New additional shortcut: `toggleFullScreen`
- Make all shortcuts work again.

Menu patch

---

ui/package.json
ui/watch.sh
ui/webpack.common.js
ui/webpack.dev.js
ui/webpack.prod.js
ui/yarn.lock

Simplifying by adding more webpack config files?! Yep.
There are now three webpack files for the `ui`, but only because there is now a common config with the webpack essentials (entry, output, babel) and two other configs with extend the base config.
`webpack.config.js` was the prod config
`webpack.dev.config.js` was the dev config
A lot of duplication of basic webpack setup
`webpack.common.js` is the base webpack config
`webpack.prod.js` extends the base config
`webpack.dev.js` extends the base config
Also updated to `webpack@3`
Note: Most of the additions are from yarn
cc @liamcardenas

Simplify webpack

---

CHANGELOG.md
ui/js/component/uriIndicator/view.jsx
ui/scss/component/_channel-indicator.scss

Fix for long channel names resulting in the inconsistent thumbnail sizes.

Issue #721 fix - Inconsistent thumbnail sizes

---

CHANGELOG.md
ui/js/component/app/index.js
ui/js/component/app/view.jsx
ui/js/redux/actions/navigation.js
ui/js/redux/reducers/navigation.js
ui/js/redux/selectors/navigation.js
ui/js/util/throttle.js

Doing some refactoring to how the scroll restore works. This fixes the issue where after navigating, pages were scrolled down a bit.
This gets ride of the need to use a `setTimeout` which was required to let the new page load before scrolling. We can handle that inside the app component which I think makes more sense because it is interacting with the DOM. I also added throttling to the scroll listener, no need to constantly fire events when scrolling.
Do we want to restore for all pages? Forwards _and_ back? Not really sure.
If users click the `settings` icon while on the settings page, maybe scroll to the top instead of doing nothing?

refactor scroll navigation/restore

---

app/main.js
package.json
ui/js/store.js

Add [React DevTools](https://github.com/facebook/react-devtools) and [Redux DevTools](https://github.com/gaearon/redux-devtools) through [Electron DevTools Installer](https://github.com/MarshallOfSound/electron-devtools-installer).
They are only installed when the environment variable `NODE_ENV` is set to `development `.
I also took the freedom to reorganize the module imports in the `main.js` file.

Integrate React and Redux devtools into Electron

---

CHANGELOG.md
ui/js/component/fileList/view.jsx

It seemed like the API changed at some point and this wasn't updated. The result was that the published files were sorted by their name and not by their title.

Fixed sorting by title for published files (#614)

---

CHANGELOG.md
ui/js/component/header/index.js

Several places in the app default to credit values of 0.01. If we are suggesting hundredths based usage of LBC, the balance in the header should also have two decimal places.

Change header balance to 2 decimal places

---

CHANGELOG.md
src/renderer/js/component/uriIndicator/view.jsx
src/renderer/scss/component/_channel-indicator.scss

Changed overflow to `inline-flex` as `inline-block` was not aligning the channel name properly in the Tipping page.

Channel names in pages appear highlighted

---

src/renderer/js/redux/actions/content.js

The old error message was very confusing to users. Users don't need to know about sd hashes and blobs, they just want to understand what the problem pertained to -- and what steps they can take to fix it.
There is no reason to show daemon errors to the user in this instance.
Before
After

Added more understandable error message

---

src/renderer/component/subscribeButton/view.jsx

To fix "must return valid react element" error
I thought I could just return an empty string but I guess you need to return `null`

return null instead of empty string

---

src/renderer/page/discover/view.jsx
src/renderer/page/subscriptions/view.jsx

Need to use `navigate` for lbry links instead of `href`. Didn't notice any problems on mac but on windows it causes issues.

Fix channel link from subscriptions page

---

src/renderer/component/link/view.jsx
src/renderer/component/subscribeButton/view.jsx
src/renderer/modal/modalEmailCollection/view.jsx
src/renderer/page/discover/view.jsx
src/renderer/scss/component/_shapeshift.scss

Added the `@` icon to the subscribe button.
Make the links to channel on the subscriptions page more noticeable
Update copy on email modal
Below is while hovering (mouse disappears during screenshots). The link style should probably just be props passed in, `linkStyle` or something generic like that. I will add that when we cleanup the Link component
I like the joke in the email modal, but I think Reilly is right, more to lose than gain from it.

Style fixes

---

package.json

Having this script causes issues with the `precommit`script.
Prettier can still be run independently, or by running `yarn precommit`

remove prettier script

---

build/install_deps.sh

Update `install_deps.sh` script to overwrite `cmdtest` for resolving [this error](https://github.com/yarnpkg/yarn/issues/2821) that happens on Ubuntu 17.04. See note on [Debian/Ubuntu Linux section](https://yarnpkg.com/lang/en/docs/install/#linux-tab).

Overwrite cmdtest when installing yarn

---

src/renderer/redux/actions/app.js
src/renderer/redux/actions/content.js
src/renderer/redux/actions/wallet.js

@kauffj, so this PR removes the dependency of abandon_claim on transaction list. Now it fetches the data from myClaims instead. @tzarebczan and I have given this a whirl and so far the edge cases work too.

Reworked abandon to not be depenedent on txn list

---

src/renderer/rewards.js

the API call uses verified_email, reverting and fixing the message type.

fix verified email snackbar, take 2

---

package.json

This PR re-introduces the functionality for building lbry-app with a directory target. This is important for isolated build environments like [solbuild](https://github.com/solus-project/solbuild) (used for Solus), where build and install directories are different (and the contents of install dir are used in a final binary package) and thus necessitate being able to have unpackaged assets be placed in a directory relative to the build location, so instructions may be performed on those assets.
Note: This patch has already been tested with [this commit to our package repo](https://dev.solus-project.com/R3654:0770e2ea0a5b5e9305cb988a0b089ddd785c4e06) and validated locally.

Re-introduce build dir / dist dir option for isolated build environments.

---

electron-builder.json

Per the menu spec https://standards.freedesktop.org/menu-spec/latest/apa.html if you specify Video you also need to specify the AudioVideo category.

Fix validity of Linux .desktop file

---

src/renderer/component/video/internal/play-button.jsx

Fixes #906 by ignoring the isLoading prop when determining the disabled state of the button.

Enable play button after clicking download

---

src/renderer/page/settings/view.jsx

There are issues with selecting dark mode when auto dark mode is already selected. This disabled the auto dark mode checkbox if dark mode is currently selected.
It also un-checks it if you select dark mode from the drop down

disabled auto dark mode if dark mode is selected

---

src/main/createWindow.js
src/main/index.js

This fixes #1111. The app wouldn't completely quit after an update was downloaded and the user has pressed "USE IT NOW".

fix: app quitting when accepting update

---

src/renderer/component/publishForm/internal/channelSection.jsx
src/renderer/component/publishForm/view.jsx

Adding 2 checks to channel bid (equal to balance, and equal to 0) based on https://github.com/lbryio/lbry-app/pull/794 because the error messages don't make it from the daemon, so will these in place.
Removed publish side check, error message from the daemon are now more accurate. 
Tested this out locally.

Remove app side balance checks

---

src/renderer/redux/reducers/claims.js

Channels may be updated with new bids and will appear as "update" in channel_list. This would also occur if claims were sent from one user to another (i.e. us transferring a channel to a youtuber).

Include updated channels in results

---

src/renderer/component/common/form-components/form-row.jsx
src/renderer/page/channel/view.jsx
src/renderer/scss/component/_form-field.scss
src/renderer/scss/component/_pagination.scss

This would close #711.
The component used for pagination (react-navigate) doesn't offer customisation options, so a separate control for choosing the target page is needed. The implementation is such that the user would enter a page number and presses the enter key.

Add go to page navigation to channel pagination options

---

CHANGELOG.md
src/main/menu/setupBarMenu.js

based on @IGassmann comment to my PR earlier ,

feat: add keyboard shortcut to quit the app on Windows

---

src/renderer/scss/component/_form-field.scss

This would close #1228.
The problem is that the input div height was fixed to 36px, which prevented it to wrap the containing text to additional lines. This simple change enables wrapping in practice.
It looks like this:

Unset form field input height to make it scale

---

src/main/createWindow.js

This would close #1200.
What this does is, when closing a window, wait for a full screen window to leave full screen mode first, before actually attempting t close it.
This works on macOS, but the code _has not_ been tested on other platforms.

Fix black screen on macOS after maximizing LBRY and then closing

---

README.md
package.json
yarn.lock

This adds Windows build tools as a prerequisite on Windows.

build: bump electron from 1.7.13 to 1.8.4

---

src/renderer/component/fileCard/view.jsx

If NSFW content is not enabled in settings, thumbnails for NSFW content are obscured, but the file titles are not. This change hides the title information, so no (likely) NSFW text (in the title or username) is shown either. The implementation before redesign actually blurred both the image and the text.
It looks like this now:

Obscure NSFW content title

---

CHANGELOG.md
src/renderer/component/header/index.js
src/renderer/component/header/view.jsx

Show exact wallet balance on mouse hover over

---

CHANGELOG.md
src/renderer/component/snackBar/index.js
src/renderer/component/snackBar/view.jsx
src/renderer/scss/_vars.scss
src/renderer/scss/component/_snack-bar.scss

This is for #1279.
Unlike modal dialogs in the redesign, this is with a dark background to make it pop a bit more. Functionality remains the same as with the original snackbar.
The prop-types package was added as a dependency.

Add flair to snackbar

---

CHANGELOG.md
src/renderer/component/fileTile/index.js
src/renderer/component/fileTile/view.jsx

This addresses #1284.
When "put something here" link is clicked, the URL here is first stripped of the lbry:// prefix, and then given as a navigation parameter. Then, the publish page uses this parameter to pre-fill the URL field in the form. Also, if the parameter exists, adding the actual file to be published will not overwrite the URL with the chosen file name.

Pre-fill publish URL after clicking "Put something here" link

---

CHANGELOG.md
src/renderer/scss/component/_search.scss

This fixes #1366.
For some reason, moving the `.icon` style here on the same level as `.wunderbar__suggestion-label` didn't work, only when it's under `.wunderbar__suggestion`.

Fix spacing in search suggestions

---

CHANGELOG.md
src/renderer/component/filePrice/view.jsx

This would fix #1427.
Note: the actual fix is just to return null in the `if (!costInfo)` block.
However, committing that was prevented by linter error `PropType is defined but prop is never used` for multiple props, even if those props are being used.
As a workaround and for less code, I think that it's enough to check props and call `fetchCostInfo` only in `render` function. Linter is happy this way. What do you think?

Remove price placeholder during thumbnail loading

---

CHANGELOG.md
src/renderer/component/video/internal/player.jsx
src/renderer/modal/modalAffirmPurchase/view.jsx
src/renderer/modal/modalFileTimeout/view.jsx
src/renderer/scss/component/_content.scss

Fix text/HTML files don't display correctly in-app anymore #1379

Fix files don't display correctly in-app anymore

---

CHANGELOG.md
src/renderer/scss/_gui.scss

This fixes both #1193 and #1392.

Price badge improvements

---

CHANGELOG.md
src/renderer/redux/actions/rewards.js

This fixes PART of the issues reported in #1436  
As  @tzarebczan reported,  this error `Uncaught (in promise) Error: Actions may not have an undefined "type" property. Have you misspelled a constant?`, the constant ACTIONS.OPEN_MODALS is not defined anymore and it throws that error as the type for an action when dispatching it is undefined:
```
dispatch({
type: ACTIONS.OPEN_MODAL,
data: { modal: MODALS.FIRST_REWARD },
});
```
Seems like the code to open modals have been refactored and changed to notifications, as far as I understand.

Show modal when claiming a reward

---

package.json

This fixes https://github.com/lbryio/lbry-app/issues/1423 per https://github.com/electron-userland/electron-builder/issues/2896. Confirmed locally.

Upgrade electron-updater

---

CHANGELOG.md
src/renderer/page/rewards/view.jsx
yarn.lock

Fix #1466 as the check for eligibility was using `user.is_identity_verified` instead of `user.is_reward_approved` which is the proper way of checking  if the user can claim rewards or not.

Fix grayed out rewards cards

---

package.json

See changes here: https://github.com/feross/render-media/commits/master
Will fix https://github.com/lbryio/lbry-app/issues/931 as it won't prompt to save anymore, but the PDF does not render in-app per the comments.
Tested videos in app briefly, doesn't look like anything breaks.

bump render-media

---

src/renderer/rewards.js

Closes issue #1488, I've searched on the entire codebase to check if there is any place where `doNotify` was being called without  `displayType` property(thanks @tzarebczan, your comment helped a lot! ).
@seanyesmunt  I wonder if we should add a default `displayType`(ex: `["snackbars"]`) in case someone forgets to add it while calling the function `doNotify`, anyway currently I've not added any default and just fixed the issue reported on #1488 
This issue on #1488 :
```
Another user had reported something similar on the show page - 
he was unable to click the delete button (could click, but not action), until a restart.
```
Was also related to the notifications being queued but not dispatched because the `displayType` was not set, I could reproduce and tested the fix.

Add display type to notifications to allow snackbar to be shown.

---

src/renderer/component/video/internal/player.jsx

This PR closes issue #1463 , which adds a callback on double click event and toggles the full screen on videos. I've only tested this on videos(I've only added the callback event when the element is a video type)

Toggle video fullscreen on doubleclick.

---

src/renderer/page/file/view.jsx
src/renderer/redux/reducers/navigation.js

Fixes https://github.com/lbryio/lbry-app/issues/1499
We store the short form of the uri being edited. That was causing an issue with properly prefilling claim edits because we were passing in the long form with a claim id. In the place that we were checking if the current uri is equal to the uri being edited, they were different so it wasn't working.
```
// check to see if you are editing
// editingUri === uri
// before
lbry://@channelName#xxx.../claim-name === lbry://@channelName/claim-name
```

fix: use short form uri when preparingEdit so users know they are editing

---

src/renderer/component/categoryList/index.js
src/renderer/component/categoryList/view.jsx
src/renderer/page/discover/view.jsx
src/renderer/page/file/view.jsx
src/renderer/redux/actions/content.js

This PR for issue #1049 
Is ready to be reviewed by @liamcardenas 
Uses existing reducers, actions, selectors
Moves `component/common/category-list.jsx` to its own top level component at `component/categoryList` because it needs props to `fetchChannel` and select `claimsByChannel` and `claimsById`
Fetches channels in `componentDidMount` when the category is a channel
Returns false in `isCardVisible` when `!section` -- this fixed the error I was getting; I'm not sure exactly how the code for the UI works
Adds const `channel` to the `CategoryList` `render` function, which is an empty array until the data comes in, and once the data comes in is an array of proper uris made with 'buildURI` from `category` selector data
Maps the `channel` array to `<FileCard>` components when appropriate …

Support channel definitions from /file/list_homepage

---

CHANGELOG.md
src/renderer/component/common/form-components/form-row.jsx
src/renderer/component/viewOnWebButton/index.js
src/renderer/component/viewOnWebButton/view.jsx
src/renderer/constants/icons.js
src/renderer/page/channel/view.jsx
src/renderer/page/file/view.jsx
src/renderer/scss/component/_form-field.scss

New PR for #1028 @tzarebczan @liamcardenas 
This creates `<ViewOnWebButton>` with a `GLOBE` icon and uses it on `<FilePage>` and `<ChannelPage>`
Also fixes ~10 eslint errors

Share speech URLs on File and Channel pages

---

CHANGELOG.md
src/renderer/component/inviteNew/index.js
src/renderer/component/inviteNew/view.jsx
src/renderer/component/rewardLink/index.js
src/renderer/component/userVerify/index.js
src/renderer/modal/modalFirstReward/index.js
src/renderer/modal/modalFirstReward/view.jsx
src/renderer/redux/actions/rewards.js
src/renderer/redux/reducers/rewards.js
src/renderer/redux/selectors/rewards.js
src/renderer/rewards.js

Refactor unclaimed rewards as array to keep order from api.lbry.io. Display reward notification message through snackbar with fallback for rewards with no message.
#1329

Rewards reorder and snackbar notifications

---

src/main/index.js

Closes #1505  as it allows https to follow redirections, it checks for status 301 and 302.
I've looked through [https docs](https://nodejs.org/api/https.html) and [github https](https://github.com/nodejs/node/blob/master/lib/https.js) to see if there was an easier way or option to allow redirections, but I couldn't find anything.

Allow https to follow redirection when requesting latest release data

---

src/renderer/component/walletSend/index.js
src/renderer/component/walletSend/view.jsx
src/renderer/modal/modalConfirmTransaction/index.js
src/renderer/modal/modalConfirmTransaction/view.jsx
src/renderer/modal/modalRouter/view.jsx
yarn.lock

Closes #947 
It adds the feature to prompt a modal before sending a transaction.
Maybe we can add the usd value of the transaction also?

Add confirmation propmt before sending a transaction.

---

src/renderer/component/categoryList/view.jsx

`categoryList`'s `componentDidMount` was calling `doFetchClaimsByChannel` without a channel `uri` (categoryLink) which calls `claim_list_by_channel` with no channel

fix empty uri calls

---

src/renderer/component/app/view.jsx
src/renderer/component/fileCard/view.jsx
src/renderer/index.js
src/renderer/util/contextMenu.js

Closes #1538 , So when [PR](https://github.com/lbryio/lbry-app/pull/1486) got merged It introduced a bug which I didn't test (#1538) , this PR add the context menu event to be listened on the `app` component inside the react rather than doing `document.addEventListener`, the function `onContextMenu` can call `event.preventDefault` && `event.stopPropagation` on child elements and that will cancel the call to open the menu handled by `app` component(parent).
Right click on video to copy a link without text being selected(copy is disabled)
Right click on video to copy a link with text selected:

Add copy text on contex menu.

---

package.json
src/renderer/component/router/view.jsx
src/renderer/component/wunderbar/index.js
src/renderer/page/search/view.jsx
yarn.lock

This is dependent on [lbry-redux/pull/31](https://github.com/lbryio/lbry-redux/pull/31)
Addresses issue #1457 
This was a small change and seems a little too simple, but the back button works as described
The only UI change was removing `noPadding` so there may be more to do there

Search page (not modal)

---

CHANGELOG.md
src/renderer/redux/actions/content.js

This will send the same unique URI for all claims, regardless of what URI the user navigated to. Also fix sending of outpoint (was passed as output, which was blank, previously)

Fix issue 1494 - uri and outpoint to API

---

src/renderer/component/viewOnWebButton/view.jsx
src/renderer/page/channel/view.jsx
src/renderer/page/file/view.jsx

This PR fixes the format of URLs called by the View on Web button which are passed to spee.ch. Channels are spee.ch/@channelname:claimID and claims are spee.ch/claimID/claimname
Also adjusts View On Web / Tip icon to the left instead of right.

fix share on Web (spee.ch) URLs

---

src/renderer/page/file/view.jsx

#797 @tzarebczan 
Call `fetchCostInfo` whenever `<FilePage>` mounts. All `fetchCostInfo` does is update `costInfo` based on `fileInfo`; there is no api call. So running it whenever a user visits a claim is not a problem where fetching `fileInfo` from the daemon could slow things down significantly.
I don't like this solution but refactoring everything about `costInfo` would be more involved and [there may be reasons for this design which are not apparent to me](https://en.wikipedia.org/wiki/Wikipedia:Chesterton's_fence).

always update costInfo on FilePage componentDidMount

---

src/renderer/redux/actions/rewards.js

Fixes #1555 @tzarebczan 
This adds an `option` parameter to `doClaimRewardType` which it uses to fail silently.
`doClaimEligiblePurchaseRewards` (called by each `doDownloadFile`) uses this option when attempting to claim `rewards.TYPE_MANY_DOWNLOADS` and `rewards.TYPE_FEATURED_DOWNLOAD`
The error modal for rewards is in the `<RewardLink>` component and displayed when `errorMessage` is defined. It was getting set in redux and sitting there until a `<RewardLink>` is rendered when a user visits the rewards page. `error` is sent `undefined` in this PR because not calling the error reducer results in the two rewards pending on the rewards page.

fix reward error notification

---

.flowconfig
CHANGELOG.md
src/renderer/page/help/index.js
src/renderer/page/help/view.jsx
src/renderer/scss/component/_card.scss

#1556 - Adding ability to open logs and view log directory on the help page.
#741 -  Fixing content address extending outside of the visible area in the card. (I am including this fix as a part of this PR since it is a small relatively small fix - 3 lines)
* Made changes to the code to include a new section to giving users the option to open the log file or the directory that contains the log file. 
* Added some type declarations since eslint and flow checkers were failing on the file that I edited. 
* Added a word wrap while to card's ```h1``` element so that long URLs do not extend outside the visible area.
#1556 
#741 
P.S: I have tested this only on macOS Sierra and theoretically should work on other operating systems as well. Let me know if it doesn't!

Adding ability to view logs and open log directory

---

src/renderer/redux/actions/user.js

#1579 
Edit: This passes the platform returned by `Lbry.version` which for me is `Linux-4.15.0-23-generic-x86_64-with-Ubuntu-18.04-bionic`

Pass app version info to internal APIs

---

package.json
src/renderer/component/common/form-components/form-field.jsx
src/renderer/component/common/tooltip.jsx
src/renderer/page/file/view.jsx
src/renderer/scss/_vars.scss
src/renderer/scss/all.scss
src/renderer/scss/component/_card.scss
src/renderer/scss/component/_content.scss
src/renderer/scss/component/_toggle.scss
src/renderer/scss/component/_tooltip.scss
yarn.lock

Very minor CSS changes, mostly dealing with thumbnail placeholders in different parts of the app.
Also added `react-toggle` to style the autoplay switch. In the future, we will move all checkboxes over to this but there were some alignment issues so I didn't want to bother with it right now.
https://github.com/lbryio/lbry-app/issues/1539

More css fixes

---

src/renderer/component/video/index.js
src/renderer/component/video/view.jsx

This is already being called in the play. No reason to call it twice.

removed direct call to doLoadVideo for autoplay handling. 

---

src/renderer/page/file/view.jsx

Reverts lbryio/lbry-app#1623
@tiger5226 reverting this because it's causing issues with images not being playable. I think the fix for that would be pretty easy but I'm not sure off the top of my head.

Revert "fixed isPlayable to only play for video or audio."

---

src/renderer/redux/selectors/app.js

Forgot to update the path in the last PR. It downloads as: LBRY_xxxx.deb

fix linux path

---

src/renderer/page/subscriptions/view.jsx

#1516 
Sometimes, a claim id would be added to `byId` in redux state even if there are no claims loaded. Maybe that shouldn't happen? This ensures that the claim has no uris loaded before fetching, before we were just checking if the claim id existed in redux or not.

fix: fetch subscriptions if there are no claims loaded

---

src/renderer/component/fileCard/view.jsx
src/renderer/redux/actions/publish.js
src/renderer/redux/reducers/publish.js
src/renderer/redux/selectors/publish.js

Don't resolve URI if it's pending.
Would be nice to resolve/show donwnloaded file icon after file is confirmed, but good enough!
@seanyesmunt I think I got some of your ux changes in here when switching branches, let me know if I need to clean up.

Pending edit magic

---

CHANGELOG.md
src/renderer/scss/component/_card.scss

- Fix can type in unfocused fields while publishing without selecting file #1456

Block pointer events of disabled cards

---

CHANGELOG.md
src/renderer/page/channel/view.jsx
src/renderer/scss/component/_pagination.scss

Navigation button resulting incorrect page designation #1502 
> We can know that if the forcePage number still the same, the page will re-render, but won't change. So when you do your search function, you should reset the forcePage number.
https://github.com/AdeleD/react-paginate/issues/198#issuecomment-381465298

Fix incorrect page designation

---

src/renderer/scss/component/_markdown-editor.scss

These changes follow **typical** styling rules for **spelling errors** in **most** applications which means people are **familiar** with the **markup** which avoids **confusion**. The changes also mean that the incorrect spelling style is more **visible** especially in the **Dark theme** where it was almost impossible to see.

Spell Checker CSS Style Changes

---

src/renderer/scss/component/_table.scss

Same **CSS** issue and fix as https://github.com/lbryio/lbry-app/pull/1692 which fixes tables issues when the app is at minimum width.
These little details help keep the app looking professional, thus helping brand reputation/authority.

Tourniquets Text to Fix Table Length Issue in Help

---

src/renderer/scss/component/_button.scss

Fixes table length issue https://github.com/lbryio/lbry-app/issues/1690

Tourniquets Text Over 20VW to Fix Table Length Issue

---

src/renderer/scss/component/_table.scss

When the new code was added the `var(--color-help)` was lost and it defaulted back to **brash white**. This adds the `var(--color-help)` back in.

2nd Column Lost it's Colour

---

src/renderer/scss/component/_button.scss

#1713 
After setting `overflow: hidden`, it changes the way height works for block elements.
https://stackoverflow.com/questions/22421782/css-overflow-hidden-increases-height-of-container
Setting to `inline` fixes this.

fix 1713: set button links to 'display: inline'

---

src/main/index.js

Prior to this, if running in dev mode, you'd get the electron version and not the LBRY-app version
Fixes https://github.com/lbryio/lbry-app/issues/1707

Get version from package.json

---

package.json

https://github.com/lbryio/lbry-app/issues/1634
Now clears the `lbry-redux` cache from yarn on `yarn` installs

clear lbry-redux cache on preinstall

---

src/renderer/page/show/view.jsx

use claimName instead of uri while loading channel page

---

CHANGELOG.md
src/renderer/component/publishForm/view.jsx

https://github.com/lbryio/lbry-app/issues/1712

take previous bid into account for total available to deposit

---

src/renderer/component/button/view.jsx
src/renderer/component/publishForm/internal/bid-help-text.jsx
src/renderer/component/publishForm/view.jsx
src/renderer/component/transactionList/internal/transaction-list-item.jsx
src/renderer/scss/component/_button.scss
src/renderer/scss/component/_card.scss
src/renderer/scss/component/_table.scss

Disabled the file input when `publishing === true`
Fix an issue with form error styling at the bottom of the publish form
https://github.com/lbryio/lbry-app/issues/1714
https://github.com/lbryio/lbry-app/issues/1647
Moved button styling to be specific to the transactions table because it was affecting buttons it shouldn't.

Publish fixes

---

src/renderer/redux/actions/publish.js

I'd like to update spee.ch's api endpoint to reject publish requests that do not include a file name or content type.  The update in this PR is to send the request as a File with a file name rather than a Blob

changed form data to attach a File rather than Blob

---

src/renderer/component/shapeShift/internal/active-shift.jsx
src/renderer/constants/shape_shift.js
src/renderer/redux/actions/shape_shift.js
src/renderer/redux/reducers/shape_shift.js

If LBC is unavailable on shapeshift (like it is right now) the app breaks on the Get Credits page. We need to explicitly check that it is available before worrying about other coins availability.
If it's unavailable, stop and show an error message.

Handle LBC unavailable error from ShapeShift without breaking the app

---

src/renderer/component/common/busy-indicator.jsx
src/renderer/page/channel/view.jsx

Issue #1255 
Moves `<BusyIndicator>` to title bar.
Refactors `contentList` to show "No content found" only after fetch is complete; `null` while fetching.
There is still some chance that a user will click the wrong tile but the update is very fast and pretty smooth. The best way I see to prevent this is to disable navigation for ~1sec following the update. This could be done by adding a throttle property to the state along with corresponding actions, reducers, and a thunk in doNavigate, or migrating from thunks to middleware, both of which seem well beyond the scope of this issue.

Channel page caching

---

README.md

Added the AUR URLs to the default download options under "Alt. Linux Build"
Before - http://hfimg.pw/i/g4py9.png
After - http://hfimg.pw/i/ohzrm.png

Added options for Arch Linux in the download options

---

.github/ISSUE_TEMPLATE.md
CHANGELOG.md
CONTRIBUTING.md
README.md
package.json
src/main/index.js
src/main/menu/setupBarMenu.js
src/renderer/component/fileList/view.jsx
src/renderer/modal/modalAutoUpdateConfirm/view.jsx
src/renderer/modal/modalAutoUpdateDownloaded/view.jsx
src/renderer/modal/modalUpgrade/view.jsx
src/renderer/page/file/view.jsx

Reviewed all instances of lbry-app and changed to lbry-desktop. There are still some that will stay at lbry-app for now (i.e. AUR/Flatpak repo names).

lbry-app > lbry-desktop

---

src/renderer/component/categoryList/index.js
src/renderer/component/categoryList/view.jsx
src/renderer/scss/component/_card.scss

I think we should keep the "row" styling somewhat there. Then users know this would be a scrollable row just like the other rows, if they change their settings.

hide community row if nsfw content is hidden

---

src/renderer/page/rewards/index.js
src/renderer/page/rewards/view.jsx
src/renderer/types/reward.js

#1572 
Removes the `componentDidReceiveProps` hook from the `<RewardsPage>` component, which was firing repeatedly.
Passes in claimed rewards through the container to differentiate between "none available" and "you claimed them all".

fetch rewards on page load

---

src/renderer/redux/actions/publish.js

This is an update for the app to use a static embed url for successful thumbnails published via spee.ch.
This is dependent upon merging the following PR on spee.ch: https://github.com/lbryio/spee.ch/pull/529

updated the url for successful thumbnail publishes

---

src/renderer/component/transactionList/view.jsx

add abandon to transaction list filter

---

src/renderer/component/rewardSummary/index.js
src/renderer/component/rewardSummary/view.jsx
src/renderer/page/rewards/view.jsx
src/renderer/redux/actions/rewards.js

#1780 
Fetch rewards after successfully claiming a reward.
Move reward fetching from `<RewardsPage>` to `<RewardsSummery>` displayed on `<WalletPage>`. Display `<BusyIndicator>` and hide unclaimed reward count while fetching rewards.

Rewards enhancements

---

src/renderer/component/page/view.jsx
src/renderer/page/subscriptions/index.js

We weren't stopping the loader timeout if the `loading` prop was passed in as `false` after it is rendered. This was causing the loading indicator to be rendered indefinitely on the subscriptions page.

stop loader timeout if not loading

---

CHANGELOG.md
src/renderer/component/publishForm/view.jsx

add FAQ to Publish Form

---

CHANGELOG.md
src/main/createWindow.js

- Middle Click Link Error #1843
> When someone middle-clicks on links within the app, it opens them up in an app window with incorrect formatting and also doesn't support the Shapeshift site.

Fix middle-click open link event

---

CHANGELOG.md
package.json
src/renderer/redux/actions/app.js
src/renderer/redux/reducers/app.js
src/renderer/redux/selectors/app.js

Clear upgrade subscribed interval after declining

---

src/renderer/redux/selectors/publish.js

If there is no `uri` or `editingUri` (which are built from the publish form values) we know they can't be editing so return `false` early.

Fix: Don't show editing mode on publish after clearing cache

---

src/renderer/analytics.js
src/renderer/component/fileViewer/internal/player.jsx
src/renderer/component/fileViewer/view.jsx
src/renderer/redux/actions/content.js

This ended up being a little more complex after realizing we need to reset analytics data when users navigate directly to another file (where the File page won't be re-mounted)
There are three scenarios:
- User has already downloaded a file: do nothing
- User started downloading but navigated away before it started playing: log `file_view` with no `time_to_start`
- User stayed on the page until the file started playing: log `file_view` with `time_to_start`

log time to play

---

CHANGELOG.md
src/renderer/component/publishForm/view.jsx
yarn.lock

Adds a message at the bottom of the page to let the user know the thumbnail is still uploading.

feat: add thumbnail loading to list of help errors

---

src/renderer/page/file/view.jsx

Before if you went to `lbry://one`, the top video under "related" would be the same claim.
In the reccomended slector, we strip out any matches to the uri, but it wasn't working for vanity claims.

use correct url for recommended content on vanity claims

---

src/renderer/page/subscriptions/index.js
src/renderer/page/subscriptions/view.jsx
src/renderer/redux/actions/subscriptions.js
yarn.lock

Not really sure what was going through my head when I first wrote this. There isn't any reason to pass the subscriptions into the component and call the `channel_list` command from there. Just call it immediately after we get them from the api.

Fix subscriptions page when subscribed to a channel with 0 claims/abandoned

---

src/renderer/page/subscriptions/index.js
src/renderer/page/subscriptions/view.jsx
src/renderer/redux/actions/subscriptions.js
yarn.lock

Rebased ontop of my other branch so the app would work while I was testing #1897

add autodownload toggle to subscriptions page

---

CHANGELOG.md
package.json
src/renderer/component/viewers/threeViewer/index.jsx
src/renderer/component/viewers/threeViewer/internal/grid.js
src/renderer/component/viewers/threeViewer/internal/renderer.js
src/renderer/scss/all.scss
src/renderer/scss/component/_dat-gui.scss
src/renderer/scss/component/_file-render.scss
yarn.lock

3D-viewer v2

---

src/renderer/component/fileList/view.jsx
src/renderer/types/file_info.js

If two claims are in the same block, also check the `absolute_channel_position` which is based on sorting that the daemon does.

fix: sorting on subscriptions with multiple claims in same block

---

src/renderer/redux/actions/publish.js

This ensures that when clicking on the notification, it goes to the correct URL. Before it could have been a different vanity URL.

use permanent url instead of uri

---

src/renderer/analytics.js
src/renderer/component/fileViewer/index.js
src/renderer/component/fileViewer/view.jsx
src/renderer/component/rewardSummary/index.js
src/renderer/component/rewardSummary/view.jsx
src/renderer/page/discover/index.js
src/renderer/page/discover/view.jsx
src/renderer/redux/actions/content.js

Refresh rewarded content when navigating to the discover page, and the wallet overview
Make sure to try and claim rewards _after_ we call the `file/view` https://github.com/lbryio/lbry-desktop/issues/1916

fetch new rewards and properly call reward claim after view event has been fired

---

src/renderer/component/selectThumbnail/view.jsx
src/renderer/scss/_gui.scss
src/renderer/scss/_vars.scss
src/renderer/scss/component/_content.scss
yarn.lock

I decided to zoom in on thumbnails if they aren't the proper aspect ratio, if we render the thumbnails as is, there are a ton of content items with incorrectly sized thumbnails. This results in a lot of content with black bars on the side. I think zooming in on some images is preferable. 
This is how we were displaying the thumbnails in the app aready. This PR just makes it consistent on the publish page.

fix: inconsistent thumbnail size on the publish page

---

CHANGELOG.md
src/renderer/scss/component/_markdown-preview.scss

- Fixes paragraphs not rendered correctly in markdown #1932

Fix paragraphs spacing on markdown render

---

CHANGELOG.md
src/renderer/scss/component/_table.scss

- Fix claim name positioning too close to transaction id #1849

Fix table elements padding and spacing

---

src/renderer/component/address/view.jsx
src/renderer/component/common/icon.jsx
src/renderer/component/socialShare/index.js
src/renderer/component/socialShare/view.jsx
src/renderer/constants/icons.js
src/renderer/modal/modalRouter/view.jsx
src/renderer/modal/modalSocialShare/index.js
src/renderer/modal/modalSocialShare/view.jsx
src/renderer/page/file/view.jsx

Resubmitted after verifying the bug I was worried about was due to redux lacking my MODAL constant.
This was closely modeled after the modalSendTip and walletSendTip components.
It should shares either anonymous and channel-based spee.ch links
Sharing is available only if the content meets shareable criteria.
It uses share urls from http://www.sharelinkgenerator.com/ to share to Facebook, Twitter, and Google Plus.
There are some improvements that could be made:
- feathericons has no actual google-plus icon, I think
- it could share a tinyurl version
- the formatting and spacing could be better
- the mouseover tooltips could be more responsive: they seem to give up sometimes - ideas?
- the link could come preselected, rather than wait for a click in the text field
- the modal could give …

feature: ModalSocialShare

---

CHANGELOG.md
src/renderer/component/common/form-components/form-field.jsx
src/renderer/component/walletSendTip/view.jsx
src/renderer/modal/modalWalletEncrypt/view.jsx
src/renderer/modal/modalWalletUnlock/view.jsx

- Add `autoFocus` prop  of `form-field` component. 
- Auto focus modals form.
- Allow typing of encryption password without clicking entry box #1969

AutoFocus form-fields

---

src/renderer/component/socialShare/view.jsx

Share on spee.ch urls using channelName need clarification and testing. Revert back to working url without channelName.
Must confirm with spee.ch group how to properly format urls using channelName.
If someone can get a url using channelName to work consistently, I can put that format in.

hotfix: share is broken; use currently working spee.ch share url

---

src/renderer/component/channelTile/view.jsx
src/renderer/component/common/truncated-text.jsx
src/renderer/component/fileCard/view.jsx
src/renderer/component/fileTile/view.jsx

A lot of titles were cut off with no way to see the entire thing without navigating to the claim. Now it will show if you hover over it.

Add proper html title to card/tile components for long titles

---

src/renderer/component/publishForm/internal/bid-help-text.jsx
src/renderer/component/publishForm/internal/name-help-text.jsx
src/renderer/component/publishForm/view.jsx
src/renderer/page/file/view.jsx
src/renderer/page/publish/index.js
src/renderer/redux/reducers/navigation.js
src/renderer/redux/selectors/publish.js
src/renderer/scss/component/_form-field.scss

More clarity for takeover amounts on claims
Show amount needed to win a claim when editing. Ex: "You have a claim at xxx, for 5 more LBC you will control it"
I created a new component `NameHelpText` for variable help text under the name input. I moved `BidHelpText` under the bid input (which is probably where it should have been in the first place)

Better messaging for takeover amounts on publish page

---

src/renderer/component/fileList/view.jsx

To get rid of the react warnings.
Outpoint is undefined in some cases

update key for FileList

---

src/renderer/page/file/view.jsx
src/renderer/redux/selectors/content.js
src/renderer/store.js

Removing claims from cache to fix https://github.com/lbryio/lbry-desktop/issues/1983
If you were viewing a lot of claims (with search/many related videos) the app would lock up when it tried to save to disk. Ideally, this would happen in a nonblocking way.

remove claims from redux-persist cache

---

src/renderer/component/copyableText/index.js
src/renderer/component/copyableText/view.jsx
src/renderer/component/socialShare/view.jsx
src/renderer/modal/modalSocialShare/view.jsx
src/renderer/page/file/view.jsx
src/renderer/scss/_gui.scss

This feels clean to me. Tooltip was causing lots of flow errors, and on reflection, I don't think it's needed.

adds open.lbry.io links to socialShare Re: Issue # 1810

---

src/renderer/component/publishForm/internal/license-type.jsx
src/renderer/component/publishForm/view.jsx
src/renderer/redux/actions/publish.js
src/renderer/redux/reducers/publish.js

Before we were treating a custom license type and copyright different. This caused a lot of additional logic. Since copyright can be a custom entry, we can use the same variable for both. This also makes populating data on edit simpler.
Fixes #1975

remove copyright from publish form state and fix other license edit

---

src/renderer/page/channel/view.jsx
src/renderer/page/show/view.jsx
src/renderer/scss/component/_card.scss

Moved the subscribe/spee.ch links to under the title so they aren't waaaaay to the right on large screens.

better channel actions alignment

---

CHANGELOG.md
src/renderer/component/selectThumbnail/view.jsx
src/renderer/component/socialShare/view.jsx
src/renderer/component/viewOnWebButton/view.jsx

issue 2015

---

CHANGELOG.md
src/renderer/component/common/tooltip.jsx
src/renderer/component/dateTime/view.jsx
src/renderer/component/fileCard/index.js
src/renderer/component/fileCard/view.jsx
src/renderer/component/fileTile/index.js
src/renderer/component/fileTile/view.jsx
src/renderer/component/recommendedContent/view.jsx
src/renderer/component/userHistory/index.js
src/renderer/page/file/view.jsx
src/renderer/redux/selectors/subscriptions.js
src/renderer/scss/all.scss
src/renderer/scss/component/_card.scss
src/renderer/scss/component/_file-list.scss
src/renderer/scss/component/_placeholder.scss
yarn.lock

- Added placeholder styles for all file cards and tiles (related content, search, channels)
- Added the published date (based on block height) to every file card and tile
- Added back the upgrades to the share modal (I accidentally removed it)

Add content placeholders and add time info to FileCard/FileTile

---

src/renderer/redux/actions/publish.js
src/renderer/redux/actions/shape_shift.js
src/renderer/redux/reducers/subscriptions.js
src/renderer/types/redux.js

While I work with flow type, I found that in the codebase there are multiple places that define Redux Dispatching type. 
So I took the liberty to centralised redux dispatch type definition into one single place.
If I break any codebase rules or established pattern, please let me know and you can close this pull request.

Proposed: Centralized redux action

---

CHANGELOG.md
src/renderer/component/common/file-selector.jsx
src/renderer/component/publishForm/view.jsx
src/renderer/component/selectThumbnail/view.jsx
src/renderer/page/settings/view.jsx
src/renderer/redux/actions/publish.js
src/renderer/redux/reducers/publish.js
src/renderer/types/claim.js
src/renderer/types/stream.js

Based on this [issue](https://github.com/lbryio/lbry-desktop/issues/1839)
Make sure file dialog only allow certain file types to be uploaded.
Also fix flow type definition in:
- component/publishForm/view.jsx
- page/settings/view.jsx
- redux/actions/publish.js
- redux/reducers/publish.js
- types/claim.js

Limit thumbnail file upload type

---

src/renderer/component/selectThumbnail/view.jsx
src/renderer/scss/_gui.scss

Messed it up when I was refactoring the filecard
The thumbnail component is different from `.card__media` where it is a static height/width

fix thumbnail height/width

---

CHANGELOG.md
src/renderer/redux/actions/content.js

Based on this [issue](https://github.com/lbryio/lbry-desktop/issues/1860)
Since when ACTIONS.FILE_DELETE dispatch in `lbry-redux`, we actually remove the outpoint from store. So in order to update status, it makes sense to check if the outpoint still exists first before we dispatch update.
Also, centralized the update interval function.

Fix issue file_list call continues indefinitely if a file is removed while downloading

---

src/renderer/scss/component/_form-field.scss
src/renderer/scss/themes/_dark.scss

Also overrides styling for error labels that is overridden by other classes.
This is just a fix for now, _real_ fix coming in my WIP PR.

Dark mode fixes

---

package.json
src/renderer/component/fileList/view.jsx
src/renderer/page/subscriptions/index.js
src/renderer/page/subscriptions/view.jsx

Channel page crashes due to missing sortBy. FileList now requires it as a prop.
requires https://github.com/lbryio/lbry-redux/pull/90

adds sortBy default prop to subscriptions and channel pages

---

src/renderer/component/cardMedia/index.js
src/renderer/component/fileListSearch/index.js
src/renderer/component/formFieldPrice/index.js
src/renderer/component/publishForm/index.js
src/renderer/component/theme/index.js
src/renderer/modal/modalAuthFailure/index.js
src/renderer/modal/modalAutoUpdateConfirm/index.js
src/renderer/modal/modalAutoUpdateDownloaded/index.js
src/renderer/modal/modalDownloading/index.js
src/renderer/modal/modalTransactionFailed/index.js
src/renderer/page/backup/index.js
src/renderer/page/getCredits/index.js
src/renderer/page/sendCredits/index.js
src/renderer/page/sendCredits/view.jsx
src/renderer/page/wallet/index.js

Hey, as a little housekeeping quest, I removed unused vars from components where it was easily doable without triggering more linting errors while committing.
I also removed redux connections where they were not needed.

Reduce unused var warnings. 

---

CHANGELOG.md
src/renderer/page/help/view.jsx

- [ x ] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ x ] I have checked that this PR does not introduce a breaking change
- [ x ] Bugfix
Issue Number: #1600 
Clicking "Open Log Folder" will open the "lbry" folder with "lbrynet" highlighted, rather than opening the "lbrynet" folder which contains the log file.
Clicking "Open Log Folder" will open the "lbrynet" folder that contains the log file.

Fix to open folder containing the log file rather than roaming folder

---

src/main/index.js

When we added the v30 daemon changes, we changed our process search to `lbrynet`, which would return results if you had any `lbrynet` files open (including `lbrynet.log`)
This fixes that issue.

Fix: correctly search for daemon process on startup

---

package.json
src/main/index.js

If daemon is already running, windows app startup would fail. Argument is not required

Fix daemon startup on Windows if daemon running already

---

src/renderer/redux/actions/subscriptions.js

Instead of calling check subscriptions after fetching them (with a timeout hack), do this directly in the fetch routine instead of calling claim_list_by_channel. This ensures claim_list_by_channel is only called once and the subscriptions are checked after every fetch.

fetch subs fix

---

src/renderer/page/discover/index.js
src/renderer/page/discover/view.jsx

This will fetch new rewards if LBRY is left open on the homepage. We refresh the featured URIs on an interval, but the reward list would not have the newly pushed LBRYCast reward available...so you would not be able to claim this until going to the rewards page.

fix: featured reward claim

---

CHANGELOG.md
src/renderer/component/fileActions/view.jsx

We should show the delete button for own claims as well, not only if downloaded.. Thanks to Brendon, a community member, who reminded me of this one.

Fix: show delete button for own claims, not only downloaded ones

---

src/renderer/page/discover/view.jsx

This was a patched last week to ensure new rewards are fetched continuously (mostly for LBRYCast) if the app is left open. Forgot to add this statement to the props. Not a big deal as this didn't work previously and a new app startup/refresh/going to rewards fixes it.

fix: missing fetchRewards

---

CHANGELOG.md
src/renderer/component/fileCard/view.jsx

Copying a link only copies the community/vanity link on some claims, such as the Community Top Bid Area.
The fix makes sure the full permanent URL is always copied.

Full Permanent URL Copy Fix

---

package.json
src/renderer/component/splash/index.js
src/renderer/component/splash/view.jsx
src/renderer/modal/modal.jsx
src/renderer/modal/modalIncompatibleDaemon/index.js
src/renderer/modal/modalIncompatibleDaemon/view.jsx
src/renderer/modal/modalRevokeClaim/view.jsx
src/renderer/modal/modalRouter/view.jsx
src/renderer/page/backup/view.jsx
src/renderer/redux/actions/app.js
yarn.lock

- Before users couldn't run the app if they had a different version of the sdk running than the one specified in the package.json.
- To help with this we just disabled that check in dev mode. 
- Now you can just click "Use Anyway"
- Also fixed flow errors.

Upgrade to 0.30.4 sdk, allow running with incompatible sdk version, improve flow support

---

src/renderer/modal/modalAutoUpdateDownloaded/view.jsx

Proposed more concise upgrade prompt. Do we need to say upfront a restart is required or is the implication enough?

Simplify upgrade text

---

src/renderer/redux/selectors/app.js

update: use 'home' icon for 'explore' tab on side bar

---

src/renderer/scss/component/_media.scss

On some cards, the background would expose itself when the app was being resized.
Background nolonger exposes itself when the app is resized.

Thumb Background Fix

---

package.json
src/renderer/index.js
yarn.lock

Can now point search to a custom endpoint with:
```
SEARCH_API_URL="http://localhost:800" yarn dev
```

 allow updating search api with env

---

CHANGELOG.md
src/renderer/component/fileViewer/internal/player.jsx
src/renderer/component/fileViewer/view.jsx

Issue Number: #2240
When you finish a video and navigate back to it, the video starts at the end. 
When you finish a video and navigate back to it, the video starts at the beginning.

fix #2240: reset time to zero on file end

---

src/renderer/component/common/yrbl.jsx
src/renderer/component/firstRun/view.jsx
src/renderer/page/subscriptions/internal/first-run.jsx

The first run view on subscriptions wasn't using the new `<Yrbl />` component.

fix: yrbl style on subscriptions page

---

CHANGELOG.md
src/main/createWindow.js
src/renderer/index.js

Tested on Windows, but it should work on Mac too (Sean to verify). For Linux, we'd need Electron 3+ (https://github.com/electron/electron/pull/15441)  or https://github.com/jostrander/mouse-forward-back

feat: add mouse back/forward navigation

---

CHANGELOG.md
src/renderer/redux/actions/publish.js

Also, decided to reset the publish status. Unless we know for sure know it's a spee.ch issue, we should let them upload again (what If i selected an mp4 or another unsupported type?) They can still manually choose the manual URL method.

fix: missing spee.ch error

---

CHANGELOG.md
src/renderer/redux/actions/content.js
src/renderer/scss/component/_modal.scss

Pass the download error message from SDK and fix up new line formatting on modals. We aren't using the timeout modal, but leaving in because we should use a special one for download failures in the future.

fix: pass error message

---

src/renderer/component/fileViewer/internal/player.jsx
src/renderer/redux/selectors/app.js

The games code removed a line that correctly showed a message saying "No preview available" for certain files.

fix: show 'no preview available' for files correctly

---

src/renderer/component/channelTile/view.jsx
src/renderer/component/common/yrbl.jsx
src/renderer/component/fileCard/view.jsx
src/renderer/component/fileListSearch/view.jsx
src/renderer/component/fileTile/view.jsx
src/renderer/component/recommendedContent/view.jsx
src/renderer/page/file/view.jsx
src/renderer/page/search/view.jsx
src/renderer/page/show/view.jsx
src/renderer/redux/reducers/navigation.js
src/renderer/scss/component/_button.scss
src/renderer/scss/component/_media.scss
src/renderer/scss/component/_placeholder.scss
src/renderer/scss/component/_search.scss
src/renderer/scss/component/_yrbl.scss
yarn.lock

- Add yrbl to search page when no content is found
- More precise placeholders so there is no content jumping
- Cleaned up a lot of styles in _media.scss with two main goals
- Less complicated nesting of styles
- Easier to reason about font sizes for cards/tiles

clean up file{card,tile} for simpler small/large adjustments and better placeholder behavior

---

package.json
src/renderer/component/fileViewer/internal/player.jsx
src/renderer/component/viewers/audioVideoViewer.jsx
src/renderer/scss/component/_button.scss
src/renderer/scss/component/_file-render.scss
yarn.lock

- Web app doesn't break when you try to watch a video (still doesn't play though)
- Flow coverage on `src/renderer/fileViewer/internal/player.jsx`
- Don't explicitly render audio different from video if they use the same player

fix: load correct video player on web

---

src/ui/component/wunderbar/view.jsx

Just noticed that an error message was slightly incorrect (AFAIK lbry URLs can use numbers) so I fixed that.
Issue Number:
Numbers weren't mentioned.
Numbers are mentioned.

Fixed error message to include numbers

---

src/ui/component/fileRender/view.jsx
src/ui/component/fileViewer/internal/player.jsx
src/ui/component/viewers/pdfViewer.jsx
src/ui/scss/component/_file-render.scss

There isn't a good way to open pdf's in the app currently. I've added some new styles and js to open these with the OSes default viewer. I think this is something we should do for other file types (probably docx too).
We could have a list of file types that you can open in other programs, most likely limited to files that are usually opened in a standard application.
PDF's are probably one of the files that we _should_ be able to to view in the app, because it's so simple in the desktop, but a pain due to https://github.com/electron/electron/issues/12337
Will definitely break on web. I might move other files to this new viewer when I fix it there, but just getting this in for the app release.

fix: open pdf's externally

---

.travis.yml
azure-pipelines.yml
electron-builder.json
package.json
yarn.lock

This will also support differential updates on Windows. Tested and working successfully, but would like to go through a final round during RC testing. On Mac, it falls back to default download. I think that's only supposed on nsis-web for Mac, something we can muck around with another time. Node v10 is required for electron-builder dependencies.

Upgrade SDK, node, enable differential updates (windows only)

---

src/ui/component/fileViewer/view.jsx
src/ui/page/file/view.jsx

Previous behavior: Paid content that was downloaded could not be viewed due to balance check.
New Behavior: insufficient balance Notification and overlay are disabled if fileInfo exists.

checks for downloaded paid content before disabling

---

src/platforms/electron/createWindow.js
src/platforms/electron/index.js

Previous behavior: opening from open.lbry.com link would open the app to the default front page.
New Behavior: opening from open.lbry.com will open the app to the desired claim or page.
Tested:
lbry://jiggytom -> jiggytom show page
lbry://?account -> account page
lbry://?subscriptions -> subscriptions
lbry://?notapage -> default home

open.lbry.com opens lbry to uri

---

src/platforms/electron/index.js

Restores mac open.lbry.com links. Seems to work with /claimName and /?pageName.

fixes mac openlinks

---

src/ui/component/publishForm/view.jsx
src/ui/component/selectThumbnail/view.jsx
src/ui/constants/modal_types.js
src/ui/modal/modalAutoGenerateThumbnail/index.js
src/ui/modal/modalAutoGenerateThumbnail/view.jsx
src/ui/modal/modalRouter/view.jsx
src/ui/redux/actions/publish.js

Issue Number: #1088 
When publishing a video a button appears on thumbnail section that opens a modal in which the user can seek through their chosen video and pick a frame to upload to spee.ch as thumbnail
I modified `doUploadThumbnail` to accept Arrays as `filePath` too

Thumbnail slider

---

src/ui/component/fileViewer/internal/player.jsx

Issue Number: #2508 
- Add a proper way to render non playable files after download is completed

Fix render logic of non-playable files

---

src/ui/component/fileActions/view.jsx
src/ui/component/fileViewer/internal/player.jsx
src/ui/component/fileViewer/view.jsx
src/ui/constants/icons.js
src/ui/index.jsx
src/ui/page/file/view.jsx
src/ui/scss/component/_content.scss
src/ui/util/full-screen.js

- Toggle video player on DoubleClick.
- Toggle fullscreen when pressing `f` #2159
- Can't exit full-screen from embedded content with key F11 #2514
- Full screen (f11) does not work for games (PDFs and images also) #2267
- Full screen Button Stops Working After Double Click #2392
- New button to toggle full screen mode of viewer.
- New shorcut to toggle fullscreen mode of viewer ( key:` f ` ).
- Fullscreen mode for all type of files.

Improve fullscreen mode of the viewer

---

src/ui/component/publishForm/view.jsx
src/ui/page/file/index.js
src/ui/page/file/view.jsx
src/ui/redux/actions/publish.js

Issue Number: #2531 
clicking edit on fileview page, loads publish page with file source selected (in case file is accessible)
for edits issued from publish page (i.e naming claim to an existing claim and editing it) thumbnail section notes user (if no thumbnail exists) to re-select their file again.

reselect file for publish edits

---

src/ui/index.jsx

Fixes #2544 
Not setting an expire time expires the auth token when the session ends.

fix: allow auth token to persist if the browser is closed

---

src/platforms/electron/createWindow.js

Issue Number: none
The LBRY app does not navigate backward or forward when using the dedicated back/forward keyboard or mouse buttons.
Back/forward keyboard and mouse buttons cause the LBRY app to navigate backward/forward.
The handlers for the 'navigate-backward' and 'navigate-forward' events introduced in #2250 look like they were removed at one point. So instead of firing those events upon receiving the back/forward app-command, I've rewritten it to call the window's WebContents goBack and goForward methods.
Tested on Windows 10 x64.

Fix back/forward navigation using dedicated mouse/keyboard buttons.

---

src/ui/scss/component/_channel.scss
src/ui/scss/component/_media.scss

Issue Number: #2317
The channel Title and Url text was overlaying the card.
Add `...` to the end of long titles.
I made a change as i've discussed on the dev-ux Discord channel.

Fix channel title and url overlay

---

src/ui/component/walletSendTip/view.jsx
src/ui/modal/modalConfirmTransaction/view.jsx
src/ui/modal/modalRemoveFile/view.jsx
src/ui/modal/modalWalletEncrypt/view.jsx

Issue Number: #2312 
.
The modal of send tips, encrypt wallet, transaction confirmation, and remove/delete file are now enterable.

Enable modal enter

---

src/ui/page/settings/view.jsx

Fixes issue #2334 
Issue Number: #2334 
Automatic dark mode can't turn on unless light mode is chosen first. 
be able to set that option regardless of the selected theme. If it is selected, it should not allow the theme to be changed.

Fix automatic dark mode.

---

src/platforms/web/server.js
static/index.html

Reverts lbryio/lbry-desktop#2546
@kauffj This broke the app when directly navigating to vanity urls, and short urls. So all share urls were busted.

Revert "Dynamic meta tags for content"

---

.travis.yml
package.json

This fixes https://github.com/lbryio/lbry-desktop/issues/1192, the bug where the SDK would not get terminated if the installer was run while the app was running. Also tested app build on Mac 10.13.6 (xcode 10) which is required now for code signing (https://github.com/electron-userland/electron-builder/releases/tag/v21.0.10). Per Julie, works fine with 10.12.5 OSX, which is good. Will confirm signing is working correctly.

maint: electron builder update

---

package.json
yarn.lock

I was checking if I could use [music-metadata-browser](https://github.com/Borewit/music-metadata-browser) with the audio-viewer, but I noticed it has been removed. 
Therefor this dependency is no longer required: jsmediatags
Related PR: #2447

Remove unused dependency jsmediatags

---

package.json

NPM package name must be lowercase: https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields

Fix illegal package name

---

src/platforms/electron/menu/setupBarMenu.js

Electron needs these menu items in order to bring shortcut keys into an app, at least on Mac.

adds selectAll to electron menu enabling CMD+A

---

src/ui/component/fileRender/view.jsx
src/ui/component/fileViewerInitiator/view.jsx
src/ui/scss/component/_content.scss
static/locales/en.json

App/Web - specific messages for unsupported content handling cases in Viewer and ViewerInitiator.

unsupported yrbl

---

src/platforms/web/server.js
src/ui/component/fileRender/view.jsx
src/ui/util/lbrytv.js
static/index-web.html
static/locales/pl.json

- fixes flash of `%%HEAD_TOKEN%%` on page load
- fixes incorrect serving of metadata for legacy URLs and potentially other cases (check out beta.lbry.tv/@brendonbrewer/3 prior to merge :man_facepalming:)
- adds video specific open graph metadata (#2806)

fixes several issues with lbry.tv metadata

---

src/ui/store.js

So the `playingUri` isn't persisted, which causes the pop-out player to play on refresh.

use contentFilter on web

---

src/ui/component/fileRender/index.js
src/ui/component/fileRender/view.jsx
src/ui/component/viewers/videoViewer/index.js
src/ui/component/viewers/videoViewer/view.jsx
src/ui/redux/selectors/content.js

This enables autoplay next, enabled by autoplay videos in settings. 
Missing features:
- separate autoplay on navigation control from autoplay next 
- prevent autoplay next related from going to non-media content types

Player stuff

---

src/ui/component/channelContent/view.jsx
src/ui/component/errorBoundary/view.jsx
src/ui/component/socialShare/view.jsx
src/ui/redux/actions/app.js

This happens randomly from file/channel pages or when the claim is not confirmed but accessed via wallet page.
+ Added note to use ctrl-R to refresh in cases the button doesn't work.

fix: crash on share modal

---

src/ui/component/commentCreate/view.jsx
src/ui/component/common/form-components/form-field.jsx
src/ui/constants/comments.js
src/ui/scss/component/_comments.scss

https://github.com/lbryio/lbry-desktop/issues/2859
No information about character count. Also no limit on the textarea for comments.
The new behavior is demonstrated in the below GIF.

Add char count and max char info near textarea of comments area

---

src/ui/redux/actions/file.js

This fixes not being able to abandon without first downloading the file.
I noticed the "go back" part is broken here and in the prod app...Sean can you see what's up there?

fix: abandoning without file

---

src/ui/redux/reducers/settings.js

This change will allow users to easly find their language even if they not know english very well.
App displays language names in English.
Now App display languages in native languages (ex. Polish = Polski)
So users can easly find their own language.

Renamed language names to their natives

---

src/ui/scss/component/_channel.scss

- [ x] Bugfix
Issue Number: #2948 
The Current behavior is on css use var(--font-heading), 
see this screenshot : 
So. For Alternative method i use xx-large css style to make this better than before i think.
like this screenshot below. my screen resulution is 1280 x 768

fix title on small screen

---

CHANGELOG.md
src/ui/component/tag/view.jsx

Issue Number: #2678
Escapes the generated link for tags by using `encodeURIComponent`

Escape link for tags

---

src/ui/scss/all.scss
src/ui/scss/component/_tooltip.scss

Incorrect styles of tooltip on dark theme #3031
There is a white border and spacing around the tooltip content visible when dark theme is active.

Fix tooltip styles

---

CHANGELOG.md
package.json
src/ui/component/cardMedia/FreezeframeLite/classes.js
src/ui/component/cardMedia/FreezeframeLite/index.js
src/ui/component/cardMedia/FreezeframeLite/styles.scss
src/ui/component/cardMedia/FreezeframeLite/templates.js
src/ui/component/cardMedia/FreezeframeLite/utils.js
src/ui/component/cardMedia/FreezeframeWrapper.jsx
src/ui/component/cardMedia/view.jsx
yarn.lock

Issue Number: #2029 
- GIFs play all the time, making the CPU/GPU work hard on GIF intensive pages
- GIFs only play if the user's mouse hovers over them. Tested using the `lbry://@3DPrinting` address.
<a href="https://cl.ly/bc1d8285a927" target="_blank"><img src="https://d2ddoduugvun08.cloudfront.net/items/1b242Q1L3f3o1O0G2Q3T/Screen%20Recording%202019-10-06%20at%2001.51%20AM.gif" style="display: block;height: auto;width: 100%;"/></a>
- I filed two feature requests to `freezeframe`, one to make the official react wrapper usable for our usecase (https://github.com/ctrl-freaks/freezeframe.js/issues/54), and the other to make sure that event listeners get cleaned up when the image is unmounted. …

[feature] Disable GIF animation unless user hovers

---

CHANGELOG.md
src/ui/component/viewers/videoViewer/view.jsx

- Can't exit full-screen from embedded content with key F11 #2514
- Toggle fullscreen when pressing `f` #2159
-  ~Gap between video player and background #3025~ ( unrelated )

Add keyboard shortcuts to toggle player fullscreen

---

src/ui/component/channelDiscussion/index.js
src/ui/component/channelDiscussion/view.jsx
src/ui/page/channel/view.jsx

Issue Number: #3005  #3047
Creates a new 'Discussion' channel tab. Uses the `?view=discussion` query param to access it by a URL, and stores the new Discussion tab at `tabIndex=2`.

Adds `channelDiscussion` to components & creates discussion tab

---

CHANGELOG.md
src/ui/component/claimListDiscover/view.jsx
src/ui/component/common/hidden-nsfw.jsx
src/ui/page/tags/view.jsx
src/ui/scss/component/_icon.scss
static/app-strings.json

Issue Number: 2703 (https://github.com/lbryio/lbry-desktop/issues/2703)
- No warning message that content might be hidden
- A message shows up in the UI near the top notifying the user that there settings might hide some content, and there is a link to go to the settings page and modify them.
- Although the ticket only asked for mature tags, the message is not too much in the users face so I thought it would be good to have it in the landing discover page, during tag searches, and during regular text searches:

add message to say content is hidden according to settings (2703)

---

src/ui/component/tagsSelect/view.jsx

useEffect was there to reenable customize screen if tags ever became 0 length, and was firing on the publish page. Chose to only trigger that on the dismissable version.

welcome tags only shows on 0 tags

---

package.json
src/ui/component/app/index.js
src/ui/component/app/view.jsx
src/ui/component/claimPreview/index.js
src/ui/component/claimPreview/view.jsx
src/ui/component/common/tooltip.jsx
src/ui/component/splash/view.jsx
src/ui/index.jsx
src/ui/modal/modalWalletEncrypt/view.jsx
src/ui/modal/modalWalletUnlock/view.jsx
src/ui/page/settings/index.js
src/ui/page/settings/view.jsx
src/ui/redux/actions/app.js
src/ui/redux/reducers/settings.js
src/ui/redux/selectors/settings.js
src/ui/store.js
src/ui/util/saved-passwords.js
static/app-strings.json
yarn.lock

- manually reverts #3001
- removes @reach/tooltip and temporarily hides claim preview tooltips
- They were causing the app to crash even more than normal and am unsure of the real fix for now
- Removes `cookie` npm module and add utils to write/delete cookies

Release blockers (warning - it's ugly in here)

---

src/ui/component/splash/view.jsx
src/ui/modal/modalWalletUnlock/view.jsx

This scenario should only happen in rare instances and calling wallet_unlock will clear it up.

fix: blank password bug

---

src/ui/component/cardMedia/view.jsx

Does not fix anything already in an issue.
However, it does fix behavior for thumbnails whose `src` URLs contain single quotes.
Thumbnail images which have URLs containing `'` are broken and do not show up.
An example is as follows:
The behavior for a thumbnail URL like `https://sesamestrong.github.io/lbry-desktop/google's%20logo.png` is that **the thumbnail does not show up**; the CSS rule changes from `background-image: url('https://sesamestrong.github.io/lbry-desktop/google's%20logo.png')` to `background-image: url((unknown));` because there is an extra `'` in the URL, which breaks CSS parsing.
The new behavior is that the CSS rule for URLs with `'` has every `'` in the URL replaced with `\'`, …

Sanitize urls with single quotation marks

---

src/ui/component/tagsSearch/view.jsx

Issue Number: #3109, #3096
tags are not normalized and duplicates are not dealt with when adding new tags.
tags are now normalized when entered, and duplicates of tags when adding multiple (e.g "tag,tag") are removed (just adds "tag" once instead of twice).

Fix tag normalization and duplication

---

src/ui/component/fileRender/view.jsx

Issue Number: #3124 
htm files are not opened in-app, while html files are
htm files are also opened in-app
resolves #3124

fix: view htm files with HtmlViewer

---

src/ui/component/viewers/videoViewer/view.jsx

fixes flow error in the player by removing unnecessary `null` declaration
Issue Number: #2024
Flow Failure in this file
Flow Success in this file

fix flow error in player

---

src/ui/component/tagsSearch/view.jsx

Issue Number: N/A (Should I create an issue?)
If no tags are passed in, then the prop is undefined and an exception causes the entire page to error out, since a map operation cannot be done on an undefined variable.
Undefined prop defaults to empty array, and the page loads successfully.

fix(tagsSearch): Undefined tagsPassedIn prop prevents page from loading

---

src/ui/component/sideBar/view.jsx

Issue Number: #2024
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/ui/component/sideBar/view.jsx:71:22
Cannot create li element because in property key:
• Either React.Element [1] is incompatible with string [2].
• Or React.Element [1] is incompatible with number [3].
src/ui/component/sideBar/view.jsx
[1]  60│                   <>
61│                     {__('Publishes')}
62│                     <Spinner type="small" />
63│                   </>
:
68│               ),
69│             },
70│           ].map(linkProps => (
71│             <li key={linkProps.label}>
72│               <Button {...linkProps} className="navigation-link" …
```

fixes flow issue in sidebar by dynamically building link key

---

src/ui/constants/licenses.js

This license is used for many presentation recordings. It would be great to have the license supported by the application directly and avoid constantly looking for the license link.
I know that adding licenses could be a controversial issue but this would be a small help for me to have smoother uploads of the videos to LBRY. If you don't agree that CC-BY 3 should be part of the common known licenses than feel free to close this. I won't be mad about that :).
Missing CC-BY v3 license in the list of licenses.
Add this license to the list.

Add Creative Commons Attribution 3.0 license

---

CHANGELOG.md
package.json
src/ui/redux/actions/app.js
yarn.lock

Issue Number: #3141
Sometimes a support can get locked up due to having a larger wallet / sdk connectivity issues, and when this happens, you can't send any other supports because the send button is greyed out.
Clearing the cache will dispatch an action, `CLEAR_SUPPORT_TRANSACTION`, which will set the sendingSupport state to false.
🚨 This PR on lbry-redux will need to be merged first for this to work. 🚨 
https://github.com/lbryio/lbry-redux/pull/231

feat(settings): Clear support state when clearing cache

---

src/ui/component/walletAddress/index.js
src/ui/component/walletAddress/view.jsx
src/ui/component/walletSend/index.js
src/ui/component/walletSend/view.jsx

Issue Number: #3143
You have to use the back button or one of the navigation steps to home/other pages to leave the send/receive pages.
New X button on the cards on the pages will send you back to where you came from.
This works on both the electron and web apps.

feat(wallet): Added close buttons on send/address pages

---

static/app-strings.json

Issue not documented separately.
The word "across" is misspelled as "accross"
Proper spelling of "across"
I'm not sure if changing the JSON key is going to cause breakage... this is my 1st attempt at patching LBRY. I'd welcome some feedback or additional information on how to validate the change!

Fix a typo s/accross/across/

---

ui/component/channelEdit/view.jsx

Issue Number: #3217 blank tags
Clicking add button for tags on channel edit page results in adding a blank tag and pressing enter updates the channel with no prompt.
Tags can be added/removed both by clicking and hitting enter. It just works but I'm not sure if I did it in the right way for handling enter key press.

fix: blank tags added on channel edit page

---

electron/createWindow.js
package.json
ui/component/embedArea/view.jsx
ui/component/settingAutoLaunch/index.js
ui/component/settingAutoLaunch/view.jsx
ui/constants/settings.js
ui/index.jsx
ui/page/help/view.jsx
ui/page/settings/view.jsx
ui/redux/actions/app.js
ui/redux/actions/settings.js
ui/redux/reducers/settings.js
ui/util/autoLaunch.js
yarn.lock

autoLaunch on startup

---

ui/component/claimListDiscover/view.jsx

Use trending group instead of trending global. Mixed already takes into account global. This index is now available on the wallet servers.

fix: adjust trending

---

lbrytv/package.json
lbrytv/webpack.config.js

The fix is running babel on node_modules with a new plugin to transpile `...` into `Object.assign()`. Also removing the `css-doodle` import on the sidebar. It isn't supported on edge but it wasn't being used anyway.

actually fix lbry.tv on edge

---

ui/modal/modalPublish/view.jsx
ui/scss/component/_card.scss
ui/scss/component/_claim-list.scss

I'm not sure what this styling was supposed to be doing previously, but faded plus no-click-indicator seems to make the most sense for pending content.

preview styling fix yolo'd from github UI

---

ui/scss/themes/dark.scss
ui/scss/themes/light.scss

This makes @eggplantbren's article https://lbry.tv/@BrendonBrewer:3/trending:a readable from lbry.tv
While this fixes that case, it also makes me wonder why this rule existed as it did. Are there cases that `<DocumentViewer>` should have a dark background?

change file viewer background color

---

ui/component/viewers/videoViewer/view.jsx

Programatically calling `play()` on the video element instead of passing the `autoplay` prop to the element seems to work better on chrome.
Firefox and Safari is still blocked until users manually allow lbry.tv to autoplay with sound. Either we will need to mute, or turn autoplay off in those cases.

when this is merged autoplay on chrome will be better

---

CHANGELOG.md
ui/component/claimPreview/view.jsx
ui/component/uriIndicator/view.jsx

Only the `@channelName` url can be clicked in the file page.
The channel thumbnail on the file page is clickable and directs you to the user's channel, if any.
- Turning the channel title into a clickable link made the rest of the UI appear inconsistent and errant, and is thus left as before.
- `UriIndicator` accepts any arbitrary Node and wraps a button around it.

Makes channel thumbnails clickable on file page 

---

package.json
static/app-strings.json
ui/component/app/view.jsx
ui/component/common/nag.jsx
ui/component/openInAppLink/index.js
ui/component/openInAppLink/view.jsx
ui/modal/modalYoutubeWelcome/view.jsx
ui/scss/all.scss
ui/scss/component/_card.scss
ui/scss/component/_splash.scss
ui/scss/component/nag.scss
ui/scss/component/tabs.scss
ui/scss/themes/light.scss
ui/util/url.js
yarn.lock

- Hides `src=open` from url
- Users coming from open.lbry.com will see this new prompt
- Only shown for users on a desktop computer or android phones
- Web only users will not see this message again when they close it.
I think this is just step 1 for this feature. Additional stuff could be remembering your choice and opening the app automatically, redirecting to the playstore/lbry.com/get if you don't have the app installed, but both of those seemed to have a few edge cases so I'd rather just get this in now to see if it does anything.
I didn't end up doing the mobile style since it would be thrown away and I think it stands out enough to be seen as is.
Also not sure what the copy should be.

Add open in app link when coming from open.lbry.com

---

CHANGELOG.md
static/app-strings.json
ui/component/dateTime/view.jsx

Tested a few channels and it seems like all the dates are the same as they are listed on youtube.

When this is merged, dates on claim previews will be the same as youtube

---

ui/component/tagsSearch/view.jsx

apparently the spread syntax [ ... new Set( someArray ) ] works in the nodejs repl, works in the chrome browser, but perhaps our babel plugin set is not perfect yet.
replaced with the more common Array.from(new Set(x))

fix strange tag values

---

package.json
static/app-strings.json
ui/component/settingWalletServer/index.js
ui/component/settingWalletServer/view.jsx
ui/component/splash/view.jsx
yarn.lock

- removes daemonSettings, fetchDaemonSettings as unnecessary
- on unmount, if available_servers is 0, clear to defaults
- modify splash behavior to reset even when wallet is_running 
- (control R after clearing servers could have been bad)
- add connecting... state
- no longer show or expect user to delete every default wallet server on switching to custom
Requires https://github.com/lbryio/lbry-redux/pull/255

improves wallet server ux and resilience

---

.travis.yml
electron-builder.json
electron/Daemon.js
webpack.electron.config.js

I was having a ton of issues electron-builder not letting me ignore the daemon files when it started bundling. I changed the webpack build to output the daemon files to their own folder, so it was easier to copy in electron-builder

Bundle headers with app

---

ui/component/fileViewer/view.jsx

Fixes "Video player out of whack after resize of window #3423" by adding event listeners prior to cleanup.
Issue Number: #3423
Does not properly resize video in response to window resizing.
Properly resizes video in response to window resizing.
I've tested the fix on Ubuntu desktop. This is my first time contributing to this project, please let me know if I should test elsewhere.
Feedback welcome.
(Broken)
(Broken)
(Fixed)

Fixes "Video player out of whack after resize of window #3423"

---

ui/util/remark-lbry.js

Only links with either matching, or open LEFT parentheses are allowed. These are the same rules that github use for this as well.
Issue Number:
Links are not allowed to have parentheses, which breaks some links which do have them
Parentheses are allowed in links in certain cases: there must be equal or more opening parentheses to closing parentheses. This is the same way that github deals with this issue

Allow parentheses in certain links

---

package.json
ui/component/claimList/view.jsx
ui/component/header/index.js
ui/component/header/view.jsx
ui/component/syncPassword/index.js
ui/component/syncPassword/view.jsx
ui/scss/component/menu-button.scss
yarn.lock

Before, we were always saving passwords to be used later, even if the sync call ended up failing, which would cause them to need to enter the password again.

Add email to header and only save passwords if they are correct

---

ui/component/common/markdown-preview-internal.jsx

- **Read as: I clicked a bunch of links on the desktop and web apps, please review carefully**
Issue Number: #3383
Please see the image below as a reference for the inspection images to follow.
When using @(some_user) in a comment, both the desktop app and lbry.tv use the following style.
This works on the desktop app but prompts the lbry.tv user to open up the desktop app which is not the desired behavior.
The desktop app continues to open these links in the desktop app, though the link path is different.
The lbry.tv app now opens these links in the user's browser.
I've got three concerns.
1. With the added code, I don't know if "SimpleLink" is fitting anymore.
2. I've got a hunch that there is …

Fixes #3383 by formatting lbry links differently

---

ui/component/channelCreate/index.js

Removes unused redux actions from `channelCreate/index.js`

Removes unused redux actions 

---

ui/scss/component/_file-render.scss

- [ x] Bugfix
When a video is fullscreen the cursor stays there. Also it changes to a hand.
The cursor is now hidden on full screen video playback as long as the mouse is inactive. The cursor only changes from a pointer to the hand when over the playback menu or when hovering over the big play button in center of screen.

Hide cursor on fullscreen

---

ui/page/channel/view.jsx

Issue Number: #3306
When a user is editing their own channel and clicks on a channel they're subscribed to, it looks like they're editing the channel they don't own. This appears to only happen if the other channel is already "cached" (if user has already clicked on this channel during app execution).
**Editing own channel**
**"Editing" other user's channel**
Once you click on a channel you don't own, you'll be taken out of editing.
@kcseb mentions the possibility of prompting a user to save or discard their changes. If this is preferred over just navigating to the selected channel (current behavior), I'd be happy to add this.

Don't Show Edit Screen for Other Channels

---

static/app-strings.json
ui/component/header/view.jsx
ui/page/fileListPublished/index.js
ui/page/fileListPublished/view.jsx
ui/scss/component/_button.scss
ui/scss/component/_card.scss

Issue Number: #3348
Font size of cancel button set to `--font-small`.
The publish form is **not** cleared by the following actions.
1. User clicks the "New Publish" drop-down item from the Navigation bar.
2. User clicks the "Publish something new" button when they go to their publishes and have not published previously.
3. User clicks the "New Publish" link when they go to their publishes and have already published content.
Font size of cancel button set to `--font-large`.
1. Has changed to just "Publish" and continues its behavior of not clearing the form.
2. Now clears form on click.
3. Now clears form on click.

Choosing "New Publish" Now Clears the Publish Form

---

ui/page/channel/view.jsx

Issue Number: #3303
User cannot navigate text in a channel search field due to the left and right arrow keys changing tabs.
*Image displaying the search field*
User can navigate text in a channel search field using the left and right arrow keys.

Navigate Channel Search with Arrow Keys

---

ui/page/channel/view.jsx

Issue Number: #3502
When searching for content within a specific channel, the channel ID for the query gets "stuck". The search results returned will be equal to the last unique channel visit. 
Ex.
User views channels A -> B -> C -> D -> E. At this point if the user uses the search field for channels A, B, C or D they'll see results for channel E.
Steps to reproduce:
1. View channel JordanBPeterson
2. Search channel content using the word "oh"
3. (observe expected) Results shown for only channel JordanBPeterson
4. View channel JohnStossel
5. View channel JordanBPeterson
6. Search channel content using the word "oh"
7. (observe bug) - Results shown for channel JohnStossel
The search will only return content that belongs to the channel being viewed.
*Image of Search Field in Question*

Fixes #3502 by Changing the Way We 'Queue' Search Queries

---

ui/component/common/file-selector.jsx

Issue Number: #3490 
If you select a file (on the publish screen), then clear the form and try to select it again, it won't select
You are able to select it on the second try now.
I've checked that these changes don't break any other places that the FileSelector component is used.

Clear the internal file selector after `clearPublish`

---

ui/page/channel/view.jsx

Issue Number: #3507
When no results are returned, the user just sees an empty section.
When no results are returned, the user will see a message saying "no results".
I noticed the styling of returned results was off when searching a channel. I dug around and saw that we could use ClaimList here, this fixes both the styling and the 'no results' issue.
*Current Search Styling*
*New Search Styling*

Add "No Results" Message When Searching Channel Content

---

electron/index.js
ui/index.jsx

I didn't realize older users were missing the auth_token cookie. So this just puts back old code, plus sets the auth token cookie so they will be set in the future.

fallback to keychain for auth_token if desktop users don't have an auth_token cookie

---

ui/component/channelCreate/view.jsx
ui/component/publishName/view.jsx

Issue Number: #3521
When editing the LBC amount on various forms by using the mouse wheel, the page scrolls along with the amount.
When the user is focusing on the LBC amount form element, don't scroll the page when the mouse wheel moves.

Mouse Wheel to not Scroll Page While Editing LBC Amount

---

build/afterAllArtifactBuild.js
build/signBuildFiles.js
electron-builder.json
package.json

- Adds an "after build" script to delete files that we don't want listed under a release. These are currently being manually deleted before we publish a release
- Adds a script to sign releases. This does everything I was manually doing to sign a release. I would like to have it automatically upload the file to github but that's more work. For now it will just spit out a file in `dist/` and then that will need to be uploaded manually

Two helpful scripts

---

ui/component/claimListDiscover/view.jsx

This at least would work on the new/trending + all content page until the SDK Fixes it.

fix: temp hack for future content

---

ui/scss/component/_media.scss

Issue Number: #3563 
URL overflows, preventing the user from accessing buttons.
Text overflow is hidden, allowing user to access buttons.

Hide Text Overflow for Long URLs in Mini Player

---

CHANGELOG.md
ui/component/claimPreviewTile/view.jsx
ui/component/fileDownloadLink/view.jsx
ui/scss/component/_claim-list.scss
ui/scss/init/_gui.scss

Issue Number:  #1676
There's no easy way to prepare content for later. Say I'm on the Explore page and I discover several videos I want to watch, but before watching I want to scroll through the Explore page to see if there's anything else I want to watch too. I either have to try to remember everything so I can click through it later, or I have to click into each video and press download so it gets stored in the Downloads of My LBRY. That's a lot of unnecessary back and forth clicking though.
When hovering over thumbnails a 'download' button should appear, clicking it downloads the content in the background while you continue exploring.

Added Download Button on hover for the thumbnail

---

ui/component/claimPreview/index.js
ui/component/claimPreview/view.jsx
ui/component/claimSubtitle/index.js
ui/component/claimSubtitle/view.jsx
ui/component/claimTitle/index.js
ui/component/claimTitle/view.jsx

I'm going to be moving a few things around to add new labels/buttons for resposts so I figured I would create this now to make the actual repost PR smaller

create more claim components to simplify ClaimPreview

---

ui/component/viewers/videoViewer/view.jsx

Issue Number: #3498 
On Firefox the video player's full-screen button maintains the focus after being clicked. This means that subsequent presses of the space bar will toggle full-screen mode. This behavior is inconsistent with both the app and chrome-based browsers.
Blur the active element after entering or exiting full-screen mode. This means that after pressing the full-screen button in Firefox, the space bar will control whether the video is paused or playing.

Prevent Space Bar from Toggling Full-Screen on Firefox

---

ui/redux/reducers/subscriptions.js

simply replaces subscriptions on populate
treat sdk preferences and sync as source of truth

fix desktop overwriting subscriptions in shared prefs

---

CHANGELOG.md
ui/component/claimPreview/view.jsx
ui/scss/component/_claim-list.scss

Issue Number: #3200 
Claims, when right-clicked, do not display a link-like context menu
Claims can be opened in new tabs via middle click and right click brings up an appropriate context menu

Fixes #3200 Claim previews right-clickable

---

static/app-strings.json
ui/component/abandonedChannelPreview/index.js
ui/component/abandonedChannelPreview/view.jsx
ui/component/claimList/view.jsx
ui/component/claimPreview/view.jsx
ui/component/splash/view.jsx
ui/page/channelsFollowingManage/view.jsx
ui/page/show/index.js
ui/page/show/view.jsx
ui/redux/actions/app.js
ui/redux/selectors/subscriptions.js
ui/scss/component/_claim-list.scss
ui/scss/themes/dark.scss
ui/scss/themes/light.scss

In manage, abandoned channels show up unfollowable.
Clicking on an abandoned channel shows a rudimentary card with unfollow.
Draft:
Cards need better style and buttons.
Components may be rearranged.

provide ability to unfollow abandoned channels

---

static/app-strings.json
ui/redux/actions/file.js

For whatever reason, dispatching connected-react-router.goBack() didn't work in batched actions.

navigate back after delete if abandoned

---

static/index-electron.html
ui/component/layoutWrapperText/view.jsx
ui/component/viewers/codeViewer.jsx
ui/component/viewers/htmlViewer.jsx
ui/redux/selectors/content.js
ui/scss/component/_main.scss
ui/scss/component/_markdown-editor.scss
ui/scss/component/_syntax-highlighter.scss

Just a few changes for the text viewer (the one which looks similar to Medium)
List of changes:
Other things: (figured i'd put them in the same pr rather than making two new pr's)

A bunch of cosmetic changes surrounding "text" files.

---

ui/component/transactionList/index.js
ui/component/transactionList/view.jsx

Currently exporting your transactions only exports the filtered list of transactions, or the first page.
All transactions are downloaded - ignoring any filtering.
The breaking change here is that the export button exports all transactions, the previous functionality of filtering may be desired by some people.
I feel, however, that most people will want to download the whole data set and filter it themselves in an external program.

Download all transactions in CSV

---

ui/scss/component/_main.scss

Issue Number: #3665 
Markdown content is on 40em width even on mobile
Markdown content now has a width of 100%
I haven't actually been able to test this yet (still need to reinstall linux), but i've thought it over for a while, and it makes a lot of sense.

Add extra media style

---

ui/scss/component/_file-render.scss

This commit changes the colors of the play button on the embed video player to blend better with other websites. This relates to Issue #3706
Issue Number: #3706
uses LBRY branding always
neutral color for the play button and then LBRY branding on hover
I would point out that the portion for the Hover color applying the opacity should work if the variable output is RGB but if it is HEX then it likely wont work. I didnt find the main variable location in my scan so its on an assumption.
If the variable color uses HEX then I would suggest putting it hardcoded like the following:
background-color: rgba(37, 119, 97,0.6);
I am not sure if this is the best approach based on your structure and I also don't know if the way I added it was how you wanted …

improved color scheme for embed player

---

ui/scss/component/_file-render.scss

This fix addresses a problem with the color variable "var(--color-primary)" being used in the hover element. The output of the variable is not compatible with the rgba modification from the previous code. This commit fixes this bug in relation to Issue #3706
Issue Number: #3706
color-primary variable is not compatible with the rgba element so the bug is that it disables the icon background.
This fixes so the LBRY branding color is used correctly for the icon background.

fixed a variable conflict for embed play button

---

ui/scss/component/_channel.scss

Issue Number:
Currently for channels with long names (Lbry.social) when the name wraps to 3 lines, the quick-action buttons become unclickable - specifically on mobile.
Clickable quick-actions on small screens
Not sure if the padding was fixing a specific issue? I can't find any issues with various length channel names.

Remove max-width channel header padding for small screens

---

ui/redux/actions/app.js

lacking sdk prefenence_clear leads to strange results bringing in preferences
do not set daemonSettings that are 'null'

do not apply daemonSettings that are null

---

ui/component/app/view.jsx

Issue Number: #3744 
Forward and backward mouse buttons do not navigate history.
Forward and backward mouse buttons *should* navigate history
I don't have forward and backward mouse buttons so I tested using the middle button and right click button. After testing I updated the buttons to properly reflect forward and backward. I'm using [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button) as a reference. **If someone can test this, it would be much appreciated**.
*Note: I'm not sure what other functionality these buttons are supposed to provide. For example if they can be used to fast-forward or rewind a video, I do not know.*

Fix Forward and Backward Mouse Buttons

---

ui/page/search/view.jsx

Once parseURI can handle the spaces / return if the URI is valid, we can remove that part and the try/catch.
Fixes https://github.com/lbryio/lbry-desktop/issues/3690 / https://github.com/lbryio/lbry-desktop/issues/3293

fix: valid URL handing in wunderbar

---

README.md

With the absence of Choffee and Iutye, I've removed them and replaced them with myself as I (and very, very rarely ProfessorDey / some other community members)) maintain the Flatpak builds now. 
Additionally, I swapped over my URL from GitHub to Keybase to better point towards places to find me.
Removed the checklist as this is just a quick change to the readme. Nothing core/functional, heh.

Updated README.md to reflect active community maintainers

---

ui/index.jsx
ui/util/saved-passwords.js

- Cookies are no longer set with `.lbry.tv` domain so they aren't accessible from player.lbry.tv, where html scripts are loaded and ran as is
- Users who open player.lbry.tv links could lose their auth token (and funds)
- Deletes old .lbry.tv cookies and replaces them
- Now able to signout properly when running app in dev mode
- Perpetual cookie refresh if users have accessed site (the fix just happened to cause this - not sure if we should keep it?)

Fix cookie security issue

---

ui/scss/init/_gui.scss

@seanyesmunt I spent a minute or two and couldn't think of or find a good reason why `user-select: none` was on all inputs. 
Do you know? It's not (at least anymore) for the copyable inputs. So I just removed it.

fix selection on firefox

---

ui/component/tagsSearch/view.jsx

Found that tag suggestions were removed if they were in followed list, but not if they were in unfollowed list.

remove selected tags from suggestions

---

package.json
ui/component/splash/view.jsx
yarn.lock

Check is_syncing while loading the app so we don't try to refresh the wallet / show error message.
Need 0.67.1 for a transcoding fix, but we can build RC2 now.

Sync status and SDK upgrade

---

package.json
ui/component/publishFile/index.js
ui/component/publishFile/view.jsx

uses publish reducer instead of react hooks to store results from file checking across page navigations.

save optimize check to fix publish navigation file reloading

---

ui/component/fileActions/view.jsx
ui/constants/claim_search.js
ui/page/discover/index.js
ui/page/discover/view.jsx

quick fix because the page isn't working
we were doing a claim_search before the reposted uri was resolved, which was causing issues. It would be nice to accept a reposted_uri too, but merging this since it fixes the page

use claim_id for reposts page instead of uri so we don't have to resolve before

---

ui/component/fileRender/view.jsx
ui/component/viewers/documentViewer.jsx
ui/component/viewers/videoViewer/view.jsx
ui/page/embedWrapper/view.jsx

We were calling `file/view` on load, instead of waiting for the video to start playing.
I tried to hook into the new FileRender logic, but I had a lot of issues with the styling. The embeds also work quite a bit differently than other videos. We render the actual `<video />` element in a paused state, instead of a placeholder div with the thumbnail.

fix viewcount being fired before video starts playing

---

lbrytv/package.json
lbrytv/src/routes.js
lbrytv/yarn.lock
package.json
ui/component/viewers/videoViewer/view.jsx
ui/util/lbrytv.js
yarn.lock

fixes #3856
fixes #3961
View events weren't firing because the streaming URL changed after the first render for new users, which caused the player to re-render and the listeners weren't added correctly. 
I thought I just needed to move the continent cookie stuff to the server, but the actual issue was that those listeners weren't being attached properly from the beginning.

fetch continent cookie on server-side and clean up video effects

---

ui/scss/component/_file-render.scss

Closes #3948
Issue Number: 3948
The bottom of portrait images get cut off.
The image is scaled to fit in the viewing area.

Make images scale properly in lbry.tv.

---

ui/page/settings/view.jsx

- [] Refactoring (no functional changes)
Fix the text displayed in other languages
Issue Number:
With the current english string there is a problem with the translation in other languages. For example in other languages current english text would be: "You have blocked channels 10" instead of "You have 10 channels blocked." Also, what happen when there si no blocked channel? So, I think the simpler form is better in this situation.
Instead of "You have x blocked channles. Manage" will be displayed "Blocked channels: x Manage"

Change text displayed for blocked channels

---

ui/component/viewers/comicBookViewer.jsx
ui/constants/file_render_modes.js

Issue Number: #4001
I have no idea how to enable this on lbry.tv since comic-book files are always  detected as `app` media type.

Fix comicbook reader ( desktop app )

---

ui/component/button/view.jsx
ui/component/subscribeButton/view.jsx

Issue Number: #2677 
When hovering over the unsubscribeButton it changes size. This leads to glitchy visual behavior when hovering over part of the unsubscribeButton's heart icon.
The unsubscribeButton stays the same size when hovered over.
This PR introduces the following issues that must be fixed before this PR is merged:

Fix #2677 glitchy subscribe button

---

ui/component/viewers/imageViewer.jsx

Show error message if image is not able to be displayed by browser.
Issue Number: #3993
If a browser cannot display an image (such as Safari and WebP images), then an empty box is displayed in place of the image.
If a browser cannot display an image, an error message is displayed in a Card.

First attempt to fix #3993. 

---

ui/component/fileRender/view.jsx
ui/component/viewers/comicBookViewer.jsx

Partial fix for #2024
Issue Number: Partial fix for #2024
Flow errors.
No more flow error for this part of the code.
Note that "fileExtension" was not being used in ComicBookViewer, so I removed it and now pass downloadPath directly instead of as part of an object, for simplicity.

Fix flow error.

---

ui/component/header/view.jsx

- Clicking the header logo will refresh the page if location is `/`, otherwise, redirect to `/`.
Issue Number: #3710 
- Header logo redirects to `/` if the location is not `/` and scrolls to the top of the page.
- Header logo refreshes the page if the location is `/`, otherwise, redirect to `/`.

Header Logo Reloads At "/"

---

ui/scss/component/_file-render.scss

Closes #3813
Improves existing functionality.
Issue Number: #3813
Displays remaining time of video 
Displays the elapsed time along with the total time with a "/" in between

Show elapsed/total instead of the countdown to the end in video player.

---

CHANGELOG.md
ui/component/subscribeButton/view.jsx
ui/effects/use-hover.js

- The hover `useEffect` hook in `/ui/effects` is now more reliable.
- The subscribe button is optimized for both desktop and mobile.
- Doesn't completely fix but improves the situation of the de-sync issue.
- Removed some redundant code and cleaned the subscribe button component.
```js
if (__('Following').length < __('Unfollow').length) {
longestStr = __('Unfollow');
}
```
Issue Number: #4048 
- The title of the subscribe button may get out of sync if used too fast.
- It cannot recover from the de-sync.
- Hover events are fired on mobile devices too and they may affect the UX.
- It is much more difficult for the subscribe button to get out of sync.
- Even if it gets out of sync, it can recover …

Better Hover, Subscribe Button

---

ui/redux/actions/content.js

Closes #4057
Issue Number: #4057
If "Always confirm before purchasing content" is selected in settings and the currency for "Only confirm purchases over a certain price" was previously set to USD, then an unnecessary check for exchange rates is occurring.
The exchange rate is only checked if "Only confirm purchases over a certain price" is selected and the currency set to USD.
Thanks to @seanyesmunt for commit https://github.com/lbryio/lbry-desktop/commit/dcb79685bc25cf3bc77d434255063fc4933cdf44 which fixes part of #4057 as well.

Fix purchase confirmation logic

---

ui/component/publishFile/view.jsx

Changed "Your video may not be the best format. Use MP4s in H264/AAC format and a friendly bitrate (720p) for more reliable streaming." to "Your video may not be the best format. Use MP4s in H264/AAC format and a friendly bitrate (under 5 mbps) and resolution (720p) for more reliable streaming." and changed the two times it says this "For video content, use MP4s in H264/AAC format and a friendly bitrate (720p) for more reliable streaming." to "For video content, use MP4s in H264/AAC format and a friendly bitrate (under 5 mbps) and resolution (720p) for more reliable streaming."
-Text changed
Issue Number:
(None)
It prints some text.
It prints slightly different text.
Sorry if I didn't fill out …

Changing some text on the publishing page

---

CHANGELOG.md
ui/component/blockButton/view.jsx
ui/component/shareButton/view.jsx
ui/component/subscribeButton/view.jsx

Issue Number: #4085 
No tooltip displayed for share, follow/unfollow, block/unblock buttons.
Tooltip is now displayed for share, follow/unfollow, block/unblock buttons.

Adding tooltip to share, block, and follow buttons.

---

CHANGELOG.md
ui/component/viewers/videoViewer/index.js
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx

PR Checklist
Issue Number: #2775
Videos start playing at beginning of the video.
Video position is saved when being played. If a previously viewed video is played again, it starts at the saved location.

Save media position in video viewer

---

CHANGELOG.md
ui/component/fileRenderFloating/view.jsx
ui/effects/use-persisted-state.js

Issue Number: #3926 
Currently, the usePersistedState acts just like a normal useState call and would be different in each component. So if you are on the channel comment page, hit reply on an existing comment, then change the top-level comment dropdown it doesn't change the same state in the reply comment. This doesn't seem to be correct as this seems to be a way to persist and share state globally.
The change was to make it a global state if you use the same key. Since it is storing in local storage if it exists was the desired outcome. It also passes a setValue function back that if a key is passed in will set all components currently mounted states not just one.
I wasn't 100% on if you wanted …

Fix channel reply switching channels.

---

CHANGELOG.md
ui/component/common/markdown-preview.jsx

Closes #3467
Issue Number: #3467
Hyperlinks in markdown (markdown files, content description, about page) open in same tab
Hyperlinks in markdown open in new tab

Open hyperlinks in new tab

---

ui/constants/claim.js

Incorrect render mode on some files #4075
> When I try `lbry://@mime#6/obj#6`, it looks like it tries to render the video player instead of the 3d viewer.
https://github.com/lbryio/lbry-desktop/pull/4076#issuecomment-620042207
`application/octet-stream` should not be forced to play as a video
> Generic binary data (or binary data whose true type is unknown) is application/octet-stream
> For text documents without a specific subtype, text/plain should be used. Similarly, for binary documents without a specific or known subtype, application/octet-stream should be used.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#Types

Fix wrong file types forced to render as video

---

ui/component/channelSelector/view.jsx
ui/scss/component/_channel.scss

- New channels dropdown alignment is off #4072
- Wrong alignment of the `menu-list` in the `channelSelector` component 
- The `data-selected` styles don't work on the menu items.
- Inconsistent horizontal space of items when channels have a long name.

Fix channel selector styles

---

CHANGELOG.md

The SDK was updated to 72.0 not 72.9 as was previously said as there isn't anything about 72.0.
Issue Number:

Version 45.1 Changed Slightly

---

CHANGELOG.md
static/app-strings.json
ui/component/comment/view.jsx
ui/component/dateTime/view.jsx
ui/page/channel/view.jsx

Issue Number: 4124
The relative date of an item (e.g. "xxx hours ago") isn't shown consistently, language-wise. 
Fixes #4124.  All relative dates (claims, comments) will now be consistently translated.  However, they will remain as English until the translations updated all the new strings.  See commit comments for more details.
There's no breakage, but today's code does now load an individual Channel's page.  I've verified that it is not due to my changes.

Fix relative-date translation

---

ui/component/button/view.jsx
ui/component/header/view.jsx

Issue Number: Fixes #3465 
Some buttons (especially those without text) is lacking tooltips.
Display tooltips for those elements.
The strings are already in place, so code was added to route the data to `title` for it to appear as tooltip.
Refer to commit message for full details.

Display tooltips for buttons, especially those without text

---

ui/component/publishFile/view.jsx

Some small errors in what was said there.
Issue Number:

Small Changes to publishFile/view.jsx

---

ui/component/socialShare/view.jsx

Closes #4177
Issue Number: #4177
"Start at" is shown for all sharing modals
"Start at" is only shown for video and audio sharing modals

Only show "start at" on share page for videos/audio

---

ui/scss/component/_content.scss

Improvement: Makes it clearer that the pop out player can be moved around
Issue Number: Partially fixes #2750, specifically the checkbox that says "make it clearer on how to drag around"
When hovering over the header of the pop out player, a pointer cursor is shown.
When hovering over the header of the pop out player, a hand cursor is shown, similar to the footer of the pop out player.

Add grab cursor to pop out player header

---

ui/page/settings/view.jsx

Problems solved (second attempt):
A. Small typo for <div className="card__title card__t itle--deprecated"> (extra space in the word **t itle**)
B. More details about problems with languages:
1. The word blocked has two forms in other languages (one for plural and one for singular) and therefore must be put together with channel and channels words. Currently it can be translated in only one form.
2. In the case there are no blocked channels there is no need to show the 0 value and is more elegant the message 'You do not have blocked channels'
3.  The link to manage the channels should not be visible in the case that there is no channel blocked, because there is no channel that need to be managed.
And about your statement: "Your change would make it harder for other languages to change this …

Changed how 'Blocked channels' are displayed on settings and a typo

---

ui/scss/component/_wunderbar.scss

Closes #4209
Issue Number: #4209
Attempting to select text in the wunderbar in the app will move the whole app window instead of selecting text.
Attempting to select text in the wunderbar in the app will actually let you select the text.

Allow selecting of text by dragging the cursor over text

---

ui/index.jsx
ui/redux/actions/app.js

Closes #4017
Issue Number: #4017
Embeds don't work in Brave with shields up because session and local storage is trying to be accessed.
Embeds work in Brave with shields because session and local storage access is avoided.
I tested this by creating a new local web site with an embedded iframe from a share link. I then modified the host from lbry.tv to localhost:9090. Without my changes I got errors and the video wouldn't load, but with my changes, the errors went away and the video played.
Note on changes: the 'startup' sesionStorage item is only used on the app, so I made that code that sets this item only appear in the app code.
The second change where I move IS_WEB to the front of the || will …

Make embeds work without sesion or local storage

---

CHANGELOG.md
ui/component/viewers/videoViewer/internal/videojs.jsx

Closes #4150
Issue Number: #4150
Videos on iPad are not playable. They do not autoplay and there are no controls to play.
Native controls for video appear on iPad allowing user to play a video.
This should also be tested on Android, which I don't have.

Make sure native controls appear on touch devices

---

CHANGELOG.md
ui/component/viewers/videoViewer/internal/videojs.jsx

Reverts lbryio/lbry-desktop#4223
@jeffslofish reverting this because it appears to mess with lbry.tv in some cases and messes up android (I should have tested this). 
Maybe this should only be added for iOS devices?

Revert "Make sure native controls appear on touch devices"

---

ui/component/i18nMessage/view.jsx

Issue Number: Fixed #4173 
Messages under `<i18nMessage>` weren't localized although the translation is available. However, the tokens for these messages are localized, causing a mixed-language final string.
Localizations using `<i18nMessage>` now works.
It appears that the original message (instead of the localized) was used in the token-substitution process.

Fix <i18nMessage> not localizing the message.

---

ui/component/comment/view.jsx
ui/component/commentCreate/view.jsx
ui/component/common/form-components/form-field.jsx
ui/component/publishText/view.jsx
ui/scss/component/_form-field.scss
ui/scss/component/_markdown-editor.scss

Issue Number: Fixes #3081 
The simple editor is being used for comments, both in Claims and Channels.
There will be a button to toggle between simple and markdown editor.  I placed the button at the upper-right instead of at the bottom so that it doesn't make the "Done|Reply|etc" button area too busy.

#3081 adv editor for comments

---

CHANGELOG.md
ui/component/app/view.jsx

Issue Number: #3870 
If playing a video and then navigating to a new page to cause the miniplayer to appear out of focus, pressing spacebar causes the video to pause and the page to scroll down in the background.
Ensures that pressing spacebar only pauses the video on the miniplayer and doesn't cause the page to scroll.

disables page scroll when pressing spacebar

---

ui/page/settings/view.jsx

Because in some languages, like Japanese, the text start with the number first (as it mentioned in https://github.com/lbryio/lbry-desktop/pull/4215#issuecomment-633264851) I rewrote the code to be more easy and clear for translators to translate the text.
Issue Number:

Changed code for "Blocked channels" settings

---

package.json
ui/component/header/index.js

- [] This PR introduces breaking changes and I have provided a detailed explanation below
Issue Number: resolves #4140 
Shows 0 in the header for credits while loading
Shows '--' in the header for credits while loading
Change in function depends on lbryio/lbry-redux#317

remove manual override in formatting for credits in header

---

CHANGELOG.md
ui/scss/component/_card.scss

- [ x] Bugfix
Issue Number:
There is a double border on cards with no title portion. 
Cards without title portion now have a single border.

fix: remove double border on single cards with not title

---

ui/scss/component/_markdown-editor.scss
ui/scss/component/_markdown-preview.scss
ui/scss/themes/dark.scss
ui/scss/themes/light.scss

Issue Number: Fixes #4154. Fixes #3468.
Text in Markdown Editor not legible (poor contrast).
See commit comments for more details.

Fix color contrast in Markdown Editor (both light & dark).

---

ui/scss/component/_markdown-preview.scss
ui/scss/component/_status-bar.scss

The status-bar merge did not include the css spacing variable rename that happened in the moonpay merge.

Fix css "--spacing-?" renaming that recent PRs missed during the merge.

---

ui/scss/component/_comments.scss
ui/scss/component/_form-field.scss

Fixes #3697 
See commit messages for rationale and decisions.
One minor "side effect" is that it pushes all the elements down when there is a need to wrap, but I think it's an ok compromise for a rare corner-case.

Fix Repost input field being off-screen

---

static/app-strings.json
ui/component/fileDetails/view.jsx

Text  for files sizes can be translated as Mo (from Mega octet) so KB, MB, GB etc will be Ko, Mo, Go etc. in other languages.
Issue Number:

Make strings from fileDetails translatable

---

ui/component/privacyAgreement/view.jsx

Removed space to sync the text "LBRY takes privacy and choice seriously. Just a few questions before you enter the land of content freedom." with that from app-strings.jsx
Issue Number:

Removed space to sync with app-strings

---

ui/scss/component/_comments.scss

Fixes #4350 `comments getting cut off mid word instead of being wrapped properly`
My bad ... was pretty sure I tested all cases in the original PR.  But here's another attempt.

PATCH: Fix [ff0cc861] that broke regular word-wrap in comments.

---

electron/createWindow.js

Fixes #4347 `[desktop] remove file://c: from status bar on hover LBRY urls`
1. The `isDev` version of the base URL was incorrectly used in the URL reconstruction, so it failed in the final build.
2. Even if the correct version was used, there is still some platform (win vs. linux) differences to handle.
If I'm correct, `update-target-url` returns in the following format:
```
Format:  file:// + "root of executable" + "claim address"
Linux:   file:///@claim
Windows: file:///C:/@claim (the root is /C:/)
```
I've tested `yarn build` on these 2 platforms, but I don't have a Mac to test on.  I assume it behaves the same as Linux.

PATCH:  Fix dev base-url being used when generating the hover URL.

---

ui/scss/component/_comments.scss

The MDE width overflows as you type.  Affects Edit Mode only (New Mode works fine).
>_The MDE used in the "new" section has a parent width parameter to limit itself, while the MDE used in the "edit" section didn't._
>
>_Fix by limiting ".comment__body_container" to 80%, which takes into account the space taken by the author's avatar. This feels a little bit dirty since it's hard-coded.  If there's a way to calculate the avatar width from here, it will be more robust._

Limit the Markdown Editor width in Edit (not New) Mode to prevent overflow

---

ui/page/help/view.jsx

Removed the leading dash for Web

About: Remove leading dash for app version in Web.

---

ui/component/transactionListTable/internal/txo-list-item.jsx

>_I tried unlocking a tip and it failed because my wallet was locked (this can happen for other reasons), but then the unlock icon was still greyed out. Only grey out if successful._
Don't gray out the buttons on `ABANDON_STATES.ERROR` for:
- Support/Tip unlock
- Claim abandonment

If support/tip unlock action fails, don't grey out

---

ui/component/walletSendTip/view.jsx

Previously, the link was missing and the button didn't do anything.
Issue Number:
The button doesn't actually lead anywhere when you click it.
As I have tested, it works and leads to the purchase LBC page.

Add link to "Buy More LBC" button (Tested Working)

---

ui/component/claimListDiscover/view.jsx
ui/component/publishForm/view.jsx
ui/page/publish/view.jsx

> _When switching between tags, the selector defaults back to Trending even though you had another option already selected. I think it makes more sense to persist them._
Also, added persistence to `Channel` selection in `Publish` Page per discussion with Tom.
Skip the suggested change in the wallet for now until this method is reviewed.  There might be better ways to handle the history.
- `orderParamUser` will store the last user state persistently. The persistent state is also made unique for each page (i.e. "Your Tags" and "All Content" will have unique states).
- If the parent component passes in a specific order, that will be respected and will also become the new persisted value. One example is "Your Following", where it always starts at 'New'.
- Handling navigation history was a bit …

Persist trending selectors between tags

---

ui/component/claimList/view.jsx
ui/component/claimListDiscover/view.jsx

This serves as precursor fixes to support #2669 `Page does not restore to top when navigating new tags`.
Even if we don't end up fixing 2669, this PR fixes a few glitches with inf-scroll and improves the performance a bit.
For 2669, I have a general fix, but more corner-cases came up during test, so I did not include it in this PR.  Back to drawing board for that.
See the commit messages for the walk-through.

Precursor fixes to support #2669 ("Page does not restore to top when navigating new tags")

---

CHANGELOG.md
static/app-strings.json
ui/component/common/icon-custom.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/constants/icons.js
ui/scss/component/_file-render.scss

Per 4325:
>_Some users may not notice that the video is muted automatically and the overlay would alert them to this. Youtube does something similar._
**Implementation:**
- The code is placed in `VideoJs` instead of `VideoViewer` as we need to control the video itself. It's more self-contained here, rather than trying to pass refs around between parent and child.
(_actually, I don't know how to control the player from the parent. I'd be curious to know how to do it in React as a side discussion_)
- useState cannot be used as it will cause a re-render when the hint it clicked and dismissed. The DOM is used to hide the button.
**Dev testing notes:**
[x] When manually unmute using regular button, the hint should go away.
[ ] When manually unmute using 'm', the hint should go away.
This is …

Show "unmute" option on videos automatically muted by browser.

---

yarn.lock

@babel/compat-data 7.8.6 to pre-7.10 series has compilation issues with newer node 12.x and 13.x releases.
Using 7.8.6 will cause the failure to find the module `'@babel/compat-data/corejs3-shipped-proposals'`, causing build failures on systems with those node releases (e.g. Solus).
This patch bumps @babel/preset-env, @babel/preset-flow, @babel/preset-react, and their deps specifically to newer releases to resolve compilation. Please note that this does **not** update all of babel to newer 7.10 series releases, just specifically resolves compilation on specific Linux platforms. Should LBRY folks want to upgrade fully to newer 7.10 series, that's probably something worth doing separately. At least during my short analysis there didn't appear to …

Resolve corejs3-shipped-proposals build issues.

---

static/app-strings.json
ui/component/walletSendTip/view.jsx

1. Fixes #4394 `add persistence to new support modal`
>_Should save my tip/support preference and last amount (button) and custom amount._
2. Should collapse the custom field when presets are selected.
_Even though the Send button repeats the amount for Tip, it's still confusing to see both the Preset being active and Custom numeric field visible._
3. Missing localization tags.

Tip-Modal: Add settings persistence and UX improvements.

---

ui/component/router/view.jsx
ui/constants/pages.js
ui/page/settings/index.js
ui/page/settings/view.jsx
ui/page/settingsNotifications/index.js
ui/page/settingsNotifications/view.jsx
yarn.lock

The notifications PR was already pretty big so I decided to strip this out and make a PR for this separately.

bring in email preferences page from lbry.com

---

CHANGELOG.md
static/app-strings.json
ui/component/autoplayCountdown/index.js
ui/component/autoplayCountdown/view.jsx

- When the autoplay overlay gets partially off-screen, the timer will be stopped. We can tweak how much down it needs to be scrolled.
- When timer is paused, the countdown resets.
- The pausing mechanism has no effect on the floating player (since the 'top' can never go negative). This behavior is the same as another big video platform.
- Pause when any `Modal` is present.
- Also present in `0.46.2`: I noticed that with the first video viewed from a fresh session, the timer takes a while to appear. (Update: seems like just need to scroll down for "Related"to load at least once).

Pause 'Autoplay' when scrolled off screen.

---

CHANGELOG.md
ui/component/wunderbar/index.js
ui/page/settings/index.js
ui/page/settings/view.jsx

Fixes #3641 `Language switch does not take effect right away`
Although `Card`s in the Settings Page are actually being re-rendered, the `actions` within them might not be getting the signal or have anything to update, depending on their props.
(1) Pass the language variable to the `actions`'s props for items that are affected.
(2) Make the Wunderbar listen to language-changes as well (the only component outside of Settings that would need an immediate update).
- The fix does feel a bit like a whack-a-mole instead of a systematic global update, but it's only a handful of components that need an update anyway; plus it's no worse than existing version, performance-wise.
- Before this PR, I noticed the `SettingsPage` seems to be re-rendered every 5 seconds, whether a change happened or not.

Fix language-change not applied to all components immediately.

---

CHANGELOG.md
ui/page/channel/view.jsx

Fixes #3750 `refresh youtube creator status when switching between channels`

Fix incorrect creator status shown when navigating between channels

---

static/app-strings.json
ui/component/abandonedChannelPreview/index.js
ui/component/abandonedChannelPreview/view.jsx
ui/constants/modal_types.js
ui/modal/modalRemoveBlocked/index.js
ui/modal/modalRemoveBlocked/view.jsx
ui/modal/modalRouter/view.jsx
ui/page/listBlocked/view.jsx

Fixes #3800 `allow unfollow / unblock of abandoned or blocked content`
If the `ClaimPreview` is in the Blocked Page, and if the claim itself is invalid, show a button to remove it from the blocked list.
- I do not know if this change covers the DMCA part of #3800 or not since I don't see any special handling for DMCA'd claims in the code to emulate it.  I assume `!claim` does cover that scenario; if not, I'll might need LBRY to DMCA one of my claims for testing.
- This change involves altering the wallet, so extra testing would be good.
- Making `ClaimPreview` specifically check if it's in the `PAGES.BLOCKED` does feels a bit dirty, but I opted for this as it's cleaner compared to passing the info down 2 layers through `props`.
```
List Blocked
ClaimList
ClaimPreview
```

Option to remove abandoned claims from Blocked Channels page

---

ui/page/fileListPublished/view.jsx

Fixes #4214 `Refresh on publish page does not have loading indicator`
`ClaimList` currently only shows the loading indicator if there is a header. We could make the indicator always appear at the top of the list when `loading=true`, but that would be the list jump up and down as the indicator appears/dissapears. I assume that is too distracting and is the reason why it was not made that way in the first place.
Show the indicator in place of the Refresh button while fetching instead.

Refresh on publish page does not have loading indicator

---

ui/component/claimList/view.jsx
ui/component/claimListDiscover/view.jsx

<details>
<summary>Test case (<em>click to expand</em>)</summary>
<ol>
<li>Search for a tag</li>
<li>Scroll down to at least load one extra page</li>
<li>Click on any claim in the list</li>
<li>Click Back</li>
<li>Scroll all the way down.  New pages aren't loaded</li>
</ol>
</details>  
In the POP operation, the `page` value is back to 1 due to the initializer `useState(1)`. If the results cache already contained more than 1 page's worth, then the rest of the logic thinks there's nothing to do.
Previous fixes to Inf-Scroll added a "page correction" code to handle the mismatch. This fix simply adds this scenario to the list of scenarios to perform the correction.
Fixed improper debouncing code.
----
<details>
<summary>Test case (<em>click to expand</em>)</summary>
1. Click Following<br>
2. …

Inf-scroll: fixes for 3071 and 4351

---

ui/component/walletSendTip/view.jsx

Issue Number: closes #4081 
The only balance seen is in the top right corner which has only 2 levels of precision.
I added 4 levels of precision to all devices with the balance and not just 2 levels on precision with the balance on mobile.

Put LBC amount with 4 precision on tip menu for all versions

---

ui/scss/component/_file-render.scss

Fixes #4220 `[moble] show time left / progress on video player bar`
For `vjs-layout-small`, there is still space to display the said controls. This layout covers devices like Galaxy S5 up to Nexus 6P.
For layouts smaller that that (e.g. 'vjs-layout-xsmall'), they will remain hidden.

[mobile] show "time left/progress" on video player bar

---

ui/page/settings/view.jsx

- Fixes #4447 `Notifications and Blocked "Manage" button doesn't work with 0 blocked channels`
- I skipped the second bullet point -- no strong arguments for either way.

Fix "Notification" page button being incorrectly disabled by 0 blocked channels

---

ui/page/settings/view.jsx

Issue #4447 (item 2)
>Notifications and Blocked Manage button doesn't work with 0 blocked channels.
>
>- The former should work regardless of blocked channel count?
> - **The latter is technically correct, but no harm to just enter the page since it will show a When you block a channel, all content from that channel will be hidden. message which seems useful for beginners?**

Allow entering Blocked Page even for 0 blocked channels.

---

ui/component/claimList/view.jsx

Fixes #2789 `Infinite scrolling should activate at end of listed claims, not subscription list`
I believe it also closes #2957 `scroll restoration issues when tags/sub list longer than page`.  Looks to be working, and any quirks with `Back` will be a common (existing) one that is unrelated to extended Tag/Following size.
If you press `End` on the keyboard, you'll go to the bottom but only 1 extra page will be loaded.  If you scroll back up slowly, inf-scroll will continue to load one page at a time.  I think this is arguably a better behavior than trying to load all the way to the bottom in one-shot;  it's laggy enough as it is.

Inf-scroll: Change region to 'main' to ignore long tag/following list.

---

ui/page/rewards/view.jsx
ui/page/rewardsVerify/index.js
ui/page/rewardsVerify/view.jsx

Makes sure the "refresh" button works properly for users that are manually approved. Also calls `user/me` for non-reward approved users on the rewards page so it updates automatically if they have been manually approved while they were using the app.

rewards redirect fix for manually approved users

---

static/app-strings.json
ui/component/claimListDiscover/view.jsx

Issue Number: No issue exists yet (introduced by #4218 thought)
The claimListDiscover contains an option to filter out on prices. The text visible to the end user for options are currently hard-coded and don't use the i18 translation method. (Untranslated: Anything, Paid and Free)
Will be translated

Translation - Un hardcoded price filter label options

---

CHANGELOG.md
ui/component/publishFile/view.jsx

Fixes #4332 `Video transcode setting not reflected correctly (MP3 incorrectly transcoded to MP4)`
2 issues here:
(1) The checkbox is mixing between user state and logic state.
(2) The variables (e.g. `optimize`, `isVid`, `filePath`, etc) will have values from the previous operation when you enter Publish Page, so GUI issues beyond Transcode can be also produced (e.g. transcode appearing for a image file)
The "Transcode" checkbox state (checked vs. unchecked) will now reflect the user's desire and will be a persisted state. Whether or not this setting is used will be reflected by the checkbox's grayed-out state (i.e. it can be checked for non videos, but it will be grayed out).

Fix video transcode setting not reflected correctly (MP3 incorrectly transcoded to MP4)

---

ui/component/settingAccountPassword/index.js
ui/component/settingAutoLaunch/index.js
ui/component/syncToggle/index.js
ui/page/settings/view.jsx

Patch for `7839bbf2: Fix language-change not applied to all components immediately`
- Missed the "Account Password" card that is used for authenticated case.
- For cards that are only used in Settings, listen to the language change in "select" instead of passing it in as a prop. I think this is cleaner.

Patch for "7839bbf2: Fix language-change not applied to all components immediately"

---

CHANGELOG.md
ui/component/viewers/videoViewer/view.jsx

Fixes #4460 `unmuted state lost / reverted`
1. Play a video.
2. Press mute.
3. Drag the volume bar to unmute.
4. Play a new video --> the video starts muted.
The `volumechange` handler was comparing against stale variables, so there are times where the state was not saved. Just save both `muted` and `volume` without additional gating (the gating is probably unnecessary in the first place, since we are in a onChange function).

Fix unmuted state lost or reverted when playing a new video.

---

static/app-strings.json
ui/component/userEmailNew/view.jsx
ui/component/userEmailReturning/view.jsx
ui/component/userPasswordReset/view.jsx

#3886 
PR Checklist
Issue Number: None
Some email place-holders use `hotstuff_96@hotmail.com` and there is also one case where it was `yourstruly@example.com`.
The `yourstruly@example.com` is probably more neutral so I keep it.
All `hotstuff_96@hotmail.com` references are now `yourstruly@example.com`

Normalize email place holder value

---

electron/createWindow.js
ui/constants/languages.js
ui/constants/supported_languages.js
ui/constants/supported_sub_languages.js

**CT** - Chinese Traditional, **CS** - Chinese Simplified
Per Julie:
> _We have Chinese in our language selection (zh) but a community member really wants to add Taiwanese (zh_tw) to the app and gave a good description how it differs and is a legit request. Right now we don't support the languages on Transifex that have the underscore in their language code._
I agree.  All translated products almost always support these 2 distinct languages.
If LBRY wants to support it, then this PR attempts to enable that.  
- "Chinese" will be split into "Chinese (Traditional)" and "Chinese (Simplified").
- It will be easier to split other common subsets like `pt-BR/pt-PT` and `en-US/en-GB` if there is demand and translator availability.
I don't have access nor the knowledge for the Transifex side:
_It …

Add ability to support language subsets, with only CT and CS enabled for now

---

ui/component/walletSendTip/view.jsx

To try and make it clearer that users are sending a permanent tip, not a support.

update title/subtitle on support modal if user is sending a tip

---

static/app-strings.json
ui/i18n.js

- The diff for new strings are polluted by the need to add a comma to the previous entry.
- Having to re-add the newline at the end of file before commiting is a repetitive pain.
Before:
After:
- When manually adding strings, developers need to put it above the `--end--` entry. Hopefully it is obvious without having to put verbose comments like `^--- add new string before this line ---^`
- Translators will surely ask how to translate `--end--`.

Improve auto string addition to produce better diffs and ease merging.

---

static/app-strings.json
ui/component/walletSendTip/view.jsx
ui/scss/component/_button.scss

Closes #4492 `Make support (tip case) dialog clearer`
- Move the "Buy More" button to the middle instead of isolated at the bottom
- Add warning sentence

TipModal: Add final warning when making a permanent tip. 

---

ui/component/claimListDiscover/view.jsx

This is a follow-up on PR-4392.
The previous PR covered "pop from within the same page but with different query/order", but missed "pop after entering a claim".
1. Click `Your Tags`.
2. Set order to `New`.
3. Restart app or reload (crucial step)
4. Click `Your Tags`.
5. Click any claim.
6. `Back`. The order incorrectly resets to `Trending` -- it should stay at `New`.

Inf-scroll: Handle case of "pop from claim"

---

static/app-strings.json
ui/component/common/icon-custom.jsx
ui/constants/icons.js
ui/page/help/view.jsx

Issue Number: Fixes: #1170
A new card on the help page links to the status.lbry.com page and also links to my recently created FAQ page on what the services are. This commit is for the FAQ getting added to lbry.com: https://github.com/lbryio/lbry.com/pull/1324

Add a LBRY Services status card to the help page (Tested Working)

---

CHANGELOG.md
ui/component/claimListDiscover/index.js
ui/component/claimListDiscover/view.jsx

Fixes #2675 `Claim search with exactly 20 results keep fetching next page`
The impact is milder now given recent fixes to inf-scroll, but still good to remove the glitch.
Use `claimSearchResultLastPageReached` (I didn't know it existed back then).
The unnecessary "loading" refresh will still happen one time, but at least now it doesn't happen every time we scroll to the bottom (and incorrectly incrementing 'page').

Inf-scroll: Fix glitch when results are exactly the page size.

---

CHANGELOG.md
electron/menu/setupBarMenu.js
ui/component/app/view.jsx
ui/effects/use-zoom.js
ui/index.jsx
ui/util/zoomWindow.js

Closes #4501`Font size`
and Discord submission
The Desktop app can now zoom the same way as browsers:
- Zoom In: `Ctrl+=` or `Ctrl+numpadPlus` or `Ctrl+WheelUp`
- Zoom Out: `Ctrl+-` or `Ctrl+numpadMinus` or `Ctrl+WheelDown`
- Zoom Reset: `Ctrl+0` or `Ctrl+numpad0`
(1) Electron provides this functionality through the `zoomIn|zoomOut|resetZoom` roles in the Menu, so it would have been a quick job.
However, given that Electron currently does not support having multiple accelerators for one item, we can't add `Ctrl+WheelUp` to the mix and would have to implement our own handler and use `webFrame`.
Given that we need to add code anyways, we handle both keyboard and mouse cases through the same handler, hence the existence of `zoomWindow.js`.  It also provides the opportunity to few a few …

Allow zooming on Desktop

---

CHANGELOG.md
static/app-strings.json
ui/component/youtubeBadge/index.js
ui/component/youtubeBadge/view.jsx
ui/page/channel/view.jsx
ui/page/file/view.jsx

Closes #3964`: Add Youtuber info to file page`
(1) Refactor the YT-info query into `YoutubeBadge` component.
(2) For the File Page case, don't show "- last sync <date>" since the date has nothing to do with the file.
[x] YT Channel page
[x] YT Channel's claim page
[x] Non YT Channel page
[x] Non YT Channel's claim page
[x] No channel (anonymous) claim page
[x] Various `RENDER_MODES`

Show "YT Creator" label in File Page as well.

---

CHANGELOG.md
static/app-strings.json
ui/component/viewers/videoViewer/internal/videojs.jsx

When there is an error in loading the video, the loading circle spins perpetually, giving false hope.  This commit removes the loading circle in that scenario.
Added a `Retry` button to reload the video without re-rendering the app or even the page.  
See example of how it looks like: https://www.youtube.com/watch?v=C3_GRWWFDC8
Note that this doesn't cover #4540 `lbry.tv: video cut-off without errors`.  There's no error message for this case, plus refreshing will produce the same cut-off anyway (server issue?)

Add option to retry video stream on failure

---

CHANGELOG.md
ui/component/publishFile/view.jsx

Currently, the checkbox grayed-out state is only correctly updated when changing from "no-file" to "file selected". If you have selected a video file and later changed to a text file, the checkbox doesn't gray out.
`fileVid` wasn't being updated for the case of non-videos; now it does.

Fix 'transcoding' checkbox state when switching file types.

---

CHANGELOG.md
ui/component/channelContent/view.jsx
ui/page/fileListDownloaded/view.jsx
ui/scss/component/_claim-search.scss
ui/scss/component/_wunderbar.scss

Fixes #4524 `[mobile] in channel search not available`
There are currently 3 wunderbars: (1) header (2) channel list (3) downloaded list.
The additional `wrapperStyle` in the header made it hard to find a solution that works for all 3, so I split 2 and 3 into `wunderbar__input--inline`.
This button is usually placed beside the `Trending|New|Top` selector, so it should have the same bottom margin. If not, anything that flows below it (e.g. in mobile) will be touching it.

Fix channel file-search not available in mobile 

---

CHANGELOG.md
ui/component/selectChannel/view.jsx

Fixes #4411 `"SelectChannel=New" doesn't show all fields on re-entry`
Correct the value of `addingChannel` in the constructor based on the given props.

New Channel: Fix incorrect GUI configuration at entry

---

CHANGELOG.md
ui/page/channel/view.jsx

When navigating back and forth between a File and Channel page, the back-action will be laggy (no response) if the channel contains a lot of comments and is in the midst of resolving them. Multiple clicks will be accumulated.
The "full" fix would be to batch-load comments, as this would improve the performance of fetching both Channel and File comments. For now, this commit focuses on the Back action problem only.
Skip fetching comments by not mounting 'ChannelDiscussion' until the tab is selected.  I couldn't find anything in the Reach UI documentation on how to not render inactive `TabPanel`s, so I used the straight-forward state method.

Skip fetching comments by not mounting 'ChannelDiscussion' until the tab is selected.

---

CHANGELOG.md

- Fixed few items mistakenly placed under 0.47.0
- `## [0.47.1] - [2020-07-23]` -- not sure if I need to deduct one day to account for timezone differences or not.  Amend if needed.

Fix changelog for 0.47.1

---

CHANGELOG.md
ui/component/common/wait-until-on-page.jsx
ui/component/recommendedContent/view.jsx
ui/page/file/view.jsx

1. Sometimes, the Related Section will load unnecessarily when a File Page is entered.  This happens more to Image claims, although I see it happening on Videos.  I think it's due to my slow connection causing the upper components to not fully inflate, so the Related Section will briefly appear on screen.
2. In the Autoplay case, if the `WaitUntilOnPage` has already opened the gates previously, the next video's Related Section will be loaded regardless of scroll position.
See the commit messages for the walkthrough.
Using the debounce method doesn't fix the first issue 100%, but it covers most cases with a decent connection speed.  In the future, I'm thinking of using a dummy placeholder component with typical Video height while waiting for Images to load.

Fix 'Related' section lazy-load not working in some scenarios

---

CHANGELOG.md
ui/component/selectChannel/view.jsx

Fixes [#4621 Can't create Comments if you recently deleted a channel](https://github.com/lbryio/lbry-desktop/issues/4621)
Fixes [#3013 Impossible to add comments](https://github.com/lbryio/lbry-sdk/issues/3013)
The `channel` that the parent passes in is from a persisted state. If the channel has been deleted, `<select>` will automatically resolve to another selectable value. However, `onChange` will not be called for this scenario, so we now have a mismatch.
- Manually check if the value has been auto-resolved and report it to the parent.
- An extra `setTimeout` was needed. It seems like `onChannelChange` needs to be called after the first `useEffect` of the parent, otherwise the call has no effect.

Fix comment-creation failure if you have recently deleted a channel

---

CHANGELOG.md
ui/component/walletSendTip/view.jsx

Fixes [#4544 Channel-creation in "Tip|Support" Modal shouldn't submit LBC immediately](https://github.com/lbryio/lbry-desktop/issues/4544)
`Form` seems to have already tried to stop the propagation of `onSubmit`, so I'm not sure why it was still propagated.
Fix by using the same method used in the `CommentCreate`, which is simply to check for `CHANNEL_NEW` as the current selection.

Tip Modal: Don't do final submit when the intention is to create New Channel.

---

ui/component/postEditor/view.jsx
ui/constants/form-field.js

From twitter:
> is there a character limit? I could only edit 70 % of my old Markdown file text.
Currently the post editor uses the same limit on description: 5000 chars.
Any previous post ( markdown file ) that is above this limit can't be edited.
I'm still unsure what should be the limit. I tried to find a limit on `medium.com` but looks like there is no actual limit or is just to big to reach unless you post an actual book. 😕 
Unfortunately a limit is necessary to have specially for the web version ( I guess the markdown preview / parser will eventually become too slow or crash in a very extreme case ? ), I just doubled up the current limit to 10,000 Idk if that's really enough or still small. …

Increase max text length of posts

---

ui/component/selectChannel/view.jsx

https://github.com/lbryio/lbry-desktop/commit/37a1fd88e3b5fe54be2e45e924a20a5567211902#commitcomment-41233752
The previous commit was over-doing the manual syncing, causing other usages like the Repost Modal to always reset to a different channel.
Only do the manual syncing when the channel does not exist.
At this point, we could also just take `channel[0]` as the new value.

Patch 37a1fd88: Sync selectedChannel only if the channel doesn't exist

---

ui/redux/actions/comments.js

merge when SDK > 79.1 ships.
--include_replies now defaults to false, included if you want full tree response
new flag to speed up comment loading

support sdk feature for fast comments

---

package.json
ui/component/publishForm/view.jsx
ui/page/publish/view.jsx
yarn.lock

Users are annoyed with the constant reset of the 'channel' setting in the Publish page.
1. Revert the previous attempt in ff7b4092. The `usePersistedState` method is bad, as it will clash with the Redux value.  It only worked on initial entry, which was ok back then with the old version of Publish, but not with the new dynamic version of Publish (and it's probably partially broken too back then).
2. Implemented the persistence in Redux -- requires "https://github.com/lbryio/lbry-redux/pull/347".

Publish: Make 'Channel' setting persistent.

---

static/index-web.html
web/bundle-id.js
web/package.json
web/src/html.js
web/webpack.config.js
web/yarn.lock

Reverts lbryio/lbry-desktop#4672
Reverting this because I still need to fix handling the HTML file for `yarn dev:web`, which is currently broken since the bundle URL is only updated in the HTML file when you run `yarn compile:web`

Revert "use dynamic js bundle urls"

---

static/app-strings.json
ui/util/homepage.js

Fixes #4665 [Translated strings with trailing spaces not shown correctly](https://github.com/lbryio/lbry-desktop/issues/4665)
While there are other strings with trailing spaces, _"Trending for "_ was the only one that mattered. The rest are standalone paragraphs or used in a single line, so it doesn't matter if the translation included the space or not.

Remove strings with trailing spaces as it's not obvious in Transifex.

---

CHANGELOG.md
ui/component/fileRenderFloating/view.jsx

Fixes #4709 [Dragging floating player via video section pauses video](https://github.com/lbryio/lbry-desktop/issues/4709)
Don't propagate the key-up action if the window was dragged. Hopefully there isn't another sub-component that relies on the action being propagated.
If you drag at exactly the "Play" icon the control bar, the issue still happens, though.

Fix floating player being paused after dragging.

---

ui/redux/selectors/search.js

Issue Number: 4607
Search suggestion drop-down box has the 'View Channel' label when the query string is in fact a URI for a file.
Label shows 'View Channel' when URI is recognized as a channel URI, and 'View File' when it is recognized as a file URI.
Suggestion for future improvement - strip '#' from the end of query string, so that URIs will be correctly recognized (and navigated to) when they are being typed out but not fully completed.

Fix search suggestions 'View Channel' Bug

---

CHANGELOG.md
ui/component/fileActions/view.jsx

Closes #4669: [Download doesn't trigger on web until 2nd attempt](https://github.com/lbryio/lbry-desktop/issues/4669)
The issue only happens when _Autoplay_ is disabled in the User Settings and the video hasn't been loaded when _Download_ is clicked.
The following code:
`if (didClickDownloadButton && streamingUrl)`
didn't triggered because:
1. `streamingUrl` has not resolved yet when the Effect ran.
2. When it did resolve, the parent component was also notified and unmounted things, causing `didClickDownloadButton` to reset.
- Change the state to the persisted version to deal with the unmounting.
- As a secondary precaution against any unexpected mismatch from the mounting/unmounting, the state was changed from `boolean` to `string`, with the compared value being the current `uri` when …

Web: Fix 'Download' not triggering until second attempt

---

ui/component/wunderbar/index.js
ui/component/wunderbar/view.jsx
ui/page/search/view.jsx
ui/redux/actions/search.js

Issue Number: 4516
Search query containing '%' causes app crash
Searches can now contain '%' character
Api request was breaking for main search and autocomplete when query string included symbols such as '%' and whitespace.
The ClaimPreview component was also throwing an exception when the claim URI was invalid, causing the app to crash.
This PR fixes all of the above, and includes a minor refactor of the wunderbar component view/index.
I have hidden the URI header in the search page (which contains the ClaimPreview component, and a couple of URI-related links) for inavlid URIs.
The search functionality still logs an error to the console when the search string contains whitespace - this comes …

Search percent sign bug

---

CHANGELOG.md
ui/redux/reducers/user.js

Fixes #4749: ["Password updated successfully" kept showing up](https://github.com/lbryio/lbry-desktop/issues/4749)
In addition to the `passwordReset*` variables, reset the `passwordSet*` variables as well in `USER_PASSWORD_SET_CLEAR`.
_Based on current usage, I think it's ok to re-use USER_PASSWORD_SET_CLEAR instead of creating another one to differentiate between Reset and Set?_

Clear 'passwordSet*' flags too in USER_PASSWORD_SET_CLEAR

---

CHANGELOG.md
ui/component/common/form-components/form-field.jsx
ui/component/common/markdown-preview.jsx
ui/scss/component/_embed-player.scss

Fixes #4644: [Markdown Preview breaks when <iframe> is present](https://github.com/lbryio/lbry-desktop/issues/4644)
`Error: "Invariant violation: could not find 'store' ..."`
Until we figure out a way to pass the store to the SimpleMDE preview formatter, just replace the embed with a stub region.

MDE: Replace the iframe with a stub in "edit + preview" mode.

---

CHANGELOG.md
ui/constants/claim_search.js

- This re-opens #4489 [Fix "Price=free" giving 0 results in Following query](https://github.com/lbryio/lbry-desktop/pull/4489) after  conversation in [Discord](https://discord.com/channels/362322208485277697/377895389992321064/756180990887591978). (github didn't allow me to re-open that PR)
- Fixes #4477

Fix "Price=free" giving 0 results in Following query

---

ui/component/common/form-components/form-field.jsx
ui/component/common/markdown-preview.jsx

(Band-aid) Fixes #4797: [Markdown preview breaks when using a lbry link in angle brackets](https://github.com/lbryio/lbry-desktop/issues/4797)
This is similar to the Embed case in commit dbcd677e.
Replaced it with a dummy link that looks like what the final outcome would be, but would not be clickable (the non-editing one would still be clickable).
Again, similar to the embed case, unless there is a way to pass the store over, I don't have an alternative that makes sense: Adding a dummy router or replacing it as a regular `<a>` will just make React spew security errors.
Not being able to click it is not ideal as we (as a user) can't verify our links, but it's better than the current case of not rendering anything at all.

MarkdownPreview: Replace 'lbry://' link with a stub when previewing an edit.

---

CHANGELOG.md
ui/component/fileDescription/view.jsx
ui/scss/component/_expandable.scss
ui/scss/component/_media.scss

The abrupt cut-off of the expandable section bugs me (looks like a rendering glitch), especially when it cuts off in the middle of a line.
In addition to the existing 'More' button, we fade out the section to provide additional visual cues.
This solution doesn't require the background color to be known, so it will work regardless where `<Expandable>` is used, or whatever color-scheme is chosen.
However, it does utilize non-standard css -- for older browsers, it should simply cut-off like the before.

Expandable: Fade out section when 'closed'

---

ui/component/comment/view.jsx
ui/component/dateTime/view.jsx
ui/scss/component/_comments.scss

When we displayed comments less than 1 second old, it would say "500 ago" (500 ms ago).
If there is no suffix, assume it is less than one second ago and show "Just now" as the time

handle comment time display correctly immediately after posting

---

ui/component/wunderbar/view.jsx
ui/page/search/view.jsx

Issue Number: 4758
404 when pasting URL from web browser into search bar, and some channel/stream URLs being reformatted before submitting, causing a search to be executed as opposed to directly navigating to the correct page.
App navigates to correct page
This bug was introduced by a refactor to the wunderbar component by me a few days ago. It's annoying to have to check for all 3 of prod, dev and local environment url prefixes in the production code, so I attempted to re-write. This introduced the bug and the 3-way check has been re-introduced by this PR. It seems like we are stuck with this check for now.
Another problem was the logic deciding whether to hide the search page URI header... (see …

Check search string for web URL prefixes and remove

---

ui/component/router/index.js
ui/component/router/view.jsx
ui/redux/actions/user.js
ui/redux/selectors/rewards.js

When page is loaded directly onto a claim, if referee reward not claimed, resolve claim and set referer to channel uri.
It seems to make sense that if some content brings you in (again) and you end up getting through reward verification after it, that content's channel may as well be your referrer.

initial page view sets referring channel

---

ui/redux/reducers/app.js

Closes #4831: [Videos start muted on Desktop (fresh install) and web (sometimes resets)](https://github.com/lbryio/lbry-desktop/issues/4831)
This covers the Desktop fresh install and Web fresh session (incognito) part. 
It doesn't cover the "sometimes reset" part -- not sure how to reproduce that.
`sessionStorage` is always empty when that piece of code is called, even for non-fresh Desktop and even in Brave. 
`localStorage` doesn't have a `volume` entry either.
We now fallback to `1` when `volume` is `null`. Still not sure the purpose of that code, but leaving it there just in case something relies on it.
[/] Desktop fresh-install is not muted.
[/] Desktop return session restores previous volume level.
[/] Web* fresh session (cleared data) is not muted.
[/] Web return session restores …

Fix: Videos start muted on initial session

---

CHANGELOG.md
ui/component/selectThumbnail/view.jsx

https://github.com/electron/electron/issues/20750#issuecomment-709505902

disable snapshot thumbnail on desktop to prevent desktop crashes

---

ui/component/notification/view.jsx
ui/redux/actions/notifications.js

Now passes `is_app_readable` to `notification/list` so the app doesn't receive email only notifications
Uses LBC icon for reward notifications

Notification fixes

---

web/middleware/cache-control.js

Not the best solution. I think I need to revisit the bundleId creation. It's really hard to work with.

pass max-age header on js bundle so cloudflare can cache it

---

ui/component/markdownLink/view.jsx

Wasn't adding the hash earlier, so file links were being displayed as channel links

fix iframe lbry links in markdown posts

---

ui/component/claimListHeader/view.jsx

Fixes #4393: [Tag query URL goes on indefinitely as you change between [Trending|New|Top]](https://github.com/lbryio/lbry-desktop/issues/4393)
Change from `append` to `set` when building the query to remove duplicates.
Flow hates null being not a string, so the FixMe was retained.

Fix long tag query-URL when changing between [Trending|New|Top]

---

ui/component/viewers/videoViewer/internal/videojs.jsx
ui/scss/component/_file-render.scss

Also puts back the video js player which has rate support - but it's hidden on smaller devices...maybe someone can fix later on.

Improve IOS inline experience

---

static/app-strings.json
ui/component/channelAbout/view.jsx
ui/component/claimListHeader/view.jsx

```
"Hrvatski": "Hrvatski",
"Nederlands": "Nederlands",
"Français": "Français",
"Deutsch": "Deutsch",
"Italiano": "Italiano",
"Polski": "Polski",
"Português": "Português",
"Русский": "Русский",
"Español": "Español",
"Türkçe": "Türkçe",
"Česky": "Česky",
```
**Remove translation macro on native language names.**
I believe we don't translate these since this is already the translated form?
(Well, there's a possibility that the original intention was to translate those languages into everyone's local language.  If that was the intention, I think we'll need to change those strings to the English version instead?  e.g. I don't know what Русский is to make the translation without googling)
**Use the contextual version of 'Post' instead of creating a new one.**
I couldn't find where this new …

Fix str-related issues with new Language setting

---

ui/component/sideNavigation/view.jsx

In the odysee branch, the tooltip for `Following` in the Sidebar was shown as `Following --[sidebar]--`.
In lbry.tv, the tooltip doesn't appear.
I believe the tooltip appeared due to the name change from 'label' to 'title' and then being passed to Button through '...passedProps'.
Fix by explicitly setting the Button's 'title' to the localized text.

Fix sidebar tooltip showing string with context metadata.

---

static/app-strings.json
ui/component/sideNavigation/view.jsx

This is actually identical to #5007, but now done on `master`.
I just noticed that a few odysee changes were promoted to master yesterday, and the issue got moved to `master`, so I'm moving this commit to `master` as well.  I believe when odysee rebases later, there should be not conflict (auto removed).
Also snuck in 1 string update.

Fix sidebar tooltip showing string with context metadata. 

---

CHANGELOG.md
package.json
ui/component/claimListDiscover/view.jsx
yarn.lock

Fixes #4609: [If claim search on latter page fails, don't clear out all previous data](https://github.com/lbryio/lbry-desktop/issues/4609)
This requires an accompanying change in `lbry-redux` (https://github.com/lbryio/lbry-redux/pull/365) that sets `claimSearchResultsLastPageReached` to `true` when the timeout occurs, and also not purging the previous pages.
1. https://lbry.tv/$/discover?t=imherelbry&content=video&order=top&fresh=year
2. Scroll down 5 pages until 100 results are shown.
3. When querying the 6th page, a timeout occurs and the past results are gone.

claim_search: Don't clear past page results if subsequent pages timeout.

---

CHANGELOG.md
ui/component/viewers/videoViewer/internal/videojs.jsx

#4913: [Can't slide volume slider in pop out mode](https://github.com/lbryio/lbry-desktop/issues/4913)
I first tried to handle this at the floating player level, but it was impossible to hack there due to how `react-draggable` works (it already moved the window before the "move" handler is called, so we can't do much).
Fix by overriding the dragging behavior of the videojs' `VolumeBar` class by not propagating the event further. It is odd that videojs didn't already do this, since it's `SeekBar` does stop the propagation.

FloatingPlayer: fix unusable volume slider in fp-mode

---

CHANGELOG.md
static/app-strings.json
ui/scss/component/_file-render.scss

Fixes #5044: Auto hide cursor on video on static hover
The existing code only hides the cursor when playing in fullscreen. Extend that to normal mode as well.

Hide mouse cursor when video is playing

---

static/app-strings.json
ui/page/home/view.jsx

The "Trending for xxx" string was being resolved and translated twice, so it often re-appears in the string list during development.
It seems like `getHomepage` is repopulated every time, so I think it is safe to just resolve and translate `title` at that level.
Remove unused "Creator analytics are down" message per recent changes.

Fix double translation in homepage

---

ui/scss/component/_navigation.scss

Closes #5094: [Followed Channel list mistakenly centered on smaller screens?](https://github.com/lbryio/lbry-desktop/issues/5094)
Copied the fix from the Odysee branch.

Sidebar: left-justify "followed channels" in lbry.tv

---

ui/scss/component/_navigation.scss

Fixes #5115 [eliminate scrollbar jumping in the sidebar](https://github.com/lbryio/lbry-desktop/issues/5115)
Make the content's width the same as the area, so that the "column flex" won't cause a shift.

eliminate scrollbar jumping in the sidebar

---

ui/component/claimListDiscover/view.jsx
ui/component/claimListHeader/view.jsx
ui/component/router/view.jsx
ui/page/channelsFollowingDiscover/view.jsx

(1) Fixes #4783: _New search query does not reset to the top_
(2) The current way that Tag Search resets the position can be overridden by the AppRouter's call.
(3) Fixes #5090: _When sorting channels, switching between Trending/Top/New returns viewer to the top of the page_
See commit message for details
- The method uses the "#anchor" hash.  I don't think the "#" is being used for something else, but bringing it up just in case.

Fix scroll problems with search

---

CHANGELOG.md
static/app-strings.json
ui/component/markdownLink/view.jsx

Closes #5130: [Support mailto hyperlinks / urls in markdown](https://github.com/lbryio/lbry-desktop/issues/5130)
The markdown components already support mailto, just that the logic here ended up making it a 'ClaimLink'

Don't parse a 'mailto:' into a lbry link.

---

CHANGELOG.md
ui/component/common/markdown-preview.jsx
ui/component/markdownLink/view.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/util/remark-timestamp.js

Fixes  #5103 [Automatically turn timestamps in a video description into links ](https://github.com/lbryio/lbry-desktop/issues/5103)
- Works in `description` and `comments` in a video page.
- Invalid timestamps like `03:99` will be ignored.
- In general, if the video player doesn't exist, the link will simply be a no-op (i.e. safe).  However, I do try to _not_ turn it into links when we know for sure it's not in a video page, e.g. in a Markdown Post.
- If _autoplay_ is turned off and video remains paused, and there will be no video instance (hence, a no-op as well).  I'm not sure if we should start playing it when the link is clicked. I think it's ok to just leave it paused (no-op).  I didn't want to duplicate code from `EmbedPlayButton` just for a corner-case.

Turn timestamps in a video markdown (description, comments) into links

---

CHANGELOG.md
ui/component/common/markdown-preview.jsx
ui/component/markdownLink/view.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/util/remark-timestamp.js

- The previous regex in #5156 uses lookback (I think ES2018?) which Safari has yet to implement.
- There were a few bugs in the previous regex too, like missing out multiple timestamps in a line, or parsing "62:02" as "2:02" (although YT does this as well).
- The previous method searched too deep (matchAll) on each 'locate' call, which was wasteful.
- `List` works, but `Bullet` does not.  The same thing happens for "@channel" parsing.  The `notInList` flag doesn't seem to work, or something is blocking it.
I'm still trying to get BrowserStack to work on localhost instances to test on Safari.  Since a simpler regex is now used, plus I don't think there's any other browser-dependent code on this PR, it should work in Safari.  Can you help to double check?

Timestamp: Handle Safari + better parsing

---

static/app-strings.json
ui/modal/modalAutoUpdateDownloaded/view.jsx

https://discord.com/channels/362322208485277697/646840786662719488/788694493532520458
It's either adding the non-capitalized "Not now" to the list, or change the usage to "Not Now".
Chose the latter since the rest of the modal (and other usages) is using the capitalized format.

Fix "Not Now"

---

ui/component/autoplayCountdown/view.jsx

Closes #5204: [Don't autoplay when commenting/video off screen](https://github.com/lbryio/lbry-desktop/issues/5204)
Previously, the checking was only done during a scroll event. We also need to check if the user has already scroll down before the component was invoked.

Fix initial pause state for the Autoplay Countdown

---

ui/component/viewers/videoViewer/internal/plugins/videojs-mobile-ui/touchOverlay.js
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/scss/component/_file-render.scss

Follow up on #5119 [Video: Mobile UI + overlay for keyboard shortcut feedback](https://github.com/lbryio/lbry-desktop/pull/5119) after it was disabled because the feature broke the chromecast button in Android Chrome

mobile-ui: Fix missing chromecast button in Android-Chrome

---

ui/scss/component/_content.scss

Closes #5221: floating player won't close during autoplay countdown
Change the z-index when hover to ensure it is really on top of everything.

FloatingPlayer: Fix close button not working when AutoplayCountdown is visible.

---

CHANGELOG.md
ui/component/app/view.jsx
ui/effects/use-history-nav.js

- Consistent behavior across Web and Desktop.

Desktop: Enable 'Alt+Left/Right' for history navigation.

---

ui/index.jsx
ui/rewards.js

Issue Number: https://github.com/lbryio/lbry-desktop/issues/2177
When a reward comes in, the open modal will be closed.
When a reward comes in, the open modal will only be closed if the reward being acquired is of type reward_code.
**NOTE**
I wasn't able to test the entire flow with real data because I don't own a reward code. I was only able to test the flow with mocked data.

When a new reward is acquired, only close modals if the reward comes from reward_code

---

ui/scss/component/_button.scss

This was preventing the control bar from hiding after inactivity. It was accidentally added with the theater mode PR

remove bad CSS rules

---

ui/component/searchOptions/index.js
ui/page/search/view.jsx
ui/redux/selectors/search.js
ui/util/query-params.js

Issue Number: https://github.com/lbryio/lbry-desktop/pull/5277
NSFW parameter is not being sent correctly when searching.
NSFW parameter is being sent correctly.
When mature content is enable, nsfw isn't sent (which allows for mature content to show up)
When mature content is disabled, nsfw is sent as false

Fix nsfw parameter in search page

---

ui/component/socialShare/view.jsx
ui/util/url.js
ui/util/web.js

Only encodes the claim/stream name this time, not the whole url

encode share url parts

---

static/app-strings.json
ui/component/viewers/videoViewer/index.js
ui/component/viewers/videoViewer/view.jsx
ui/redux/reducers/settings.js

Closes #5308: [Ability to choose default play speed and theatre mode or regular playback size](https://github.com/lbryio/lbry-desktop/issues/5308)
Initially, I used the local storage, as per 'muted' and 'volume' -- I thought that would be appropriate. 
Later, I saw that Theater Mode is already using Client Settings, so I re-did everything to match that.
Also, there is an accompanying commit in lbyr-redux.

Make 'playback rate' persistent

---

package.json
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx
yarn.lock

Currently, we can only cast from Android Chrome (Mobile).  This PR extends it to browsers that support casting.  Goggle Chrome supports it by default, while other browsers will require some flag-tweaking or installing an extension.
- The chromecast API ignores `http`, so `dev-server` alone won't work.  Needs `https`.  I used `ngrok` for testing.

Add Chromecast support on cast-able browsers

---

static/app-strings.json
ui/component/claimRepostAuthor/view.jsx
ui/component/claimSupportButton/view.jsx

String fix for 'Support Repost'
- Added to json
- Don't need the context note for this case.
Fix split string

String fix for 'Support Repost'

---

ui/util/url.js
ui/util/web.js

This PR has made me realize we should probably combine `util/web.js` and `util/url.js` (or at least combine parts of them)

manually encode "'" because encodeURIComponent doesn't encode it

---

ui/constants/settings.js
ui/effects/use-zoom.js
ui/redux/reducers/settings.js
ui/util/zoomWindow.js

Zoom on Desktop always starts with 1.0 -- this PR makes the setting persistent, matching the `web` behavior.
- Do I need to sync `DESKTOP_WINDOW_ZOOM` to `lbry-redux` if this is Desktop-only?

Make zoom level persistent on Desktop

---

ui/component/viewers/videoViewer/internal/videojs.jsx

This is a refactor of the video.js component's lifecycle hooks.
Existing behavior can cause strange behavior and may cause more than 1 video to play at the same time. This is because when any prop is updated for the VideoViewer component, it causes the entire video.js instance to be recreated. 
Additionally it relies on a callback from an asynchronous function to begin the creation of a new video.js instance which further leads to unstable behavior. For instance, when the player is switching to a new source URL it begin a fetch to get the content's headers. While waiting for this fetch to return, if we close the player, it will be removed from the DOM by a parent component (FileRender). Our fetch will then finish and execute the callback which now creates a new videojs instance on a dom …

Fix edge case issue where 2 videos players existed on page causing double audio

---

ui/component/claimPreview/index.js
ui/component/claimPreview/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/5245
When searching, if the first claim is nsfw and the user has the nsfw enabled (meaning, show mature content = true), the claim is hidden because "Mature content hidden by your preferences".
When the user has nsfw enabled, if the first result is nsfw it won't be hidden because of nsfw settings.

Fix first claim nsfw result being hidden even if nsfw is enabled

---

ui/component/comment/index.js
ui/component/comment/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/5384
Editing a comment that has an embed in the playing state, doesn't hide the player
Editing a comment that has an embed in the playing state, does hide the player

Fixing inline videos in comments

---

ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx

Adds new `autoplay` prop to `VideoJs` component for specifying the value of `autoplay` passed to `video.js` player.
Copy pastes the old logic (used to calculate `shouldPlay` into this new property, and passes it to `VideoJs` component.
The result should be that in cases where `shouldPlay` is false, player would behave identically to previous behavior (before refactoring) by setting the `autoplay` flag to false, and *not* calling the function to try and begin autoplaying.
`shouldPlay` will return false when player is embedded *and* `autoplayIfEmbedded` is *also* false. Therefore, this should not impact the improvements made on LBRY / Odysee that we received from turning autoplay to `true`.
Partially resolves #5391

Hotfix: Fix autoplay issues for embedded players

---

.eslintignore

I never ran the linter locally when PR'ing because I would get some many linting errors I wouldn't even be able to scroll up far enough to see the relevant errors.
This is because the lint command will lint all `.js` and `.jsx` files in the `web/` directory... which includes `web/dist/**`.
This PR just adds `web/dist/**` to the `.eslintignore` file so that build files don't get linted, and brings some sanity to running `yarn lint`.

stop linting my web build files please

---

ui/scss/component/_animation.scss

I was annoyed that our dropdown menus didn't actually... dropdown.
So I fixed them:
The CSS change uses a translation instead of a scalar operation to translate the popover menu down 80px rather than expanding by scaling about the center of Y.
Translated 80px because that is the height of the top bar, and for some reason the popover component will affect the scroll position if it renders offscreen. That is, if we were to translate by 100px, it being partially offpage when it is first created will cause the page scroll up by 20px.
I looked into why it is that way, and it's because the popover menu is rendered as `position:absolute` and the position depends on the scroll location. Seems like this really should just be a `position:fixed`, but I don't want to open that Pandora's box …

Make dropdown menus actually dropdown

---

CHANGELOG.md
package.json
ui/component/common/markdown-preview.jsx
ui/component/zoomableImage/index.js
ui/component/zoomableImage/view.jsx
ui/constants/modal_types.js
ui/modal/modalRouter/view.jsx
ui/modal/modalViewImage/index.js
ui/modal/modalViewImage/view.jsx
ui/scss/component/_markdown-preview.scss
yarn.lock

Closes #4899: [Ability to expand images in markdown posts for viewing](https://github.com/lbryio/lbry-desktop/issues/4899)
- I think it should be fine, but please double-check on my usage of `window.app.store.dispatch` and `import { doOpenModal } from 'redux/actions/app';` in a jsx file.
- ![output](https://user-images.githubusercontent.com/64950861/105838291-dede9280-600a-11eb-813f-f66859c25c67.gif)
_p/s: Thanks to `btzr-io` for some pointers._

Zoomable image viewer in Markdown (posts and comments)

---

.eslintignore
ui/component/viewers/videoViewer/internal/videojs.jsx

Discovered while reviewing https://github.com/lbryio/lbry-desktop/pull/5401
VideoJs's reference to itself was not stateful, and was possible for the component to lose it's state and the reference to itself due a rerender.
A hacky way around this was using `window.player` to store the reference globally, but that's bad practice. Instead we should maintain state within the component and persist state across renders.
This seems like a more "react-y" way of doing this.

Hotfix: Make VideoJs's internal reference stateful

---

CHANGELOG.md
ui/constants/file_render_modes.js

Issue Number:  #2903
PDFs can only be downloaded in the desktop app. They are not viewable in the app.
PDFs can be viewed directly in the desktop app.

Enable PDF Viewer in App

---

package.json
web/src/html.js
yarn.lock

Issue Number: https://github.com/lbryio/lbry-desktop/issues/3575
Raw markdown syntax is being displayed in `og:description` and `description` header tags.
Markdown is removed from `og:description` and `description` header tags.
**NOTE**: Please double check if these changes indeed solve the issue. I tried testing it using `yarn dev:web` but the `og:description` content was always the value of `SITE_DESCRIPTION`. I tried using the production build; using the dev web server (`yarn dev:web-server`); and even with `pm2` just in case but the descriptions weren't generated as seen in lbry.tv.

Remove markdown from og and description header tags

---

ui/component/channelThumbnail/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/3751
When the channel thumbnail can't be loaded, nothing gets displayed.
When the channel thumbnail can't be loaded, a default image is displayed.

Display default image for channel thumbnail on error

---

ui/scss/component/_button.scss
ui/scss/component/_comments.scss

Issue Number:
https://github.com/lbryio/lbry-desktop/issues/3930
Long commenter name (channel name) causes the whole comment wrapper to be expanded
Long commenter name (channel name) no longer causes the whole comment wrapper to be expanded.

"Fix Long commenter name issue"

---

ui/page/publish/view.jsx

I am not sure where this function is used / called (it might not be used even)
But I saw the comment in the code and this is an easy fix / feature using the `scrollTo` method with `behavior: 'smooth'`
If there are other locations where scrolling is done programmatically, it would be nice to copy paste this over to those areas to get smooth scrolling transitions by the browser (hardware accelerated too!).
`Element.scrollTo()`: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo
You can use this command to see how smooth scrolling is:  
`document.querySelector("html").scrollTo({top: 0, behavior: 'smooth'});`

Use smooth scrolling

---

ui/component/fileRenderFloating/view.jsx
ui/scss/component/_content.scss

Closes #5438: [Keep floating player in view area](https://github.com/lbryio/lbry-desktop/issues/5438)
- Restore correct z-index
-  The bug came as a side effect of cbac2174. Redo cbac2174 to cover both close button and floating player.
- Remove wobbling when dragging to bottom-right.
-  The extra gap introduced is fighting against react-draggable. If gaps are needed, handle it entire ourselves or do it somewhere in react-draggable; neither is worth the effort, so the gap was removed.

Fix 5438: Keep floating player in view area

---

ui/scss/component/_file-render.scss

It's not actually cropped -- the control bar was opaque.
Use 0.80 opacity to somewhat see the full picture.
Using 0.5 or less would be even better, but due to the default tiny size of the control bar, the text becomes unreadable (it's readable if you zoom the browser to get larger text). Don't want to mess with sizing for now, so using 0.80 to get the best of both worlds.

videojs: make control bar slightly transparent.

---

ui/page/search/index.js

Closes #2731: [Searches with forward slashes returns no results](https://github.com/lbryio/lbry-desktop/issues/2731)
The slash-removal came from (https://github.com/lbryio/lbry-redux/commit/0db20834f9ff99d3ba7acd8e4e8ebb5a41f7e7b4).
Removing the 2 `replace(/\//, ' ')` from lbry-desktop fixes it, but this PR assumes the slash-removal is intentional to cover something else. So, we'll make the Search side do the same thing to match what's happening in `doSearch`.
A little bit ugly, but there's already a comment about this in `makeSelectSearchUris`, so it'll probably get cleaned up together in the future.

Search: Get `uris` with same query as `doSearch`

---

config.js
package.json
ui/component/claimPreview/view.jsx
ui/component/fileThumbnail/view.jsx
yarn.lock

Issue Number: https://github.com/lbryio/lbry-desktop/issues/3290
There is no default thumbnail for channel or stream.
A new environment variable has been added to act as a default thumbnail for channels and streams in case the thumbnail can't be loaded.
The variables are:
- `CHANNEL_THUMBNAIL_FALLBACK`: For channels
- `STREAM_THUMBNAIL_FALLBACK`: For streams
A new library has been included to handle the image fallback: https://github.com/mbrevda/react-image

Handle broken invalid thumbnails

---

static/app-strings.json
ui/page/settingsAdvanced/view.jsx

PR basic info:
Details:
Change the word 'download' to 'purchase' in 2 files ([source code](https://github.com/lbryio/lbry-desktop/blob/master/ui/page/settingsAdvanced/view.jsx) and [translation strings file](https://github.com/lbryio/lbry-desktop/blob/master/static/app-strings.json)).
Change reason:
This change is located in the [Advanced Setting Page](https://github.com/lbryio/lbry-desktop/blob/master/ui/page/settingsAdvanced/view.jsx) and it asked whether the app send a confirmation message when the user is going to make a payment higher than a certain value. **Notice that you make payment through purchasing and tipping, rather than downloading.** I'm a translator working on [transifex](https://www.transifex.com/user/profile/johnspirit/) and …

fix wrong word 'downloads' to 'purchases'

---

ui/component/wunderbarSuggestions/view.jsx

N/A
When double clicking the search box in non-mobile view, the window will maximize. This is a little annoying because it's common (at least for me) to double click to select a word in an input field, or triple click to select all text (triple clicking is currently impossible because of the maximizing).
Double clicking the search box does not maximize the window.
I'm unfamiliar with this code, so I wasn't really sure what the testing procedure is. I just confirmed it fixed the issue in electron and didn't break the web version/mobile view. I only tested on Linux.
#4208 Introduced double-clicking to maximize the window. This code did prevent double clicking the search box maximizing the window. …

Do not propagate double click event on search input

---

ui/component/channelCreate/view.jsx
ui/component/channelEdit/view.jsx
ui/component/publishName/view.jsx
ui/component/walletSend/view.jsx
ui/component/walletSendTip/view.jsx
ui/component/walletSpendableBalanceHelp/index.js
ui/component/walletSpendableBalanceHelp/view.jsx
ui/scss/init/_gui.scss

Since it was removed from the header, some places that require credits can be confusing if you don't know your spendable balance.

add immediately spendable balance inline wherever credits are used

---

ui/page/wallet/index.js
ui/page/wallet/view.jsx

So that the wallet page is still visible if people have 0 available balance

use totalBalance for check to show empty wallet page or not

---

ui/component/fileActions/index.js

The active channel wasn't being set properly on edits. So if you had channel a selected as the active channel, then tried to edit a claim made by channel b, it wouldn't work.

correctly set active channel on edits

---

ui/util/remark-timestamp.js

Closes #5523: [timestamps not interpreted in some cases](https://github.com/lbryio/lbry-desktop/issues/5523)
`remark-breaks` previously kept repeating the same index in the loop, causing some corner-cases to be parsed oddly. I added code to address that.
Later, `remark-breaks` fixed the problem and we recently just bumped up the component version. My hack is no longer necessary.

Remove hack in Timestamp parser now that 'remark-breaks' has addressed the original problem.

---

ui/component/userSignUp/index.js
ui/component/userSignUp/view.jsx

This doesn't fix the larger issue that is preventing the "first_run_started" value being actually saved in the wallet. But it should prevent users from losing subs when they run into the bug that prompts them to start the first run flow again.

don't set setting until preferences are ready

---

ui/constants/supported_browser_languages.js
ui/constants/supported_languages.js

Closes #5458: [add Finnish/Norwegian languages to supported](https://github.com/lbryio/lbry-desktop/issues/5458)
_Not sure how to do this (I'd like to know, though). I tested by creating a claim in Finnish, and then filtering it via a search -- seems to work._

Add Finnish and Norwegian

---

ui/component/fileRenderFloating/view.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/scss/component/_content.scss
ui/scss/component/_file-render.scss

Closes #5349: [Remove theater mode button from player in comments](https://github.com/lbryio/lbry-desktop/issues/5349)
Closes #5519: [Theatre mode button doesn't do anything in full screen mode [Odysse/LBRY desktop app]](https://github.com/lbryio/lbry-desktop/issues/5519)
5349: Wanted to hide for `markdown` as well, but it seems useful for `markdown` (to clear the screen from Related), so I did not include it.

Theater: hide button when not needed

---

ui/component/channelStakedIndicator/view.jsx

Needed amounts seemed odd, did small fix hopefully the right way
- [X ] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ X] I have checked that this PR does not introduce a breaking change
- [ X] Other - Please describe: Fixes small logic error with amounts.
When account has exactly 1000LBC it would be level 1
When account has exactly 1000LBC it would be level 5
I wasn't sure if lvl 4 was supposed to start at 100 or 250..... As lvl 3 ends to 250

Small fixes for amounts

---

ui/component/searchOptions/view.jsx
ui/util/query-params.js

Issue Number: https://github.com/lbryio/lbry-desktop/issues/3660
Media type filter isn't sent when Everything is selected.
Media type filter is sent when Everything is selected.

Fix mediaType filter parameter in search

---

ui/component/claimPreview/view.jsx
ui/component/claimPreviewTile/view.jsx
ui/util/context-menu.js

Closes #5500 [Allow right click + report feature on tiles ](https://github.com/lbryio/lbry-desktop/issues/5500)
- Refactored context-menu code so that both Claim Preview and Claim Tile uses the same popup.
- Added ability to Report from the context menu.
_I left the commits separated to hopefully ease the review process. Feel free to squash if necessary._

Report claims via right-click

---

package.json
ui/util/remark-timestamp.js
yarn.lock

Reverts lbryio/lbry-desktop#5525
This hack is still needed. The page may break depending on the description of a claim

Revert "Remove hack in Timestamp parser now that 'remark-breaks' has addressed the original problem."

---

ui/component/channelThumbnail/view.jsx
ui/page/channel/view.jsx

Assuming the change for now is simply to revert, this PR helps to do that.
`util/thumbnail :: getThumbnailCdnUrl` is retained for future use.
Closes #5564: [Don't use optimized URLs on channel pages (profile/banner)](https://github.com/lbryio/lbry-desktop/issues/5564)

Undo CDN images on channel banner and profile

---

ui/component/publishName/view.jsx

Closes #5563: [don't allow URL change on edit](https://github.com/lbryio/lbry-desktop/issues/5563)
- `<PublishName>` lost the `disabled` info after the re-arrangement.  
- Note: old logic was:
```
const formDisabled = (fileFormDisabled && !editingURI) || emptyPostError || publishing;
disabled = isStillEditing || formDisabled
```

Touch up for active-channel refactoring

---

ui/component/publishName/index.js

Closes #5575[: Show "URL already used" msg when publishing](https://github.com/lbryio/lbry-desktop/issues/5575)
Seems like `uri` just got accidentally removed from db87125d

Restore 'duplicate claim URL' msg while waiting for 3704

---

ui/component/fileDownloadLink/view.jsx

The removal of `svg` from `media__subtitle` in 09b689ba made the icon black.
Both 'Open File' and 'Download' should have the same css class in the first place.

Fix broken 'Open File' icon color

---

ui/component/fileRenderInline/index.js
ui/redux/actions/file.js
ui/redux/selectors/content.js

Closes #4959: `Deleting MD from downloads list causes spinning icon to run forever`
Closes #5077: `player doesn't close when video deleted`
The "view" eye button now appears in this scenario, just like it was back in Oct 2020.
The following is my understanding (please correct me if I'm wrong; been wondering about it for a while):
- `primaryUri` - the URI of the file page
- `playingUri` - the URI for the media that's currently playing. It's usually the same as `primaryUri`, but could be something else for the case of Floating Player.
The components were looking at `primary`, plus comparisons with `playing` weren't done correctly (it's an object, not string).

Restore "view" button when downloaded file is deleted

---

ui/scss/component/_markdown-editor.scss

The border became white recently, which made it look "focused" all the time. 
Confirmed with Sean that the change wasn't intentional.

Fix broken markdown editor border color

---

ui/component/fileViewerEmbeddedTitle/view.jsx

- Most titles don't fit the embed container width. I wish to know what the title is without having to click on it first.
- Also, add clarity that the LBRY icon brings you Home.
Just the usual tool-tip addition to a button/link.

Add tooltip to embed's Title and Home button

---

ui/page/show/view.jsx

So that content is still visible in the desktop app when internal-apis is down

show file page even if blacklistedOutpoints call fails

---

static/app-strings.json
ui/component/wunderbarSuggestions/view.jsx

Closes #5598[: support all URLs regarldess of domain on search bar](https://github.com/lbryio/lbry-desktop/issues/5598)
- There is already a `KNOWN_APP_DOMAINS[]`, so I just used that.
- I retained `value.includes(x)`, per original code. I wonder if it should be `value.startsWith(x)` instead.

Allow any URL from known domain in wunderbar

---

electron/index.js

Potentially closes #4729[: LBRY desktop auto-sets itself as default application for opening html files in Linux file managers like nemo after logout and login or a cold/warm boot](https://github.com/lbryio/lbry-desktop/issues/4729)
- https://gitlab.freedesktop.org/xdg/xdg-utils/-/issues/180:
- It appears that there is a piece of code in xdg that defaults the type to 'text/html' if the parameter is empty. I'm not sure if that's entirely xdg's fault, or it's the way Electron's `setAsDefaultProtocolClient` uses it.
- `setAsDefaultProtocolClient` is called on app startup, causing the incorrect 'text/html' association every LBRY starts.
In Linux Mint at least, it seems like the `protocols` entry in `electron-builder.json` is enough to associate the LBRY protocol to this app. The extra …

Linux: Don't add extra call to associate 'lbry://'

---

ui/redux/actions/notifications.js
ui/redux/reducers/notifications.js

Closes #5515[: All videos marked as read when clicking a single notification from notification list](https://github.com/lbryio/lbry-desktop/issues/5515)
- Augment `doReadNotifications` to only clear the given IDs. If the argument is `null` or is not a valid array (e.g. when used as a click handlers, the click event object is passed in), all notifications will be cleared.
- Augment `NOTIFICATION_READ_COMPLETED` to only clear the given IDs.
- Wasn't sure of the API will fail if the ID is invalid (not in the list), so I start from `unreadNotifications` first, then only filtering it further with the given ID. Otherwise, we could just skip the `unreadNotifications` filtering.

Don't clear all notifications when only 1 is clicked. 

---

ui/component/viewers/videoViewer/internal/plugins/videojs-hls-quality-selector/plugin.js

Just hides the hls-quality-selector button from the UI until metadata is loaded that indicates multiple quality levels are available.
This will hide the "auto" button that currently appears while waiting for the video's pre-fetch to complete indicating whether the file in an mp4 or m3u8 file.

hide quality selector by default

---

ui/component/viewers/videoViewer/internal/videojs.jsx

Closes #5554[: Video: loading circle sometimes does not appear until 2nd click](https://github.com/lbryio/lbry-desktop/issues/5554)
videojs behavior:
(a) A `src` change makes the Play button re-appear.
(b) An `onPlay` (or `play()`) makes the button go away.
Due to the `m3u8` header async fetch (i.e. return is potentially delayed), the initial `onPlay` (which cleared the button) that happened after user clicked Play gets negated by a potentially-delayed `src` change.  
I believe in our use case, a change in `src` always means "change src and resume play". A `src` change always comes from a Play action, and we don't pause (don't need to anyway) the player during the change.
So, hiding the button after `src` is changed seems reasonable.
We now see the spinning loading circle when video is …

Restore video loading circle

---

ui/component/channelContent/index.js
ui/component/channelContent/view.jsx
ui/scss/component/_placeholder.scss

Closes #5597[ batch resolves on channel search page](https://github.com/lbryio/lbry-desktop/issues/5597)
Do a batch-resolve immediate after getting the results and before setting the result variable, as the latter would result in the Claim* components resolving individually.
I enabled `returnCachedClaims` -- I assumed that's a reasonable thing to do. I don't see other places use it, though, so highlighting it here.

Batch-resolves channel page query

---

static/app-strings.json
ui/component/viewers/videoViewer/internal/videojs.jsx

Partially closes #3041[: Display/hint what keyboard shortcuts are available in videos](https://github.com/lbryio/lbry-desktop/issues/3041)
(minus the suggested "all shortcuts" overlay -- saving that for another day)
We override the text to:
1. Add keyboard shortcut to the tool-tip.
2. Override videojs' i18n and use our own (don't want to have 2 systems).
I was hoping the text can be set once during setup instead of using event listeners, but videojs itself updates the text to it's default strings at those listeners (thus resetting our effort), so we'll have to use listeners as well.

videojs: Localize + add shortcut tooltip

---

.github/workflows/deploy.yml

We shouldn't have any issues upgrading to Node 14, and as such, we should begin the upgrade process now as 14 is still in Active LTS, and 10 will be reaching EOL soon.
Better to begin the upgrade process early by adding Node 14 CICD testing to our pipeline.

Add Node 14 Support and Testing to CICD

---

ui/component/viewers/videoViewer/internal/plugins/videojs-hls-quality-selector/plugin.js

Fixes this warning in the web console:
`VIDEOJS: WARN: Using hls options is deprecated. Use vhs instead.`
**V**ideo.js-**H**ttp-**S**treaming has replaced `hls` tech, and deprecated `.tech().hls` in favor of the more generic and broad `.tech().vhs`
This just modifies our custom hls-quality-selector plugin to use the new tech name so that we don't throw needless warnings out from video.js
Additionally renames internal `getHls()` to `getVhs` to match internal function, and provide deprecation warning in case someone for some reason is attempting to access our internal state externally.
Adds backwards compatibility with `getHls()` by proxying function to `getVhs` with the addition of a deprecation warning.

hls options is deprecated. Use vhs instead.

---

CHANGELOG.md
ui/component/wunderbarSuggestions/view.jsx

- Closes #5316[: Home and End keys not working in search box](https://github.com/lbryio/lbry-desktop/issues/5316)
Home/End key now behaves like it normally would in a typical text box, i.e.:
- Brings you to the start or end position.
- Adding a Shift key also selects the text from the current position.
To select the top or bottom item in the Suggestion Popup List, use Ctrl+Home/End instead (without this change, it was just Home/End previously).
Adding the listener at the element level allows us to run it before the component's listener.

Wunderbar: Use typical Home/End behavior instead of ReachUI's.

---

ui/analytics.js
ui/component/viewers/videoViewer/internal/videojs.jsx

Adds new performance for detecting how long it takes for a video fetch to complete so we can attempt to investigate why some videos take long to loads, and why others are quicker.

Track duration for initial video fetch time

---

ui/component/common/status-bar.jsx

Fixes
to
just like in the web browsers

Fix unencoded StatusBar on Desktop

---

ui/component/claimMenuList/view.jsx

The old share link was showing open.lbry.com on odysee

fix share link in claim menu to use SHARE_DOMAIN_URL

---

ui/component/claimPreviewTile/view.jsx

Fixes this:
Because using a `URI` with the `link` attribute nested in a `NavLink` generates an `a` tag within an `a` tag.
Both point to the same location anyways - and normally we don't even show channels on the odysee homepage (so this isn't an issue normally) but on dev it can cause errors and cause the client to show an error screen.
Fix: we remove the link aspect since it's not needed and problematic

Fix invalid DOM

---

ui/component/markdownLink/view.jsx

Closes #4936[: Don't process markdown formatting as lbry:// url previews](https://github.com/lbryio/lbry-desktop/issues/4936)
Fix by assuming the link is the non-labelled format if the `text` is the same as `href`.
This opens up one corner-case that we can't handle, which is when the user explicitly set the label using the href, e.g. `[https://lbry.tv/befreeonlbry](https://lbry.tv/befreeonlbry)`. This will still resolve to an embed. There's not enough data at the parsed (remark) level to know if the label was autofilled by the parser or given by user -- we would need to parse the content ourself before `remark`, which I think is not worth it.
If you see that the link doesn't resolve to an embed regardless of the format used, that's probably just due to `5636: Disable video previews in …

Markdown: don't convert '[label](uri)' to embeds.

---

package.json
ui/component/repostCreate/index.js
ui/component/repostCreate/view.jsx
yarn.lock

- Closes #5673[: Reposts are all listed under "Annoymous"](https://github.com/lbryio/lbry-desktop/issues/5673)
- Requires `lbry-redux::PR_391`
- Fixes #5661[: can't choose anonymous from channel on repost page](https://github.com/lbryio/lbry-desktop/issues/5661)

Repost: fix "author" label + "can't use Annoymous"

---

ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx

Closes #5450[: Video showing previous audio clip's thumbnail instead](https://github.com/lbryio/lbry-desktop/issues/5450)
`createVideoPlayerDOM` depends on `isAudio`
Closes #5513[: Video-setting persistence broken](https://github.com/lbryio/lbry-desktop/issues/5513)
- Per videojs recommendation, the setting-restoration should be done after the video has been loaded, so the action was moved to `loadedmetadata`. This fixed the volume slider problem, and should have fixed the playbackRate too.
- For playbackRate, there is another special case where it gets reset to 1 (refer to comments in code).
- One caveat on moving to `loadedmetadata` is that the rate will be incorrect ("1") while the video is initially loading.

Video fixes

---

ui/component/header/view.jsx

Not really sure if the attribute is needed or not, but retained just in case.

Settings button: Fix typo that's causing error message.

---

package.json
static/app-strings.json
ui/page/fileListPublished/index.js
ui/page/fileListPublished/view.jsx
yarn.lock

- Closes item 2 of #4563[: Publish page + reposts](https://github.com/lbryio/lbry-desktop/issues/4563)
- Requires [lbry-redux::392](https://github.com/lbryio/lbry-redux/pull/392/files)
- Updated `fetchClaimListMine` to include another optional parameter for us to pass the filter type.

Uploads: Add 'All,Uploads,Reposts' filter

---

ui/component/livestreamComments/index.js
ui/component/livestreamComments/view.jsx
ui/component/livestreamLayout/view.jsx
ui/redux/actions/websocket.js

To prevent people from connecting multiple times if they navigate away, then come back.
The websocket handler will now reconnect on `onerror` events, and do nothing for `onclose` events. This allows manually disconnecting from a specific websocket connection.

disconnect from comment websocket when leaving livestream page

---

web/component/ads/view.jsx

I decided to concatenate the tags into the name, title, and description, set to lowercase, and check some truncated strings ('vaccin') to catch the majority of offenders with a single early-exit for loop and a short array.
Tested on steve, this seemed to allow ads on david pakman's minimum wage videos, but not the ones that mention vaccines.

get out of (adsense) jail free

---

static/app-strings.json
ui/page/youtubeSync/view.jsx

Closes #5537[: Allow youtube sync new pass language to api](https://github.com/lbryio/lbry-desktop/issues/5537)
- Default language for the selector comes from browser (`navigator.language`)
- Can't seem to get both the 'channel' and 'language' to align right unless I removed `--smushed`, but that leaves an extra margin at the top.

YT-Sync: Add field to select channel

---

ui/component/recommendedContent/index.js
ui/component/recommendedContent/view.jsx
ui/redux/selectors/content.js

Closes #3661: [Autoplay + Related go into loops ( infinite ) sometimes](https://github.com/lbryio/lbry-desktop/issues/3661)
Push the actual "next" item into the top of the list.
1. Skip if the next item is itself.
2. The URL stored in the history comes in various forms, so a direct comparison won't work.
- There's also a weird case where the URL differs by just a little (p.09 vs p-09), but with the same claim ID:
lbry://vacuum-tube-computer-p.09-–-building#5212bc8bc63c373e2bf1ebc5b765595ed7b6514d
lbry://vacuum-tube-computer-p-09-–-building#5212bc8bc63c373e2bf1ebc5b765595ed7b6514d
Check the claim_id as well to cover cases like these.

Fix autoplay infinite loop

---

ui/component/viewers/videoViewer/internal/overlays.js
ui/component/viewers/videoViewer/internal/videojs.jsx

Issue Number:
Keyboard shortcuts are limited
Changed left and right arrow keys to move 5 in time, added J and L to move 10 and K for pause. Also added up and down keybinds for 5% volume change, now mimicking other platform's keyboard shortcuts

improve keyboard shortcuts

---

ui/component/sideNavigation/view.jsx

The real fix is probably replacing this with a "checkout odysee!" message. But just hiding it for now.

remove signup nudge in sidebar for lbry.tv

---

ui/modal/modalPublishPreview/index.js
ui/modal/modalPublishPreview/view.jsx
ui/scss/component/_table.scss

Closes #5721: [Publish-Preview updates](https://github.com/lbryio/lbry-desktop/issues/5721)
(1) Match the recent "incognito" change that sets the channel to `undefined` via `updatePublishForm`. This change would also cover `null` -- I don't think it's being used to represent something else, so showing "Anonymous" for `null` should be fine.
(2) Added channel icons, so it'll be more obvious to the user if they accidentally selected the wrong channel.

PublishPreview: Add chan icon; fix "anonymous" label

---

CHANGELOG.md
ui/component/fileActions/index.js

Closes #5720: [Edit: channel-selector should re-populate with original channel](https://github.com/lbryio/lbry-desktop/issues/5720)
'incognito' was not set to false, causing the 'ChannelSelector' to select Anonymous.

prepareEdit: ensure 'incognito' is false when channel is active.

---

ui/component/fileRenderInline/index.js
ui/redux/selectors/content.js

- Closes #5811: Video-embed in markdown-post is broken
- Re-opens #4959: Deleting MD from downloads list causes spinning icon to run forever
- Revert "Fix 'makeSelectIsPlaying' to look at 'playing' instead of 'primary'." dabdc980a1ff1446d03353192e19f9291340ca88.
- Revert "Fix 'isPlaying' to reflect 'playing' instead of 'primary' URI" 351890decff63a19db177bfb631edb6cb8a44d63.
Reverting means `Deleting MD from downloads list causes spinning icon to run forever 4959` gets re-opened, but this is a way less severe issue.  Will re-visit 4959 later.
The revert is very safe in the sense that it  is very localized (only affects `FileRenderInline` and `FileRenderInitiator`) -- we are back to original code.  I think there are no recent changes that would impact this.

Fix broken video embed

---

ui/component/fileSubtitle/view.jsx
ui/component/fileTitleSection/view.jsx
ui/component/livestreamLayout/view.jsx

Issue Number:
Livestream says people are watching but at the same time that it isn't live yet
Says it isn't live but there are people waiting to watch it

Minor improvement: if not live yet, say users are waiting instead of watching

---

ui/component/dateTime/view.jsx

It is impossible to know the exact date for some of these. For videos you can click into the video to get the date of the video (but not the time).
You can now hover your mouse on the "time ago" dates and a title will pop up with the exact timestamp.
Screenshots: (my mouse cursor is unfortunately not visible)
Video tile:
Comment:
Channel about page:
Next I plan to see how hard it would be to introduce a setting to display time in 12-hour or 24-hour format. Please let me know if this is a change that you would like.

Add a title with the exact date to dateTime elements that use timeAgo

---

CHANGELOG.md
ui/scss/component/_file-render.scss
ui/scss/component/_media.scss

Issue Number: #5822 
Upload date and view count are displayed vertically on with little horizontal space.
Upload date and view count are displayed horizontally with more horizontal space.

Fixes #5822 display of upload date and view count on smaller screens

---

CHANGELOG.md
ui/component/comment/index.js
ui/component/comment/view.jsx
ui/scss/component/_comments.scss

Issue Number:
In filled comment sections it gets hard to track the Content Creator's own comments, also it could happen that someone has the same channel name and profile picture as the file owner
Added a highlight to the creator's own comments, making it better for visualization also to verify it is the actual owner.
Image example from this video: https://lbry.tv/@LBRY-Invest:c/How-to-earn-LBC-on-LBRY-Odysee:d
I just don't know how I feel about the colors, maybe this could be improved?

Highlight comments made by content owner

---

ui/component/claimLink/view.jsx
ui/component/common/icon-custom.jsx
ui/component/common/markdown-preview.jsx
ui/component/embedPlayButton/view.jsx
ui/component/markdownLink/view.jsx
ui/scss/component/_markdown-preview.scss

Closes #5738: [expand video preview level requierment to markdown images also ](https://github.com/lbryio/lbry-desktop/issues/5738)
- Videos:
- Show blank poster, plus help text on Odysee.  (Aside:  I think we still revolve back to the original problem of "not knowing what's going on" if we continue to exclude the message for Desktop).
- The "Learn More" currently points to the post in Odysee about Levels. 
- ![image](https://user-images.githubusercontent.com/64950861/113396318-eb49e780-93cd-11eb-9bbc-445569575024.png)
-  Image:
- Show a simple hyperlink, embellished with some dark background, along with help icon for Odysee.
- ![image](https://user-images.githubusercontent.com/64950861/113396332-f270f580-93cd-11eb-921a-45e1be8b054c.png)

Levels: Better presentation of blocked previews + include Images 

---

ui/component/channelAbout/index.js
ui/component/channelAbout/view.jsx
ui/component/common/markdown-preview.jsx
ui/component/fileRender/index.js
ui/component/fileRender/view.jsx
ui/component/viewers/documentViewer.jsx
ui/scss/component/_markdown-preview.scss

- Fix "channel levels" being applied to all MarkdownPreview usages
- SimpleImageLink: simplify (back to basic link) + use 'src' as last resort 
- Only apply Staked Levels to Comments (allow it in Posts)

Level: Apply to 'comments' only + simplify image link

---

ui/component/repostCreate/view.jsx

Closes #5857 [Channel does not update on display when reposting (but actually does)](https://github.com/lbryio/lbry-desktop/issues/5857)

ReportCreate: Fix anonymous url prefix

---

ui/component/wunderbarSuggestions/view.jsx

- Patch for #5316: "Home and End keys not working in search box"
Seems like 'shift+home' wasn't highlighting the text. 'shift+end' works.
Was pretty sure I tested that previously. Anyway, adding the direction variable seems to fix it.

Wunderbar: handle 'shift+home' key not highlighting text

---

CHANGELOG.md
ui/component/channelThumbnail/view.jsx
ui/component/fileThumbnail/FreezeframeWrapper.jsx
ui/component/fileThumbnail/view.jsx
ui/effects/use-lazy-loading.js
ui/util/useLazyLoading.js

Issue Number: #5795
All claim images and channel thumbnails are queued when a page is loaded; this slows down the app's overall responsiveness when many claim images are encountered on a page.
Claim images and channel thumbnails are queued as they enter the user's viewport (when about 25% of the image container is shown). This frees up network resources and makes the app feel quicker.
Before the change, 37 image requests and a total of 60, were initiated on this page when only 4 claims are visible in the viewport.
After the change, only 11 image requests are made and a total of 28 requests when those same 4 claims are visible. This is ~53% reduction in total requests.

Fix #5795 - Claim images not lazy loaded

---

web/src/html.js

The wrong `duration` value is being set in the Google Video metadata, causing the indexed data to be incorrect.  
Forgot that `moment.duration()` takes in ms.

GoogleVideoSearch: fix duration

---

web/src/html.js

Closes #5923 video metadata issues
- Description & Thumbnail
- Since these are "musts", we just drop the metadata if the values are not good.
- For thumbnails, future claims should have correct thumbnails after `5925 Fix thumbnail-checking and block 'data:image'`. For existing claims, we'll just skip the metadata to avoid the crawler error. Users can easily update their thumbnails.
- For the `OlivOliv` thumbnail url case, I wasn't sure whether to go all out to fetch and verify each thumbnail. I ended up just checking whether it starts with `http(s)`
- Duration
- There are claims without this field.  Just exclude this field from the metadata (instead of everything entirely) since `duration` is just a "recommended" field.

GoogleVideoSearch: fix blank description; invalid thumbnails

---

ui/component/copyableText/view.jsx
ui/component/walletSwap/view.jsx

Part of #5873[: Rounds 2 of LBC swaps](https://github.com/lbryio/lbry-desktop/issues/5873)
It was an intended feature to include the currency -- I can paste the full string into my note book, while pasting into wallet apps like Exodus will automatically trim off the currency anyway.
Regardless, removed the 'feature' :D
Updated `CopyableText` with `onCopy` prop that allows the client to override the full text selection.

Swap: Don't copy the currency, only amount

---

ui/component/channelThumbnail/view.jsx

Quick fix for #5933 [Thumbnail lazy-load causes ChannelSelector icon to not update](https://github.com/lbryio/lbry-desktop/issues/5933)

Disable thumbnail lazy-load for Channels

---

ui/component/claimLink/view.jsx
ui/component/markdownLink/view.jsx

Channel links were showing the "This channel isn't staking enough LBRY Credits for link previews." -- channel links shouldn't be showing previews in the first place.
Moved the logic into `ClaimLink`, which is the better place to put it anyway. I think I was trying to not touch as many components as possible (i.e. not passing `allowPreview` down too many layers) in the initial implementation. This caused the `isChannel` consideration to be missed.

Fix channel links being filtered by Staked Level

---

ui/component/viewers/videoViewer/view.jsx
ui/effects/use-get-ads.js

Unruly said we weren't sending enough fetches for them to start returning ads. Fetch for all homepages but only show ads for unauth users

fetch ads provider for all homepage videos (but still only show ads for unauth users)

---

ui/component/viewers/videoViewer/internal/plugins/videojs-mobile-ui/plugin.js

One of the items in #5865 [Video shortcut issues](https://github.com/lbryio/lbry-desktop/issues/5865)
This one is not really an issue, but it would be nice to match what the arrow keys are doing. Also, in slower regions, seeking 10s will almost always end up buffering.

Mobile: make double-tap match the arrow keys (+/-5s instead of 10s)

---

ui/constants/supported_browser_languages.js
ui/constants/supported_languages.js

While looking at the next RC, I noticed the new languages were lost. I recall the new language PR included some refactoring which had to be reverted due to some webpack issue.
Re-add those languages in the old (non-refactored) method.

Restore lost languages

---

ui/scss/themes/light.scss

The snack bar on Odysee Light is currently invisible due to the undefined `--color-success`.  
Followed `master`'s version of using `--color-primary` from the base theme for Light mode.

Fix invisible snack in Odysee Light Theme

---

static/app-strings.json
ui/component/walletSwap/view.jsx

Closes #5975: [swap stop at processing even though response comes through](https://github.com/lbryio/lbry-desktop/issues/5975)
Occasionally, the first websocket message doesn't come through (seems like the commerce didn't send?). There's really no need to wait for one more 'status=NEW' message to ensure the right data is being populated (was being over-cautious to get the amount right).

Swap: populate 'status' from 'btc/swap' response instead of waiting for first websocket input.

---

ui/component/commentMenuList/view.jsx
ui/component/livestreamComment/view.jsx
ui/component/livestreamComments/index.js
ui/component/livestreamComments/view.jsx

- Closes #5832: can't remove own comments in live stream mode (if you have multiple channels?)
- Looks like it was just missing `commentIsMine` for the new component
- Indirectly fixes "Block | Mute" appearing for own comment.
- Disable editing livestream comments.
- It doesn't do anything at the moment anyway.
- Disable deleting hyperchats 
- The "total tipped" will get deducted when hyperchats are deleted, which doesn't make sense (doesn't reflect actual total that the creator received).

Livestream comment delete/edit fix

---

package.json
yarn.lock

Closes #6044 "thumbnail is invalid" not reset with new thumbnail upload 
Requires lbry-redux update.
Defining a default value will cover both CLEAR_PUBLISH and DO_PREPARE_EDIT

[+redux] Define default value for 'thumbnailError'

---

ui/component/notification/view.jsx
ui/constants/notifications.js

Closes #6021: `Notifications: Missed Out`
kp.odysee.com
See full commit messages for details.
Addition notes:  the tooltip change doesn't really help Mobile, but maybe we'll add "press-and-hold" for tooltips one day.

Notification: further handle "missed_out" + other tweaks

---

static/app-strings.json
ui/component/common/icon-custom.jsx
ui/component/postViewer/index.js
ui/component/postViewer/view.jsx
ui/constants/icons.js
ui/scss/component/_post.scss

Closes #5882: `tip unlock + claim id detials missing from markdown posts view`
kp.odysee.com
The easiest solution would be to put `FileDescription` into posts, but I think that goes against the clean up of the Post layout, where the focus should be on the content. The faded style of the File Details section will be too distracting, plus we don't want the File Description anyway.
Fixed by:
- Make the existing "LBC amount" clickable to show credit details. An additional padlock will appear to the right if the content is yours and you have tips to unlock.
- Add an "info" icon to the left to show file details.
These "link" buttons are usually lit, but I dimmed it in this case to make them stand out less. Again, focusing on Post content instead of buttons.

Posts: restore "Tip unlock | Claim details" component

---

ui/component/fileThumbnail/FreezeframeWrapper.jsx
ui/effects/use-lazy-loading.js

Closes #6010: `hyperchat send display issues with GIF profiles`
The `FreezeFrameWrapper` have no `src` to freeze due to the lazy loading.
Delay the freezing by making the lazy-load effect return a state to indicate when then `src` has been loaded.
Since the lazy-loader will `unobserve` after loading, the state should/will never go back to false, so we don't need to handle the case of preventing `new FreezeFrameWrapper` from being called multiple times from it's effect.

Fix blank gif avatars

---

ui/component/claimListDiscover/view.jsx
ui/component/claimTilesDiscover/view.jsx
ui/util/search.js

This completes the change in c24c016e, covering ClaimListDiscover as well, in case it changes again in the future.
No functional change, just refactored the function so that both Tile and List uses the same code.

Livestream-only query cleanup.

---

ui/component/fileRenderInitiator/view.jsx

Issue Number: #5309 
A timestamped video will not autoplay if autoplay is turned off
Even if autoplay is turned off for the user, the video will autoplay if a timestamp is present
I don't know if this is the best design in the world, perhaps it would be more appropriate have a React component hook into the Prop value to automatically pre-empt and change it, but it's a simple and working solution, really I'd like to talk to someone who is more familiar with the codebase and ask for their take but I can confirm this as a working solution.

Force video autoplay when a timestamp is present in URL

---

ui/component/fileRenderInitiator/view.jsx

Closes #6078 `"Autoplay media files = disable" is broken`
`if (-1)` is "truthy"

Restore "Autoplay media files" behavior

---

ui/component/channelThumbnail/view.jsx
ui/page/channel/view.jsx

- Closes #6067 `ChannelThumbnails: revisit image optimization`
- Better attempt for #5564 `Don't use optimized URLs on channel pages (profile/banner)`
This is not the best/full solution yet, but it is better than what we have to today (one step in the right direction). The main page should load faster now.
Changes:
- Re-enabled optimization for `ChannelThumbnail`, but disable it for the avatar in Channel Page and also if it's a GIF.
Optimized channel thumbnail size is currently hardcoded to a lowest common denominator.  Filed as #6074 `Get exact optimized thumbnail sizes instead of hardcoded to lowest denominator`
- Closes #6066: `Revisit lazy-loading Channel thumbnails`.
- Properly fixes #5933: `Thumbnail lazy-load causes ChannelSelector icon to not update`.
- Add effect-dependency on …

ChannelThumbnail fixes

---

ui/component/commentCreate/view.jsx
ui/component/commentsList/view.jsx
ui/util/comments.js

Issue Number: A fix from (#5939)
I just noticed when you add multiple comments they replace each other at the top:
Improved the logic so that all show up:

Improve logic for own comments showing first

---

ui/component/fileRenderInitiator/view.jsx

It's useful to show the thumbnail as the player's backdrop when Video Autoplay is OFF, but it's a wasted fetch when it's ON because the videojs component will be blocking it.
Although it's the same image as the ClaimPreview, this one will be in full size, so a fetch will always happen.
Aside: videojs handles the backdrop for the audio and embed case, so this change won't affect those items.
```
<VideoJs
poster={isAudio || (embedded && !autoplayIfEmbedded) ? thumbnail : ''}
/>
```
Future: for "mobile + autoplay=OFF", we should consider using the optimized thumbnail. 6074 should help.

Skip thumbnail fetch if autoplay is ON

---

ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx

When opening a video directly in Chrome Incognito, the video should autoplay (since that's the default Lbry setting), but it doesn't due to browser policy
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
- We don't want to forcefully mute the video when `autoplay=true`; we just want to do it when the browser policy is applied.
- Fortunately, there is already an existing code-block for us to check that.
- I've seen `error` occasionally being undefined in the `catch` block. In those cases, the solution doesn't work. We could remove `if (player.autoplay() && !player.muted())` and simply just try muting it, but for now it's better to ensure `NotAllowedError` is due to unmuted first before applying the fix.
- This doesn't work for Firefox as there is an explicit "Allow …

Mute video when autoplay is blocked by browser policy

---

ui/scss/component/_videojs.scss
ui/scss/themes/dark.scss

- Closes #5998 Theme color problems
- "_Seeing the theme go blue when a modal pops up. There's a change in color on Odysee branch also when this happens (but not as apparent)_"
1. Fix overlay background color back to gray theme.
2. Also, fixed the Active Toggle Button back to primary colors.
3. Fix hard-to-read "videojs time tooltip". Using the primary colors is a nice touch, but people have complained in Discord that it's too dim given it's transparent background. Just use 'white' instead. Don't use '--color-white' since that's a bit dimmed down.
4. Fix odd highlight in the volume slider (the bright primary color was used in the background). https://github.com/lbryio/lbry-desktop/pull/5549#issuecomment-801194115

More theme color fixes

---

ui/component/fileRenderInitiator/view.jsx
ui/component/fileRenderInline/index.js
ui/component/fileRenderInline/view.jsx

- Auto fetch paid-content if already paid
- Seems odd to force users to manually "play" purchased files.
- Fix #5932 "no way to buy Paid Images or Posts"
- FileRenderInitiator: we don't display if it's not Audio or Video ("playables"). But only do that if it's free or was purchased, otherwise there's no button to buy it.
- FileRenderInline: if the user have not purchased it, don't show anything (not even the spinner).

Fix #5932 "no way to buy Paid Images or Posts" 

---

ui/component/dateTime/view.jsx

Part of [#5834 Performance investigation](https://github.com/lbryio/lbry-desktop/issues/5834)
In a homepage with 120 tiles, the lists get rendered 3 times during initial update*. The sub-components are updating recursively*, so instead of 120 DateTime renders, we have 1000+ renders.
<sub>*will investigate separately on the 3-updates + why recursively</sub>
The resolved DateTime string for `timeAgo` rarely changes, and even if the string was "a few seconds ago", there's no real need to constantly update it.
Require a minimum 1-minute delta when deciding whether the component should update. Clients can change this value as needed.
After:

DateTime: avoid unnecessary update

---

ui/redux/actions/comments.js

The "Muted Words" PR elevated Comment-API errors so we can handle it (previously, it goes unnoticed). This broke the other Comment functions because the spammer mitigation might return an error, causing `Promise.all` to bail early.
Changed to `Promise.allSettled` and reconstructed the results. This will make it equivalent to the code prior to the "Muted Words" PR.
----
@jessopb @tzarebczan, I had to bypass lint for this one.  Not sure how to add `allSettled` to lint.  Was trying to tweak the Bluebird file but didn't work -- not sure where else to tweak.

Fix broken Block List due to surfacing of error

---

ui/scss/component/_notification.scss

Closes [#6056 Extend notificaiton text to show more characters](https://github.com/lbryio/lbry-desktop/issues/6056)
Looking at the code and comments, I couldn't figure out what was the reason for adding the width constraint (just in case this breaks something).
My guesses:
- Try not to make the rhs thumbnail too far apart from the lhs thumbnail.
- Try not to make the rhs thumbnail misaligned due to dynamic width of the "xx days ago" string on the far right.
Extended the width as much as possible, while retaining some gap before the "xx days ago" string and "unread dot" so that thumbnails stay align in the general case.
The components still reflows nicely (as it did previously) per window-size.

Bump up notification content width to show more text

---

ui/component/page/view.jsx

Closes [#6112 Side menu expanded by default unless collapsed by user](https://github.com/lbryio/lbry-desktop/issues/6112)
Changes won't appear in Odysee until merged.
Did it in `master` to reduce diffs between `odysee`. 
`master` was already expanding by default.  It seemed like it was intentional to collapse it by default in Odysee back then.

Open the sidebar by default

---

ui/redux/reducers/tags.js
web/package.json
web/yarn.lock

1. Update `web.package.json` to point to the latest `lbry-redux` and `lbryinc` (discussed in Slack)
- It's odd that things have been working fine without the correct reference.  Hopefully this doesn't cause more issues that it tries to fix.
2. Optimized `getDefaultKnownTags`
- Requires `web.package.json` to point to the right dependencies.

Optimized `getDefaultKnownTags` || update `web.package.json`

---

ui/component/loginGraphic/index.jsx
ui/scss/component/_main.scss

1. Lock the width of the second pane so that the layout doesn't shift after the image is fetched.
2. The image is huge, so pass through the optimizer. Wait until the container is mounted to get the exact image width.
Unfortunately, it still takes 0.8s on average to fetch the image, regardless of how small the new image has been optimized.
Here's a 100px*200px request needing 2s.  I guess the optimizer is just waiting for `cdn.lbryplayer.xyz` to deliver the original.
- ![image](https://user-images.githubusercontent.com/64950861/120094063-bac5c600-c150-11eb-8ae1-3ba88aead2c5.png)

Login graphic improvements

---

ui/component/viewers/videoViewer/internal/videojs.jsx
ui/scss/component/_file-render.scss

Issue Number: #5737
Uses ios native player (no styling, can't change speed, auto fullscreen)
Use videojs stylized frontend, also use playsinline to view video without auto full screen

use video js viewer for ios and add playsinline

---

ui/component/fileActions/view.jsx

Closes [#6167 Make downloading more intuitive / obvious in web mode](https://github.com/lbryio/lbry-desktop/issues/6167)
- Hidden for SIMPLE_SITE in e10647b5, but not sure why.  Did we have an important reason to block?
- Requires odysee merge for the changes to be live.

Re-enable "file download" in Odysee

---

ui/analytics.js
ui/component/viewers/videoViewer/view.jsx

Time to start is multiplied by 1000, which was supposed to be a division if we're trying to get milliseconds, but metrics endpoint expects seconds anyway so there is no need for it.

Fix time to start metric

---

ui/scss/component/_notification.scss
ui/scss/themes/dark.scss

Closes [#6196 Bright Theme is Broken](https://github.com/lbryio/lbry-desktop/issues/6196)
I was trying to fix the problem of the border not visible in Desktop Dark because the highlight color was the same as the border color.  The approach didn't take Light and Odysee into account ... oops.
Round 2.
- Odysee side:
- take (restore) `background-color: var(--color-card-background-highlighted);`
- ignore the change in border color (retain odysee color).

Fix notification color.

---

web/static/pwa/manifest.json

I had decided that `standalone` was probably the better `display` value for the pwa over `minimal-ui` but never ended up changing it in the code, here is a pull request to make that change
Here's documentation on the different display values and their corresponding look on mobile:
https://superpwa.com/doc/web-app-manifest-display-modes/

use standalone as the display instead of minimal-ui

---

package.json
ui/component/publishAdditionalOptions/view.jsx
web/package.json
web/yarn.lock
yarn.lock

[Continuation of lbryio/lbry-redux/pull/414]
Publish page tries to set the upload language to the user langauge, and it does so on edit and overwrites the existing value.
Closes #6132
selectPublishFormValues was trying to return "language" from formValues but would always return false, and set the language as default instead, should return "languages" instead.

Don't reset content language on edit [+redux]

---

ui/component/commentCreate/view.jsx

Issue Number: Closes #6063
In case of failed comment, allows to re-submit the previous tip, without having to send another tip
_(tried to comment twice, first tip failed, re-submitted without tipping twice)_

Handle comment + tip failure, don't re-support

---

package.json
ui/component/publishAdditionalOptions/view.jsx
web/package.json
web/yarn.lock
yarn.lock

Reverts lbryio/lbry-desktop#6178.  This was breaking `/$/upload`

Revert "Don't reset content language on edit [+redux]"

---

ui/component/fileActions/index.js
ui/component/fileActions/view.jsx
ui/component/fileDownloadLink/view.jsx
ui/util/downloadClaim.js

Closes [#6236 Add context menu to file page](https://github.com/lbryio/lbry-desktop/issues/6236)
The download button actually handles a lot of things -- generating 'streamingUrl', differences between Web and Desktop, download progress for Desktop, etc.  A simpler fix would be to put something else (maybe "Share") into the overflow menu instead.
Anyway, went ahead to do it per 6236, but retained the item for Desktop since we need a progress label.

Move 'Download' and 'Report Content' into overflow menu.

---

static/app-strings.json
ui/component/claimPreview/view.jsx
ui/page/settingsCreator/view.jsx
ui/util/search.js

While Lighthouse allows looser searching like "Tom from LBRY", it doesn't show the expected results when direct channel name with partial ID is entered to disambiguate.  Instead of having 2 ways of searching/validating, stick with the one that works (using `resolveUri` on the search term).

Moderation: resolve chan name or URL instead of using Lighthouse.

---

ui/component/viewers/videoViewer/internal/videojs.jsx

Closes #6278 Video doesn't switch when floating player is up
Not sure why the double `src` call is needed, but it is.

Fix videos not switching when floating player is up

---

ui/component/fileViewCount/view.jsx

`isLive` is being checked instead of `livestream`.

fix incorrect variable being used to determine view state for live view count

---

README.md

Kiyui has made it evident that they're no longer on Arch and outright removed themselves as a maintainer for the AUR package.
See: https://aur.archlinux.org/packages/lbry-app-bin#comment-813900
Best wishes to em' in their journies!

Remove kiyui as maintainer for AUR package

---

ui/component/viewers/videoViewer/view.jsx

Fixes issue where shouldPlay becomes undefined and will break autoplay if video is transcoded due to a new load request being started.

fix autoplay for transcoded files

---

ui/page/channels/index.js
ui/page/channels/view.jsx

Closes [#6237: Analytics button from Channels page doesn't open analytics to right channel](https://github.com/lbryio/lbry-desktop/issues/6237)
I assume we have changed to the `activeChannel` method, so we are dropping the direct URL support.  Saves us the need to update the URL when user changes from the selector after entering the page.

Set 'activeChannel' before entering Dashboard

---

ui/component/fileThumbnail/view.jsx
ui/component/loginGraphic/index.jsx

Closes [#6301: don't use CDN for GIF thumbnails](https://github.com/lbryio/lbry-desktop/issues/6301)
Just a minor mistake in the recent thumbnail refactoring; left out the handling when `allowGif` is true.

FileThumbnail: don't go through optimizer if GIF

---

ui/component/viewers/videoViewer/internal/plugins/videojs-recsys/plugin.js

- The `rateChange` event now logs the updated speed,
not just the    time at which it occurred.
- The `scrub` now (more) accurately logs the position
it came from before the destination.
- The recsys events get consolidated for logical consistency.

FIX video.js event firing issues for RecsysPlugin

---

ui/component/wunderbarSuggestion/index.js
ui/component/wunderbarSuggestion/view.jsx
ui/component/wunderbarSuggestions/view.jsx
ui/effects/use-lighthouse.js

This cherry-picks the wunderbar-debouncing PR from `master` to `odysee`
- Resolve conflict -- Assuming we'll collapse odysee first before rebasing to master, this PR will help reduce the amount of conflicts (there was a recent attempt to adjust the throttle in odysee as well).
- Bring over the changes to odysee early to lighten up Lighthouse, without having to rebase to master.  I assume we don't want to bring in 'code-split' yet until it's proven ok in lbry.tv.

Pick wunderbar-debouncing fixes to odysee

---

ui/component/viewers/videoViewer/internal/videojs.jsx

Per this PR: https://github.com/lbryio/lbry-desktop/pull/6315/
It was determined that the CC button showing up errantly was being caused by the m3u8 spec requiring explicit disabling of captions when there are multiple video tracks in latest iOS versions.
So the true fix of this is the backend to include the CLOSED-CAPTIONS=NONE in the proper tag in the m3u8 file (documented by Xander in the linked PR above).
Though disabling closed captioning by default will cause an issue whereby people who stream with live captions to livestreaming will have that temporarily disabled, the jarring effect of this CC popping up on all transcoded videos on iOS, that this will affect/confuse a lot more viewers than those who will be affected by the disabling of live captions on livestreams,  we will turn …

dont display cc button via videojs settings

---

ui/scss/component/_main.scss

Issue Number: #5680 
On iOS (and probably other mobile devices) the secondary content section gets stretched. Check #5680 for more information
No longer is stretched by the comment section

fix div being stretched by comment section

---

package.json
ui/component/claimMenuList/view.jsx
ui/util/url.js
web/src/chainquery.js
web/src/routes.js
web/src/rss.js
yarn.lock

- Test:  https://kp.odysee.com
- ⚠️ Note that you'll need to append the 'kp' subdomain yourself after copying the RSS URL.
- This PR is on `master`.  Cherry-pick the commits (no conflicts as of writing) to Odysee if there's urgency.
----
Closes #3779 RSS feed for channels
- RSS only (no atom -- simplifies selection GUI).
- <strike>Grabs latest 10 entries (Beamer had concerns).</strike>
- RSS link can be copied from the channel page's context menu.
- Still trying to figure out how to replace the generic RSS icon with the channel thumbnail:
- <img src="https://user-images.githubusercontent.com/64950861/123931715-5b630c00-d9c3-11eb-85b4-410d68e23c28.png" width="400">
Feedly example:
- <img src="https://user-images.githubusercontent.com/64950861/123931827-759cea00-d9c3-11eb-9c99-3f24a2259a0f.p …

RSS feed for channels

---

ui/component/common/wait-until-on-page.jsx
ui/page/home/view.jsx

See commit messages for complete walkthrough.
- `WaitUntilOnPage` never unregisters scroll-callback, and was also registering on every update.
- Run `claim_search` when category is approaching the viewport.
- `WaitUntilOnPage` was not responding to window-resize or zoom changes, so it could stay hidden until a scroll event happens.

Front-page lazy-load fixes and improvements

---

ui/component/recommendedContent/view.jsx

When seeking on a video, RecommendedContent gets re-rendered, which causes the 20 ClaimPreviews to be re-rendered, several times. ClaimPreview has lots of children, plus it's constantly checking against the blacklist, among other things.
The culprit seems to be the `recommendedContent` array -- the contents are actually the same.
Do a deep compare instead.
- Is there a more elegant way to deep-compare?
- For `claim`, is comparing the `claim_id` sufficient?
- Not really sure why `SET_CONTENT_POSITION` would end up marking `makeSelectRecommendedContentForUri`.
Circled item indicates React activity when seeking a video. Reduced from (24ms * N) to (8ms).
- Before:
- <img src="https://user-images.githubusercontent.com/64950861/123607933-e65fcd00-d830-11eb-8946-82b9862a74a3.png" width="400">
- …

RecommendedContent: prevent excessive render

---

ui/component/claimLink/view.jsx
ui/component/fileRender/view.jsx
ui/component/fileRenderFloating/view.jsx
ui/component/fileRenderInline/view.jsx
ui/component/viewers/videoViewer/internal/overlays.js
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx
ui/constants/classnames.js
ui/page/embedWrapper/view.jsx
ui/scss/component/_file-render.scss
ui/scss/component/_videojs.scss
ui/scss/third-party.scss

The loading circle wasn't showing up, causing confusion.
Splitting CSS doesn't seem trivial as there seems to be a huge dependency on the load order. Pretty much similar to what this person is facing https://lihautan.com/css-code-splitting/#the-problem
This reverts videojs-specific changes from 4d638bcf.

Revert lazy-loading videojs

---

ui/component/common/icon-custom.jsx

@jessopb, is this the right fix?  What puzzles me is that if `buildIcon` is needed for props to be forwarded, then shouldn't all icons use it to avoid surprises?

Fix RSS icon not having a gap

---

ui/modal/modalRemoveFile/view.jsx
ui/modal/modalRevokeClaim/view.jsx

I edited this on GitHub and didn't run it

remove words like "revoke" and "claim" from abandon modal

---

web/webpack.config.js

The old JS clearing functionality but only run when it's not on prod
Useful for development to avoid a buildup of JS files in the dist/public folder

clear stale js files on nonprod environments

---

web/webpack.config.js

If was failing the build for environments without a prior build.

Check if folder exist before clearing stale js

---

static/index-web.html
ui/component/app/view.jsx
ui/component/claimPreview/view.jsx
ui/component/errorBoundary/view.jsx
ui/component/fileRender/view.jsx
ui/component/page/view.jsx
ui/component/router/view.jsx
ui/component/wunderbar/view.jsx
ui/modal/modalRouter/view.jsx
ui/page/file/view.jsx
ui/page/show/view.jsx
ui/util/lazyImport.js

@jessopb, if the solution is acceptable, I'll rework the entire to repo to change from `React.lazy` to `lazyImport`  
Currently, I only applied it to `Settings` and `TipModal` to test the concept.
Solutions that I know of:
1. Reload on behalf of user (this PR). 
2. Similar to 1, but instead of reloading directly, we display a message somewhere saying "A new version is available. Please refresh".
3. Run a `serviceWorker` to listen for changes, and somehow update the current page (this is beyond my understanding to implement at the moment).
It seems like either approach would require a reload, so number 1 seems the easiest.
There are a few caveats, though:
1. It works seamlessly for Pages (other than the user seeing a brief flash from the reload), but it's a bit odd for smaller lazy-loaded …

Handle stale/missing chunks

---

ui/component/channelContent/index.js
ui/component/channelEdit/index.js
ui/component/channelMuteButton/view.jsx
ui/component/channelSelector/index.js
ui/component/claimCollectionAddButton/index.js
ui/component/collectionEdit/index.js
ui/component/collectionMenuList/view.jsx
ui/component/collectionPreviewOverlay/view.jsx
ui/component/livestreamComment/view.jsx
ui/component/livestreamComments/index.js
ui/component/livestreamList/index.js
ui/component/markdownLink/index.js
ui/component/nagContinueFirstRun/index.js
ui/component/notificationBubble/index.js
ui/component/notificationContentChannelMenu/index.js
ui/component/publishAdditionalOptions/index.js
ui/component/recommendedContent/index.js
ui/page/settingsAdvanced/index.js
ui/page/settingsAdvanced/view.jsx
ui/page/settingsNotifications/index.js
ui/page/settingsStripeCard/index.js
ui/page/settingsStripeCard/view.jsx

I believe it was just due to copy/pasting from another file and not renaming it.

Rename default import/exports for clarity in text search (no functional change)

---

ui/scss/init/_gui.scss
ui/scss/themes/dark.scss

Odysee: fix missing '--color-help-warning-bg' for Dark

---

ui/component/claimMenuList/view.jsx
ui/util/url.js
web/src/routes.js
web/src/rss.js

Tom mentioned I should use canonical instead of arbitrarily slicing.
- Change to canonical_url (with ':').
- The old format of 'claimName/claimId' needs to be supported still, since we shipped with it.
- It would be nice to use regex instead of 2 separate paths, but I couldn't figure out how to make the koa variables work.

RSS: Use canonical_url (with ':') instead of slicing to 2 characters.

---

ui/scss/component/_file-render.scss

Closes #6447
`https://github.com/videojs/video.js/pull/7098`
videojs was recently upgraded.
Override videojs default theme of hiding the time control in smaller layouts.

Fix missing "currrent/remaining time" control is mobile

---

ui/component/searchOptions/index.js
ui/component/wunderbarSuggestions/index.js
ui/page/search/index.js
ui/page/search/view.jsx
ui/redux/actions/search.js
ui/redux/selectors/search.js

Closes #6414 <Don't use "exact match" setting outside of main search - cuases no results in related>
`doSearch` was used in Wunderbar and Recommended, but it was adding in Wunderbar options all the time.
- Fix `doSearch` to not use hardcoded options (take from arguments).
- Refactors the searchOption-creation code so that we don't duplicate the logic in both .js and .jsx.

Fix "exact match" being applied to Recommended

---

ui/component/claimMenuList/index.js
ui/component/claimMenuList/view.jsx
ui/component/claimPreview/view.jsx
ui/component/claimPreviewTile/view.jsx
ui/component/collectionContentSidebar/view.jsx
ui/component/collectionSelectItem/view.jsx
ui/component/collectionsListMine/view.jsx
ui/component/fileWatchLaterLink/index.js
ui/component/fileWatchLaterLink/view.jsx
ui/page/collection/view.jsx
ui/scss/component/_claim-list.scss

Issue Number: [WIP] for #6205
Switched around Watch Later to appear as a hover action on thumbnail:
So the last used playlist can be at the popup menu, the reasoning is so the menu doesn't get too filled and makes both actions quicker, single click to watch later, first option on popup to most recent list:
_edit: adding another reason here: makes it easier to verify if you already added a certain video to watch later just by hovering the mouse on the thumbnail, since the icon should change you don't need to keep checking_
But it still doesn't remember last used playlist choice, it's set to Favorites for now
_also added a link to the watch later list on the Toast in case I want to jump into the …

Add watch later to hover action for last used playlist on popup

---

ui/component/commentsList/view.jsx

myReactions will never be filled in incognito. Also, it's probably enough to just check othersReactions, but for now, still do both when logged in.

Fix continuous reaction fetch in incognito

---

ui/component/walletSendTip/view.jsx

Someone mentioned about odysee.com showing "tip" related text when supporting **own** claims. Now it should default to "Boost" related text for **own** claims.
L167: Line not edited but not sure if "claimIsMine" is needed there any more.
Issue Number:
When supporting own channel ,app/site shows text about tipping.
When supporting own channel, app/site shows text about boosting.

Minor fix suggestion: Default to "TAB_BOOST" when supporting own claims

---

static/index-web.html

We probably don't need to preload fonts (it will reduce browser warnings), since it wasn't working all this while.
But it's probably there to address something (perhaps to handle OG better?), so do it right by setting the proper flags.
https://stackoverflow.com/questions/1330825/preloading-font-face-fonts/46830425#comment87712868_46830425
Font is re-fetched

Preload fonts properly with 'crossorigin'

---

ui/component/channelThumbnail/view.jsx
ui/component/optimizedImage/index.js
ui/component/optimizedImage/view.jsx
ui/page/channel/view.jsx

> Core Web Vitals:  "Keep request counts low and transfer sizes small"
_Channel banners can hit several MBs._
Optimize the banner filesize, but don't compromise on the quality (i.e. never show blurry banner)
1. Visually, the banner is as sharp as the version before this PR, with the exception of the following scenarios:
- If you load the page in a smaller zoom and then zoomed out, it will be potentially blur if you go from one extreme to the other. A reload is required to get a sharp image in the new zoom setting.
- It's the same in YT's banner.  When cache is disabled, YT seems to listen to window-resizing and grabs an updated image.  I don't think we need to do that.
- Depending on the format (mostly on JPG), images with sharp edges will be slightly aliased due to the compression. But …

Optimize channel banner

---

ui/component/optimizedImage/view.jsx

Recently changed to `<OptimizedImg>`, which was assuming the `src` never changes.
dejavu ... we also hit this issue when implementing the `IntersectionObserver` lazy-loading.

Fix channel-selector thumbnail not updating

---

web/middleware/cache-control.js

Cache any js file residing in `/public` that ends with a 12-character hash.  12 is the shortest among webpack-split files.

Improve cache for hashed js files

---

ui/component/claimPreviewTile/view.jsx

Closes #6589
`parseURI` will return `isChannel=false` due to the reposted channel URL not having the '@' symbol.
Since we already have the claim object, check `value_type` directly instead.

Fix reposted channels incorrectly showing the channel thumb

---

ui/component/claimListDiscover/view.jsx

Closes [#6542 Livestream listing and blocked list kills CLS score](https://github.com/lbryio/lbry-desktop/issues/6542)
This is basically a repeat of what was done on `claimTileDiscover` (homepage), but now on `claimListDiscover` (category pages).
This handles the unnecessary re-render when:
- the uri list temporarily being zero while waiting for new claim-search results.
- livestream claim-search invalidating the list.
Store the last uri list and use that when we know that claim-search is still not done.  Most of the time, we ended up with the same list of uris.
1. Ran Lighthouse on category pages (force a livestream channel on it). CLS score must be green.
2. Block `claim_search` from Dev Tools and move to another category. The page should say "timed out" instead of "no results" (i.e. …

claimListDiscover: don't re-render until query is done

---

ui/component/postViewer/view.jsx
ui/component/viewers/documentViewer.jsx
ui/scss/component/_file-render.scss
ui/scss/component/_main.scss

Closes [#6068 Fix "Cumulative Layout Shift" for Core Web Vitals](https://github.com/lbryio/lbry-desktop/issues/6068)
In Posts, the Comments section appears first while we fetch the MD file. When the MD is fetched, Comments get pushed to the bottom (or shifted up for short posts), hence the red CLS scores.
There are too many layers between `<FilePage>` and `<DocumentViewer>` to pass the `loading` state around to hide the Comments section, so just make Comments fade in after a 2s delay.
- Posts: Add 2s fade-in delay to Comments.
- Posts: remove the gray placeholder. This improves the score a bit more, and reduces flicker as well. There's already a spinner from `FileRenderInline` to tell the user to be patient.
- Posts: add a minimum 30vh height so that short posts don't get collapsed too …

Improve CLS on Posts

---

ui/component/claimPreview/claim-preview-loading.jsx
ui/scss/component/_ads.scss
web/component/ads/view.jsx

[#6068 Fix "Cumulative Layout Shift" for Core Web Vitals ](https://github.com/lbryio/lbry-desktop/issues/6068)
[#6057 Investigate low Core Web Vitals score from google ](https://github.com/lbryio/lbry-desktop/issues/6057)
- Fix wrapper-size mismatch between "loading" vs "loaded" state.
- Reserved space for video ads by assuming a 16:9 aspect ratio. 
- When the ad is injection, the margin changed a bit. Not sure where that is coming from, but the impact is small on the score.

Fix CLS in `Recommended` section

---

ui/redux/actions/comments.js
ui/redux/reducers/comments.js

Creating Settings suddenly start to stop loading correctly for some of my channels.
`settings.List` now returns null instead of empty array. Double-checked the Commentron repo and this is indeed the case.
Updated the code to handle null.

Fix muted-words now returning null instead of ""

---

ui/component/viewers/videoViewer/internal/videojs.jsx
ui/redux/actions/comments.js

Seems like lint is being bypassed recently?
Reviewing just in case this was intentional, but it's messy in production and interferes with developer's own logging locally.

Remove console.log

---

static/app-strings.json
ui/redux/actions/comments.js

Feel free to change the text.  Currently, we are showing "Unable to create comment".  Neither that nor "duplicate comment!" looks polished.

Beautify/elaborate comment spam-check message

---

ui/page/channel/view.jsx

In the Channel Page, if the _Collections_ `claim_search` comes in after the main content's `claim_search`, the Collection's `ChannelContent` is being re-rendered despite not being in the active Tab. This causes a 0.4 CLS score (it's ridiculous that invisible components are taken into account). Apparently 41% of users are hitting this scenario, causing a poor aggregate.
Don't mount the `ChannelContent` components unless its tab is the active one. It doesn't seem like Reach Tab unmounts components under the inactive tab (?)
Can merge directly is approved/no issues.

Fix Channel-Page CLS

---

ui/component/fileThumbnail/thumb.jsx
ui/component/fileThumbnail/view.jsx

Closes [#6721 Notifications: Thumbnail for "new content" not showing up in Desktop layout](https://github.com/lbryio/lbry-desktop/issues/6721)
The `className` wasn't propagated during the `FileThumbnail` refactoring to `Thumbs`.

Fix missing file-thumbnail in Notifications

---

ui/component/collectionContentSidebar/index.js

Right now the list will show the selected file as "active", not the currently playing one
Even if the playing item is floating, it will remain as active, until another file starts playing:
[![Anima-o.gif](https://i.postimg.cc/zfvrL4YJ/Anima-o.gif)](https://postimg.cc/xXw7hxd7)

Fix currently active playing item on playlist

---

static/app-strings.json
ui/component/livestreamLink/view.jsx

Issue Number: #6632 
Changelog update: #6735

Fix unnecessary livestream api calls in channel page

---

ui/scss/component/_header.scss

From discord:
> Nikkei•プレーヤー#3
— 
Today at 11:10 AM
Ah I see what you mean, If you're using mozilla based browser the odysee logo is pretty squished, In chrome based browser looks fine.
https://discord.com/channels/362322208485277697/363049604461232148/871424669075513375

Fix logo size on firefox

---

ui/component/claimMenuList/view.jsx

b164a5d1 accidentally nulled the changed.
While at it, moved the "Copy RSS" button below "Copy Link" -- I think that looks better.

Restore "Use better icon for "Copy Link"" -- lost in a merge.

---

web/src/html.js

Closes [#5951: OG messed up if `$"` is in title](https://github.com/lbryio/lbry-desktop/issues/5951)
To replicate: `web:dev-server` with CQ credentials, then open the link mentioned in the issue.
The replacement string would contain `...$&quot...`. The character `$&` has special meaning in `replace`, so the output was messed up.
Use a direct slice approach. A bit less elegant.

Fix: OG messed up if `$"` is in title

---

CHANGELOG.md
ui/scss/component/_button.scss

Fix links line breaking mid word

---

CHANGELOG.md
ui/page/show/view.jsx
web/src/html.js

Closes #6780
Closes #6464
Closes #6812

Use resolve for OG metadata

---

.github/PULL_REQUEST_TEMPLATE.md

1. Add hint on adding "Closes", "Fixes", etc. keywords to directly update the Issue state when the PR gets merged
2. Collapse "PR Checklist" and "PR Type".
- With the assumption that these 2 items are mainly reminders for contributors, and that reviewers will typically only look at it one time, we collapse these sections to reduce clutter in the PR description.
----
Jessop, given that you're the chief reviewer, feel free to close this if you don't like it.

Add keyword hint | Collapse "PR Checklist" and "PR Type"

---

ui/component/commentCreate/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/6852
When submitting a comment, the cancel button isn't disabled.
When submitting a comment, the cancel button is disabled.
</details>
</details>

Disable cancel button when submitting a comment.

---

ui/component/claimMenuList/index.js
ui/modal/modalRemoveFile/index.js
ui/redux/selectors/content.js

Issue Number: Closes #6797
`makeSelectSigningIsMine` was just a workaround and is not needed anymore, replaced it back to `makeSelectClaimIsMine` as to identify anon claims
</details>
</details>

Fix delete option broken / missing

---

ui/component/repostCreate/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/6802
When accessing the repost page, the message "Winning amount: n" is always displayed, no matter what bid is required to take over:
The component `BidHelpText` is used to properly display the bid message.

Reuse BidHelpText for reposts

---

flow-typed/Comment.js
ui/component/livestreamComment/view.jsx
ui/component/livestreamComments/index.js
ui/component/livestreamComments/view.jsx
ui/redux/actions/websocket.js
ui/redux/reducers/comments.js
ui/redux/selectors/comments.js
ui/scss/component/_comments.scss
ui/scss/component/_livestream.scss

Fixes [#6420 Pinned Updates in SuperChats ](https://github.com/lbryio/lbry-desktop/issues/6420)
The top (latest) pinned comment will be displayed at the top of the livestream chat.  Only 1 pinned message will be displayed (same as other platforms).  When a comment is unpinned, the next pinned comment (if exists) will replace it's spot.
- Livestream comments are retrieved from 2 ways:
- From initial entry, `comment.List` is used to retrieved the chat.  Due to the recent pagination changes, the pinned comments will always be placed at the "top" (or in the chat GUI, the "bottom").
- Subsequent messages will come via websocket. 
- We handle both cases by storing the pinned comment IDs in the reducer stage.
kp.odysee.com

Livestream: implement Pinned Comments

---

flow-typed/Comment.js
ui/comments.js
ui/component/commentCreate/index.js
ui/component/commentCreate/view.jsx
ui/component/commentsList/index.js
ui/component/commentsList/view.jsx
ui/page/settingsCreator/index.js
ui/page/settingsCreator/view.jsx
ui/redux/actions/comments.js
ui/redux/reducers/comments.js
ui/redux/selectors/comments.js
ui/scss/component/_comments.scss
ui/util/claim.js

Closes #6119 (min tips)
jimbo.lbry.tv (⚠️ different test instance from usual -- troublesome to merge with existing PRs multiple times).
- "Creator Settings" page now include a "Min Tip" and "Min Hyper Chat" amount setting.
- An advisory text will be displayed beside the comment-create submission button to indicate the minimum amount.  For livestreams, and additional bubble will appear to describe the min hyper chat amount.
- How does fiat-comments come into play?
- There is no mechanism to avoid mismatched payment.  I tried to handle it as much as possible, as describe in the Notion post.

Creator: Enable "min tips" and "min hyperchat"

---

ui/component/userChannelFollowIntro/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/6836
The auto channels to follow are being counted in UserChannelFollowIntro and it's not clear.
The auto channels to follow are not counted in UserChannelFollowIntro.
</details>
</details>

Do not count auto follow channels for UserChannelFollowIntro.

---

ui/component/claimListDiscover/view.jsx

_This should go into the next Desktop RC as it is very annoying._
Closes [#6743: Desktop: "Back" in Following Page no longer restores scroll position](https://github.com/lbryio/lbry-desktop/issues/6743)
This was a side-effect of [#6609 claimListDiscover: don't re-render until query is done](https://github.com/lbryio/lbry-desktop/pull/6609). That PR did not handle the case of navigating backwards, which typically would just need to display past result. It ended up always starting with a blank list on mount, so the scroll position could not be restored correctly.
I don't know why it still worked on Web/Chrome -- maybe the latest browser knows how to move to desired scroll position when the height is available.
If navigating backwards, initialize the final URI list with the previous result. …

Fix scroll position not restored when doing Back on Desktop

---

ui/component/commentsList/index.js
ui/component/commentsList/view.jsx
ui/component/livestreamComments/index.js
ui/component/livestreamComments/view.jsx
ui/redux/reducers/comments.js
ui/redux/selectors/comments.js

Closes [#6879: Previously pinned livestream comments show as latest](https://github.com/lbryio/lbry-desktop/issues/6879)
`comment.List` will always display the pinned comment first, hence the problem when the chat is refreshed.
Completely split pinned comments from top-level comments in the Reducer, and the let the GUI (e.g. regular comments, livestream comments) decide how they want to display it.
For the case of livestream, there is no need to repeat the pinned comments in the regular chat area, since there is a dedicated area on top.

Livestream: stop pinned comments from appearing as latest

---

ui/redux/actions/sync.js

- Closes [#5504 Signing out of account causes page to break in other tabs](https://github.com/lbryio/lbry-desktop/issues/5504)
- Closes [#6829 merged accounts - force log out / fail sync when x-auth-token and cookie auth token are different](https://github.com/lbryio/lbry-desktop/issues/6829)
1. Login to odysee with account-A.
2. Open another tab, and split both tabs on the screen.
3. Logout from the 1st tab. Do not activate (focus) the 2nd tab.
4. On the 1st tab, login with account-B.
5. Activate (focus) the 2nd tab. The wallet would have been merged, and we are still logged in as account-A.
Reload when the LBRY API token no longer matches the auth token.
- Will there be valid scenarios where the API token can be different?

Reload when auth token mismatch is detected

---

ui/redux/reducers/comments.js

If the linked-comment is also a pinned comment, it was displayed twice.
When separating out pinned comments, I forgot that `comment.ByID` was another place where we fetch comments.

Fix double linked-comment if it was also pinned

---

ui/component/publishForm/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/6679
1 - Enter publish
2 - Select a file
3 - Complete all fields to publish a file
4 - Reload
5 - Go back to publish
The publish form can be submitted even though the file couldn't be restored.
The file input gets always reset since it can't be restored.
</details>
</details>

Reset file input on publishing when accessing since it can be restored to previous value.

---

ui/component/livestreamComments/view.jsx
ui/scss/component/_livestream.scss

- Regain a few lines of comments given that the chat can be cramped when donations and pinned-comments are present.
- Visual improvements.

"Scroll to recent" button improvements

---

flow-typed/Comment.js
ui/component/comment/index.js
ui/component/comment/view.jsx
ui/component/commentsReplies/index.js
ui/component/commentsReplies/view.jsx
ui/redux/reducers/comments.js
ui/redux/selectors/comments.js

- Tom, this is the changes we talked about in Slack.
- Available in the usual dev instance.
- Given how close this is to Saturday's stream, we should only merge in next week (just in case).
----
<details>
<summary>Comments: include Commentron blocklists when filtering</summary>
- When you block Channel-X, Channel-X's comments will still be visible on someone else's content. This feels odd.
- https://github.com/lbryio/lbry-desktop/issues/6107#issuecomment-897884114
In addition to the blacklist, filter-list and muted-list, we now include the Commentron blocklists (personal, admin, moderator) when filtering out comments.
`makeSelectCommentsForUri`, `makeSelectTopLevelCommentsForUri` and `makeSelectRepliesForParentId` all perform the same filtering code. Factor that out to …

Hide comments based on own blocklist

---

ui/component/common/icon-custom.jsx
ui/component/subscribeButton/view.jsx
ui/constants/icons.js

Make it easier to know the subscription state in a glance, without actually having to reading the text, especially for certain languages where it's just one character difference.
Noticed that mobile forces the "unsubscribe" (broken heart) in place of "subscribe", I believe due to the fact that we can't mouse-hover.  So, the solid heart doesn't appear in Mobile.

Use solid heart for "subscribed"

---

ui/component/commentCreate/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/6941
Can't click cancel on hyperchat if message is empty.
You can click cancel on hyperchat even if the message is empty.
</details>
</details>

Allow to cancel hyperchat if message is empty.

---

CHANGELOG.md
ui/component/comment/view.jsx
ui/component/commentCreate/index.js
ui/component/commentCreate/view.jsx
ui/component/commentMenuList/view.jsx
ui/component/commentReactions/view.jsx
ui/component/commentsReplies/view.jsx
ui/component/notification/view.jsx
ui/modal/modalRemoveComment/view.jsx
ui/page/notifications/index.js
ui/page/notifications/view.jsx
ui/redux/actions/comments.js
ui/scss/component/_comments.scss
ui/scss/component/_notification.scss
ui/scss/component/menu-button.scss

Issue Number:   #5062, and closes #6906
(Previously https://github.com/lbryio/lbry-desktop/pull/6711, now with issues addressed)
</details>
</details>

Direct reacting from notifications

---

ui/component/router/view.jsx
ui/constants/pageTitles.js

- While changing the "Back" behavior in the Settings Page PR, it was a pain to troubleshoot when the entire history list is listed as "odysee.com".
- If you have multiple tabs open, it's hard to know which is which for non-claim and non-channel pages.
- <img src="https://user-images.githubusercontent.com/64950861/130814854-da2e582c-f801-4ce3-822b-f3618723466f.png" height="300"> <img src="https://user-images.githubusercontent.com/64950861/130814981-5380032e-2788-48f0-b573-e1d32906924e.png" width="300">
Initially, I thought of overriding the document's title through the `<Page>` component, since the titles are usually defined there. However, given that the router is already doing the overriding, I think it's best to do the same thing all in one place.
Downside: devs might forget to add the …

Add page titles (affects browser Tab, History, etc.)

---

ui/page/show/view.jsx

Issue Number: Closes #6310
Directly typing an address is adding a ' ? ' at the end when trying to replace the format to include the claim id/list id, example: https://odysee.com/@luke
</details>
</details>

Fix Question Mark appearing on address

---

web/src/html.js

Closes #6849 category metadata shows in place of creator channel when using vanity URL

Fix Category-Metadata path parsing

---

ui/page/file/index.js
ui/page/file/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/6948
If the video is almost done playing, when the user comes back, the position is restored and thus, the autoplay is displayed.
The video position won't be restored if the video playing position is past 90% or the video is too short (less than 10 seconds).
</details>

Ignore/reset player position if video is too short or almost finished playing.

---

ui/component/comment/view.jsx
ui/component/livestreamComment/view.jsx

Remove defunct "show comment menu on hover" implementation.
It was re-rendering on every mouse movement, plus the css classname no longer exists, and also it wasn't working right in the first place (reverted few Desktop revision back, and all it did was highlighting the menu rather than controlling the visibility).
If we want the "show comment menu on hover" behavior again in the future, the CPU usage problem can probably be addressed by debouncing/throttling state-change.

Fix extra renders when hovering over comments

---

ui/component/comment/view.jsx
ui/component/commentsList/view.jsx
ui/constants/classnames.js

Closes #6946: Linked-comment scroll position is inconsistent
- If it is a deeply-nested reply, the positioning is incorrect.
- If there are pinned comments, the positioning is way off.
- If there is a delay in mounting, the positioning doesn't happen.
- When clicking on the comment's date to highlight it, the comment goes missing and the scroll position is weird.
- Take into account that replies can be linked-comments.
- Perform a "one-time" search for the linked-comment after the initial fetch, if necessary. The expensive DOM search is only be executed minimally.

Fix linked-comment auto scroll

---

ui/component/commentReactions/index.js
ui/component/commentReactions/view.jsx
ui/page/notifications/view.jsx

Issue Number: Closes #6980, closes #6992, closes #6993
- Claim wasn't resolved so it would fail to reply (no claim_id) and to return if should show creator heart
- Notifications page wasn't fetching reactions list if not fetched yet
</details>

Fix notifications fetching issues

---

package.json
yarn.lock

❗Requires [lbry-redux PR 428](https://github.com/lbryio/lbry-redux/pull/428)
Closes [#6985 fromentries app crash - fix or add polyfill](https://github.com/lbryio/lbry-desktop/issues/6985)
- Tested on Chrome 65 on Windows 10 (via BrowserStack)
- Tested on Samsung Browser on Galaxy S10 (via BrowserStack)
- Tested on UC Browser on obscure phones (via BrowserStack)
- Roughly compared the output of the function before and after the polyfill.
- Did some regression-testing over popular browsers.

Fix Object.fromEntries crash on some browsers

---

ui/component/viewers/videoViewer/internal/videojs.jsx

#6989 console errors and warnings are getting out of hand!
```
16:07:53.259 react_devtools_backend.js:2850 VIDEOJS: ERROR: TypeError: Cannot read properties of undefined (reading 'controlText')
at Player.resolveCtrlText (videojs.jsx?8d8d:319)
at HTMLDivElement.data.dispatcher (video.es.js?6651:2207)
at trigger (video.es.js?6651:2349)
at Player.trigger$1 [as trigger] (video.es.js?6651:3277)
at Player.handleTechLoadStart_ (video.es.js?6651:23074)
at Player.eval (video.es.js?6651:22824)
at HTMLVideoElement.data.dispatcher (video.es.js?6651:2207)
```
This method was previously criticized in 5643. But given that no better solution was submitted after a long while, nor was there a new solution for doing i18n, I'm reviving it again. It'll be no worse from the status quo.
Despite try-catch being …

vjs: hide errors when updating i18n

---

ui/scss/component/_icon.scss

Reasons:
- Better symmetry.
- When used on a form-field label, the off-centeredness causes an extra offset at the top. Since the icon goes away when there is an input error, the form-field shifts a bit. (An alternative is to use a smaller icon, but I think size 16 is the best for legibility).

Vertically center 'icon--help'

---

package.json
ui/component/channelContent/view.jsx
ui/component/claimListDiscover/index.js
ui/component/claimListDiscover/view.jsx
ui/component/claimPreviewSubtitle/view.jsx
ui/component/claimPreviewTile/view.jsx
ui/component/claimTilesDiscover/index.js
ui/component/claimTilesDiscover/view.jsx
ui/component/fileViewCountInline/index.js
ui/component/fileViewCountInline/view.jsx
ui/scss/component/_claim-list.scss
yarn.lock

Closes #3587
Limited to just "channel pages" for now as specified in the ticket.
Can be enabled for all claim previews, as long as there's an efficient spot to run the batch fetching. Either make `fetchViewCount` prop default to true, or add the parameter in places that need it.

Show content view counts on channel pages

---

ui/component/claimPreview/view.jsx
ui/component/claimPreviewTile/view.jsx

Closes [#6776 Missing follow button on channel reposts](https://github.com/lbryio/lbry-desktop/issues/6776)
| Issue | Fix |
| ------------- | ------------- |
| Missing "follow" button  | For reposts, `parseURI` will fail to determine if it's a channel because the URL doesn't have enough info. Determine from the claim object instead. |
| "follow" button not working in Channel Page  | The repost uri doesn't link back to the source channel, so we'll need to handle it by obtaining it from the claim object.  |

Fix missing and broken "Follow" button on reposts

---

package.json
ui/component/blockList/index.js
ui/component/blockList/view.jsx
ui/component/common/paginate.jsx
ui/page/listBlocked/view.jsx
ui/scss/component/_block-list.scss
yarn.lock

kp.odysee.com
Closes [#6834 Support pagination + search in moderation sections](https://github.com/lbryio/lbry-desktop/issues/6834)
- Added app-side pagination.
- Improved the "moderator-block" visuals a bit
- Added search bar for blocklists.
- Fuzzy search is supported, but is slow when the list is huge. Ended up using "CONTAINS" search.
- Can play around with other types if the search is not good enough:
> CASE SENSITIVE EQUALS: Case-sensitive equality trumps all. These will be first. (ex. France would match France, but not france)
EQUALS: Case-insensitive equality (ex. France would match france)
STARTS WITH: If the item starts with the given value (ex. Sou would match South Korea or South Africa)
WORD STARTS WITH: If the item has multiple words, then if one of those words starts with …

Blocklist: paginate + search

---

ui/component/channelBlockButton/view.jsx
ui/modal/modalBlockChannel/index.js
ui/modal/modalBlockChannel/view.jsx
ui/redux/actions/comments.js

Closes #7003 Can't unblock if delegator deleted their channel
- Changed the function parameter from 'creatorId' to 'creatorUri'
- It got short-circuited because we don't resolve deleted channels. But the client already have the full creator URI (containing the needed 'name' and 'id'), so there is no need to actually look at the resolved list -- just pass the uri like all the other functions.

Fix: Can't unblock if delegator deleted their channel

---

static/app-strings.json
ui/component/blockList/view.jsx

Also, re-use existing strings instead.

Blocklist: don't show pagination widget when searching.

---

ui/component/settingsSideNavigation/view.jsx

With 'instant', it is not clear that we are actually scrolling within the existing page (not opening a new page).

Settings: use 'smooth' instead of 'instant' scroll.

---

ui/scss/component/_wunderbar.scss

Fixes #6912
File price overflows the search suggestion thumbnail.
Overflow is hidden on the search suggestion thumbnail.
</details>

Hide overflow on search suggestion thumbnails

---

ui/modal/modalUpgrade/view.jsx
ui/scss/init/_gui.scss
web/scss/themes/odysee/init/_gui.scss

Closes [#5848 Remove scroll-bar in update prompt](https://github.com/lbryio/lbry-desktop/issues/5848)
- Make scrollbars appear only when necessary.
- Style the scrollbar. Similar to other areas, we skip this for Mac (can't recall why we need to skip).

Fix scrollbar in upgrade modal

---

ui/component/livestreamLayout/view.jsx
ui/page/listBlocked/view.jsx

https://discord.com/channels/362322208485277697/646840786662719488/887345736033918997
I meant to only add the macro at the client call during the refactoring, but forgot.
Having said that, I now think it's cleaner to put the macro where it is defined, and it's easier for Translators to find, so I added the macro in the definition instead of at the client call.

Fix missing localization macro during refactoring

---

ui/component/fileViewCountInline/index.js
ui/component/fileViewCountInline/view.jsx

It is breaking in old Safari 10. Revert for until; will get to a cleaner solution later.

Revert "Use SI notation for view_count ... bbcdcfe4"

---

ui/scss/component/_claim-list.scss
ui/scss/component/_claim-search.scss
ui/scss/component/_form-field.scss

Fixes #6927
Dropdown caret has no space to the right
Dropdown caret has space on either side
</details>

Fix dropdown caret spacing

---

ui/component/fileViewCountInline/index.js
ui/component/fileViewCountInline/view.jsx

Closes #7102 Failed to initialize numberformat on some browsers
Just revert to the non-SI notation (but still locale aware) for browsers that does not support the `compactDisplay` option.
I thought of adding an English-only abbreviation for that corner-case, but I think it's not worth the effort maintaining. There are worse issues happening on older browsers, such as icons not aligning properly in buttons and functions that require polyfilling.

Handle view_count formatting on old browsers

---

ui/component/fileViewCountInline/view.jsx

If you navigated to a Channel Page and returned to the homepage (or any page with ClaimPreview), the view-count is shown because we have that data.
Instead of passing props around through the long "list" component chain (`ChannelContent -> ClaimListDiscover -> ClaimList -> ClaimPreview`) to indicate whether we should display it , just check the pathname at the lowest component level;  I believe eventually we would display it everywhere anyways, so this we'll be the easiest to clean up.

Fix view-count showing up in non-Channel pages

---

ui/component/commentsList/view.jsx
ui/scss/component/_main.scss

Fixes #6907
Recommendations move to the bottom of the screen when the screen size is small or medium.
https://user-images.githubusercontent.com/31634995/133525600-644648b2-99aa-42c4-9fdc-6f3c4b243fc1.mp4
</details>

Fix theater mode layout on small and medium screens

---

ui/component/claimPreviewTile/view.jsx

The `Date` object and blocklist arrays causes unnecessary render since their references are always different in the shallow-compare.
Here the result on one of the many extra renders, with just the Cheese section alone (50% savings per cycle):

ClaimPreviewTile: render optimization

---

ui/redux/actions/comments.js

https://kp.odysee.com
Closes [#7121 Missing mod block option (large number of moderated channels?)](https://github.com/lbryio/lbry-desktop/issues/7121)
It was bad to assume `channelSignatures` would be the same length as the promise result -- any failure in signing would cause a misalignment.
For my case, an accidentally-merged channel couldn't be signed due to a missing private key. I think it's the same for Drew.

Fix moderator data misalignment.

---

static/app-strings.json
ui/scss/component/_file-render.scss
web/component/fileViewerEmbeddedEnded/view.jsx

Point your embed to kp.odysee.com
Closes [#7113 embed improvements for peakprosperity ](https://github.com/lbryio/lbry-desktop/issues/7113)
- Added a replace button;  replaced "Rewatch and Discuss" to "Discuss /".
- Make the message font size dynamic based on container height, so that it won't clip.

Embed: add replay button + msg resizing

---

ui/page/listBlocked/view.jsx
ui/redux/actions/comments.js

There's nothing to do when you don't have a channel, so hide the button and ensure redux fails gracefully.

Blocklist page: fix perpetual spinner when trying to refresh with no channels

---

ui/component/claimTilesDiscover/index.js

#7165 homepage queries don't take into account blocked channel ids (mute does)
resolveSearchOptions: was not grabbing redux data correctly.

Fix homepage tiles not filtering blocked channels

---

ui/scss/component/_expandable.scss

Closes #6944 Comment expansion sometimes doesn't reveal extra text (already showing everything)
Reconcile some constants between JS and CSS.

Adjust comment fade-out height

---

ui/component/claimTilesDiscover/index.js
ui/component/claimTilesDiscover/view.jsx

Closes #7176
Pitfalls of pausing render via React.memo:
- We'll miss the `doClaimSearch()` since that is sparked by an `useEffect`.
Seems like we can't avoid having a redundant copy of the previously-displayed URIs.
The blocklist order was also causing the extra blinking render.

Fix missed render and flashing (regression) when blocklist is fetched

---

ui/component/claimTilesDiscover/index.js
ui/component/claimTilesDiscover/view.jsx
ui/redux/selectors/blocked.js

@jessopb, can you help review this, particular the usage of `selectCommentsState` (whether it is anti-pattern or not). If it is good, I'll apply the same method to other beefy selectors.
Muted and blocked channel IDs are constantly being re-calculate on every update cycle. This PR tries to memoize it through `createSelector`
The input selectors to `createSelectors` must be plain, i.e. no transformations, otherwise it breaks memoization 
<sub>(aside: I believe most of our `makeSelect**` selectors break this rule, which explains why we've been getting new references in each cycle, causing extra renders).</sub>
That was why I used `selectCommentsState` instead of importing `selectModerationBlockList` from the other file. Even if I created a new `selectModerationBlockListRaw` (which doesn't …

Memoize 'mutedAndBlockedChannelIds'

---

CHANGELOG.md
ui/scss/component/menu-button.scss

Issue Number: #5652 
When the user’s email exceeds a certain width (depending on the viewport) the menu gets stuck in an animated behavior sliding from right to left or simply gets rendered outside the viewport.
The menu now has a maximum width. If the email still needs more horizontal space, it will be rendered with an ellipsis at the end. For example “thisisalongemail@gm...”. Even if the email gets truncated it should still contain enough information that the user can be confident in knowing which account they are currently signed into.
The problem lies within the [Reach UI](https://reach.tech/menu-button) collision detection mechanism which cannot resolve these types of rendering challenges well. [This issue](https://github.com/reach/reach-ui/issues/631) seems to be the one we are …

Fix “Your Account” popup on mobile (#5652)

---

ui/redux/reducers/comments.js

Closes #7146
Wasn't aware of that, and that was causing 7146 ("show replies" visible when there are no replies).

Commentron now includes `replies` for `ByID` request

---

CHANGELOG.md
ui/component/channelMentionSuggestion/index.js
ui/component/channelMentionSuggestion/view.jsx
ui/component/channelMentionSuggestions/index.js
ui/component/channelMentionSuggestions/view.jsx
ui/component/channelMentionTopSuggestion/index.js
ui/component/channelMentionTopSuggestion/view.jsx
ui/component/claimLink/index.js
ui/component/claimLink/view.jsx
ui/component/commentCreate/index.js
ui/component/commentCreate/view.jsx
ui/component/commentsList/view.jsx
ui/scss/all.scss
ui/scss/component/_channel-mention.scss
ui/scss/component/_comments.scss
ui/scss/component/_livestream.scss
ui/util/remark-lbry.js
web/scss/lbrytv.scss
web/scss/odysee.scss

🟢 Live for testing on: https://salt.odysee.com 
Issue Number: Closes #5982
</details>

Add Channel Mention selection ability

---

ui/redux/actions/search.js
ui/redux/selectors/search.js
ui/util/search.js

.../archives/C02FQBM00Q0/p1633044695010600
When querying a search key, it has to be an exact match. This was broken by the insertion of `free_only` in the fetch in #7089.
Added a function to generate the options, so that all clients stay in sync.

Fix wrong 'recsysId' sent due to search-key mismatch

---

web/src/html.js

Part of [#7166 improve search metadata](https://github.com/lbryio/lbry-desktop/issues/7166)
Depending on the search term and timing, Google extracts data from the sidebar or page content to use as the search-result description.
Defined `description` (on top of the existing `og:description` and `twitter:description`).
While I couldn't find a definitive doc saying that this is the solution, this is present in all other sites (and matches their description in a Google Search results).
Until Julian replies, and assuming this works, the description will appear as:
```
Launch your own channel | Watch and share videos
```
This is defined in the `.env`, and we might also need to update the one in the server if the old string exists in the override file.  No access to that.
It appears we can't …

Prevent random description in Google Search results for "odysee"

---

ui/component/claimLink/index.js
ui/util/remark-lbry.js

Issue Number: Closes #7208
here https://madiator.com/@Super-Grand-Ad:f?view=about can be seen the user had a mis-typed mention on the 'Description', and getValidClaim was intended to only keep going in case of a failed claim that has a punctuation mark at the end, and not for non existent claims
</details>

Fix Mis-typed claimLink

---

web/src/html.js

It should be `name`, not `property`. Copy-paste error from the OG version.

Corrected meta for "description" (patch for #7206)

---

ui/component/sideNavigation/view.jsx

Part of #6989 `Fix console spam in dev`
`EXTRA_SIDEBAR_LINKS` should be a `SideNavLink` object, so trim down the return object from `GetLinksData`.

Fix 'pinnedUrl' error.

---

web/src/html.js

Category cards are showing up as "odysee.com" cards in Facebook.
- `og:url` is supposed to be the canonical URL. It was hardcoded to "odysee.com", so every category was being redirected when the card is being generated.
- ![image](https://user-images.githubusercontent.com/64950861/135784811-539b5080-8d2a-4eec-836f-bef998f242d0.png)
- Removed `twitter:url`. The documentation says it will fall back to `og:url`, so there is not need to define both if it's the same.

OG: fix url for categories

---

web/src/category-metadata.js

- 'technology' was renamed to 'tech'.
- Leave both entries there for now. Not sure if other homepages still use the old link or not.

OG: Technology category missing due to rename

---

ui/scss/component/_livestream.scss
ui/scss/component/_main.scss

Issue Number: Closes #6984
no more distracting gaps: [![image.png](https://i.postimg.cc/GpnBcmW5/image.png)](https://postimg.cc/68z6ct5r)
properly centered on wide screens: [![image.png](https://i.postimg.cc/8k4LtM2P/image.png)](https://postimg.cc/8sFFCJkq)
</details>

[Livestream] Fix spacing / centering live stream + comments section

---

ui/component/commentMenuList/index.js
ui/component/commentMenuList/view.jsx

Issue Number: Closes #4994 maybe fixes #5970 since now there is always the copy url menu option? and I couldn't reproduce the 2nd one so it must've been fixed? @infinite-persistence 
</details>

[Comments] Add copy comment URL menu option

---

ui/component/snackBar/view.jsx
ui/scss/component/_snack-bar.scss

Issue Number: #7207
Overflow is hidden but doesn't show text ellipses.
Overflow is hidden but now shows text ellipses as expected.
</details>

Update CSS for toast message

---

ui/scss/component/_comments.scss

If the comment contains embedded videos the page becomes wider than the viewport on mobile. This causes the page to scroll horizontally.
Comments are now contained properly.

Prevent embedded videos in comments from breaking the layout on mobile

---

static/app-strings.json
ui/page/settingsNotifications/view.jsx

Notifications page was broken on app if unauthed

fix notifications page on unauthed app

---

ui/component/fileRenderFloating/view.jsx

- 251 Dragging the floating player is super laggy
Recent changes and/or refactoring combined the effects or added dependancies into the effects, causing them to re-run excessively.
- Restored effects to their original behavior.
- Don't perform the position check when dragging -- only do it when released.
- Do proper debouncing for the 'resize' listener -- the previous method was incorrect as a new function is created on each render.

Floating player position-listener fixes (#289) (cherrypick)

---

ui/component/claimMenuList/view.jsx

Issue Number: #7326
`MenuButton` in the component `claimMenuList` toggles `MenuList`(dropdown) on mosePress event
`MenuButton` in the component `claimMenuList` toggles `MenuList`(dropdown) on click event
`MenuButton`s in other components still toggle dropdowns on mouse press. It doesn't relate to this bugfix but my proposition is to change their behavior to toggle dropdown on click as well. 
</details>

Fix MenuButton behavior from toggle dropdown onMousePress to onClick

---

ui/component/viewers/videoViewer/internal/plugins/videojs-mobile-ui/touchOverlay.js
ui/scss/component/_file-render.scss

Cherry-pick from Odysee https://github.com/OdyseeTeam/odysee-frontend/pull/496
- Desktop doesn't need it.  It doesn't use mobile-ui and can probably remove that too, but not mixing PRs here.
- Chromecast needs to be done differently in Desktop (needs a plugin to handle the broadcasting stuff built into Chrome)

Remove old mobile chromecast css hack

---

ui/scss/component/_form-field.scss
ui/scss/init/_base-theme.scss

Issue Number: #5551
Inputs have no borders on light mode:
</details>

update input border color in light theme #5551

---

ui/component/collectionActions/view.jsx

Clicking shuffle and going back to the list and editing shows items edit buttons using the wrong indexes. There are better fixes - for now, just turn off shuffle when editing/publishing.

clear shuffle when entering edit or publish for collections

---

.github/workflows/deploy.yml

I think the following 4 environment variables/secrets aren't used at all during the build.
Am I right?
Regards,
Melroy vd Berg

Unused environment vars/secrets

---

.github/workflows/deploy.yml

The [afterSignHook](build/afterSignHook.js) script is already executed via electron-builder.json "afterSign" configuration.
As you can see here: https://github.com/lbryio/lbry-desktop/blob/master/electron-builder.json#L96
So the electron builder is calling this script already. No need to add this to the CI job again. 
Correct, right?
Regards,
Melroy

Remove duplicate after sign hook

---

.github/workflows/deploy.yml

Fix `if statement` of the Windows binary artifact upload of GH Actions.
The current if statement makes no sense at all for the Windows build artifacts.

Fix WIndows artifact upload

---

ui/scss/component/_file-render.scss

The "/" in "0:00 / 1:00" in the video player was not really visible.  This makes it the same color as the rest of the text.

Video: fix grayed out "/" in time indicator

---

ui/component/comment/index.js
ui/component/comment/view.jsx
ui/component/fileActions/view.jsx
ui/component/publishForm/index.js
ui/component/repostCreate/index.js
ui/component/repostCreate/view.jsx
ui/component/settingAccount/index.js
ui/component/settingAccount/view.jsx
ui/component/walletSend/index.js
ui/page/channels/index.js
ui/page/channels/view.jsx
ui/page/creatorDashboard/index.js
ui/page/creatorDashboard/view.jsx
ui/page/listBlocked/index.js
ui/page/listBlocked/view.jsx

- selectMyChannelClaims depends on `byId`, which currently is always invalidated per update, so it is not memoized.
- Most of the use-cases just needs the ID or the length of the array anyways, so avoid generating a Claim array (in selectMyChannelClaims) unnecessarily -- the client need to reduce it back down to IDs again :/
- The simpler boolean also removes the need to memoize the selector, which saves a bit of memory.
Issue Number:
</details>

Use 'selectHasChannel' instead of the full 'selectMyChannelClaims'

---

CHANGELOG.md
ui/component/claimPreview/view.jsx

Adds duration overlay in ClaimPreview.
Issue Number: closes #7385 
Currently only ClaimPreviewTitle shows duration.
Claim previews also show duration.
Duration is implemented using the same code from the overlay code already in ClaimPreviewTitle
</details>

add property overlay to ClaimPreview

---

electron/createWindow.js
ui/component/common/form-components/form-field.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7478
The guide button in the markdown editor doesn't work.
The guide button in the markdown editor now works and opens up the guide in a new browser tab.
</details>

Fix markdown guide button.

---

electron/index.js
ui/util/diskspace.js

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7498
The implementations for getting the disk space in windows and mac are missing.
The implementations for getting the disk space in windows and mac are implemented.
</details>

Add disk space functions for windows and mac.

---

ui/component/claimMenuList/index.js
ui/component/claimMenuList/view.jsx
ui/redux/reducers/collections.js
ui/redux/selectors/collections.js

Issue Number: https://github.com/lbryio/lbry-desktop/issues/6205
The last used collection is not displayed in the menu options.
The last used collection is displayed in the menu options:
</details>

Add last used collection to right click menu.

---

ui/redux/reducers/comments.js

It was causing the nudge to add a comment to still appear after one has just entered a comment.
Ticket: Odysee 928

Fix comment count not incremented when it was previously 0

---

ui/component/claimPreview/view.jsx
ui/component/claimPreviewTile/view.jsx
ui/component/fileThumbnail/index.js
ui/component/fileThumbnail/view.jsx
ui/redux/selectors/reactions.js
ui/scss/all.scss
ui/scss/component/_file-thumbnail.scss

Issue Number: https://github.com/lbryio/lbry-desktop/issues/3614
Users can't quickly see if a video has been watched and for how long.
Users can see a bar in the thumbnail of audios and videos representing how long it's been watched so far.
(See last video at the bottom right)
</details>

Add viewed bar in thumbnails.

---

.env.defaults
extras/lbryinc/constants/errors.js

Updated important instances of LBRY.tv to LBRY.com or simply LBRY. This should no longer have the old "LBRY.tv is better when yadayadayada" message in the app.

Updated important instances of LBRY.tv to LBRY.com 

---

.env.defaults
extras/lbryinc/constants/errors.js

Reverts lbryio/lbry-desktop#7558
I thought this might be ok, but it wasn't.

Revert "Updated important instances of LBRY.tv to LBRY.com "

---

ui/component/channelForm/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7545
No max length for fields in the channel creation form.
Add reasonable limits for fields in the channel creation form.
</details>

Add max length to fields in channel creation.

---

ui/component/claimMenuList/view.jsx
ui/component/collectionActions/view.jsx
ui/component/collectionPreviewOverlay/view.jsx
ui/component/collectionsListMine/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7140
When playing empty lists there is an error showing up.
- No error is thrown when trying to play an empty list.
- The play/shuffle button gets disabled for an empty list.
- The shuffle button doesn't appear for empty lists.
</details>

Do not throw error when trying to play empty collections.

---

ui/component/claimMenuList/view.jsx
ui/component/viewers/videoViewer/index.js
ui/redux/selectors/collections.js
ui/util/claim.js

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7575
Only videos and audio can be added to playlists.
All types of claims can be included in the playlists.
When played:
- If the first claim of the playlist is not a video/audio, the claim URL will be loaded.
- If the first claim of the playlist is video/audio, it will play, and when finished, it will jump to the next playable item.
When played, all the items will be displayed in the claim list. The reason for this is to show the user the content of the list and not confuse the user as to what the list contains.
</details>

Handle non playable items in playlists.

---

ui/component/fileThumbnail/index.js

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7582
The watch progress gets displayed when playing a collection/claim
The watch progress is hidden if the claim is being played.
</details>

Hide watched progress if claim is being played.

---

ui/component/channelThumbnail/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7617
Some channels can trigger many network requests in order to fetch
the channel's thumbnail.
A limit of retries (3 in this case) is set to prevent multiple requests.
If the image couldn't be fetched after those retries, the default picture
will be used instead.
</details>

Use a retry counter/limit to fetch thumbnails.

---

ui/component/common/file-selector.jsx
ui/component/publishFile/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/1811
Currently the "Choose File" button opens the root folder of the program and not "My documents" or "My computer" which generates confusion in new users,  this error only happens in windows.
Clicking on the "Choose File" button opens the user's root folder.
</details>

use default path in windows when choosing a file

---

ui/component/common/form-components/form-field.jsx
ui/scss/component/_button.scss
ui/scss/component/_form-field.scss

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7564
</details>

fix hover style for char count field

---

ui/component/channelForm/view.jsx
ui/component/selectAsset/view.jsx
ui/modal/modalImageUpload/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7159
When the image gets uploaded, it doesn't mean the image
is immediately available to be displayed (that's how the
upload image service seems to work) If we try to display
the image before it's ready, the image will result in
an error that locks the submit button.
When the image gets uploaded, instead of waiting for the 
upload image service, we just display a local preview using
base 64. This way, the preview becomes available much faster
and the error no longer occurs.
</details>

Use image preview to display the cover image recently uploaded.

---

ui/component/supportsLiquidate/view.jsx

Issue Number: https://github.com/lbryio/lbry-desktop/issues/4428
Dots and commas are not properly handled (it 
erases the whole content of the input)
Dots and commas are properly handled.
</details>

Properly handle decimals in supports liquidate component.

---

extras/lbryinc/redux/selectors/ban.js
flow-typed/Claim.js
ui/page/show/index.js
ui/page/show/view.jsx
ui/redux/actions/claims.js
ui/redux/reducers/claims.js
ui/redux/selectors/claims.js

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7663
Blacklisted claims are not being handled properly.
Blacklisted claims (those with `errors.censor`) will now be
marked as blacklisted properly.
</details>

Properly handle blacklisted claims.

---

ui/redux/actions/comments.js

doFetchModBlockedList is blocking the ui thread.
Duplicate data in `doFetchModBlockedList::blockListsPerChannel` to about 1000. The tab is dead when function hits, about 4s after reload.
- Yield occasionally using the `setTimeout` method.
- Doing a chunk size of 1 for now so we don't have to yield the inner loop as well (seems good enough). This is just based on a relatively large blocklist size.
- Can't do `await` in a callback, so must change the `forEach` to a `for`.

doFetchModBlockedList: don't block ui thread

---

ui/component/fileRenderFloating/view.jsx
ui/scss/component/_content.scss

Issue Number:
When the screen is narrow enough, the video is not render at the same location than the cover.
Because it's rather on the top of the window, the top of the video is hidden by the header.
The video is played at the exact same location than the cover, and is fully visible.
As well, because that area has then no margin with the border of the window, I removed the rounded border (seems to already be a pattern).
This is a very minor change.
(On narrow window, it may look even better with an overlay scrollbar.)
Anyway, it may not be the best fix, but it solves my problem. Thank you for making lbry.
</details>

Fix viewer position and shape in mobile mode

---

electron/index.js
flow-typed/file-with-path.js
flow-typed/web-file.js
package.json
ui/component/channelForm/view.jsx
ui/component/common/file-list.jsx
ui/component/common/file-selector.jsx
ui/component/fileDrop/view.jsx
ui/component/postEditor/view.jsx
ui/component/publishFile/view.jsx
ui/component/publishForm/view.jsx
ui/component/selectAsset/view.jsx
ui/component/selectThumbnail/view.jsx
ui/component/settingSystem/view.jsx
ui/modal/modalAutoGenerateThumbnail/view.jsx
ui/modal/modalConfirmThumbnailUpload/index.js
ui/modal/modalConfirmThumbnailUpload/view.jsx
ui/modal/modalFileSelection/view.jsx
ui/modal/modalImageUpload/view.jsx
ui/modal/modalPublishPreview/view.jsx
ui/redux/actions/publish.js
yarn.lock

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7646
Even though a file filter is being used, the "All Files"
option allows users to select any file when uploading 
an image.
The electron filter is being used so the "All Files" 
option is no longer displayed.
</details>

Allow only images in modal image uploader.

---

electron/index.js
ui/component/common/file-selector.jsx
ui/component/fileDrop/view.jsx
ui/component/publishFile/view.jsx

Issue Number:
- https://github.com/lbryio/lbry-desktop/issues/7687
- https://github.com/lbryio/lbry-desktop/issues/7685
The behavior when selecting a file is different
than the behavior when it's dragged and dropped.
The behavior when selecting a file and 
dropped no longer differs.
</details>

Better handling of uploaded files.

---

ui/util/parse-data.js

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7692
When exporting to CSV, no sanitization is being performed, thus,
the export may be incorrect if any of the values use a comma
or `"`.
All values are enclosed in `"` and extra `"` are escaped.
</details>

Sanitize values for CSV.

---

README.md

Fixed Arch AUR package name and current maintainer
Issue Number: https://github.com/lbryio/lbry-desktop/issues/7694
Currently a new user will click on the dead AUR package link, which might cause confusion
New user clicks on AUR package link and it navigates to the correct package which has a new name & maintainer
</details>

Fixed dead link in README.md

---

ui/component/commentCreate/view.jsx
ui/component/commentsList/index.js
ui/component/commentsList/view.jsx
ui/scss/component/_card.scss
ui/scss/component/_comments.scss
ui/scss/init/_vars.scss

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7365
</details>

Swap comment servers without going to settings page #7365
