- config.js
> change player domain

- package.json
- ui/component/rewardLink/index.js
- yarn.lock
Required lbryinc changes that I pushed to master too.
> fix: actually pass claim code

- ui/component/app/view.jsx
- ui/component/fileViewerInitiator/view.jsx
- ui/component/publishName/view.jsx
- ui/component/viewers/videoViewer/view.jsx
- ui/constants/claim.js
- ui/redux/actions/app.js
- ui/redux/actions/file.js
Fixes a couple known issues...
- Claim /channel/transaction list no longer run multiple times on startup, but claim searches still do (this must be a similar bug, but in another part of the code)
- Don't delete files on web
- Move forced player types to constant
- add 1.75 x playback rate
- Fix clear cache (no longer signs out, but instead clears session cache and reloads)
> Tom's small fixes

- ui/component/socialShare/index.js
- ui/component/socialShare/view.jsx
- ui/scss/component/_modal.scss
- ui/scss/component/_share.scss
- Adds a button on mobile "Share via..." that opens up the phone OS' share UI
> Use web share api on mobile inside share modal

- ui/component/router/view.jsx
We were decoding the url, but were losing search params in the process.
> keep search params when decoding url on frontend

- package.json
- static/app-strings.json
- ui/component/claimList/view.jsx
- ui/component/claimListDiscover/view.jsx
- yarn.lock
> only show timed out message when claim_search times out

- static/app-strings.json
- ui/component/claimPreviewTile/view.jsx
- ui/component/subscribeButton/view.jsx
> drop follow label for mobile inside claimPreviewTile to save space

- ui/component/fileValues/view.jsx
use support_amount from claim meta
> fix janky support amount on file page

- ui/component/fileDetails/view.jsx
Killed this on rebase - putting it back.
> restore repost count to file details

- ui/component/page/index.js
- ui/component/page/view.jsx
- ui/component/sideNavigation/view.jsx
- ui/page/home/view.jsx
- ui/scss/component/_navigation.scss
> new homepage searches, always show sidebar

- ui/component/supportsLiquidate/view.jsx
Made sure deleting by text field makes sense.
Made *some* message at the bottom at all times to prevent the box from jumping.
> fix tip select slider messaging and behavior

- ui/constants/transaction_types.js
- ui/modal/modalRevokeClaim/view.jsx
Fixes https://github.com/lbryio/lbry-desktop/issues/3956
> fix: double confirmation on channel updates

- lbrytv/src/chainquery.js
- lbrytv/src/html.js
- ui/util/lbrytv.js
Fixes https://github.com/lbryio/lbry-desktop/issues/3723
I didn't try this locally, please test!  https://lbry.tv/@LBRY-Tom:c/lex:d
> fix: image previews on links without thumbnails

- lbrytv/src/chainquery.js
- lbrytv/src/html.js
- ui/util/lbrytv.js
Reverts lbryio/lbry-desktop#3949
> Revert "fix: image previews on links without thumbnails"

- lbrytv/src/chainquery.js
- lbrytv/src/html.js
- ui/util/lbrytv.js
The first PR broke channel pages.
> Thumbnail preview fix #2

- static/app-strings.json
- ui/component/supportsLiquidate/view.jsx
- ui/scss/init/_gui.scss
huge errors would expand the modal too much
loading... showing when it was done trying to load
Amount available 0 was showing just because it hadn't gotten the amount yet.
> style and limit height of errors on tip unlock modal

- electron-builder.json
> GitHub updater

- package.json
- ui/component/commentCreate/view.jsx
- ui/component/selectChannel/view.jsx
- yarn.lock
if channels are empty, show the channel create
> fix empty reducer and fix empty channelSelect creation

- ui/component/fileRender/view.jsx
- ui/constants/file_render_modes.js
Issue Number: #3977
The height of viewer is not showing properly, sometimes you can't even see the viewer unless you resize the window, this also is a problem for the comic viewer, not sure how to fix  yet.
> Fix 3d viewer

- package.json
- ui/component/userEmailNew/index.js
- ui/component/userEmailReturning/index.js
- ui/component/userEmailReturning/view.jsx
- ui/component/userFirstChannel/view.jsx
- ui/component/userSignUp/view.jsx
- yarn.lock
This makes it so the email verification is always shown if someone is midway through a sign up.
Before they could start a signup, not verify their email, then login with that same email.
> Email verify fix

- lbrytv/setup/publish.js
Partial fix for #2024
Issue Number: Partial fix for #2024
Should be the same, except that the flow error checking has one less error.
> Flow error fix.

- CHANGELOG.md
- ui/component/channelContent/view.jsx
- ui/component/claimListDiscover/view.jsx
- ui/component/invited/view.jsx
The invite page now displays 5 of the creators trending/top/new videos. Image below.
Issue Number: #4005
> Better Invite Page

- lbrytv/effects/use-degraded-performance.js
this is already live on lbry.tv
> new status endpoint

- package.json
- static/app-strings.json
- ui/component/viewers/comicBookViewer.jsx
- ui/scss/component/_file-render.scss
- yarn.lock
Issue Number:
- Fix cbz reader #4035
> Fix comicbook viewer

- .github/ISSUE_TEMPLATE/--first-timers.md
Hi @seanyesmunt. I have finalized the template for the FTO issues. Please make the lable `first-timers-only` and add this template. Thank you!
> Add FTO Template

- static/app-strings.json
- ui/component/fileRenderInline/view.jsx
- ui/component/viewers/threeViewer/index.jsx
- ui/component/viewers/threeViewer/internal/scene.js
- ui/constants/file_render_modes.js
- ui/scss/component/_dat-gui.scss
- ui/scss/component/_file-render.scss
- Fix 3d viewer styles: see #4035
- Fix minor warnings from three.js
- Remove deprecated themes
- Fix #4074
Test this if you can, just to make sure everything works as  expected.
> Fix and enable 3D viewer

- ui/component/publishForm/view.jsx
I did this as a pull request earlier and then I edited some other stuff in my repo and it added that also. This is a working change.
Issue Number:
> Changed the edit button to Save

- ui/component/claimList/view.jsx
- ui/component/claimTags/view.jsx
- ui/component/common/card.jsx
- ui/component/fileRender/view.jsx
- ui/component/recommendedContent/view.jsx
- ui/component/txoList/view.jsx
- ui/page/help/view.jsx
- ui/scss/component/_card.scss
- ui/scss/component/_claim-list.scss
> add card style for lists of claims

- CHANGELOG.md
> Update CHANGELOG.md for #4051

- ui/component/common/loading-screen.jsx
- ui/component/embedPlayButton/index.js
- ui/component/embedPlayButton/view.jsx
- ui/component/fileRenderFloating/view.jsx
- ui/component/fileRenderInline/view.jsx
- ui/redux/selectors/content.js
- ui/scss/component/_content.scss
- ui/scss/component/_file-render.scss
It was floating when it shouldn't in some cases.
Also fixed the loading screen for files rendered inline.
> improve embed floating behavior

- package.json
- ui/component/channelContent/view.jsx
- ui/component/channelCreate/view.jsx
- ui/component/channelEdit/view.jsx
- ui/component/walletSendTip/view.jsx
- ui/modal/modalConfirmSendTip/view.jsx
- ui/modal/modalConfirmTransaction/view.jsx
- ui/modal/modalRevokeClaim/view.jsx
- ui/page/show/view.jsx
- ui/scss/component/_header.scss
- ui/scss/component/section.scss
- ui/scss/init/_gui.scss
- ui/scss/themes/dark.scss
- ui/scss/themes/light.scss
- yarn.lock
Moved a couple modals over to use `type="card"`. Still a few left
> modal consistency cleanup

- config.js
- lbrytv/src/html.js
- lbrytv/src/routes.js
- ui/util/lbrytv.js
to test out cdn.lbryplayer.xyz
> remove dynamic streaming url generation

- ui/scss/component/_markdown-editor.scss
- ui/scss/component/_markdown-preview.scss
- ui/scss/init/_gui.scss
- Markdown - numbered list shows as bullet #4113
- Extra spacing in markdown quotes in comments #3522
- Hyperlinks on markdown hard to read in dark mode #3468
> Fix markdown styles

- CONTRIBUTING.md
Issue Number: [#4166](https://github.com/lbryio/lbry-desktop/issues/4166)
[`src/platforms/electron/index.js`](https://github.com/lbryio/lbry-desktop/blob/master/src/platforms/electron/index.js) had the broken link.
Now I had updated this [`src/platforms/electron/index.js`](https://github.com/lbryio/lbry-desktop/blob/master/electron/index.js) with the live link.
> Updated the broken link

- package.json
- ui/component/common/markdown-preview.jsx
- yarn.lock
Single new lines in description not rendered #2390
> Force new lines to render on markdown preview

- ui/component/walletSendTip/view.jsx
Just rebased with the changes requested on https://github.com/lbryio/lbry-desktop/pull/4091/files
> fallback to channel name if title doesn't exist

- lbrytv/component/footer.jsx
- ui/component/page/view.jsx
- ui/page/channelsFollowing/view.jsx
- ui/page/discover/view.jsx
- ui/page/tagsFollowing/view.jsx
- ui/scss/all.scss
- ui/scss/component/_footer.scss
> add footer for web

- lbrytv/component/footer.jsx
Issue Number:
https://www.reddit.com/lbry gives page not found.
It actually goes to the lbry subreddit.
> fix dead link

- static/app-strings.json
- ui/component/creatorAnalytics/view.jsx
- ui/component/transactionListTable/internal/txo-list-item.jsx
- ui/component/walletBalance/view.jsx
- ui/modal/modalRevokeClaim/view.jsx
- ui/page/home/view.jsx
- ui/page/rewards/view.jsx
- Add more info to rewards denial page
- Fix tip modal / icon
- Add more info to creator analytics page
- Add help icons to paid content beta and wallet page (tipping)
- Add more creators to paid beta
> A few tweaks

- ui/component/header/view.jsx
- ui/component/navigationButton/view.jsx
- ui/component/wunderbar/view.jsx
Closes #4207
Issue Number: #4207
Double clicking in the header of the app does nothing.
Double clicking in the header of the app maximizes the app window.
> Allow double-clicking in header to maximize the app.

- static/app-strings.json
Update strings for (https://github.com/lbryio/lbry-desktop/blob/master/ui/page/settings/view.jsx) 'Blocked channels' settings
Issue Number:
> Update strings for 'Blocked channels' settings

- CHANGELOG.md
- ui/component/channelThumbnail/view.jsx
- ui/component/fileThumbnail/view.jsx
- ui/component/txoList/view.jsx
- ui/page/channel/view.jsx
- ui/scss/component/_claim-list.scss
- ui/scss/component/_main.scss
- ui/scss/init/_mixins.scss
The width calculations for `.claim-preview--tile` is pretty bad since it needs to know about the sidebar, and app container width. I'm not sure how else to do this though since we need an explicit height on the freezeframe canvas and image.
> pause gifs until hover

- CHANGELOG.md
- ui/component/channelThumbnail/view.jsx
- ui/component/fileThumbnail/view.jsx
- ui/component/txoList/view.jsx
- ui/page/channel/view.jsx
- ui/scss/component/_claim-list.scss
- ui/scss/component/_main.scss
- ui/scss/init/_mixins.scss
Reverts lbryio/lbry-desktop#4256
> Revert "pause gifs until hover"

- ui/component/publishFile/view.jsx
Strings can be translated now
Issue Number:
> Made text translatable

- ui/component/userPhoneVerify/view.jsx
Texts will be translated now
Issue Number:
> Made texts translatable

- ui/page/buy/view.jsx
> Correct typo on buying page

- ui/component/channelContent/view.jsx
> Make strings from channelContent translatable

- ui/component/claimInsufficientCredits/view.jsx
> Fix boolean declaration in claimInsufficientCredits

- package.json
- static/app-strings.json
- ui/analytics.js
- ui/component/button/view.jsx
- ui/component/privacyAgreement/view.jsx
- yarn.lock
> strip ga calls

- ui/constants/supported_languages.js
Issue Number: #4312
This will add Catalan to the list of supported languages.
> Add Catalan language

- package.json
- ui/redux/actions/app.js
- yarn.lock
passes DOMAIN from config to doAuthenticate for use in doInstallNew
> install_new domain parameter

- CHANGELOG.md
> Changelog update for Catalan support

- static/app-strings.json
- ui/modal/modalRevokeClaim/view.jsx
> fix channel revoke confirmation

- ui/page/help/view.jsx
Issue Number:
Nothing
Added a link to the changelog that takes you to the page on GitHub with the whole changelog.
I tested it by running from source on Linux Ubuntu 20.04 and it shows everything correctly and the link works properly.
> Add link to changelog next to version number (Tested Working)

- ui/component/settingWalletServer/view.jsx
Made connecting string translatable
Issue Number:
> Made strings from settingWalletServer translatable

- static/app-strings.json
- ui/component/creatorAnalytics/view.jsx
- ui/component/fileViewCount/view.jsx
Issue Number:
Too many forms of word "views" and "view" to translate, with caps and without in different places.
We need to choose the same displayed text in all the places.
> Made uniform display of text views

- CHANGELOG.md
Issue Number:
Changelog should be one word.
> Change some Change Logs to Changelogs

- static/app-strings.json
> Add string

- ui/page/help/view.jsx
> Spacing between info sentence and link

- CHANGELOG.md
> Add new unreleased version to changelog

- static/app-strings.json
Issue Number:
No translation.
Translation once the strings are uploaded to Transifex and people translate them.
> Add new app strings from tip/support merge

- package.json
- static/app-strings.json
- ui/component/channelAbout/view.jsx
- ui/component/channelEdit/index.js
- ui/component/channelEdit/view.jsx
- ui/component/claimAbandonButton/view.jsx
- ui/component/claimPreviewTile/view.jsx
- ui/page/channel/index.js
- ui/page/channel/view.jsx
- ui/page/channels/index.js
- ui/page/channels/view.jsx
- ui/redux/actions/publish.js
- yarn.lock
> support channel pending state

- static/app-strings.json
> Update app-strings (Rebased)

- ui/component/claimListDiscover/view.jsx
1. Fixes #2669 `Page does not restore to top when navigating new tags.`
To replicate the issue, you will need to first visit the tag and scroll down, move to another tag, then re-visit the first tag. Querying new tags won't show the issue. 
2. "Encountered children with the same key" error (duplicate entries shown).
(Also reported by https://github.com/lbryio/lbry-desktop/issues/4367#issuecomment-645449206)
1. Ignore the history if it's a new query (i.e. explicitly clicked). The BACK history will still behave as normal (doesn't reset to top).
2. Previously, the `page` variable will continue to increment as you scroll and stay within the page (e.g. Trending vs New, or clicked another Tag). As you move between queries, we hit a scenario where `page` is significantly under or over the latest …
> Inf-scroll: (1) Reset to top (2) Fix "page vs. results" being out of sync

- static/app-strings.json
- ui/component/settingAccountPassword/view.jsx
- New Settings Page strings
- Skip translating blank string.
> Skip translating blank string; Add new strings from Settings Page.

- ui/component/splash/view.jsx
> Fix unresolved translations in the Splash Screen.

- ui/analytics.js
matomo needs userid to track cohorts.
> add userid for matomo

- web/src/html.js
optimization of an earlier fix that was required after some webpack changes.
> don't read html file on every html request

- electron/index.js
- package.json
- static/app-strings.json
- ui/modal/modalPublish/view.jsx
- ui/redux/actions/publish.js
- yarn.lock
sometimes the lbry publish will be successful, but lbryfirst will fail
> make sure lbryfirst error makes it up to UI

- ui/constants/pages.js
Fix from https://github.com/lbryio/lbry-desktop/pull/4473/files
> fix password reset link

- ui/component/youtubeBadge/view.jsx
- ui/page/file/view.jsx
- ui/scss/component/_media.scss
Oops, missed out one file in the previous PR.
> Changed YT label from "last updated" to "last checked" (part 2)

- static/app-strings.json
> Strings for 0.47.1

- static/app-strings.json
- ui/component/fileRender/view.jsx
- ui/component/fileRenderFloating/index.js
- ui/component/fileRenderFloating/view.jsx
- ui/component/sideNavigation/view.jsx
- ui/component/wunderbar/view.jsx
- ui/page/home/view.jsx
- ui/scss/component/_claim-list.scss
- ui/scss/component/_content.scss
A few changes to simplify some things.
> Ux improvements/style changes

- package.json
- ui/scss/all.scss
- ui/scss/component/_badge.scss
- ui/scss/component/_button.scss
- ui/scss/component/_form-field.scss
- ui/scss/component/_table.scss
- ui/scss/init/_color.scss
- ui/scss/init/_gui.scss
- ui/scss/init/_mixins.scss
- ui/scss/init/_reset.scss
- ui/scss/init/_vars.scss
- yarn.lock
I think a lot of what is being brought in can be simplified, but I'm not going to do that now. I'm just bringing these in so we can start untangling some of the weird rules that have been made to cope with the separation of styles.
> bring in styles from @lbry/components

- static/app-strings.json
- ui/component/router/view.jsx
- ui/constants/pages.js
- ui/page/settings/view.jsx
- ui/page/settingsAdvanced/index.js
- ui/page/settingsAdvanced/view.jsx
Moved LBC/data network/ffmpeg settings into a new component `SettingsAdvanced`
> group similar settings in preparation of tabular settings page

- web/src/chainquery.js
- web/src/html.js
This reverts commit de15a56ed8f78dafd02fa77383beeb3bc18fa4de.Reverts lbryio/lbry-desktop#4595
> Revert "redirect reposted claims serverside"

- web/src/chainquery.js
- web/src/html.js
Fixes the issue that was introduced in my reverted PR
> fix html metadata for collisions and redirect reposted claims serverside

- package.json
- static/index-electron.html
- static/index-web.html
- webpack.base.config.js
- [ X ] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ X ] I have checked that this PR does not introduce a breaking change
- [  ] This PR introduces breaking changes and I have provided a detailed explanation below
- [  X ] Feature
Issue Number: [#4430](https://github.com/lbryio/lbry-desktop/issues/4430)
Right-to-left languages are not properly supported by the application. Neither direction switch nor CSS adaptions are implemented yet.
PostCSS-plugin  will generates RTL rules with flipped properties and generate one file for both directions.
Manage direction by switching between dir="ltr" and dir="rtl" on <html> element
> Integrate PostCSS-plugin for RTL-adaptivity

- ui/component/header/index.js
- ui/component/header/view.jsx
- ui/redux/actions/settings.js
Also check syncEnabled at the redux action level.
> trigger sync on theme change in nav menu

- static/app-strings.json
> Add one new string

- .flowconfig
- flow-typed/notification.js
- ui/component/notification/view.jsx
- ui/constants/notifications.js
- ui/page/notifications/view.jsx
- ui/scss/component/_notification.scss
If there are 2 or more comment notifications from the same author on the same claim, they will now be grouped. And will link to the most recent comment.
Also cleaned up some of the styles
> group comment notifications and clean up notification style

- ui/component/router/index.js
- ui/component/router/view.jsx
Arriving on settings needs to check/pull sync, not push set it.
> pull sync on nav to settings

- ui/util/homepage.js
Reverts lbryio/lbry-desktop#4611
> Revert "add imhere row at top"

- web/src/chainquery.js
- web/src/html.js
This adds the following metadata to content pages:
- Channel name: `og:video:series`
- Duration/Audio Duration: `og:video:duration`
- Release time: `og:video:release_date`
Some notes:
- `og:video:series` seemed like a reasonable place to put the channel name according to the [opengraph model](http://ogp.me), but let me know if you have another suggestion!
- I decided to put whichever of `duration` or `audio_duration` was available into the `og:video:duration` property. There is an `og:music:duration`, but it didn't seem right to use `og:music:...` for one property and `og:video:...` for all the rest. One question: are `duration` and `audio_duration` ever *both* specified on a claim?
Audio content example: 
Video content example:
What kind …
> Add more metadata to content pages.

- ui/page/search/view.jsx
To make it easier to navigate to claims by claim_id
> redirect to claim if entering a valid claim_id in the search bar

- ui/component/publishForm/view.jsx
I tried to change the title of a post in lbry.tv  but it didn't let me until I changed the post content ( write something on the markdown editor)
> Save metadata changes if post content doesn't change

- static/app-strings.json
- ui/component/claimPreview/view.jsx
- ui/component/claimPreviewTile/view.jsx
- ui/component/fileThumbnail/FreezeframeWrapper.jsx
- ui/component/fileThumbnail/view.jsx
- ui/scss/component/_claim-list.scss
- ui/scss/component/_file-properties.scss
z-index is to raise it above the gif canvas
file-properties is now a couple different things and should probably be renamed - file-properties-tags?
> put file properties such as type and duration over thumb

- ui/analytics.js
Reverts lbryio/lbry-desktop#4654
> Revert "check matomo and disable if necessary"

- ui/component/fileRender/view.jsx
- ui/component/recommendedContent/view.jsx
- ui/scss/component/_file-render.scss
Fixes layout for documents
Removes "WaitUntilOnPage" for related content since it will always be at the top.
> Layout fixes

- CHANGELOG.md
- static/opensearch.xml
- web/src/html.js
- web/src/xml.js
- web/webpack.config.js
lbry does not provide any OpenSearch search provider
lbry now provides an OpenSearch search provider
> OpenSearch implementation

- ui/component/sideNavigation/view.jsx
The sidebar text stuck in English despite already translated.
I'm guessing the i18n macro only ran once for the global object.
Run the macro on the label when passing it to the `Button`.
> Fix translation failure on the Sidebar

- flow-typed/web-file.js
- ui/component/postEditor/view.jsx
- ui/component/publishFile/view.jsx
- ui/component/publishForm/view.jsx
> Fix flow errors

- custom/homepage.example.js
- ui/component/page/view.jsx
- ui/effects/use-media.js
- ui/effects/use-screensize.js
- ui/index.jsx
- ui/page/home/view.jsx
- ui/scss/component/_claim-list.scss
- ui/scss/component/_main.scss
- ui/util/homepage.js
Reverts lbryio/lbry-desktop#4659
> Revert "full width homepage"

- README.md
Update links to point into building for ARM documentation.
> Changed Raspberry Pi to ARM

- static/index-web.html
- web/bundle-id.js
- web/package.json
- web/src/html.js
- web/webpack.config.js
- web/yarn.lock
With a fix that I didn't add in the previous PR
https://github.com/lbryio/lbry-desktop/pull/4674
> use dynamic js bundle urls

- ui/page/show/index.js
Fixes https://github.com/lbryio/lbry-desktop/issues/4555
> handle google webcache urls

- electron/createWindow.js
- electron/index.js
- package.json
- ui/component/settingClosingBehavior/index.js
- ui/component/settingClosingBehavior/view.jsx
- ui/constants/settings.js
- ui/page/settingsAdvanced/view.jsx
- ui/redux/actions/settings.js
- ui/redux/reducers/settings.js
- yarn.lock
Issue Number: 2220
When the app is closed, the system tray is always used instead of asking the user if the app should really quit or stay on the system tray.
A new setting has been added under Advanced Settings to allow the user to control how the quit action should behave. Now the user can control if the app should minimize to the system tray when closed or quit.
A new setting has been included into lbry-redux: https://github.com/lbryio/lbry-redux/pull/346
> Add app closing behavior setting

- static/app-strings.json
> String update for 0.47.2

- ui/component/publishFile/view.jsx
Issue Number: https://github.com/lbryio/lbry-desktop/issues/4686
> Limit content type for text posts

- static/app-strings.json
- ui/redux/reducers/blocked.js
- ui/redux/selectors/blocked.js
> patch null blocked error

- static/app-strings.json
- ui/component/creatorAnalytics/view.jsx
This adds some stats for most commented recent video. 
+ fix up other minor issues and added weekly change figure to recent content
+ app strings
> add comment stats to creator analytics

- config.js
- ui/index.jsx
> Add lbry apis to config

- ui/component/sideNavigation/index.js
- ui/component/sideNavigation/view.jsx
- ui/scss/component/_navigation.scss
https://github.com/lbryio/lbry-desktop/pull/4723 but I removed the last commit.
> Sidebar: Bring back the "Followed Tags" list

- static/app-strings.json
- ui/component/inviteNew/view.jsx
Missing strings reported from translators.
https://discord.com/channels/362322208485277697/646840786662719488/751814236732129332
> Translator-found missing strings

- ui/analytics.js
- ui/component/viewers/videoViewer/view.jsx
- ui/redux/actions/app.js
Reverts lbryio/lbry-desktop#4744
> Revert "add logging of player point of presence"

- ui/component/commentCreate/index.js
- ui/redux/actions/comments.js
- ui/redux/reducers/comments.js
already fixed on `release`, quick fix so initial comments don't mysteriously fail
> quick comment fix while waiting for release branch to be merged into master

- ui/analytics.js
- ui/component/viewers/videoViewer/view.jsx
- ui/redux/actions/app.js
Reverts lbryio/lbry-desktop#4746
The original PR works as intended.
> Revert "Revert "add logging of player point of presence""

- ui/component/wunderbar/index.js
- ui/component/wunderbar/view.jsx
- ui/page/search/view.jsx
- ui/redux/actions/search.js
Reverts lbryio/lbry-desktop#4730
> Revert "Search percent sign bug"

- ui/component/header/view.jsx
> Fix incorrect icon for 'Sign Up' and 'Sign In'

- ui/page/embedWrapper/view.jsx
- ui/scss/component/_embed-player.scss
https://secure.helpscout.net/conversation/1285658525/72326?folderId=2324565
> add option for light background on embeds

- static/app-strings.json
- ui/page/channelsFollowingDiscover/view.jsx
Added the translation macro in the component parameter.  Most of the strings are already in `app-string.json`.
> Missing translation in the Discover page.

- static/app-strings.json
- ui/component/publishAdditionalOptions/view.jsx
Issue Number:
While uploading a video to lbry.tv I realized there's no option to set the language as Persian. I created this PR to address that. I'm not familiar with the codebase. This is kind of my first effort. If anything is missing please let me know, I'll correct the PR.
Thanks.
> Add Persian language to upload menu language dropdown

- package.json
- ui/component/button/view.jsx
- ui/component/sideNavigation/view.jsx
> Handle external pinned sidebar links

- .gitignore
- custom/robots.allowall
- custom/robots.disallowall
- web/src/robots.js
- web/webpack.config.js
Copies robot.txt from /custom folder to dist if it exists on compile
> copy custom robots_txt in webpack on compile

- config.js
- ui/component/channelContent/view.jsx
- ui/component/claimList/view.jsx
- ui/component/claimListDiscover/view.jsx
- ui/component/claimListHeader/view.jsx
- ui/component/claimSupportButton/view.jsx
- ui/component/commentCreate/view.jsx
- ui/component/commentsList/index.js
- ui/component/commentsList/view.jsx
- ui/component/common/card.jsx
- ui/component/common/icon.jsx
- ui/redux/selectors/comments.js
- ui/scss/component/_card.scss
Bringing in some changes from the odysee branch (even if they aren't actively used) to reduce the diff between the branches.
I will create several small PR's to hopefully better track all of the changes
> Odysee code alignment

- ui/component/fileActions/view.jsx
- ui/component/fileDescription/view.jsx
- ui/component/fileDownloadLink/view.jsx
- ui/component/fileSubtitle/index.js
- ui/component/fileSubtitle/view.jsx
- ui/component/fileTitle/view.jsx
- ui/component/fileViewCount/view.jsx
- ui/page/file/view.jsx
- ui/scss/component/_button.scss
- ui/scss/component/_claim-list.scss
- ui/scss/component/_file-render.scss
- ui/scss/component/_icon.scss
- ui/scss/component/_media.scss
- ui/scss/component/_purchase.scss
- ui/scss/component/section.scss
>  align FileActions with odysee style

- ui/component/button/view.jsx
- ui/component/commentsList/view.jsx
- ui/component/common/card.jsx
- ui/component/fileActions/view.jsx
Continuation of #3465 [More tooltips throughout app](https://github.com/lbryio/lbry-desktop/issues/3465)
> Tooltips and more

- package.json
- ui/component/claimListDiscover/view.jsx
- ui/component/claimListHeader/view.jsx
- ui/component/common/icon-custom.jsx
- ui/redux/actions/notifications.js
- web/bundle-id.js
- yarn.lock
reverting my revert after fixing the uuid import issue
> More odysee alignment

- ui/component/commentsList/view.jsx
https://github.com/lbryio/lbry-desktop/issues/4788
> add infinite scroll for comments

- ui/component/comment/view.jsx
- ui/component/commentCreate/index.js
- ui/component/commentCreate/view.jsx
- ui/component/commentsList/index.js
- ui/component/commentsList/view.jsx
- ui/component/common/icon-custom.jsx
- ui/constants/comment.js
- ui/constants/icons.js
- ui/redux/actions/comments.js
- ui/redux/selectors/comments.js
- ui/scss/component/_card.scss
- ui/scss/component/_comments.scss
- ui/scss/component/_wunderbar.scss
- ui/scss/init/_mixins.scss
- ui/scss/themes/dark.scss
- ui/scss/themes/light.scss
- ui/util/comments.js
> add comment sorting and improve comment focus styles

- static/app-strings.json
- ui/component/channelAbout/view.jsx
- ui/component/youtubeBadge/view.jsx
- ui/page/channel/view.jsx
> move youtube badge to 'channel about' section

- ui/component/embedTextArea/view.jsx
- ui/component/socialShare/view.jsx
- ui/util/web.js
So users can properly be referred via embeds too
> Add referral link to embed markup

- ui/component/claimLink/view.jsx
- ui/component/comment/view.jsx
- ui/component/commentsList/view.jsx
- ui/component/fileReactions/view.jsx
- ui/component/previewLink/view.jsx
- ui/scss/component/_markdown-preview.scss
- ui/util/number.js
Part of https://github.com/lbryio/lbry-desktop/issues/4849
> Styling for Lbry links in comments + fix scroll bug for linked comment

- ui/component/comment/index.js
- ui/component/comment/view.jsx
- ui/scss/component/_comments.scss
> hide comments that were slimed to death TM

- static/robots.txt
- web/webpack.config.js
Must add robots.txt with allow * to /custom on relevant servers before merge
> robots.txt defaults to disallow

- ui/page/home/index.js
- ui/page/home/view.jsx
- ui/util/homepage.js
> pass 'showNsfw' to 'getHomepageData'

- static/app-strings.json
- ui/component/userSignInPassword/view.jsx
> Fix typo "Logging in in as ..."

- static/app-strings.json
- ui/component/publishFile/view.jsx
> bump allowed upload size to 2gb on web

- ui/component/claimListDiscover/view.jsx
- don't pass fee_amount: >=0 when nothing is set to avoid timeouts
- remove homepage hack from ClaimListDiscover and fix order so release_time filter is set properly
> Claim search fixes

- ui/component/fileDescription/index.js
- ui/component/fileDescription/view.jsx
- ui/component/fileDetails/view.jsx
- ui/component/fileSubtitle/index.js
- ui/component/fileSubtitle/view.jsx
- ui/component/fileValues/view.jsx
- ui/component/walletSendTip/view.jsx
- ui/page/file/view.jsx
- ui/page/search/view.jsx
- ui/page/top/view.jsx
- ui/scss/component/_card.scss
- ui/scss/component/_media.scss
- ui/scss/component/_table.scss
Added the winning claim to the search page for everyone
Moved file details under the file description
Moved lbc details under a button with the total staked LBC
> Refactor file/lbc details UI

- ui/component/fileDescription/index.js
- ui/component/fileDescription/view.jsx
- ui/scss/component/_form-field.scss
> add unlock button nex to expandable credits button

- .env.defaults
- config.js
- ui/component/comment/view.jsx
- ui/component/commentReactions/index.js
- ui/component/commentReactions/view.jsx
- ui/component/commentsList/view.jsx
- ui/component/common/icon-custom.jsx
- ui/constants/icons.js
- ui/constants/reactions.js
- ui/scss/component/_comments.scss
They can be enabled with the `ENABLE_CREATOR_REACTIONS` config value
> Creator only comment likes

- ui/component/claimPreview/view.jsx
- ui/component/common/help-link.jsx
- ui/component/searchTopClaim/index.js
- ui/component/searchTopClaim/view.jsx
- ui/page/search/index.js
- ui/page/search/view.jsx
- ui/page/top/view.jsx
- ui/redux/selectors/search.js
- ui/scss/component/_media.scss
- ui/scss/component/_search.scss
Now resolves `lbry://{query}` and `lbry://@query`
Shows channels/streams on top page too
> improve winning search claim on search page

- ui/component/subscribeButton/index.js
- ui/component/subscribeButton/view.jsx
Reverts lbryio/lbry-desktop#4977
> Revert "Only show bell icon for users with notifications enabled"

- ui/component/fileThumbnail/view.jsx
- ui/component/subscribeButton/index.js
- ui/component/subscribeButton/view.jsx
- ui/scss/component/_channel.scss
- yarn.lock
Fixed a couple of things borked in the first go
> per channel notification settings take 2

- ui/component/viewers/videoViewer/internal/videojs.jsx
- ui/scss/component/_file-render.scss
Reverts lbryio/lbry-desktop#4965
test to see if this fixes ios scroll issues
> Revert "Improve IOS inline experience"

- static/app-strings.json
> Fix malformed string.

- static/app-strings.json
- ui/page/creatorDashboard/view.jsx
Localize the "analytics down" message.
> Localize the "analytics down" message.

- static/app-strings.json
Adding this in master to avoid future conflicts.
The string will be used in Odysee branch.
> Add another 'About' string for Odysee.

- ui/component/sideNavigation/view.jsx
- web/component/footer.jsx
Extend context for `About` in the Odysee branch (footer and sidebar)
> Str-context-split: "About"

- static/app-strings.json
- ui/component/claimSupportButton/index.js
- ui/component/claimSupportButton/view.jsx
- ui/component/header/view.jsx
- ui/component/sideNavigation/view.jsx
- ui/page/settings/view.jsx
- ui/redux/actions/app.js
- ui/scss/all.scss
- ui/scss/component/_button.scss
- ui/scss/component/_navigation.scss
- ui/scss/component/_nudge.scss
- ui/scss/component/section.scss
> Nudges to sign up

- ui/page/embedWrapper/index.js
- ui/page/embedWrapper/view.jsx
We weren't showing this message on embeds, just on the file page.
> add basic dmca message on embeds page

- ui/page/settings/view.jsx
- ui/redux/actions/settings.js
We aren't pushing language to preferences so it doesn't need to be kept behind auth
> Allow changing language when not signed in

- ui/component/selectThumbnail/view.jsx
- ui/modal/modalConfirmThumbnailUpload/view.jsx
- ui/scss/init/_gui.scss
Pretty bad, but just adding something quick
> add basic message for thumbnail uploads

- config.js
- ui/component/claimListDiscover/view.jsx
- ui/component/claimListHeader/view.jsx
- ui/page/top/view.jsx
- ui/scss/component/_channel.scss
- ui/scss/component/_claim-list.scss
- ui/scss/component/_claim-search.scss
- ui/scss/component/_form-field.scss
- ui/scss/themes/dark.scss
- ui/scss/themes/light.scss
In preparation for them being on odysee
> clean up claim_search filters

- package.json
- ui/redux/actions/settings.js
- ui/redux/actions/user.js
- yarn.lock
needs https://github.com/lbryio/lbryinc/pull/106 and bump
> Fix api language

- static/app-strings.json
- Fix my previous mistake of removing a string. The new "Tailor your experience" had a diff that looked like a replacement, but it was actually a new file that was probably cloned from the settings file.
- Add few more new strings.
> String update

- .flowconfig
- ui/analytics.js
- ui/component/sideNavigation/view.jsx
- ui/redux/actions/comments.js
- ui/redux/actions/notifications.js
- ui/redux/actions/publish.js
- yarn.lock
Also removed flow uses that aren't needed
> enable 'discover' page for everyone

- ui/component/button/view.jsx
- ui/component/claimSupportButton/index.js
- ui/component/claimSupportButton/view.jsx
- ui/component/fileReactions/view.jsx
- ui/component/nudgeFloating/index.js
- ui/component/nudgeFloating/view.jsx
- ui/component/sideNavigation/view.jsx
- ui/scss/component/_nudge.scss
> move nudge to FileReactions and add src param to sign up redirects

- ui/page/home/view.jsx
- ui/scss/component/_claim-list.scss
> remove special styling for first homepage category

- ui/component/markdownLink/view.jsx
Fixes some file pages crashes with crazy links in the description
> handle malformed markdown links

- ui/scss/component/_file-render.scss
- Personally annoyed of having to switch to landscape just to change the setting. There's still space for it.
- This serves as a quick-fix until "[4712: Video: Allow access to all control in small screen](https://github.com/lbryio/lbry-desktop/issues/4712)" is figured out
> videojs: Squeeze in 'playback rate' button for Mobile Portrait.

- CHANGELOG.md
- ui/component/viewers/videoViewer/internal/videojs.jsx
`">" (shift + .)` = Speed Up
`"<" (shift + ,)` = Speed Down
> videojs: Add shortcuts for Playback-Rate

- ui/analytics.js
- ui/component/fileRender/view.jsx
- ui/component/viewers/videoViewer/view.jsx
sends player loaded and player started with embedded? data
> Player loaded

- ui/analytics.js
- ui/component/viewers/videoViewer/internal/videojs.jsx
- ui/component/viewers/videoViewer/view.jsx
- ui/scss/component/_ads.scss
> add preroll ads for unauthenticated users

- ui/redux/actions/user.js
Store a lock value in session storage while authenticating to prevent multiple userIds from multiple embeds.
> Prevent multiple embeds from creating new users

- ui/scss/themes/dark.scss
A darker and more colourful preview code area for a more comfortable and stylish look.
Issue Number:
> Darker Area for Code

- ui/scss/component/_file-render.scss
Wider post area for bigger text, while keeping the character count the same or less.
Removed `overflow: auto;` as it was not required and was creating unnecessary scrollbars when margins were incorrectly calculated.
Issue Number:
> Wider Post Area

- ui/component/sideNavigation/view.jsx
- ui/page/buy/view.jsx
- fixes moonpay on desktop
- fixes https://github.com/lbryio/lbry-desktop/issues/5082
> rc fixes (final)

- .env.defaults
- config.js
- ui/component/fileThumbnail/view.jsx
> use cdn for thumbnails

- .env.defaults
- config.js
- ui/component/fileThumbnail/view.jsx
Reverts lbryio/lbry-desktop#5149
> Revert "use cdn for thumbnails"

- .env.defaults
- config.js
- ui/component/fileThumbnail/view.jsx
Reverts lbryio/lbry-desktop#5154
> Revert "Revert "use cdn for thumbnails""

- ui/component/app/view.jsx
- web/effects/use-degraded-performance.js
Fixes https://github.com/lbryio/lbry-desktop/issues/5052
> pass x-lbry-auth-token to apis status call for email verified users

- static/app-strings.json
- ui/component/creatorAnalytics/view.jsx
- ui/component/fileViewCount/view.jsx
- ui/component/youtubeTransferStatus/view.jsx
- ui/scss/init/_gui.scss
- Show upload/sub count with transfer status
- Don't show 'claim' button if the channel has already been claimed
- Unrelated view_count API fix
> Youtube sync fixes

- ui/component/commentReactions/index.js
- ui/component/commentReactions/view.jsx
- ui/component/fileThumbnail/view.jsx
- ui/component/notification/index.js
- ui/component/notification/view.jsx
- ui/component/notificationHeaderButton/index.js
- ui/component/notificationHeaderButton/view.jsx
- ui/component/wunderbarSuggestions/view.jsx
- ui/page/channel/view.jsx
- ui/page/notifications/view.jsx
- ui/scss/component/_notification.scss
- ui/util/thumbnail.js
- ui/util/url.js
- Swap read/seen behavior for notifications (no UI changes, just changed how we use the values from apis)
- Fixes #5158
> Random fixes

- CHANGELOG.md
- package.json
- static/app-strings.json
- ui/component/header/view.jsx
- ui/component/sideNavigation/view.jsx
- ui/component/transactionListTable/internal/txo-list-item.jsx
- ui/scss/component/_table.scss
- yarn.lock
> Fixes + show message on tips from LBRY inc

- web/middleware/redirect.js
> remove unnecessary redirect in server

- ui/page/tagsFollowing/index.js
- ui/page/tagsFollowing/view.jsx
- Something I miss every time I switch to lbry.tv.
- Consistent with other search pages like Discover.
> Enable tile layout for 'Your Tags' page

- static/app-strings.json
- ui/component/repostCreate/view.jsx
- web/component/footer.jsx
Reported by translators
Aside:
`Do a thing` sounds weird.  Should we change it?  Wasn't sure if it was an intentional meme, so I added the string anyways.
> i18n update

- ui/component/sideNavigation/view.jsx
- ui/component/walletSendTip/view.jsx
- web/component/footer.jsx
Updated to use the contextual string
> Use contextual "Support" string (odysee)

- package.json
- ui/component/common/markdown-preview.jsx
- yarn.lock
Issue Number: #5206 
Front-matter in `yaml` format is ignored from rendering.
> Prevent front-matter (yaml) render on markdown

- web/middleware/redirect.js
Reverts lbryio/lbry-desktop#5198
Seeing if this fixes the current embed issue. I don't think it will but this seems like the only recent commit that could have anything to do with weird redirects.
> Revert "remove unnecessary redirect in server"

- web/middleware/redirect.js
Reverts lbryio/lbry-desktop#5227
> Revert "Revert "remove unnecessary redirect in server""

- web/src/html.js
Need to look more into why this just started happening. This code hasn't been touched in a while
> quickly fix embed redirecting

- ui/component/userEmailVerify/view.jsx
'We just sent an email to %email% with a link for you to %verify_text%. Remember to check other email folders like spam or promotions.',
> email spam reminder

- .github/workflows/deploy.yml
- package.json
Wasn't included in initial github actions work
> download blockchain headers before building desktop app

- ui/component/viewers/videoViewer/internal/videojs.jsx
- ui/scss/component/_file-render.scss
`fetch` the streaming url before trying to play to see if it will be redirected to a `m3u8` stream
> Fix for hls support

- ui/component/viewers/videoViewer/internal/videojs.jsx
> turn it back on but ✨head✨

- ui/scss/component/_comments.scss
Issue Number: 3221
Bullet points on the comments seems to be out of place
> Change list style in comments to be inside.

- electron/createTray.js
Issue Number: 719
Maximize the application window. Minimize the application to the taskbar. Double click on the tray icon or click on Open LRBy. The application gets restored in an unminized state.
The application gets restored properly (if it was maximized, the window will be maximized).
> Properly restore maximized window from taskbar if required

- ui/component/fileRenderFloating/index.js
- ui/component/fileRenderFloating/view.jsx
- ui/component/fileRenderInitiator/view.jsx
- ui/component/page/index.js
- ui/component/page/view.jsx
- ui/component/recommendedContent/view.jsx
- ui/component/viewers/videoViewer/index.js
- ui/component/viewers/videoViewer/internal/theater-mode.js
- ui/component/viewers/videoViewer/internal/videojs.jsx
- ui/component/viewers/videoViewer/view.jsx
- ui/page/file/index.js
- ui/page/file/view.jsx
- ui/redux/actions/settings.js
- ui/redux/reducers/settings.js
- ui/scss/component/_button.scss
- ui/scss/component/_content.scss
- ui/scss/component/_main.scss
- ui/scss/component/section.scss
- ui/scss/themes/light.scss
https://github.com/lbryio/lbry-desktop/issues/2627
> Theater mode

- config.js
> fix lbry.com links triggering lbry:// link file render

- ui/page/search/view.jsx
- ui/redux/selectors/search.js
Issue Number: https://github.com/lbryio/lbry-desktop/issues/5245
The NSFW parameter is not being sent correctly when searching.
The NSFW parameter is correctly sent.
> Fix nsfw parameter in search page

- ui/redux/actions/app.js
fixes sync issues for users with multiple accounts signed in to multiple tabs
> call user/signout on signout

- ui/page/search/view.jsx
- ui/redux/selectors/search.js
Reverts lbryio/lbry-desktop#5277
> Revert "Fix nsfw parameter in search page"

- ui/component/notificationBubble/view.jsx
- ui/scss/component/_notification.scss
> notifications 20+

- web/src/html.js
> Test google adwords2

- ui/redux/actions/user.js
This doesn't apparently fix the issue on the embed page, but I think it avoids some problems.
> Fix embed loading session storage

- package.json
- ui/component/viewers/videoViewer/internal/videojs.jsx
- ui/component/viewers/videoViewer/view.jsx
- yarn.lock
This reverts commit bb828385d02f2d786cc58fd44f76eb77247ade5f.Reverts lbryio/lbry-desktop#5271
Revert to fix the video player playing two videos at once in some cases
> Revert "Pass the title and channel name to Chromecast."

- ui/component/viewers/videoViewer/internal/videojs.jsx
Explained here: https://github.com/lbryio/lbry-desktop/issues/5323#issuecomment-763983790
Issue Number: https://github.com/lbryio/lbry-desktop/issues/5323
`true`
less `true` if `IS_ANY_SAFARI` browser.
All relevant info and discussion is linked in my comment here:
https://github.com/lbryio/lbry-desktop/issues/5323#issuecomment-763983790
> fix overrideNative option for video-js

- .github/workflows/deploy.yml
> fix builds for PRs from forks

- ui/constants/livestream.js
- ui/page/livestream/view.jsx
Shame me for this code later, but it works
> Add support for livestream countdown timer

- ui/component/viewers/videoViewer/internal/videojs.jsx
- ui/component/viewers/videoViewer/view.jsx
Add "t" as shortcut for Theather Mode.
Once again, another prop is added but I think it won't cause a re-render.
> Add "t" as shortcut for Theather Mode

- ui/component/app/index.js
- ui/component/app/view.jsx
- ui/redux/actions/app.js
- ui/redux/actions/settings.js
- ui/redux/actions/sync.js
- ui/store.js
rename syncSubscribe to syncLoop, taking an optional param to disable interval behavior
add syncLoop(disable = true) to 'focus' event listener inside the "readyForSync" hook.
be sure to do full syncLoop when entering settings page
testing on bob
> sync again

- .github/workflows/deploy.yml
- CHANGELOG.md
- electron-builder.json
- package.json
- static/app-strings.json
- ui/component/common/icon.jsx
- ui/component/fileRenderFloating/view.jsx
- ui/component/header/index.js
- ui/component/header/view.jsx
- ui/component/privacyAgreement/index.js
- ui/component/privacyAgreement/view.jsx
- ui/component/uriIndicator/view.jsx
- ui/util/url.js
- web/middleware/redirect.js
Bumped the sdk to v0.88.0
I took the changes from #5317 then just copy/pasted one function from that file so the web server can use it.
Also fixed an issue with install/new not being called for first run desktop users
Added immediately spendable balance to wallet link tooltip
> fix desktop build/RC prep

- static/app-strings.json
- ui/component/publishFile/view.jsx
- ui/component/publishForm/view.jsx
Maybe a little less confusing this way
> move channel selection to top of publish form

- ui/component/viewers/videoViewer/index.js
- ui/component/viewers/videoViewer/internal/videojs.jsx
- ui/component/viewers/videoViewer/view.jsx
The ads never actually worked, and the divergence from the master branch was getting harder to maintain.
Will rebase against master with the videojs refactor as soon as this is merged.
> Remove ads code custom to Odysee

- ui/component/viewers/videoViewer/internal/videojs.jsx
> Fix quality selector not showing up and prevent stream request being served from cache

- electron/createTray.js
- electron/index.js
- package.json
Issue Number:  #4027
Linting is broken.
Linting is fixed and all lint errors resolved.
> Fix linting errors.

- ui/scss/component/_animation.scss
Reverts lbryio/lbry-desktop#5381
@DispatchCommit Reverting because this causes weird behavior with the comment menu button leading to accidentally deleting comments.
> Revert "Make dropdown menus actually dropdown"

- ui/component/fileDrop/view.jsx
(should) Correctly add missing react lifecycles hooks (`useCallback`) for handling file drag and drop.
Removes unnecessary FlowFixMe, adds additional code comments, handles all variable dependencies correctly (memoizing results).
Quick tests reveal behavior and functional remain the same, but now there is **1 less warning** when running `yarn lint` 😃 
Shouldn't functionally change any behavior.
> Add missing react lifecycle hooks to fileDrop

- package.json
- yarn.lock
Reverts lbryio/lbry-desktop#5496
> Revert "Bump react-router from 5.1.2 to 5.2.0"

- config.js
- package.json
- ui/component/claimPreview/view.jsx
- ui/component/fileThumbnail/view.jsx
- yarn.lock
Reverts lbryio/lbry-desktop#5430
> Revert "Handle broken invalid thumbnails"

- homepages/homepage.js
Until wallet server starts returning the correct data
> disable trending classics

- ui/component/common/form-components/form-field.jsx
Closes #4505[: Highlight url instead of text when embedding a link](https://github.com/lbryio/lbry-desktop/issues/4505)
_Too used to Github's editor behavior, so was annoyed at this too. It makes more sense to highlight the URL placeholder since that needs to be filled._
For to the unhighlighted case, then the cursor should be at the Label.
Until the upstream code decides to fix it (`github::Ionaru/easy-markdown-editor/issues/85`), we'll handle it ourself by listing to the 'changes' events.
> Markdown "Create Link": highlight URL instead of label

- ui/redux/reducers/comments.js
quick fix. the real solution is to prevent multiple websocket connections
> fix to prevent duplicate comments

- static/app-strings.json
- ui/component/channelContent/view.jsx
- ui/component/claimTilesDiscover/index.js
- ui/component/claimTilesDiscover/view.jsx
- ui/component/fileAuthor/view.jsx
- ui/component/header/view.jsx
- ui/component/recommendedContent/view.jsx
- ui/page/channel/index.js
- ui/page/channel/view.jsx
- ui/page/listBlocked/view.jsx
- ui/redux/actions/comments.js
- ui/scss/component/_channel.scss
- ui/scss/component/_claim-list.scss
- ui/scss/component/_header.scss
- ui/scss/init/_color.scss
- ui/util/thumbnail.js
Fixes https://github.com/lbryio/lbry-desktop/issues/5613
> moderation UI fixes

- ui/component/common/icon-custom.jsx
merging this into odysee may make rebase easier.
> prune unused icons

- ui/page/home/view.jsx
> updating meme

- ui/util/remark-timestamp.js
https://discord.com/channels/362322208485277697/363087331475062785/817972023347249153
Open up the range as per YT, indirectly fixing the regex mistake.
> Fix timestamp regex error

- homepages/homepage.js
- static/app-strings.json
- ui/component/claimTags/view.jsx
- ui/component/fileAuthor/view.jsx
- ui/component/fileRenderInitiator/view.jsx
- ui/component/fileRenderInline/view.jsx
- ui/component/fileTitle/view.jsx
- ui/component/fileTitleSection/index.js
- ui/component/fileTitleSection/view.jsx
- ui/component/page/view.jsx
- ui/component/postViewer/index.js
- ui/component/postViewer/view.jsx
- ui/component/viewers/documentViewer.jsx
- ui/page/file/view.jsx
- ui/scss/all.scss
- ui/scss/component/_claim-list.scss
- ui/scss/component/_content.scss
- ui/scss/component/_file-render.scss
- ui/scss/component/_main.scss
- ui/scss/component/_media.scss
- ui/scss/component/_post.scss
- ui/scss/component/section.scss
> better posts styling

- ui/component/page/view.jsx
- ui/page/file/view.jsx
- ui/scss/component/_claim-list.scss
- ui/scss/component/_file-render.scss
- ui/scss/component/_main.scss
Keep the old styling for pdf, scripts, text files, etc
> only use new post styling for markdown

- ui/component/publishForm/view.jsx
Allows for pre-selecting an upload form type via a query parameter.
e.g. https://odysee.com/$/upload?type=livestream
> Allow specifying upload type via query to preselect form option

- CHANGELOG.md
- package.json
- ui/component/splash/view.jsx
- ui/component/syncFatalError/view.jsx
- web/effects/use-degraded-performance.js
Issue Number: https://github.com/lbryio/lbry-sdk/pull/3201 and https://github.com/lbryio/lbry-redux/pull/390
`status.connection_status` is gone
use `status.wallet.connected`
depends: https://github.com/lbryio/lbry-redux/pull/390
> fix for connection_status -> wallet.connected

- ui/component/notificationBubble/index.js
- ui/component/notificationBubble/view.jsx
- ui/component/sideNavigation/index.js
- ui/component/sideNavigation/view.jsx
Closes #5664[: notification bell shows is_read, not is_seen](https://github.com/lbryio/lbry-desktop/issues/5664)
> Notification bell shows is_read, not is_seen

- ui/component/postViewer/view.jsx
I need to add the tip unlock/lbc details to this view, but unsure how to do that right now.
> show correct amount on post staked amount

- ui/component/app/view.jsx
- ui/component/syncFatalError/view.jsx
> ensure lbrytv api status is web only

- ui/component/channelContent/view.jsx
- ui/component/claimPreviewTile/view.jsx
> don't show placeholder if claim already exists

- CHANGELOG.md
- ui/component/lastReleaseChanges/view.jsx
- ui/modal/modalRouter/view.jsx
- ui/scss/init/_gui.scss
> prevent release notes from extending beyond height of app

- ui/component/publishForm/index.js
- ui/component/publishForm/view.jsx
> hide livestream on upload form if not experimental UI

- static/app-strings.json
- ui/component/livestreamLink/view.jsx
> i18n: Livestream, category, and retiring strings

- package.json
- ui/component/publishForm/view.jsx
- ui/modal/modalPublish/index.js
- ui/modal/modalPublish/view.jsx
- ui/modal/modalPublishPreview/view.jsx
- ui/page/embedWrapper/view.jsx
- ui/page/livestreamSetup/index.js
- ui/page/livestreamSetup/view.jsx
- ui/redux/actions/publish.js
- yarn.lock
display pending publish
filter publish modes on ENABLE and experimental values
WIP
> livestream fixes

- ui/redux/selectors/settings.js
Reverts lbryio/lbry-desktop#5757
> Revert "no mature for simplesite"

- ui/component/comment/view.jsx
- ui/component/livestreamComments/view.jsx
- ui/component/uriIndicator/view.jsx
- ui/redux/actions/sync.js
- ui/redux/selectors/comments.js
- ui/scss/component/_comments.scss
- ui/scss/component/_livestream.scss
This needs some more testing but seems to work.
So the creator can moderate livestream comments
> use comment component for livestream comments

- ui/component/fileActions/index.js
- ui/component/fileActions/view.jsx
- ui/component/publishFile/view.jsx
- ui/component/publishForm/index.js
- ui/component/publishForm/view.jsx
- ui/modal/modalPublishPreview/view.jsx
- ui/page/livestreamSetup/view.jsx
- ui/redux/actions/publish.js
- web/setup/publish.js
adds a persisted one time help card for livestream
improves the jumpy loading a bit but not perfect
> Feat livestream beta help

- ui/component/channelContent/index.js
- ui/component/claimListDiscover/index.js
- ui/component/claimListHeader/index.js
- ui/component/claimTilesDiscover/index.js
- ui/component/wunderbarSuggestions/index.js
- ui/page/home/index.js
- ui/page/search/index.js
- ui/page/settings/index.js
- ui/redux/selectors/comments.js
- ui/redux/selectors/search.js
- ui/redux/selectors/settings.js
puts master in line with odysee
> use show mature selector

- ui/page/buy/view.jsx
Issue Number: #5397 
Shows "German Democratic Republic":
Does not show "German Democratic Republic":
While it does fix #5397 it does not remove entries like "USSR", "European Union" etc.
These probably need to be marked as "deleted" in https://github.com/OpenBookPrices/country-data/blob/master/data/countries.json and/or https://github.com/OpenBookPrices/country-data/blob/011dbb6658b0df5a36690af7086baa3e5c20c30c/data/deleted_countries.csv
> page: buy: filter out deleted countries (fixes #5397)

- ui/component/publishForm/view.jsx
> do not get stuck on publishing spinner

- ui/component/fileRenderFloating/index.js
- ui/component/fileRenderFloating/view.jsx
- ui/component/recommendedContent/index.js
- ui/component/recommendedContent/view.jsx
- ui/redux/actions/search.js
Closes #5000: [AutoPlay in Floating Player only works one time](https://github.com/lbryio/lbry-desktop/issues/5000)
Factor out the code that queries the recommendation. It needs to be called in two places:
(1) `RecommendedContent` - need to cover the case of floating player + visit another video page.
(2) When video is floating and autoplayed the next video.
I think there's no need for `React.useCallback` anymore, but please double-check in case it was needed for something else.
> Fix autoplay not working in floating mode

- ui/component/comment/view.jsx
- ui/component/fileTitleSection/view.jsx
- ui/component/uriIndicator/view.jsx
- ui/scss/component/_main.scss
- ui/scss/component/_post.scss
- ui/scss/init/_gui.scss
> Add helplbrysavecrypto section on file page and fix UI bugs

- CHANGELOG.md
- static/app-strings.json
- ui/component/settingLanguage/view.jsx
- ui/constants/languages.js
- Various updates (see commit messages)
- Worth another Transifex push:
- Includes the petition message
- About 70+ new strings since last push.
> i18n: weekly update

- package.json
- static/app-strings.json
- ui/component/channelEdit/view.jsx
- ui/component/claimPreview/view.jsx
- ui/component/claimPreviewTile/index.js
- ui/component/common/card.jsx
- ui/component/livestreamLink/view.jsx
- ui/component/publishForm/view.jsx
- ui/component/router/view.jsx
- ui/modal/modalPublish/view.jsx
- ui/modal/modalPublishPreview/index.js
- ui/modal/modalPublishPreview/view.jsx
- ui/page/file/index.js
- ui/page/livestream/view.jsx
- ui/page/livestreamSetup/view.jsx
- ui/redux/actions/publish.js
- yarn.lock
This cleans up desktop app publish by moving url name to top, covering it with a spinner during publish, and making the success modal clear the publish rather than waiting for the button click.
It also makes it more compatible for merge with odysee.
> Update master for odysee changes

- ui/redux/actions/websocket.js
This is partly putting it back to how it was before the comment websocket stuff was added.
> Fix websocket not reconnecting when apis go down/have issues

- ui/component/settingLanguage/view.jsx
Fix mistake in language-sorting (got the key wrong).  Oops.
> Sort the language list (correctly)

- ui/component/claimLink/view.jsx
- ui/component/embedPlayButton/view.jsx
- ui/component/markdownLink/view.jsx
- ui/scss/component/_markdown-preview.scss
- If low level:
- ![image](https://user-images.githubusercontent.com/64950861/113792181-decfe100-9777-11eb-84e2-e84355445b8e.png)
- If sufficient level:
- ![image](https://user-images.githubusercontent.com/64950861/113792226-fb6c1900-9777-11eb-90e9-188e10972dba.png)
> Revert the use of blank poster for insufficient level preview

- ui/analytics.js
- ui/component/claimList/view.jsx
- ui/component/searchOptions/view.jsx
- ui/page/search/index.js
- ui/page/search/view.jsx
- ui/scss/component/_search.scss
I ended up just removing the search filters since they are being phased out anyway.
> style pass for #5742

- ui/component/claimListDiscover/view.jsx
- ui/component/common/card.jsx
- ui/component/recommendedContent/index.js
- ui/component/recommendedContent/view.jsx
- ui/scss/component/_card.scss
- ui/scss/component/_search.scss
Created a new PR so I could push to it with a style commit + rebase
Original PR is #5789
> Reopening #5789 - "more from" in related side bar

- static/app-strings.json
- ui/component/searchOptions/view.jsx
#5842: search filters fall out
> SearchOptions: label fixes

- ui/page/show/index.js
- ui/page/show/view.jsx
This fixes non-channel claims. It needs to alternately send you to channel create page, I suppose.
> fix publish something empty

- ui/component/wunderbarSuggestions/view.jsx
- ui/scss/component/_wunderbar.scss
> add back tags search

- ui/component/common/icon-custom.jsx
- ui/constants/icons.js
> add br mindblown icon

- web/src/category-metadata.js
> Julian's category changes

- ui/component/sideNavigation/view.jsx
- ui/page/discover/view.jsx
- ui/scss/component/_claim-search.scss
- ui/scss/component/_navigation.scss
> add tags to mobile navigation and add manage tags link on tag page

- ui/component/fileSubtitle/view.jsx
- ui/component/fileTitleSection/view.jsx
- ui/component/fileViewCount/index.js
- ui/component/fileViewCount/view.jsx
- ui/component/livestreamLayout/view.jsx
> trigger file/view event for livestream claims

- ui/component/publishFile/view.jsx
fix the publish accept on master
> allow non video selection when not odysee

- package.json
- yarn.lock
But I think the ID will change after merge in lbryinc.
> bump lbryinc for blacklist (with build)

- ui/component/claimTilesDiscover/view.jsx
- ui/component/publishFile/view.jsx
- ui/component/publishFormErrors/index.js
- ui/component/publishFormErrors/view.jsx
- ui/component/searchOptions/view.jsx
fixes https://github.com/lbryio/lbry-desktop/issues/5895
> Odysee audio support

- web/src/html.js
Closes #5870: Add metadata for google video search
The "Live URL" test was able to pick up the metadata from the dev instance.
<details>
<summary>📷  Screenshots  📷 ... </summary>
- ![image](https://user-images.githubusercontent.com/64950861/114683592-bda45d00-9d42-11eb-98d6-165a0e6b23de.png)
- ![image](https://user-images.githubusercontent.com/64950861/114688053-eb8ba080-9d46-11eb-8b3e-bbc5481fd75c.png)
</details>
For `contentURL`, the manual says:
```
A URL pointing to the actual video media file, in one of the supported encoding formats. 
Don't link to the page where the video lives; 
this must be the URL of the video media file itself.
Example
"contentUrl": "https://www.example.com/video/123/file.mp4"
```
Between `generateDirectUrl` and `generateStreamUrl`, I chose the former since it …
> Add Google Video Search metadata

- ui/component/viewers/videoViewer/internal/videojs.jsx
Issue Number: 5865
CTRL+F is a commonly used hotkey for searching text on a page
LBRY currently has an "F" hotkey that will put the video player in fullscreen mode.
Unfortunately, it will activate fullscreen even if the user is trying to use the CTRL+F shortcut.
This PR makes it so the F hotkey only works if the control key/metakey are not also being pressed.
Tested it on windows and it works. 
Haven't tested on OS X, but I think it should also work, since this also checks for the metakey (⌘ Command / ⊞ Windows )
and the shortcut is Command + F on OS X
[https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/ctrlKey](url)
[https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey] …
> Fullscreen hotkey fix

- README.md
N/A
N/A
I've recently packaged Lbry in the Nix package repos, and have added it in the "Community Managed Packages" table.
> Update README to include Nix package

- homepages/homepage.js
- ui/component/claimTilesDiscover/view.jsx
- ui/component/commentMenuList/view.jsx
- ui/component/publishForm/view.jsx
- ui/component/publishFormErrors/view.jsx
- ui/redux/actions/websocket.js
- Fix for homepage to allow livestreams under the "Recent from following section"
- Fix websocket data typo
- Force thumbnail on uploads
> Random livestream/notification fixes

- ui/component/publishFile/view.jsx
- ui/component/publishForm/view.jsx
- ui/constants/publish_types.js
- ui/page/home/view.jsx
- ui/page/livestreamSetup/index.js
- ui/page/livestreamSetup/view.jsx
- ui/scss/component/_livestream.scss
- ui/scss/themes/dark.scss
- ui/scss/themes/light.scss
All the gross pending logic goes away when it's moved to just use claim search wrapper and selector in redux.
> livestream related publish fixes

- ui/component/claimTilesDiscover/index.js
- ui/component/claimTilesDiscover/view.jsx
> add back blocked/muted channels to homepage claim_search

- ui/component/common/icon-custom.jsx
- ui/component/livestreamList/view.jsx
- ui/redux/reducers/comments.js
- ui/scss/component/_livestream.scss
thumbnail gifs weren't being sized correctly in hyperchats
the total tip amount wasn't being added up correctly
> fix hyperchat size when thumbanil is gif and fix totalAmount calculation

- static/app-strings.json
- ui/scss/component/_ads.scss
- ui/scss/component/_button.scss
- ui/scss/component/_card.scss
- ui/scss/component/_channel.scss
- ui/scss/component/_claim-list.scss
- ui/scss/component/_comments.scss
- ui/scss/component/_file-properties.scss
- ui/scss/component/_footer.scss
- ui/scss/component/_form-field.scss
- ui/scss/component/_header.scss
- ui/scss/component/_icon.scss
- ui/scss/component/_markdown-preview.scss
- ui/scss/component/_media.scss
- ui/scss/component/_navigation.scss
- ui/scss/component/_nudge.scss
- ui/scss/component/_purchase.scss
- ui/scss/component/_search.scss
- ui/scss/component/_wunderbar.scss
- ui/scss/component/nag.scss
> unify some styles with master

- ui/analytics.js
- ui/constants/pages.js
- ui/page/buy/view.jsx
- ui/page/help/view.jsx
- ui/page/search/index.js
- ui/page/search/view.jsx
- ui/page/top/view.jsx
> Chore integrate odysee

- ui/component/common/form-components/form-field.jsx
- ui/component/reportContent/view.jsx
> remove emojis from reporting

- ui/component/notification/view.jsx
- ui/constants/notifications.js
Closes [#6022 Notifications: Creator Commented](https://github.com/lbryio/lbry-desktop/issues/6022)
- Beautify - show creator avatar instead of generic bell.
- When clicked, link to then comment directly (+highlight) instead of just opening the claim.
> Notification: handle "creator_comment"

- package.json
- ui/component/publishAdditionalOptions/view.jsx
- ui/component/publishReleaseDate/index.js
- ui/component/publishReleaseDate/view.jsx
- ui/modal/modalPublishPreview/view.jsx
- ui/scss/component/_card.scss
- ui/scss/component/_form-field.scss
- yarn.lock
- #5514: [Add release date field ](https://github.com/lbryio/lbry-desktop/pull/5514)
- I'm creating a new PR since I couldn't figure out how update someone else's fork (I know it's possible since Sean did update mine in the past).
- The authorship of the original commits (squashed) is retained.
- kp.odysee.com
- Upgrade to latest react-datetime-picker
- Handle dark theme and general style fixes.
- Fixed how "Edits" were being handled.  See accompanying PR in lbry-redux (https://github.com/lbryio/lbry-redux/pull/412)
I think the calendar should only appear when the calendar button is clicked, and not when the numerical fields are clicked.  It's not easy to change without forking (`https://github.com/wojtekmaj/react-datetime-picker/issues/36`), so I'm leaving as is for now.
> Continuation of "Add release date field #5514"

- ui/component/commentCreate/view.jsx
- ui/component/commentsList/view.jsx
- ui/util/comments.js
> own comments show first in controversial / best #5905

- ui/component/channelContent/view.jsx
- ui/component/claimList/view.jsx
- ui/component/claimListDiscover/view.jsx
- ui/component/claimMenuList/index.js
- ui/component/claimMenuList/view.jsx
- ui/component/claimPreviewTile/view.jsx
Issue Number: #5981 #5978 #5968
> Fix blocking/muting issues on channel pages

- package.json
- yarn.lock
> "thumbnail is invalid" not reset with new thumbnail upload

- ui/component/channelThumbnail/view.jsx
> Fix merge on ChannelThumbnails

- ui/scss/init/_base-theme.scss
- ui/scss/themes/dark.scss
Closes #5998 `Theme color problems`
- This is the `master` version.  
- `odysee` version coming soon in a separate PR.
- When merging to `odysee` later, 
- `_base-theme.scss` - take `master`'s version directly.
- `dark.scss` - retain `odysee`'s version (don't merge).
> Theme color fixes (master)

- ui/scss/init/_base-theme.scss
- ui/scss/themes/dark.scss
- ui/scss/themes/light.scss
Closes #5998 `Theme color problems `
See commit messages for walkthrough.
The last commit will most likely need to go through a style pass, but I tried not to make drastic changes, so hopefully it works straight away.
https://kp.odysee.com
> Theme color fixes (odysee)

- ui/scss/component/_button.scss
> Fix "Buy More" button touching the presets

- ui/component/walletSend/index.js
- ui/component/walletSend/view.jsx
- ui/modal/modalConfirmTransaction/index.js
- ui/modal/modalConfirmTransaction/view.jsx
- ui/page/send/view.jsx
- ui/util/form-validation.js
Issue Number: #5985
Just wallet address:
Wallet address + channel or content handle:
> allow sending directly to a channel or content address

- ui/scss/component/_file-render.scss
- ui/scss/component/_markdown-preview.scss
- ui/scss/init/_gui.scss
Details are in the commit messages.
> Markdown editor tweaks

- ui/page/home/view.jsx
there's so much room for activities
> change tagline

- ui/scss/component/_form-field.scss
- ui/scss/init/_vars.scss
> fix recipient address mobile view

- ui/redux/actions/comments.js
> fix: ignore flow linter promise allsettled

- ui/component/claimTilesDiscover/view.jsx
GUI fix for [#5979 claim search runs twice sometimes and "refreshes" view](https://github.com/lbryio/lbry-desktop/issues/5979)
The search query might encounter minor alterations after rendered (e.g. for the case of 5979, the `moderation.Blocklist` data came late). The code currently resets the result to 0 before initiating `claim_search`, so we see the GUI blink.
There is a possibility that the query-change does not alter the final results in the end. Instead of reseting to the results to zero, hold on to the previous results until the fetch is done.
The tiles no longer blink if there is no change, but the "LIVE" indicator still does. I didn't want to propagate the info too deep, so leaving as is for now. It can be considered a feature ("blinking LIVE indicator" :))
- No blinking if …
> ClaimTilesDiscover: pause visual update until new results are fetched

- ui/component/sideNavigation/view.jsx
Same solution as in the `odysee` branch.  Only affects `master` if custom homepage is used.
> Fix SidebarNavigation key errors

- ui/redux/actions/comments.js
- The snackbar when blocking a channel can then take a while to appear.
- Was also suggested in [#5979 claim search runs twice sometimes and "refreshes" view ](https://github.com/lbryio/lbry-desktop/issues/5979), although it does not address the "twice" issue in the end.
- ![image](https://user-images.githubusercontent.com/64950861/119632793-b6916400-be43-11eb-9966-4d34857c7dbd.png)
- ![image](https://user-images.githubusercontent.com/64950861/119632987-e17bb800-be43-11eb-91ef-5783462d2243.png)
- 10-channel per account case (starts to depend on server speed, it seems):
- ![image](https://user-images.githubusercontent.com/64950861/119633229-1ab42800-be44-11eb-8f99-1ad8c093fb13.png)
> Parallelize 'channel_sign' calls.

- ui/scss/component/_file-render.scss
> Fix for multi line links

- web/src/html.js
> Check Against Domain To See If PWA Manifest Should Be Added

- ui/page/channel/view.jsx
- ui/scss/component/tabs.scss
> quick fix for reposts

- ui/analytics.js
- ui/component/viewers/videoViewer/internal/videojs.jsx
The function was removed, but the caller side wasn't removed.
> Fix lint (removal of videoFetchDuration)

- package.json
- ui/component/publishAdditionalOptions/view.jsx
- web/package.json
- web/yarn.lock
- yarn.lock
Issue Number: https://github.com/lbryio/lbry-desktop/issues/6132#issuecomment-860168781
> Don't reset content language on edit [+redux] Part 2

- ui/component/livestreamComments/view.jsx
> fix-superchats

- ui/component/viewers/videoViewer/index.js
- ui/component/viewers/videoViewer/internal/plugins/videojs-recsys/plugin.js
- ui/component/viewers/videoViewer/internal/videojs.jsx
- ui/component/viewers/videoViewer/view.jsx
> Recsys plugin for video.js

- ui/component/livestreamComments/view.jsx
> Button to scroll to recent live chats (scroll to bottom)

- ui/scss/component/_file-render.scss
Issue caused by https://github.com/lbryio/lbry-desktop/commit/213c3361920ab5606a1a16ae4175c6683bf11109 (thanks to @infinite-persistence for finding)
[![image.png](https://i.postimg.cc/fRJKqM5M/image.png)](https://postimg.cc/qNHyzV9F)
[![image.png](https://i.postimg.cc/7LzNDXpc/image.png)](https://postimg.cc/KKZTD7cr)
> Fix preview link background

- ui/component/wunderbarSuggestion/index.js
- ui/component/wunderbarSuggestion/view.jsx
- ui/component/wunderbarSuggestions/view.jsx
- ui/effects/use-lighthouse.js
- Closes [#6314: prevent lighthouse spam from wunderbar](https://github.com/lbryio/lbry-desktop/issues/6314)
- Related [#6273: Weird CORS issue with Lighthouse search](https://github.com/lbryio/lbry-desktop/issues/6273)
Also updated the GUI with spinners and placeholders to reflect any pending slow state like "waiting for LH" or "resolving claims".
> Wunderbar: change throttle to debounce + add min chars

- ui/scss/component/_livestream.scss
- ui/scss/component/_main.scss
> Center livestream viewing mode

- ui/component/claimMenuList/view.jsx
- ui/component/claimPreview/view.jsx
- ui/component/claimPreviewTile/view.jsx
- ui/component/repostCreate/view.jsx
- ui/modal/modalRevokeClaim/index.js
- ui/modal/modalRevokeClaim/view.jsx
Issue Number: Closes #6246, Closes #6308
- doAbandonClaim needed to Resolve the claim in order to return transaction
- channelUri wasn't properly returning the channelUri on channel claims
> Fix repost deletion and Channel claim options

- .env.defaults
- ui/util/thumbnail.js
this should resolve the slow load times for some thumbnails
> use new optimizer for thumbnails CDN

- ui/component/viewers/videoViewer/index.js
- ui/component/viewers/videoViewer/internal/plugins/videojs-recsys/plugin.js
- ui/component/viewers/videoViewer/internal/videojs.jsx
- ui/component/viewers/videoViewer/view.jsx
- Closes #6305
- Also ported the autoplay fixes so that both platform stays in sync.
Lint fails in the external plugin.
> Port recsys + autoplay fixes to `master`

- ui/component/viewers/videoViewer/internal/plugins/videojs-recsys/plugin.js
I think different browsers behave in different ways for the media
API. As a result, I think I was losing information for browsers
that weren't the same as mine (Chromium). For now, preprocessing
is removed. In the future, I'll add it again (better storage
and transmission properties).
> FIX stop event translation and remove preprocessing

- ui/component/viewers/videoViewer/internal/plugins/videojs-mobile-ui/plugin.js
- ui/component/viewers/videoViewer/internal/plugins/videojs-mobile-ui/touchOverlay.js
- ui/component/viewers/videoViewer/internal/plugins/videojs-overlay/plugin.js
- ui/component/viewers/videoViewer/internal/plugins/videojs-recsys/plugin.js
- ui/component/viewers/videoViewer/internal/videojs.jsx
using two separate import statements for video.js causes issues with module resolution with some packages.
> fix video.js import statements

- ui/component/claimMenuList/view.jsx
- ui/component/common/icon-custom.jsx
- ui/constants/icons.js
- web/src/rss.js
fixes undefined with missing thumbs or descriptions
adds rss icon
shows rss only on web
> fix rss, add icon

- static/app-strings.json
- ui/redux/actions/comments.js
Closes #6370
- "Moderator-block" was already handled
- Added "admin-blocked" and "disabled".
> Show comment failure reason

- ui/component/stripeAccountConnection/view.jsx
> touchup frontend to show balance

- ui/redux/actions/notifications.js
Closes #6343
Also look at upgrading electron in the near future?
> Fix notifications "mark all" not working on Desktop

- package.json
- yarn.lock
> upgrade video.js to 7.13.3

- ui/component/claimListDiscover/index.js
Is there a purpose to do it differently here?
> Remove unused (?) selector

- static/app-strings.json
- ui/redux/actions/comments.js
It won't work with the hardcoded value.
Still waiting for commentron (error code + data) enhancement. It's pretty weird having to parse the number, then add it back in.
> Fix slow mode error message

- ui/component/notification/view.jsx
- ui/constants/notifications.js
- ui/redux/actions/notifications.js
> Fiat notification skin

- ui/scss/component/_claim-list.scss
- ui/scss/component/_search.scss
- ui/scss/component/_snack-bar.scss
Issue Number: Closes #6290
[![image.png](https://i.postimg.cc/PqcZv364/image.png)](https://postimg.cc/CZGdWNpB) [![image.png](https://i.postimg.cc/0jZyDrks/image.png)](https://postimg.cc/rR0TLVRn)
[![image.png](https://i.postimg.cc/VLYSvPfw/image.png)](https://postimg.cc/G953gNTg) [![image.png](https://i.postimg.cc/Cx9Lj3gz/image.png)](https://postimg.cc/ZWFSmD0S)
Also did the same for toast
[![image.png](https://i.postimg.cc/BZzsKnV5/image.png)](https://postimg.cc/Lhjrd2Rh) [![image.png](https://i.postimg.cc/qvVT1Z0z/image.png)](https://postimg.cc/bsTWJgZh)
_(Not sure why it didn't add the dots (...) here)_
> Fix recommended tab style issues

- ui/component/subscribeButton/view.jsx
- ui/redux/actions/subscriptions.js
Issue Number: Closes #6331
[![image.png](https://i.postimg.cc/g2BJJdQD/image.png)](https://postimg.cc/LJLRQdHY)
> Fix notification bell toast

- ui/component/common/wait-until-on-page.jsx
- ui/effects/use-lazy-loading.js
See commit messages for walkthrough
> Thumbnail improvements

- static/app-strings.json
- ui/component/sideNavigation/view.jsx
> Prevent sidebar shortcut activation on textarea

- static/app-strings.json
- ui/component/creatorAnalytics/view.jsx
- ui/component/rewardLink/view.jsx
Issue Number: #6323  #5991
Upload button triggers error.
Upload button triggers navigation to publish page.
> Fix upload button on creator analytics

- ui/component/viewers/videoViewer/internal/plugins/videojs-aniview/plugin.js
- ui/component/viewers/videoViewer/internal/videojs.jsx
Cleaned up code for the plugin and relocated the functionality from the main file into the plugin correctly.
> move ad logic into it's plugin

- ui/component/claimMenuList/view.jsx
- ui/component/common/icon-custom.jsx
- ui/constants/icons.js
Not re-using the same icon as "Share".
> Use better icon for "Copy Link"

- ui/component/claimMenuList/view.jsx
> Copy Link: use canonical

- ui/component/claimList/view.jsx
- ui/component/claimPreview/view.jsx
- ui/component/collectionContentSidebar/index.js
- ui/component/collectionContentSidebar/view.jsx
- ui/scss/component/_claim-list.scss
Issue Number: : #6204
There is no indication of which item is playing.
A simple highlight style for the playing item.
> Show currently active playing item on playlist

- static/app-strings.json
- ui/component/app/view.jsx
> Render filedrop component for only authenticated web users

- ui/component/collectionContentSidebar/view.jsx
- ui/page/collection/view.jsx
- ui/scss/component/_card.scss
- ui/scss/component/_claim-list.scss
- ui/scss/component/_collection.scss
Issue Number: #6211
spacing:
[![image.png](https://i.postimg.cc/TYJm03q8/image.png)](https://postimg.cc/mtht2R5V)
alignment:
[![image.png](https://i.postimg.cc/SRF4nqJV/image.png)](https://postimg.cc/k6czH0Nt)
[![image.png](https://i.postimg.cc/HsgXbyM4/image.png)](https://postimg.cc/LhxJphNn) [![image.png](https://i.postimg.cc/L4Yhh60k/image.png)](https://postimg.cc/hhnK5gnh)
> Playlist style fixes

- ui/component/commentsReplies/view.jsx
> Don't show "comments disabled" while still fetching.

- package.json
This will automatically fix files to be in line with linter config
> add a command to automatically lint files

- ui/component/fileActions/view.jsx
> Hide 'download' for livestreams

- ui/component/commentCreate/view.jsx
- ui/component/walletSendTip/view.jsx
- ui/component/walletTipAmountSelector/view.jsx
Quick fix for presentational bug
> disable review button if no card saved also some cleanup

- ui/component/walletSendTip/view.jsx
> hotfix for bug

- ui/util/thumbnail.js
...sometimes produces larger-than-original file sizes too.
> 100% compression doesn't work with current CDN url

- ui/component/comment/index.js
- ui/component/commentReactions/index.js
- ui/component/commentsList/index.js
- ui/component/commentsList/view.jsx
- ui/redux/actions/comments.js
- ui/redux/reducers/comments.js
See commit messages for details
6561
> Fix reaction-fetch infinite retries when no results are returned

- ui/component/comment/index.js
- ui/component/commentReactions/index.js
- ui/component/commentsList/index.js
- ui/component/commentsList/view.jsx
- ui/redux/actions/comments.js
- ui/redux/reducers/comments.js
> #6576: Fix reaction-fetch infinite retries when no results are returned

- web/src/rss.js
RSS: Add enclosure for media
Closes #6369
> _received complaints that RSS readers can't download the content. We can try adding a .mp4 and/or ?download=1 to the media URL_
Not really sure if I'm addressing the issue, as I couldn't find a reader that downloads meida within a feed item.  It sounded like they want a feed that links to the direct download, rather than the page?
Anyway, comparing with feeds from other sites, it seems like putting the media into the 'enclosure' tag should be sufficient.  The enclosure provides the direct link to the CDN.
- Moved the thumbnail from 'enclosure' to 'description' by appending the thumbnail in front.
- Generate enclosure for media. It's up to readers on how they will handle it. Some will display the inline video player, some will just provide a …
> RSS: Add enclosure for media

- ui/component/livestreamComments/view.jsx
> Fix 'Recent Comments' button for livestreams

- ui/component/claimMenuList/index.js
- ui/component/claimMenuList/view.jsx
- ui/component/claimPreview/view.jsx
- ui/component/claimPreviewTile/view.jsx
- ui/modal/modalRemoveFile/index.js
- ui/modal/modalRemoveFile/view.jsx
- ui/page/channel/view.jsx
- ui/redux/actions/comments.js
- ui/redux/actions/file.js
Issue Number: Closes #6325, Closes #6439, Closes #6452, Closes #6463
- Some code improvements, removed some unneeded variables
- Fixed file deletion issue
[![image.png](https://i.postimg.cc/vHYFbSn9/image.png)](https://postimg.cc/0rBHCnc2)
- On a reposted claim, name the channel on Follow to avoid confusion:
[![image.png](https://i.postimg.cc/v8gQKjd9/image.png)](https://postimg.cc/vDyFg0TH)
_so in this case if it's just saying "Follow" or "Unfollow" you could think it's going to Follow "lbry"_
- Watch Later wasn't working well for reposts, fixed it:
[![image.png](https://i.postimg.cc/Twb4VnZy/image.png)](https://postimg.cc/tZXkynRy)
- Fixes List on list layout …
> Pop up Menu Fixes and Improvements

- ui/util/lazyImport.js
- 2 issues in 1 PR
- This PR pushes to Odysee, since can't test Commit 2 on the person's site with lbry.tv)
Commit 1: Closes #6490 - embeds crashing in incognito
Commit 2: To confirm if this is causing "6636 Slow Embed".  Most likely it is.
`kp` test instance is currently pointing to this branch.
> Embed problems

- ui/util/lazyImport.js
Closes #6490
Cherry-picked from Odysee (tested there)
> Fix broken embeds in incognito

- ui/component/walletSendTip/view.jsx
- ui/component/walletTipAmountSelector/view.jsx
Fix error display for fiat tip send
> Merge to odysee

- ui/component/walletSendTip/view.jsx
- ui/component/walletTipAmountSelector/view.jsx
A bit of wrong logic not showing errors properly for fiat tips
> add check for two decimals and fix showing error for fiat tip

- ui/page/settingsStripeAccount/view.jsx
> bugfix not updating the frontend on account add

- static/app-strings.json
- ui/component/claimMenuList/view.jsx
Concatenated strings are hard to translate.
> Fix split (concat) string usage

- ui/component/fileThumbnail/thumb.jsx
- ui/component/fileThumbnail/view.jsx
This cherry-picks the fix from `master` to `odysee`
> Fix missing file-thumbnail in Notifications (ody)

- .env.defaults
Closes [#6705 - Odysee.com Commentron](https://github.com/lbryio/lbry-desktop/issues/6705)
Hm .. I think that's all that needs to be done?
The other PR that allows customization of the comment-server URL will be rebased to this once this gets merged.
> Decentralize: change Commentron URL

- CHANGELOG.md
> Fix typo on changelog links

- ui/scss/component/menu-button.scss
- ui/scss/init/_base-theme.scss
- ui/scss/themes/dark.scss
- web/scss/themes/lbrytv/dark.scss
- web/scss/themes/odysee/init/_base-theme.scss
> Fix context-menu icon lost

- ui/component/notification/view.jsx
> Fix notification menu button styles

- CHANGELOG.md
- ui/component/comment/view.jsx
- ui/component/commentMenuList/index.js
- ui/component/commentMenuList/view.jsx
- ui/constants/modal_types.js
- ui/modal/modalRemoveComment/index.js
- ui/modal/modalRemoveComment/view.jsx
- ui/modal/modalRouter/view.jsx
Issue Number: Closes #5723
new modal:
[![image.png](https://i.postimg.cc/Bng8MJwz/image.png)](https://postimg.cc/PCCrqnHb)
also alerts in case of deleting a comment with a support:
[![image.png](https://i.postimg.cc/wx0G8NRx/image.png)](https://postimg.cc/MXfD1vYg)
> Add confirmation on comment removal

- .env.defaults
- config.js
- ui/redux/actions/search.js
Issue Number: #6706
Changelog update: #6735
> Update lighthouse search api

- .env.defaults
- config.js
- static/app-strings.json
- ui/component/socialShare/view.jsx
Issue Number:  #6678
Changelog update: #6735
> Improve twitter share

- ui/component/claimTilesDiscover/view.jsx
- ui/page/discover/view.jsx
- ui/util/buildHomepage.js
I think the connected are solved by this.
I don't see limits being passed.
> no limit on stream types for following

- ui/scss/component/_channel.scss
> Fix channel staked badge in the wrong line

- ui/component/commentsList/view.jsx
- ui/scss/component/_card.scss
- ui/scss/component/_comments.scss
Issue Number: Closes #6230
Big comment sections makes it hard to reach Recommended/Playlist tabs
At first comments show contracted, and new pages can be loaded or the whole thread can be collapsed:
[![image.png](https://i.postimg.cc/50jSMrWx/image.png)](https://postimg.cc/YGKW6bSV) [![image.png](https://i.postimg.cc/XJ3XfGxt/image.png)](https://postimg.cc/Y4npkS5x)
> Mobile view: Make comments expandable

- CHANGELOG.md
- ui/component/claimCollectionAddButton/index.js
- ui/component/claimCollectionAddButton/view.jsx
- ui/scss/component/_button.scss
Issue Number: Closes #6206
[![image.png](https://i.postimg.cc/rFXqB1QJ/image.png)](https://postimg.cc/6TcsRvs2) [![image.png](https://i.postimg.cc/nh1VYXK1/image.png)](https://postimg.cc/w17d9TGt)
Just indicates that the file is currently already saved in a List, the button is still the same and clicking allows to remove/edit
[Requires lbryio/lbry-redux/pull/419]
> Show on content page if a file is part of a playlist already

- static/app-strings.json
Forgot to remove the context string from the actual string.
> Fix string context entry

- ui/component/commentsList/view.jsx
Reverts lbryio/lbry-desktop#6488
> Revert "Mobile view: Make comments expandable"

- CHANGELOG.md
- electron/index.js
> Fix desktop deep links handler

- CHANGELOG.md
- ui/scss/component/_livestream.scss
> Fix text overflow past 3 dot menu

- ui/component/publishBid/index.js
- ui/component/publishName/index.js
Issue Number: https://github.com/lbryio/lbry-desktop/issues/6751
Bid message is not updated.
Bid message is updated.
> Fix amountNeededForTakeover message for bids.

- ui/component/claimMenuList/index.js
- ui/component/claimMenuList/view.jsx
- ui/component/claimPreview/view.jsx
- ui/component/claimPreviewTile/view.jsx
- ui/scss/component/_claim-list.scss
Issue Number: Closes #6754 closes #6719 
- Can delete downloads from popup menu
- Shows download hover again:
[![image.png](https://i.postimg.cc/sDCHfjq3/image.png)](https://postimg.cc/bdL93hq5)
> Download overlay + delete from popup

- ui/util/web.js
- web/src/rss.js
> RSS Podcast improvements

- CHANGELOG.md
- web/src/html.js
> Fix wrong embed OG metadata

- CHANGELOG.md
- web/src/html.js
Issue Number:  #6839
</details>
</details>
> Fix og error: Truncated unicode character

- ui/page/livestreamCurrent/view.jsx
Got tired of hijacking code. Didn't want to alter my account either.
> Add 'ENABLE_WIP_FEATURES' for live page.

- ui/scss/component/_claim-list.scss
> Fix slight alignment off

- ui/component/walletFiatPaymentHistory/view.jsx
- ui/page/settingsStripeAccount/view.jsx
- ui/page/settingsStripeCard/view.jsx
- ui/page/wallet/view.jsx
> various small bug fixes

- ui/component/livestreamComments/view.jsx
Closes [#6886 Livestream auto-scroll problems](https://github.com/lbryio/lbry-desktop/issues/6886)
- `performedInitialScroll` was problematic as it won't allow auto-scroll even when user scrolled back to the bottom.
- The dependence on `commentElement` seems to assume a certain comment height? Not sure.
- Add a scroll listener and stash the last scroll position.
- When a message is received, check if it's at the bottom (>=0). If yes, maintain that position after the new comment is added. If not, leave as is.
- When submitting a comment, always reset to the bottom.
> Fix livestream autoscroll

- CHANGELOG.md
- ui/component/commentCreate/view.jsx
> Fix comment create redirection

- CHANGELOG.md
- ui/component/notification/view.jsx
- ui/scss/component/_notification.scss
Issue Number: Closes #5095
- Notification links improved
- Now can right click on notification items, open in new tabs, open other users channel, etc.
- Added reactions to comments:
[![image.png](https://i.postimg.cc/7ZydpNB0/image.png)](https://postimg.cc/D8BxG13w)
> Notifications improve links

- CHANGELOG.md
Issue Number:
</details>
</details>
> Fix typo on changelog version

- README.md
Addresses: https://github.com/lbryio/lbry-desktop/issues/6058
> Fix the link to the web server

- ui/page/channel/view.jsx
Closes [#6911 pass claim_type = stream,repost on channel page claim searches](https://github.com/lbryio/lbry-desktop/issues/6911)
> Filter out playlists from main channel listing

- ui/component/channelContent/view.jsx
The search wunderbar was lost due to the additional type added
> Patch: Filter out playlists from main channel listing (#6931)

- ui/component/channelEdit/view.jsx
- ui/component/channelThumbnail/view.jsx
- ui/component/common/file-selector.jsx
- ui/component/selectAsset/view.jsx
- ui/component/selectThumbnail/view.jsx
- ui/modal/modalConfirmThumbnailUpload/view.jsx
- ui/modal/modalImageUpload/index.js
- ui/modal/modalImageUpload/view.jsx
- ui/scss/component/_channel.scss
Issue Number: Closes #6082, closes #6098, closes #6097, closes #6835
- Can re-select file on thumbnail upload
- Channel thumbnail isn't uploaded immediately
- Channel create checks if URL is valid
- Editing profile picture reflects newly uploaded photo
- Editing Channel allows empty values (can remove profile picture and go back to Gerbil)
</details>
</details>
> Thumbnail fixes

- static/app-strings.json
- ui/component/livestreamComments/view.jsx
- ui/scss/component/_livestream.scss
This serves as a temp fix to regain the chat space in Mobile, until the Livestream page in Mobile is revamped.
> Ability to dismiss Pinned Comment in Livestream

- ui/component/claimPreview/view.jsx
- ui/component/claimPreviewTile/view.jsx
- ui/component/fileWatchLaterLink/view.jsx
- ui/effects/use-hover.js
- ui/scss/component/_claim-list.scss
> Remove hover/watch later bug for mobile devices

- web/scss/themes/odysee/init/_gui.scss
Fix overflow text on meme div causing viewer to stretch on mobile
> fix overflow text on meme div

- ui/component/fileThumbnail/FreezeframeLite/styles.scss
> Fix hover on gif thumbnails

- ui/component/wunderbarSuggestions/view.jsx
Issue Number: 2116
Pressing escape would cause the wunderbar to lose focus.
Pressing escape now clears out the wunderbar and brings it in focus so the user can continue searching. Also Ctrl+K will now highlight anything in the wunderbar and bring it into focus.
<details><summary>Pressing escape in wunderbar should do something useful.</summary>
</details>
> Pressing escape in wunderbar should do something useful

- ui/component/fileActions/view.jsx
Issue Number: Closes #7020
</details>
> Fix auto downloads

- ui/component/searchChannelField/index.js
- ui/component/searchChannelField/view.jsx
- ui/page/settingsCreator/index.js
- ui/page/settingsCreator/view.jsx
- ui/scss/component/_search.scss
- ui/scss/component/section.scss
> Improve "moderator search" usability

- ui/component/livestreamComments/view.jsx
Addresses: https://github.com/lbryio/lbry-desktop/issues/7045
> change display of donations to chronological order

- ui/component/claimListDiscover/view.jsx
- ui/component/claimTilesDiscover/view.jsx
Also guard against null array.
> Don't fetch view_count on empty list.

- ui/component/walletSendTip/view.jsx
- ui/page/settingsStripeCard/view.jsx
Addresses: https://github.com/lbryio/lbry-desktop/issues/7008
> Fiat tip improvements

- ui/component/autoplayCountdown/view.jsx
- ui/component/claimMenuList/index.js
- ui/component/claimMenuList/view.jsx
- ui/component/claimPreviewTile/view.jsx
- ui/component/collectionActions/index.js
- ui/component/collectionActions/view.jsx
- ui/component/collectionMenuList/index.js
- ui/component/collectionMenuList/view.jsx
- ui/component/collectionPreviewTile/view.jsx
- ui/component/common/icon-custom.jsx
- ui/component/fileRenderFloating/index.js
- ui/component/fileRenderFloating/view.jsx
- ui/component/fileRenderInitiator/index.js
- ui/component/fileRenderInitiator/view.jsx
- ui/component/uriIndicator/view.jsx
- ui/component/viewers/videoViewer/index.js
- ui/component/viewers/videoViewer/view.jsx
- ui/constants/icons.js
- ui/redux/actions/content.js
- ui/redux/actions/settings.js
- ui/util/url.js
Can test it now on: https://salt.odysee.com/
Issue Number: Closes #7009
- Improved and optimized code, removed what was unneeded and reduced complexity and repetition, which also allowed to fix and improve things like hiding the floating player while navigating with < and >
- Better handling of paid content during list playback (https://salt.odysee.com/$/list/91e0456af8eb0ca922bfe5107aa06cfa8278caf1)
- Added snack bar notification when you enable / disable autoplay next so users know what it is.
</details>
> Playlist fall out fixes

- ui/component/collectionMenuList/index.js
just noticed "Delete List" option was breaking
</details>
> Fix collection delete breaking

- ui/component/userChannelFollowIntro/view.jsx
- ui/page/channelsFollowingDiscover/view.jsx
Reverts lbryio/lbry-desktop#7081
> Revert "fix recommended follows"

- ui/component/wunderbarSuggestions/view.jsx
- ui/scss/component/_wunderbar.scss
Closes #7075 Move "explore tags" to a stable position 
See commit messages for details.
> Wunderbar: various fixes

- ui/redux/actions/comments.js
- Hopefully this is easier to understand, and easier to add/remove entries.
- The link support will be needed by the upcoming Appeal process.
> Commentron err replacement:  fix readability + added link support.

- ui/component/button/view.jsx
- ui/component/fileViewerEmbeddedTitle/index.js
- ui/component/fileViewerEmbeddedTitle/view.jsx
- ui/component/searchTopClaim/view.jsx
- ui/component/wunderbarTopSuggestion/index.js
- ui/component/wunderbarTopSuggestion/view.jsx
- ui/constants/tags.js
- ui/scss/component/_embed-player.scss
- ui/scss/component/_file-render.scss
- web/component/fileViewerEmbeddedEnded/index.js
- web/component/fileViewerEmbeddedEnded/view.jsx
- web/scss/themes/odysee/component/_file-render.scss
Disable link buttons and title links on embeds during and after playback.
Still some details to work out - what to do at the end?
> support embed preference

- ui/component/userChannelFollowIntro/view.jsx
Closes [#7118 advanced filtering adjustments for channel related context](https://github.com/lbryio/lbry-desktop/issues/7118)
> Disable adv filters in "Find channels to follow"

- ui/component/viewers/videoViewer/index.js
- ui/component/viewers/videoViewer/view.jsx
if embedpreferred, don't "end" video.
> embed preferred no end

- ui/component/publishFile/view.jsx
> Fix incorrect context for 'New' string

- ui/component/notification/view.jsx
Issue Number: Closes #7143 
</details>
> Fix channel name URL issue

- ui/component/fileRenderFloating/index.js
- ui/component/fileRenderFloating/view.jsx
- ui/redux/selectors/content.js
Issue Number: Closes #7098
</details>
> Fix video embeds in comments not playing and resize issues

- ui/redux/reducers/settings.js
Issue Number: Closes #7090
</details>
> Fix autoplay next default value

- .flowconfig
- package.json
- ui/component/claimPreviewSubtitle/view.jsx
- ui/component/claimPreviewTile/index.js
- ui/component/claimPreviewTile/view.jsx
- ui/component/dateTime/view.jsx
- ui/component/fileViewCountInline/view.jsx
- ui/scss/component/_claim-list.scss
- ui/scss/component/_view_count.scss
Fixes #7078
This address specifically 'large' view of over 1600px, where the worst offending was happening, but should also fix issues on other sizes as well, if anyone sees the view counts creating a third line on channel overview let me know and I'll take a look.
> Fix issue where channel upload viewcounts were creating a new line

- ui/component/collectionPreviewOverlay/index.js
- ui/component/collectionPreviewTile/index.js
- ui/redux/reducers/claims.js
- ui/redux/selectors/claims.js
> A few minor redux fixes

- README.md
I noticed that source code for running web version of LBRY (lbry.tv) is removed from this repo so I updated readme to remove instructions for it from readme cause it was confusing people.
</details>
> Updating readme - Removing web app setup

- ui/component/viewers/videoViewer/view.jsx
Cherry-picked from https://github.com/OdyseeTeam/odysee-frontend/pull/379
> Debounce volume and muted state update.

- ui/scss/component/_media.scss
Cherry-picked.  Maybe useful?
- Closes https://github.com/lbryio/lbry-desktop/issues/7222
- Also felt it's too squished for the longest time. Previously fixed comments but didn't handle this.
> File description (collapsed): show ~3 lines instead of ~1

- ui/constants/claim_search.js
- ui/page/channelsFollowingDiscover/view.jsx
- ui/util/buildHomepage.js
> update trending to use trending_score

- ui/component/claimListHeader/view.jsx
- ui/scss/component/_claim-search.scss
> cleaner discover filters display

- ui/scss/component/_card.scss
- ui/scss/init/_base-theme.scss
To go with the input border PR, trying some other styles to make it less busy. Adding more whitespace around cards.
> more  whitespace on cards

- ui/redux/actions/settings.js
- ui/redux/reducers/settings.js
reducers shoudn't do these functions, actions should.
> clean sync_client_Settings reducer

- ui/redux/actions/settings.js
Turns out this was a quick fix.
> Fix shared prefs all values

- electron/index.js
- static/app-strings.json
- ui/component/app/index.js
- ui/component/app/view.jsx
- ui/component/lastReleaseChanges/index.js
- ui/component/lastReleaseChanges/view.jsx
- ui/component/settingDisableAutoUpdates/index.js
- ui/component/settingDisableAutoUpdates/view.jsx
- ui/component/settingSystem/view.jsx
- ui/constants/settings.js
- ui/index.jsx
- ui/redux/actions/app.js
- ui/redux/reducers/app.js
- ui/redux/selectors/app.js
- ui/redux/selectors/settings.js
- ui/scss/all.scss
- ui/scss/component/_last-release-changes.scss
Issue Number: https://github.com/lbryio/lbry-desktop/issues/7480
- Updates can be downloaded multiple times
- Update nag notification is visible even if the update modal is open
- Users can't disable auto updates
- Updates will be downloaded once
- Update nag notification is hidden if the update modal is open
- Users can disable auto updates from settings
In order to test these changes, we need to somehow let electron think there is an update.
Create a new file in `dist/electron/webpack/dev-app-update.yml` with the following content:
```yaml
owner: lbryio
repo: lbry-desktop
provider: github
```
Comment line 193 out of file `lbry-desktop\ui\redux\actions\app.js`:
```js
if (autoUpdateDeclined || isDev) {
// return; <- here
}
```
Comment lines from 509 to 517 out …
> 7480 upgrade modal is broken

- electron/index.js
- ui/index.jsx
- ui/modal/modalUpgrade/index.js
- ui/modal/modalUpgrade/view.jsx
- ui/redux/actions/app.js
- ui/redux/selectors/app.js
Issue Number: https://github.com/lbryio/lbry-desktop/issues/7480
- Updates can be downloaded multiple times
- Update nag notification is visible even if the update modal is open
- Users can't disable auto updates
- Updates will be downloaded once
- Update nag notification is hidden if the update modal is open
- Users can disable auto updates from settings
In order to test these changes, we need to somehow let electron think there is an update.
Create a new file in `dist/electron/webpack/dev-app-update.yml` with the following content:
```yaml
owner: lbryio
repo: lbry-desktop
provider: github
```
Comment line 193 out of file `lbry-desktop\ui\redux\actions\app.js`:
```js
if (autoUpdateDeclined || isDev) {
// return; <- here
}
```
Comment lines from 509 to 517 out …
> 7480 upgrade modal is broken (reopen)

- ui/component/claimCollectionAdd/view.jsx
- ui/component/claimList/view.jsx
- ui/component/claimListHeader/view.jsx
- ui/component/playlistsMine/view.jsx
- ui/component/searchOptions/view.jsx
- ui/component/txoList/view.jsx
- ui/component/walletTipAmountSelector/view.jsx
- ui/page/fileListDownloaded/view.jsx
- ui/page/fileListPublished/view.jsx
- ui/page/listBlocked/view.jsx
- ui/page/top/view.jsx
- ui/scss/component/_badge.scss
- ui/scss/component/_button.scss
- ui/scss/component/_card.scss
- ui/scss/component/_channel.scss
- ui/scss/component/_claim-list.scss
- ui/scss/component/_claim-search.scss
- ui/scss/component/_comments.scss
- ui/scss/component/_header.scss
- ui/scss/component/_main.scss
- ui/scss/component/_markdown-editor.scss
- ui/scss/component/_modal.scss
- ui/scss/component/_textarea-suggestions.scss
- ui/scss/component/menu-button.scss
- ui/scss/init/_gui.scss
- ui/scss/themes/dark.scss
- ui/scss/themes/light.scss
mature tag color fix
comment suggestion style fixes
other button color fixes
scrolling fix
staked indicator fix
removed some !important s
> style fixes

- ui/component/channelThumbnail/view.jsx
- ui/component/optimizedImage/view.jsx
Issue Number: https://github.com/lbryio/lbry-desktop/issues/7550
On the sidebar, sometimes thumbnails do not show the proper image (defaults to the default thumbnail even though there is a correct image to display)
Thumbnail gets displayed correctly.
</details>
> Fix thumbnails missing while searching in side bar.

- .env.defaults
- config.js
- extras/lbryinc/lbryio.js
- ui/page/youtubeSync/index.js
- ui/page/youtubeSync/view.jsx
- ui/redux/actions/app.js
- ui/redux/actions/user.js
Broke login in production, probably due to cookie policy
> Revert "strip lbrytv"

- ui/analytics.js
- ui/component/sideNavigation/view.jsx
- ui/component/userEmailNew/view.jsx
- ui/redux/actions/user.js
> Revert "more lbrytv removal"

- ui/component/channelAbout/view.jsx
- ui/component/claimPreview/view.jsx
- ui/component/claimPreviewSubtitle/view.jsx
- ui/component/comment/view.jsx
- ui/component/commentReactions/view.jsx
- ui/component/fileReactions/view.jsx
- ui/component/fileViewCount/view.jsx
- ui/component/publishBid/bid-help-text.jsx
- ui/component/walletBalance/view.jsx
- ui/page/channel/view.jsx
- ui/util/comments.js
- ui/util/format-credits.js
- ui/util/intlNumberFormat.js
- ui/util/number.js
Issue Number: https://github.com/lbryio/lbry-desktop/issues/7120
</details>
> Format numbers internationally.

- flow-typed/homepage.js
- ui/util/buildHomepage.js
Issue Number: https://github.com/lbryio/lbry-desktop/issues/7546
N/A
When the user's language isn't English, a new category 
with the top content in the user's language gets displayed.
</details>
> Add language category.

- flow-typed/Settings.js
- ui/component/appStorageVisualization/view.jsx
- ui/component/hostingSplash/view.jsx
- ui/component/settingViewHosting/view.jsx
- ui/util/diskspace.js
windows was reporting bytes rather than kb
free/total changed type to number
> fix diskspace windows bytes

- ui/component/splash/view.jsx
- ui/scss/component/_splash.scss
Issue Number: https://github.com/lbryio/lbry-desktop/issues/7592
</details>
> Fix splash error message when the app can't initialize.

- ui/scss/component/_markdown-editor.scss
- ui/scss/init/_base-theme.scss
- ui/scss/themes/dark.scss
- ui/scss/themes/light.scss
Issue Number: https://github.com/lbryio/lbry-desktop/issues/7619
</details>
> changed the color of the editor-toolbar_hover class

- ui/redux/selectors/file_info.js
Issue Number: https://github.com/lbryio/lbry-desktop/issues/7405
Downloads are sorted to show the oldest first.
Downloads are sorted so the newest/recently-downloaded-elements
are shown first.
</details>
> Sort downloads (show newest first)

- yarn.lock
Issue Number: https://github.com/lbryio/lbry-desktop/issues/7700
NA
App upgraded to Electron 17.2.0.
</details>
> Upgrade to Electron 17.2.0.

- ui/component/txoList/view.jsx
- ui/constants/txo_list.js
Issue Number: https://github.com/lbryio/lbry-desktop/issues/6231
</details>
> Add 'Collections' into txo filter

- ui/component/commentCreate/view.jsx
- ui/component/commentsList/view.jsx
- ui/component/fileThumbnail/index.js
- ui/scss/component/_card.scss
- ui/scss/component/_comments.scss
Title level buttons on file page had bad layout. Main view is better now. mobile size still has messed up spacing for the comment sorting block.
> fix comment area display
