- app/menu/main-menu.js
This includes a Developer menu that can be enabled or disabled through the UI.
This Web UI PR is needed to enable and disable the menu: https://github.com/lbryio/lbry-web-ui/pull/193
> Add basic menubar

- ui/CHANGELOG.md
- ui/js/component/file-actions.js
- ui/js/component/file-tile.js
- ui/js/lbry.js
- ui/js/page/file-list.js
- ui/js/page/show.js
- ui/js/page/watch.js
This covers _almost_ everything. There are a couple of places that still use names or SD hashes because the APIs haven't been updated yet.
> Use outpoints for unique IDs

- ui/js/page/file-list.js
Needed for compatibility with this lbrynet change: https://github.com/lbryio/lbry/pull/513
> Change nOut to nout

- ui/js/app.js
Windows and Linux were incorrect
> Fix filenames for downloaded upgrades

- ui/js/component/channel-indicator.js
- ui/js/component/file-actions.js
- ui/js/component/file-tile.js
- ui/js/page/discover.js
- ui/js/page/publish.js
- ui/js/uri.js
- ui/scss/all.scss
- ui/scss/component/_channel-indicator.scss
- Adds indicator to file tiles listing the channel and auth status
- Adds ability to choose and create channels on Publish page
> Channels (WIP)

- ui/js/page/publish.js
Save the new name as soon as it's entered instead of after resolution, so that it's possible to publish before the results from resolve() and claim_list_mine() come back.
> Publish: improve state management of names

- CHANGELOG.md
- ui/js/component/common.js
- ui/js/component/file-actions.js
- ui/js/component/file-tile.js
- ui/js/lbry.js
- ui/js/lbryio.js
- ui/js/page/show.js
- ui/js/page/watch.js
- ui/scss/_canvas.scss
- On Show page and file tiles, display provisional price based on available info instead of waiting for Lighthouse to respond. I'm almost certainly not doing this right, hence WIP
- Show price in confirmation modal for download/watch
- Don't show confirmation modal if user clicks Watch but they already have the file
- Misc. cleanup/minor bugfixes
> Improvements to watch and download process

- CHANGELOG.md
- ui/js/component/channel-indicator.js
- ui/js/component/file-actions.js
- ui/js/component/file-tile.js
- ui/js/lbry.js
- ui/js/lbryuri.js
- ui/js/page/discover.js
- ui/js/page/file-list.js
- ui/js/page/publish.js
- ui/js/page/show.js
- Rename module and functions
- Add special keys for building channel claims, so you don't need special logic when you might have either a channel claim or anon claim
> Improve URI module

- ui/js/component/auth.js
- ui/js/page/wallet.js
- ui/js/rewards.js
> prefer wallet_unused_address over wallet_new_address

- app/menu/main-menu.js
There are ways to make this just a shortcut with no (visible) menu option at all, if we want.
> Add Select All option to Edit menu

- CHANGELOG.md
- app/main.js
Also enables single instance mode on Windows, so clicking a link (or clicking the icon again) just focuses the existing window instead of launching a second copy of LBRY. Single instance mode is still disabled on Linux for now due to some weird behavior that's probably coming from an Electron bug.
> Windows URI handling

- ui/js/component/auth.js
- ui/js/component/common.js
- ui/js/component/fileActions/view.jsx
- ui/js/component/form.js
- ui/js/component/link/view.js
- ui/js/component/load_screen.js
- ui/js/component/menu.js
- ui/js/component/modal-page.js
- ui/js/component/modal.js
- ui/js/component/notice.js
- ui/js/component/reward-link.js
- ui/js/component/snack-bar.js
- ui/js/component/splash.js
- ui/js/component/tooltip.js
- ui/js/component/video/view.jsx
- ui/js/page/developer.js
- ui/js/page/help/view.jsx
- ui/js/page/publish/view.jsx
- ui/js/page/report.js
- ui/js/page/rewards.js
- ui/js/page/settings/view.jsx
- ui/js/page/start.js
Close to done. There are probably still a few callbacks that need to be wrapped in arrow functions.
> Convert all remaining old-style components to ES6 classes (WIP)

- ui/js/actions/content.js
- ui/js/component/video/view.jsx
The checks around downloaded but deleted files were broken
> Fix playing videos that were deleted and require no cost info

- ui/js/actions/content.js
- ui/js/component/fileActions/index.js
- ui/js/component/video/index.js
- ui/js/component/video/view.jsx
- ui/package.json
- ui/webpack.config.js
- ui/webpack.dev.config.js
Fixes having to click play twice. We have an `autoplay` variable but I don't see where it's getting set, so right now no files will actually autoplay still.
> Fix autoplaying

- ui/js/actions/settings.js
- ui/js/actions/wallet.js
- ui/js/lbry.js
https://github.com/lbryio/lbry/pull/669
> update deprecated commands

- package.json
- ui/package-lock.json
- ui/package.json
I installed it in the wrong directory
> move why-did-you-update to package.json ui/

- app/package-lock.json
- ui/js/actions/cost_info.js
- ui/js/component/userEmailNew/index.jsx
- ui/js/component/video/internal/loading-screen.jsx
- ui/js/component/video/internal/player.jsx
- ui/js/component/video/view.jsx
- ui/js/reducers/claims.js
- ui/js/selectors/claims.js
- ui/package-lock.json
> Metadata at end

- app/package-lock.json
- package-lock.json
- ui/package-lock.json
Beginning to wonder how these lock files actually help. However, I can't run the app without them right now.
> Regenerate lock files

- ui/js/component/form.js
- ui/js/page/publish/view.jsx
Also includes some general refactoring and improvements to the state management
> Pre-fill metadata on Publish page

- ui/js/lbry.js
Checked [here](https://chromium.googlesource.com/chromium/src/+/master/net/base/mime_util.cc#64) for compatibility.
> Support more file extensions

- ui/js/component/fileCard/view.jsx
- ui/js/component/fileTile/view.jsx
> File tile error

- ui/js/actions/user.js
- ui/js/page/rewards/index.js
- ui/js/page/rewards/view.jsx
Rewards were not being fetched on the rewards page. Also, they were not being fetched for me on startup either as the `doUserFetch` doesn't seem to get called, so I've added it to the after authentication success too.
> Fix rewards page

- ui/js/actions/app.js
- ui/js/main.js
- ui/js/reducers/app.js
Stayed up until 3am to watch the live feed so figured I should use the time to fix something too :)
I used hash based routing as it seems easier than trying to intercept refreshes, reload the app and then redirect back to the previous path. Might be stupid, I'm tired.
> Fix refreshing

- ui/js/reducers/file_info.js
- ui/js/selectors/file_info.js
This naming is a bit clearer IMO.
> Rename fileInfo.fileInfos to fileInfo.byOutpoint

- ui/js/reducers/file_info.js
- ui/js/selectors/file_info.js
@kauffj this one is important to get in before the next release. Master is broken right now.
> Two file info fixes since last merge

- ui/js/page/filePage/view.jsx
Just occurred to me that this might be useful.
> Add claim_id to DMCA links

- app/main.js
Also refactors and simplifies the code for handling URIs requested from outside apps.
Code complete, tested on Mac. If someone else wants to test it on Win and Linux, it's ready to merge on any time. Otherwise I'll do it tomorrow (6/28).
> Reliably focus app window when opening lbry:// links (WIP)

- app/main.js
> On Windows, denormalize URI when opening link with app closed

- ui/js/component/video/internal/play-button.jsx
- ui/js/component/video/internal/player.jsx
- Pressing the space bar can initiate video playback
- Pressing the space bar can pause and resume video playback
- Clicking on the video area (above the video controls) after initial playback can pause and resume video playback
> Issue #311 playback input improvements

- ui/js/component/cardMedia/index.js
- ui/js/component/cardMedia/view.jsx
- ui/js/component/fileCard/view.jsx
- ui/js/component/fileTile/view.jsx
- ui/scss/component/_card.scss
Implemented CardMedia component as requested in https://github.com/lbryio/lbry-app/pull/281#issuecomment-315220777
> CardMedia UI component

- ui/js/component/fileCard/view.jsx
- ui/scss/component/_card.scss
- Reduced the card size
- Reduced the font size of the card titles
- Reduced the font size of the card description
- Moved the title, publisher and price below the card thumbnail.
> [WIP] Discover page UI tweaks

- CHANGELOG.md
- ui/js/actions/app.js
- ui/js/component/fileActions/view.jsx
- use `toQueryString` in `app/actions`
- add a loading fileinfo message on file actions
> A couple of little fixes

- ui/js/actions/app.js
- ui/js/component/modalIncompatibleDaemon/index.js
- ui/js/component/modalIncompatibleDaemon/view.jsx
Based on discussion I think this is what was asked. But since the earlier PR was closed so I added a new one.
This one displays a Learn More link pointing to the appropriate faq.
> (quickfix) Now displays quit button in IncompatibleDaemonModal.

- CHANGELOG.md
- ui/js/component/publishForm/view.jsx
I'm not sure if this is the best way to fix this but it works without breaking anything(based on some testing).
A quickfix for issue #462
> (quickfix) Check for required fields during publishing

- ui/js/component/publishForm/view.jsx
> Update bid input field in view.jsx to not go past 0

- ui/js/component/walletSend/view.jsx
Minor fix for: https://github.com/lbryio/lbry-app/issues/441
( this should close the issue ^^ )
> Prevent negative value in WalletSend bid input

- .gitignore
- build/build.sh
@lyoshenka I swear I had a PR for this, but it seems to have disappeared?
> skip downloading the daemon if it exists and the version matches

- CHANGELOG.md
- ui/js/component/formField/view.jsx
- ui/js/component/walletSend/index.js
- ui/js/component/walletSend/view.jsx
- ui/js/lbryuri.js
- ui/js/selectors/wallet.js
> Validate address on Send page

- build/build.sh
[How To Use Colors In Bash](https://docs.google.com/document/d/145mpTLHAQW2RgoWkLflyF6fYdgLxpYwPcdMD7SOwIJA/edit?usp=sharing)
also is there point to having the set -e at the top it defeats the purpose of the rest of the set -e wrappers you guys put together
> added color to echo's to stand out more(build.sh)

- README.md
Adding guide on how to build for windows.
> Adding Windows Build Instructions

- ui/watch.bat
Batch file to provide node-sass/webpack watching for windows users.
> Windows Watch Batch

- build/build.sh
better set -x wrappers for non-debugging everything and added a couple extra echos
> better (build.sh)

- ui/js/page/channel/view.jsx
Fixes #389. Can be merged any time, but won't work until #555 is merged.
> Show local file indicator on Channel page

- CHANGELOG.md
- ui/js/actions/content.js
- ui/js/constants/settings.js
- ui/js/lbry.js
- ui/js/page/settings/index.js
- ui/js/page/settings/view.jsx
- ui/js/reducers/settings.js
- ui/js/selectors/settings.js
> Instant Purchase

- CHANGELOG.md
- ui/js/actions/content.js
> Reset playing uri after error or timeout #643 
> UI glitch after accessing a video without enough credits #605
> Fix issues with playing uri

- CHANGELOG.md
- ui/js/actions/content.js
> Channel without claims shows "fetching content...", console error #636
> Fix channel fetching without claims 

- ui/js/component/publishForm/view.jsx
This changes amount > effective_amount which provides a more accurate top bid. Tested locally. 
Fixes https://github.com/lbryio/lbry-app/issues/631
> show effective amount as top bid

- app/main.js
- package.json
- yarn.lock
Fixes #164 by upgrading to Electron 1.7.9
> Stop lbry:// links from opening a new window on Linux

- CHANGELOG.md
- ui/js/component/transactionList/index.js
- ui/js/component/transactionList/internal/TransactionListItem.jsx
Also added a function that capitalizes the first letter of all tx types, as this looked better.
> Rewards marked in txn list

- CHANGELOG.md
> changelog addition

- CHANGELOG.md
- ui/js/actions/content.js
- ui/js/actions/file_info.js
- ui/js/component/transactionList/index.js
- ui/js/component/transactionList/internal/TransactionListItem.jsx
- ui/js/component/transactionList/view.jsx
- ui/js/constants/modal_types.js
- ui/js/constants/transaction_types.js
- ui/js/modal/modalRevokeClaim/index.js
- ui/js/modal/modalRevokeClaim/view.jsx
- ui/js/modal/modalRouter/view.jsx
- ui/js/reducers/claims.js
- ui/js/selectors/claims.js
- ui/scss/component/_table.scss
> Revoke claims from Txn list

- build/build.ps1
Didn't update the windows script
https://github.com/lbryio/lbry-app/blob/master/build/build.sh#L61
> Fix windows ui build

- ui/js/modal/modalCreditIntro/view.jsx
> Added currentBalance to props in modal credit intro

- ui/js/component/fileCard/view.jsx
- ui/js/component/uriIndicator/view.jsx
- ui/js/page/file/view.jsx
- ui/scss/component/_card.scss
- ui/scss/component/_channel-indicator.scss
Not super happy with this fix, but good to get it in sooner since it looks so bad right now.
> fix channel name alignment on file page

- ui/js/util/redux-utils.js
Nice little helper to avoid some of the redux boiler plate.
> add handleActions redux util

- package.json
- src/renderer/js/component/publishForm/index.js
- src/renderer/js/component/publishForm/internal/channelSection.jsx
- src/renderer/js/component/publishForm/view.jsx
Also added a start script just for fun.
Mostly a test to see what it would look like. Not sure if we want to go this route, or go through the daemon for everything
> Check the users balance before trying to publish/create a channel

- src/renderer/js/component/form.js
🤕 
Actually fix the typo this time
> need to use static with propTypes

- src/renderer/js/rewards.js
Also fixed many downloads text.
Fixes important part of #803, a less critical refresh issue still exists.
> add referral message type

- src/main/main.js
removing the user-agent from other request caused errors, not a priority to figure out at this point in my opinion
> Set app-wide user agent

- build/build.ps1
- build/build.sh
- webpack.renderer.additions.js
Removes Flow type checking from production.
> Fix windows build

- flowtype-plugin.js
- package.json
- webpack.renderer.additions.js
- yarn.lock
Also updated the prettier script
> use flow check and move flowtype-plugin to top level

- src/renderer/rewards.js
Snackbar text was blank  - looks like the type was mismatched.
> fix snackbar text

- README.md
I am now running Antergos (arch linux) as my OS btw
> Added build instructions for arch linux and other distros

- src/renderer/component/wunderbar/view.jsx
Change "movies" to "videos" (more generic)
See "Manchester first run experiments" doc on Google drive
> update wunderbar text

- CONTRIBUTING.md
I wanted to get started with contributing, however a column character is missing on the level links resulting on the filter matching no issue.
> Fix CONTRIBUTING.md level issues links

- package.json
- yarn.lock
> Keeps node_modules up-to-date when yarn.lock changes due to git

- src/renderer/component/fileCard/view.jsx
- src/renderer/component/fileList/view.jsx
- src/renderer/component/fileListSearch/view.jsx
- src/renderer/component/fileTile/view.jsx
- src/renderer/component/publishForm/internal/channelSection.jsx
- src/renderer/component/publishForm/view.jsx
- src/renderer/component/transactionList/internal/TransactionListItem.jsx
- src/renderer/component/uriIndicator/index.js
- src/renderer/component/uriIndicator/view.jsx
- src/renderer/component/walletSend/view.jsx
- src/renderer/component/wunderbar/index.js
- src/renderer/component/wunderbar/view.jsx
- src/renderer/lbryURI.js
- src/renderer/page/channel/view.jsx
- src/renderer/page/discover/view.jsx
- src/renderer/page/file/view.jsx
- src/renderer/page/search/view.jsx
- src/renderer/page/show/view.jsx
- src/renderer/redux/actions/content.js
- src/renderer/redux/actions/search.js
- src/renderer/redux/selectors/claims.js
- src/renderer/redux/selectors/media.js
- src/renderer/redux/selectors/navigation.js
Separate named exports optimize the code so it only imports necessary resources.
Resolve #952.
> Refactor lbryuri.js into separate named exports

- package.json
- yarn.lock
> Revert "Keeps node_modules up-to-date when yarn.lock changes due to git"

- flow-typed/npm/mixpanel-browser_v2.11.x.js
- package.json
- src/renderer/analytics.js
- src/renderer/index.js
- src/renderer/redux/actions/navigation.js
- src/renderer/redux/actions/settings.js
- src/renderer/redux/actions/user.js
- yarn.lock
Unfortunately, due to changes in how we route URLs as well as increasing the power, scope, and privacy of analytics, I had to introduce analytics calls outside of renderer/index.js. That said, all the code is contained to one separate file, so its not bad at all.
> Analytics overhaul

- src/renderer/component/video/internal/player.jsx
- src/renderer/util/setBadge.js
This closes #965 and fixes #754. It also fixes a bug that would prevent the macOS app badge icon to show up.
> Fixes Video Player "waits for metadata"

- CHANGELOG.md
- src/renderer/redux/actions/settings.js
Change to 21:00, which is 9PM, so that it matches the settings page.
> Fix night mode start time

- CHANGELOG.md
- src/renderer/index.js
https://spee.ch/a/ScreenCapture2018-2-26-042956.mp4
#1045 ( my old PR i close because i cannot squash github)
> [FIX #988] Disable drag and drop 

- CHANGELOG.md
- src/renderer/component/rewardSummary/view.jsx
Add Reward FAQ URL to LBRY App , Based issues No 1029.
> [#1029] Added Rewards FAQ to LBRY App

- CHANGELOG.md
- package.json
- src/main/index.js
Fixes https://github.com/lbryio/lbry-app/issues/1117 for Windows per suggestions from https://github.com/electron/electron/issues/10864.
> Fix Windows notifications

- package.json
Daemon 0.19.1 was just built and ready for use in the latest app.
> Update to Daemon 0.19.1

- CHANGELOG.md
- package.json
- src/main/createWindow.js
- yarn.lock
> Retain previous screen sizing on startup

- .eslintrc.json
- CHANGELOG.md
- src/renderer/app.js
- src/renderer/lbry.js
- src/renderer/redux/selectors/settings.js
This fixes https://github.com/electron-userland/electron-webpack/issues/52
> fix: __static path not resolving on development environment

- src/renderer/index.js
- src/renderer/redux/actions/app.js
> Revert "Authenticate early"

- src/renderer/component/fileList/view.jsx
- src/renderer/lbry.js
- Add `getFileTitle` function: Extracts the correct title from metadata. https://github.com/lbryio/lbry-app/issues/1115#issuecomment-375513600
- Fix sort by title on download / publish page ( for good )
- Fixes https://github.com/lbryio/lbry-app/issues/1115
> Fix sort by title 

- .eslintrc.json
- src/renderer/component/common/form-components/form-field.jsx
- src/renderer/component/publishForm/view.jsx
- src/renderer/component/userEmailNew/view.jsx
- src/renderer/component/wunderbar/view.jsx
- src/renderer/modal/modal.jsx
- src/renderer/modal/modalEmailCollection/view.jsx
- src/renderer/modal/modalPublish/view.jsx
- src/renderer/page/auth/view.jsx
- src/renderer/page/backup/view.jsx
- src/renderer/page/discover/view.jsx
- src/renderer/page/rewards/view.jsx
- src/renderer/scss/_gui.scss
- src/renderer/scss/_vars.scss
- src/renderer/scss/component/_button.scss
- src/renderer/scss/component/_card.scss
- src/renderer/scss/component/_form-field.scss
#1204
#1195 
#1205 
#1211 
Improved backup page styling
> [redesign] fixes

- src/renderer/component/walletAddress/view.jsx
based on issues https://github.com/lbryio/lbry-app/issues/1224
> fix button redesign on receive credits section

- src/renderer/component/common/icon.jsx
inspiration based on issues no #1250
> modify featured content badge to red colour

- CHANGELOG.md
- electron-builder.json
This closes https://github.com/lbryio/lbry-app/issues/1254.
> feat: build for both architectures (x86 and x64) on Windows

- src/renderer/component/fileList/view.jsx
- src/renderer/component/fileListSearch/view.jsx
- src/renderer/component/publishForm/view.jsx
- src/renderer/component/userEmailVerify/view.jsx
- src/renderer/modal/modalRemoveFile/view.jsx
- src/renderer/redux/actions/publish.js
- src/renderer/redux/selectors/file_info.js
- src/renderer/scss/component/_button.scss
Fixes:
#1198
#1206 
#1217 
#1220 
#1221
> [redesign] moar fixes

- src/renderer/component/fileList/view.jsx
> fix: add back newestFirst/oldestFirst sorting to published/downloaded pages

- src/renderer/component/fileActions/index.js
- src/renderer/component/transactionList/index.js
- src/renderer/modal/modalRouter/index.js
- src/renderer/redux/actions/content.js
- src/renderer/redux/actions/user.js
- yarn.lock
> Revert "update doOpenModal imports with correct source, and some lint fixes"

- src/renderer/component/fileActions/index.js
- src/renderer/component/transactionList/index.js
- src/renderer/modal/modalRouter/index.js
- src/renderer/redux/actions/content.js
- src/renderer/redux/actions/user.js
- yarn.lock
> Revert "Revert "update doOpenModal imports with correct source, and some lint fixes""

- CHANGELOG.md
- src/renderer/component/inviteNew/view.jsx
@seanyesmunt ready to merge guys. i close and delete my old branch
> add FAQ to Referral page

- src/renderer/page/settings/view.jsx
@seanyesmunt referenced my bad PR #1247
> Hide Price Form Field

- src/renderer/component/publishForm/view.jsx
If "Free" Selected
If "Choose Price" Selected
> Show/Hide Price on Publish Form

- src/renderer/component/fileActions/index.js
- src/renderer/component/transactionList/index.js
- src/renderer/modal/modalRouter/index.js
- src/renderer/redux/actions/content.js
- src/renderer/redux/actions/user.js
- yarn.lock
> [reopening]  update doOpenModal imports with correct source, and some lint fixes 

- src/renderer/page/settings/view.jsx
> fix wording

- CHANGELOG.md
- src/renderer/scss/all.scss
- static/themes/dark.css
Minor css fixes for dark theme:
- Fix Description box on Publish (dark theme) #1356 
- Add alternate row shading for transactions on dark theme #1355
> Dark theme patch

- package.json
Clear the global cache and reinstall.
``` Shell
yarn clean
```
Fix for Yarn isn't pulling in latest lbry-redux changes #1382
> Add clean command

- CHANGELOG.md
- package.json
- src/renderer/index.js
- src/renderer/page/show/index.js
- src/renderer/page/show/view.jsx
- src/renderer/store.js
- yarn.lock
Creating a new branch because we need to move some of these changes to `lbry-redux`
> Merge dmca changes into master

- src/renderer/component/walletSend/index.js
- src/renderer/component/walletSend/view.jsx
> fix: send correct values to sendTx

- .travis.yml
- package.json
- yarn.lock
> fix linux build

- CONTRIBUTING.md
- README.md
- package.json
I removed the yarnhooks for now since they are slightly annoying.
updated readme with resetting packages section
update contributing.md with lbry-redux section
Also added a nice intro after seeing this tweet
https://twitter.com/ScribblingOn/status/995715231300050944
> Docs and remove yarnhooks

- src/renderer/component/walletSendTip/index.js
- src/renderer/component/walletSendTip/view.jsx
I addressed the error message part of #738 in [lbryio/lbry-redux/pull/23](https://github.com/lbryio/lbry-redux/pull/23). This PR is to prevent the common cause of that.
> disable Send button when tip amount is zero

- .eslintrc.json
- src/renderer/component/common/icon.jsx
- src/renderer/component/fileListSearch/view.jsx
- src/renderer/component/fileTile/view.jsx
- src/renderer/component/video/index.js
- src/renderer/component/video/internal/play-button.jsx
- src/renderer/component/video/view.jsx
- src/renderer/component/wunderbar/index.js
- src/renderer/component/wunderbar/internal/autocomplete.jsx
- src/renderer/component/wunderbar/view.jsx
- src/renderer/modal/modalIncompatibleDaemon/view.jsx
- src/renderer/page/search/view.jsx
- src/renderer/redux/actions/app.js
- src/renderer/redux/reducers/app.js
- src/renderer/scss/_gui.scss
- src/renderer/scss/_vars.scss
- src/renderer/scss/component/_button.scss
- src/renderer/scss/component/_card.scss
- src/renderer/scss/component/_file-list.scss
- yarn.lock
https://github.com/lbryio/lbry-app/issues/1419
https://github.com/lbryio/lbry-app/issues/1257
https://github.com/lbryio/lbry-app/issues/1264
https://github.com/lbryio/lbry-app/issues/1406
https://github.com/lbryio/lbry-app/issues/1404
https://github.com/lbryio/lbry-app/issues/1478
> Release blockers

- src/renderer/redux/reducers/navigation.js
> set default route back to /discover

- src/renderer/component/filePrice/view.jsx
#1427 
return null when costInfo is undefined
> do not display "PRICE"

- src/main/index.js
- src/renderer/component/router/index.js
- src/renderer/component/router/view.jsx
- src/renderer/index.js
Implements https://github.com/lbryio/lbry-app/issues/1352 - tested on Windows/Mac/Linux
Fixes https://github.com/lbryio/lbry-app/issues/959
This will also enable us to use magic links on Windows, as before the `?` was not being escaped properly. 
Will need to update: https://github.com/lbryio/lbry.io/blob/b81191c7c5312183c25d072f3068b09fcdd1719e/view/template/acquisition/verify.php#L54
Tested magic link on Windows by setting the user agent. 
Thanks to @seanyesmunt for help with the doNotify logic :)
> special links/invalid URIs

- .eslintrc.json
- package.json
- src/renderer/component/externalLink/view.jsx
- src/renderer/component/publishForm/view.jsx
- src/renderer/component/video/view.jsx
- src/renderer/modal/modal.jsx
- src/renderer/modal/modalAffirmPurchase/view.jsx
- src/renderer/modal/modalCreditIntro/view.jsx
- src/renderer/page/channel/index.js
- src/renderer/page/channel/view.jsx
- src/renderer/page/file/view.jsx
- src/renderer/page/publish/index.js
- src/renderer/redux/actions/publish.js
- yarn.lock
https://github.com/lbryio/lbry-app/issues/1219
https://github.com/lbryio/lbry-app/issues/1515
> The fixes never end

- src/renderer/scss/component/_content.scss
Show hand pointer when hovering over anywhere on video thumbnail.
Close issue #1564
> Adds pointer on hover for video thumbnail

- src/renderer/scss/component/_content.scss
Show hand pointer when hovering over anywhere on video thumbnail and when the video is paused or playing.
> Show hand pointer when hovering over anywhere on video.

- src/renderer/component/wunderbar/view.jsx
To close https://github.com/lbryio/lbry-app/issues/1428
> modified text to make unified search bar clearer.

- src/renderer/component/fileCard/index.js
- src/renderer/component/fileCard/view.jsx
> Show smaller NSFW tag if it's my content

- src/renderer/page/help/view.jsx
Fixed wording and added link to support FAQ
> Fix wording + add link

- package.json
- src/renderer/component/publishForm/view.jsx
- src/renderer/component/selectThumbnail/view.jsx
- src/renderer/redux/actions/publish.js
- src/renderer/redux/reducers/publish.js
- yarn.lock
https://github.com/lbryio/lbry-app/issues/1584
> Thumbnail edit improvements

- README.md
> Broken contact link fix

- src/renderer/redux/actions/user.js
Didn't test this yet, but it should function the same way as the credit card portion on line 303
> claim first reward on phone verification

- src/renderer/redux/actions/user.js
> Revert "claim first reward on phone verification"

- src/renderer/redux/actions/user.js
Also made some search fixes as they were broken from previous merge.
> added lbry_id to install/new api call.

- src/renderer/component/publishForm/view.jsx
- src/renderer/component/selectChannel/view.jsx
- src/renderer/component/walletSend/view.jsx
- src/renderer/component/walletSendTip/view.jsx
- src/renderer/modal/modalRouter/view.jsx
- src/renderer/page/transactionHistory/view.jsx
- src/renderer/redux/actions/user.js
- src/renderer/redux/reducers/user.js
Includes
-some better error messages when using credits (publish, tip, send)
-claim new user reward after phone verification (requires API change)
-vertical stacking on send screen
-add missing blank slate message for transaction history
> Minor UX fixes

- src/renderer/redux/actions/user.js
- src/renderer/redux/reducers/user.js
This ensures that a newly verified user, via phone verification, automatically claims the new user reward.
> Fix phone verification + claim first reward

- src/renderer/component/walletSendTip/view.jsx
otherwise this shows 0 to start off with.
> bring back the tip placeholder

- CHANGELOG.md
- src/renderer/modal/modalDownloading/index.js
- src/renderer/modal/modalDownloading/view.jsx
And show manual install message
> Fix Linux upgrade path

- src/renderer/index.js
- src/renderer/modal/modalAutoUpdateConfirm/view.jsx
- yarn.lock
Fixes modal when clicking "upgrade app" from the top right menu.
Fixes double modal on autoupdate, issue https://github.com/lbryio/lbry-app/issues/1613
> Autoupgrade fixes

- src/renderer/redux/selectors/publish.js
This seems to fix ordering of pending publishes - worth a shot.
> pending publishes magic

- src/renderer/component/common/icon.jsx
- src/renderer/component/common/tooltip.jsx
- src/renderer/component/fileActions/view.jsx
- src/renderer/component/fileDownloadLink/view.jsx
- src/renderer/component/fileListSearch/index.js
- src/renderer/component/fileListSearch/view.jsx
- src/renderer/component/shapeShift/internal/active-shift.jsx
- src/renderer/component/userEmailVerify/view.jsx
- src/renderer/component/walletAddress/view.jsx
- src/renderer/component/wunderbar/index.js
- src/renderer/component/wunderbar/view.jsx
- src/renderer/modal/modalEmailCollection/view.jsx
- src/renderer/page/file/view.jsx
- src/renderer/page/search/index.js
- src/renderer/page/search/view.jsx
- src/renderer/scss/_gui.scss
- src/renderer/scss/component/_card.scss
- src/renderer/scss/component/_file-download.scss
- src/renderer/scss/component/_search.scss
- src/renderer/scss/component/_tooltip.scss
- Simplified search autocomplete. Tried to make it easier to notifiy users if they are going to a claim/channel/search page
- #1598 
- #1636 
- Removed auto search, we may add it back but it did not need to be on the `FileList` component, that was when we had the search modal.
- Other minor fixes accross the app
> UX changes

- src/renderer/component/wunderbar/internal/autocomplete.jsx
- src/renderer/component/wunderbar/view.jsx
- src/renderer/scss/component/_search.scss
https://github.com/lbryio/lbry-app/issues/1656
> fix sticky autocomplete

- src/renderer/component/common/form-components/form-field.jsx
- src/renderer/scss/component/_form-field.scss
- Fix fade automatic dark mode text when dark themes selected #1658
> Fix disabled form-field css style

- CHANGELOG.md
- src/renderer/component/common/file-exporter.jsx
- src/renderer/component/common/file-selector.jsx
- Fix shouldn't allow to open multiple export and choose file dialogs #1175
> Fix multiple dialog windows bug

- CHANGELOG.md
- src/renderer/component/common/file-exporter.jsx
- src/renderer/component/common/file-selector.jsx
- src/renderer/component/common/form-components/form-field.jsx
- src/renderer/component/externalLink/view.jsx
- src/renderer/component/fileListSearch/view.jsx
- src/renderer/component/wunderbar/index.js
- src/renderer/component/wunderbar/view.jsx
- src/renderer/constants/icons.js
- src/renderer/constants/settings.js
- src/renderer/page/channel/view.jsx
- src/renderer/page/search/index.js
- src/renderer/page/search/view.jsx
- src/renderer/page/settings/index.js
- src/renderer/page/settings/view.jsx
- src/renderer/redux/reducers/settings.js
- src/renderer/scss/component/_card.scss
- src/renderer/scss/component/_form-field.scss
- src/renderer/scss/component/_pagination.scss
- Minor component structure fix.
- Add icons for external / internal links.
- Better UI/UX for external links #1655.
The current style looks pretty obvious to me :upside_down_face:
> External-internal links (UX/UI)

- src/renderer/component/app/view.jsx
- src/renderer/component/common/icon.jsx
- src/renderer/component/fileDownloadLink/view.jsx
- src/renderer/component/header/index.js
- src/renderer/component/header/view.jsx
- src/renderer/component/sideBar/index.js
- src/renderer/component/sideBar/view.jsx
- src/renderer/constants/icons.js
- src/renderer/page/file/view.jsx
- src/renderer/scss/_gui.scss
- src/renderer/scss/_vars.scss
- src/renderer/scss/component/_card.scss
- src/renderer/scss/component/_header.scss
- src/renderer/scss/component/_nav.scss
- src/renderer/scss/component/_search.scss
- static/themes/dark.css
Some changes based on comments [here](https://github.com/lbryio/lbry-app/pull/1650#issuecomment-398911888)
- Brought back the sticky header. Based on @Invariant-Change's design
- Send tip icon is now a present
- Change the download icon color, purple looked on light mode.
- Green looks better, but doesn't stand out as much as black. Maybe we should just use black on light mode?
- Slightly improve spacing on file page (you are right, there are some kinks to be worked out with form row/form elements that are causing inconsistent spacing)
- Will revist, but better than what we currently have
> Additional UX fixes

- src/renderer/component/uriIndicator/view.jsx
- src/renderer/redux/actions/publish.js
https://github.com/lbryio/lbry-app/issues/1684
> Fix channel links and license type prefil on edit

- src/renderer/component/selectThumbnail/view.jsx
The other part of the original **typo** I posted in Discord that wasn't addressed in the PR posted by @ykris45. https://github.com/lbryio/lbry-app/pull/1697
> Url To URL Typo Fix

- src/renderer/scss/component/_nav.scss
> fix: increase sidebar width on large screens (#1705)

- src/renderer/component/fileList/view.jsx
- src/renderer/page/fileListDownloaded/view.jsx
Gets rid of the console errors in #1327
> use outpoint as key in FileList

- CHANGELOG.md
- package.json
- src/renderer/component/common/form-components/form-field.jsx
- src/renderer/util/contextMenu.js
- yarn.lock
- Can't right click > paste into description on publish and textarea #1664 
- External fix  https://github.com/RIP21/react-simplemde-editor/pull/68
> Fix context-menu

- package.json
- src/main/index.js
- src/renderer/redux/actions/app.js
- src/renderer/util/form-validation.js
- yarn.lock
- No address validation with `NO_ADDRESS_VALIDATION` env
- No daemon mismatch modal when running in dev mode
- Keep the app open if something crashes when running in dev mode
Waiting on testing from @eukreign
> Improve app/daemon development

- CHANGELOG.md
- src/renderer/page/file/view.jsx
One of these conditions (including tipping) will always apply, no need to hide the div.
> Fix #1756 - Remove check for div

- package.json
- src/renderer/component/cardMedia/view.jsx
- src/renderer/component/categoryList/view.jsx
- src/renderer/component/fileCard/view.jsx
- src/renderer/component/fileListSearch/view.jsx
- src/renderer/component/fileTile/index.js
- src/renderer/component/fileTile/view.jsx
- src/renderer/component/hiddenNsfwClaims/index.js
- src/renderer/component/hiddenNsfwClaims/view.jsx
- src/renderer/page/channel/index.js
- src/renderer/page/channel/view.jsx
- src/renderer/page/search/view.jsx
- src/renderer/page/subscriptions/view.jsx
- src/renderer/scss/component/_card.scss
- src/renderer/types/claim.js
- yarn.lock
Dependent upon https://github.com/lbryio/lbry-redux/pull/53
Currently causes issues with the community top bids section. That will be fixed in a future PR.
> Actually hide NSFW content

- CHANGELOG.md
- src/renderer/modal/modalIncompatibleDaemon/view.jsx
Changed the error message given when the daemon and LBRY app are on different versions of the API to make it more clear for the user what their next steps are.
Regarding ticket: https://github.com/lbryio/lbry-app/issues/1749
ticket complete.
> Changed the error message given when the daemon didn't update

- src/renderer/redux/reducers/shape_shift.js
The current error message sounds like LBRY is broken, when in fact it's a ShapeShift issue.
This message is friendlier and more accurate, which helps to keep LBRY's brand reputation stronger :)
> Better Error Message

- src/renderer/redux/actions/publish.js
Reverts lbryio/lbry-desktop#1778
> Revert "updated the url for successful thumbnail publishes"

- src/renderer/component/viewers/threeViewer/index.jsx
- src/renderer/component/viewers/threeViewer/internal/grid.js
- src/renderer/component/viewers/threeViewer/internal/loader.js
- src/renderer/component/viewers/threeViewer/internal/scene.js
- src/renderer/component/viewers/threeViewer/internal/three.js
- Fix model auto position and scale
- Add `obj` loader
> lbry://OBJ-test#1acb60d7d286622be5b6d9c01550202e4e462ff0
> Three-viewer patch

- src/renderer/component/page/view.jsx
Forgot to add this `setState` call
> Fix loading indicator on Page component

- package.json
- webpack.renderer.additions.js
- yarn.lock
See https://github.com/lbryio/lbry-desktop/issues/1485
and https://github.com/lbryio/lbry-redux/pull/62
also https://github.com/electron-userland/electron-webpack/issues/178
and https://github.com/electron-userland/electron-webpack/issues/183
Whole lotta things to work around!
> Watch lbry-redux for changes

- src/renderer/modal/modalAutoUpdateDownloaded/view.jsx
> Disable confirm button after pressing "Use It Now" button

- CHANGELOG.md
- src/renderer/redux/actions/publish.js
Otherwise it would just say "upload failed"
> Pass spee.ch error message

- CHANGELOG.md
- src/renderer/component/publishForm/internal/bid-help-text.jsx
**Line 33:**
From: `'You are currently editing this claim. If you change the URL, you will need reselect a file.'`
To: `'You are currently editing this claim. If you change the URL, you will need to reselect a file.'`
@ceoger
> Missing Word

- CHANGELOG.md
- package.json
- src/main/index.js
- yarn.lock
Also includes fix from https://github.com/electron/electron/issues/13008#issuecomment-400261941
Tested on Windows/Mac/Linux, don't see any issues. We'll revisit electron 3 when they are out of beta.
> update electron to 2.0.6

- src/renderer/util/contextMenu.js
Breaking change in Electron 2.0
https://github.com/electron/electron/pull/11968
> fix: context menu

- CHANGELOG.md
- package.json
- src/renderer/component/common/form-components/form-field.jsx
- src/renderer/component/common/form-components/form-row.jsx
- src/renderer/component/fileCard/view.jsx
- src/renderer/component/filePrice/view.jsx
- src/renderer/component/fileTile/view.jsx
- src/renderer/component/recommendedContent/index.js
- src/renderer/component/recommendedContent/view.jsx
- src/renderer/modal/modalCreditIntro/view.jsx
- src/renderer/page/file/view.jsx
- src/renderer/scss/_gui.scss
- src/renderer/scss/_vars.scss
- src/renderer/scss/component/_card.scss
- src/renderer/scss/component/_file-list.scss
- src/renderer/scss/component/_form-field.scss
- src/renderer/scss/component/_nav.scss
- src/renderer/scss/component/_toggle.scss
- src/renderer/scss/component/_tooltip.scss
- src/renderer/types/claim.js
- static/themes/dark.css
- yarn.lock
> get recommended videos from search based on title

- package.json
- src/renderer/component/splash/view.jsx
- yarn.lock
> Handle new daemon startup for encryption

- package.json
- src/renderer/component/fileListSearch/view.jsx
- src/renderer/component/fileTile/view.jsx
- src/renderer/component/recommendedContent/view.jsx
- src/renderer/component/wunderbar/index.js
- src/renderer/page/search/view.jsx
- src/renderer/scss/_gui.scss
- src/renderer/scss/_vars.scss
- src/renderer/scss/component/_card.scss
- src/renderer/scss/component/_file-list.scss
- src/renderer/scss/component/_search.scss
- src/renderer/types/claim.js
Depends on https://github.com/lbryio/lbry-redux/pull/67
Defaulting to `search` when entering on the url bar
Making the exact url stand out more on the search page.
> Search ux improvements

- src/renderer/component/recommendedContent/index.js
- src/renderer/component/recommendedContent/view.jsx
- src/renderer/page/file/view.jsx
Show message if no search results are returned for a specific title for related content.
> add message for 0 returned results in related content

- src/renderer/redux/actions/subscriptions.js
This will be looked at again when I work on making new subscription content stand out more but this fix should be fine for now. Don't add the `(1)` to the sidebar for a new piece of content if you are on the subscription page.
> don't show notification for new subscription if on subscription page

- src/renderer/component/recommendedContent/view.jsx
- src/renderer/component/spinner/view.jsx
- src/renderer/scss/component/_spinner.scss
- yarn.lock
> add spinner to related content

- src/renderer/page/help/view.jsx
- src/renderer/scss/component/_table.scss
> add email management link next to email

- CHANGELOG.md
- src/renderer/scss/component/_pagination.scss
- Fix "Go to page" not aligned with page numbers #1877
> Fix pagination spacing and align issues

- src/renderer/redux/reducers/navigation.js
Forgot to do this before merging the user history PR.
> set default path back to discover

- src/renderer/component/fileCard/view.jsx
This gets rid of the icon I forgot to remove when creating a component for history viewing.
> remove position icon from FileCard

- src/renderer/component/walletSendTip/view.jsx
Tip modal now disables send button on all invalid actions and shows feedback.
> refactors and enhances tip modal

- CHANGELOG.md
- src/renderer/component/common/tooltip.jsx
- src/renderer/scss/component/_tooltip.scss
> Smart tooltip

- src/renderer/page/rewards/view.jsx
Moving the reward codes to the bottom of the rewards list.
cc @tzarebczan
> move reward code to bottom of rewards list

- .eslintrc.json
- CHANGELOG.md
- src/renderer/component/transactionListRecent/view.jsx
- src/renderer/component/userHistory/view.jsx
- src/renderer/component/userHistoryItem/view.jsx
- src/renderer/page/help/view.jsx
- src/renderer/redux/actions/navigation.js
- src/renderer/scss/_gui.scss
- src/renderer/scss/_vars.scss
- src/renderer/scss/all.scss
- src/renderer/scss/component/_button.scss
- src/renderer/scss/component/_card.scss
- src/renderer/scss/component/_item-list.scss
- src/renderer/scss/component/_search.scss
- src/renderer/scss/component/_table.scss
- src/renderer/scss/component/_time.scss
- static/themes/dark.css
- Changed text color for easier reading
- Black text is no longer pure black, changed it to #&#xfeff;444
- White text is no longer pure white, changed it to #efefef
- Defaulted `font-family` to `metropolis-medium`
- This was being used in more places than `metropolis-semibold` so it makes sense to default to this
- Down with tables!
- Created new css class family `item-list` for vertical lists of items
- Fixed the issue where the layout was wonky on large screens (due to table weirdness)
- Fixed link issue when navigating to file page
> Style improvements and user history bugs

- CHANGELOG.md
- src/renderer/redux/actions/content.js
> change channel page amount to 48

- package.json
Updates while I was doing a first pass at a video
> Updates for video

- src/renderer/component/rewardSummary/index.js
- src/renderer/page/discover/index.js
- src/renderer/redux/actions/app.js
- src/renderer/redux/actions/content.js
- src/renderer/redux/selectors/content.js
Guess we never started using these from the other modules. They are already included in the other modules so we don't need to update anything.
> use lbryinc/lbry-redux for rewards/featured content

- CHANGELOG.md
- src/renderer/component/rewardListClaimed/view.jsx
- src/renderer/index.js
add Reverse Order & Use System/Location Time/Date
> #1772 - add Reverse Order & Use System/Location Time/Date

- src/renderer/component/fileRender/index.js
- src/renderer/component/fileRender/view.jsx
Small Hacktober fest contribution: Flow type errors #2024
> Fix flow errors of fileRender component

- CHANGELOG.md
- src/renderer/scss/component/_snack-bar.scss
- Obstructive notifications (snackbar) #1974
> Change snackbar notification postion to bottom-left

- package.json
- src/renderer/component/common/markdown-preview.jsx
- src/renderer/component/fileRender/view.jsx
- src/renderer/component/viewers/codeViewer.jsx
- src/renderer/component/viewers/documentViewer.jsx
- src/renderer/component/viewers/docxViewer.jsx
- src/renderer/component/viewers/pdfViewer.jsx
- src/renderer/component/viewers/threeViewer/index.jsx
- yarn.lock
Hacktober fest contribution: Flow type errors #2024
> Fix flow type errors of all viewers

- LICENSE
Solves #2046 
Added Inc to the end of the org name
> Update LICENSE org

- src/renderer/component/button/view.jsx
- src/renderer/component/cardVerify/view.jsx
- src/renderer/component/channelTile/view.jsx
- src/renderer/component/common/form-components/form-field.jsx
Fixed a few flow errors, connected to this issue:
https://github.com/lbryio/lbry-desktop/issues/2024 .
Let me know what you think 🤘
> Fixed flow errors on a few 'view.jsx' files and 'form-field.jsx'

- CHANGELOG.md
- package.json
- src/renderer/component/fileList/index.js
- src/renderer/component/fileList/view.jsx
- src/renderer/page/fileListDownloaded/index.js
- src/renderer/page/fileListDownloaded/view.jsx
- src/renderer/page/fileListPublished/index.js
- src/renderer/page/fileListPublished/view.jsx
- src/renderer/page/subscriptions/index.js
- src/renderer/page/subscriptions/view.jsx
- src/renderer/store.js
- yarn.lock
Re: https://github.com/lbryio/lbry-desktop/issues/1967
> persist fileList sorting

- src/renderer/component/cardVerify/view.jsx
Improved type checking for CardVerify component.
> Improve type checking for card verify

- src/renderer/component/cardVerify/view.jsx
Reverts lbryio/lbry-desktop#2057
This PR was causing the app to crash when the component was rendered. After a quick look it's because it's trying to access methods on the Type variable, instead of the component.
> Revert "Improve type checking for card verify"

- CONTRIBUTING.md
What kind of change does this PR introduce? Typo / grammar fix
> Fix grammatical error

- README.md
> Added release badge to the Readme and updated contributions!

- src/renderer/modal/modalAffirmPurchase/index.js
- src/renderer/modal/modalConfirmTransaction/index.js
- src/renderer/modal/modalError/index.js
- src/renderer/modal/modalFileTimeout/index.js
- src/renderer/modal/modalFirstSubscription/index.js
- src/renderer/modal/modalIncompatibleDaemon/index.js
- src/renderer/modal/modalOpenExternalLink/index.js
- src/renderer/modal/modalRemoveFile/index.js
- src/renderer/modal/modalRevokeClaim/index.js
- src/renderer/modal/modalRewardApprovalRequired/index.js
- src/renderer/modal/modalSendTip/index.js
- src/renderer/modal/modalWelcome/index.js
- src/renderer/page/report/index.js
- src/renderer/page/show/index.js
- src/renderer/page/transactionHistory/index.js
- src/renderer/page/userHistory/index.js
This PR fixes the easy linting errors in the modal and pages folder. The errors were the result of having prettier in the project. This paves the way for more complex fixes.
Issue Number: #2065
Quite a lot of files being changed by running `yarn lint`
Less files changed by running `yarn lint`
> Linting/quick wins modal & pages

- package.json
- src/renderer/constants/claim.js
- src/renderer/page/channel/index.js
- src/renderer/redux/actions/content.js
- src/renderer/redux/actions/subscriptions.js
- src/renderer/redux/selectors/content.js
- yarn.lock
https://github.com/lbryio/lbry-desktop/issues/2059
Channel page displays wrong number of pages to nav to, 
Channel page displays the right number of pages
> Uses a constant for PAGE_SIZE

- CHANGELOG.md
- src/renderer/page/channel/index.js
- src/renderer/page/channel/view.jsx
https://github.com/lbryio/lbry-desktop/issues/2077
- [ X] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ X] I have checked that this PR does not introduce a breaking change
- [ X] Feature
Share used old ViewOnWeb share
Now it uses the modalSocialShare.
> adds shareModal to channel page

- CHANGELOG.md
- flow-typed/i18n.js
- src/renderer/component/common/tooltip.jsx
- src/renderer/component/splash/internal/load-screen.jsx
- src/renderer/component/splash/view.jsx
- src/renderer/scss/component/_button.scss
- src/renderer/scss/component/_load-screen.scss
- src/renderer/types/status.js
- yarn.lock
#2021
If the app can't connect to the daemon, or the daemon returns an error, it sits at `Loading` forever
If the daemon returns an error show an error message with a refresh button, or if the connection times out, show the error page.
> Handle daemon startup errors/timeouts

- CHANGELOG.md
- src/renderer/page/help/view.jsx
- src/renderer/page/report/view.jsx
- [x ] I have checked that this PR does not introduce a breaking change
- [ x] Feature
> Add FAQ and Some Link in Report pages

- src/renderer/component/fileDetails/view.jsx
> update copy - soon TM

- .travis.yml
This PR enables external PRs to build without failing.
> Make external PRs pass travis

- src/renderer/component/address/view.jsx
- src/renderer/component/cardVerify/view.jsx
- src/renderer/component/categoryList/view.jsx
- src/renderer/component/common/file-exporter.jsx
- src/renderer/component/common/icon.jsx
- src/renderer/component/copyableText/view.jsx
- src/renderer/component/fileCard/view.jsx
- src/renderer/component/fileDownloadLink/view.jsx
- src/renderer/component/fileTile/view.jsx
- src/renderer/component/fileViewer/internal/play-button.jsx
- src/renderer/component/header/view.jsx
- src/renderer/component/inviteList/view.jsx
- src/renderer/component/publishForm/view.jsx
- src/renderer/component/rewardTile/view.jsx
- src/renderer/component/socialShare/view.jsx
- src/renderer/component/splash/internal/load-screen.jsx
- src/renderer/component/transactionList/internal/transaction-list-item.jsx
- src/renderer/component/transactionList/view.jsx
- src/renderer/component/transactionListRecent/view.jsx
- src/renderer/component/userVerify/view.jsx
- src/renderer/component/viewOnWebButton/view.jsx
- src/renderer/component/walletAddress/view.jsx
- src/renderer/component/wunderbar/view.jsx
- src/renderer/page/channel/view.jsx
- src/renderer/page/file/view.jsx
- src/renderer/page/help/view.jsx
- src/renderer/page/search/view.jsx
- src/renderer/page/settings/view.jsx
Some constant imports were being named with lowercase and some were uppercase. This PR changes all of them to uppercase and moves the constant import to the top. It also moves type imports above constants.
New import pattern
```
// import types
// import constants
// rest of imports
```
> standardize constant naming/imports

- CHANGELOG.md
Could use 2nd pair of eyes to make sure I didn't miss anything.
> change log cleanup

- package.json
- src/renderer/index.js
- src/renderer/modal/modalRouter/index.js
- src/renderer/redux/actions/app.js
- src/renderer/redux/reducers/app.js
- yarn.lock
- Unsure of the formatting changes. I plan to actually spend some time sometime soon to try and figure out why we see changes sometimes.
This uses a new `lbryinc` module with no references to modals. We can manualy add callbacks to ensure the correct modals are opened after specific events happen.
> remove modals from lbryinc

- CHANGELOG.md
- package.json
- src/renderer/component/channelTile/view.jsx
- src/renderer/index.js
- src/renderer/page/rewards/view.jsx
- src/renderer/page/subscriptions/internal/first-run.jsx
- yarn.lock
A few fixes on 0.26.0. We will release a patch after these are merged.
> 0.26.1 Fixes

- src/renderer/modal/modalFirstSubscription/view.jsx
Is this too wordy? Was thinking we could give a link the edit email preferences but would need to bring in the access token here. P
> update subscription modal text

- CHANGELOG.md
- src/renderer/scss/component/_button.scss
SVG icons seem to have a rendering error that can happen when the app is displayed at different sizes. So far, this has only been seen in the Social Share area.
https://github.com/lbryio/lbry-desktop/issues/2142
This fixes the SVG rendering error that can happen when the app is displayed at different sizes by reducing the `stroke-width` to `1`.
> SVG Rendering Error Fix For Buttons

- src/renderer/component/categoryList/view.jsx
- src/renderer/component/fileCard/view.jsx
- src/renderer/component/walletSendTip/view.jsx
- src/renderer/modal/modal.jsx
- src/renderer/modal/modalConfirmThumbnailUpload/view.jsx
- src/renderer/modal/modalRemoveFile/view.jsx
- src/renderer/page/getCredits/view.jsx
- src/renderer/page/subscriptions/internal/user-subscriptions.jsx
- src/renderer/redux/actions/content.js
- src/renderer/redux/selectors/app.js
- src/renderer/scss/component/_button.scss
- src/renderer/scss/component/_card.scss
- src/renderer/scss/component/_content.scss
- src/renderer/scss/component/_header.scss
- src/renderer/scss/component/_main.scss
- src/renderer/scss/component/_media.scss
- src/renderer/scss/component/_modal.scss
- src/renderer/scss/component/_subscriptions.scss
- src/renderer/scss/init/_gui.scss
- src/renderer/scss/init/_vars.scss
- #2154 
- Lower priority for channel name/date so they aren't the same color as the title
- Lots of spacing consistency improvements (modals will need some work moving forward)
- Add "Invite" link to the left nav
- Add gerbil to the "All caught up" subscriptions view
- Moved related back to right side, tried to use grid to move it below/right with media queries. It's super close but I kept running into a lot of issues.
> Fixes/Changes for 0.27.0

- src/renderer/component/inviteNew/view.jsx
- src/renderer/component/subscribeButton/view.jsx
- src/renderer/component/userEmailNew/view.jsx
- src/renderer/modal/modalAutoUpdateConfirm/view.jsx
- src/renderer/scss/component/_table.scss
Final fixes before the last RC
> Final fixes

- CHANGELOG.md
- src/renderer/component/rewardListClaimed/view.jsx
- src/renderer/scss/component/_table.scss
- [x ] I have checked that this PR does not introduce a breaking change
- [x ] Bugfix
Issue Number: 2196
as described on this issue no 2196 link https://github.com/lbryio/lbry-desktop/issues/2196
i change class from card__content table table--stretch to table table--transactions table--stretch to fixing a issue i filed it a few hours ago based Mr Thomas give me a special job..  and i fix it about a hour later. 1 hour estimated time to find out about how to solve this issue. i hope it will help and solve this issue as described on the no 2196
> fixed issue for jiggytom

- CHANGELOG.md
- src/renderer/component/publishForm/view.jsx
- [x ] I have checked that this PR does not introduce a breaking change
- [x ] This PR introduces breaking changes and I have provided a detailed explanation below
- More language select option when upload file into LBRY Network :)
Edited GUI to show more languages, and tested if this not break chainquery ( test positive it works how it should) 
> More Languages

- yarn.lock
Resolves a memory limit issue in the depedency
> Update to latest lbry-format, fixes encountered memory limit

- src/renderer/scss/component/_content.scss
- src/renderer/scss/component/_main.scss
- src/renderer/scss/component/_markdown-preview.scss
- src/renderer/scss/init/_vars.scss
#2219 
- File page changes layout based on screen width.
- Moves the related content below the video on smaller screens
> fix: responsive layout on file page for #2219

- src/main/startSandbox.js
Should fix the firewall prompt on some machines.
Please make sure this goes into the next RC @seanyesmunt 😃
> Restrict sandbox port to local

- CHANGELOG.md
- src/renderer/component/fileCard/view.jsx
- src/renderer/component/fileTile/view.jsx
- src/renderer/scss/component/_media.scss
> Add Published icon to file{card,tile} for your own files

- src/renderer/redux/actions/content.js
If the SDK produces an uncaught error, show this also. It will help us with debugging.
> fix: better download error message

- yarn.lock
> Fix game unpacking on older Node versions (includes Electron v2)

- src/renderer/component/categoryList/view.jsx
- src/renderer/page/discover/view.jsx
- src/renderer/redux/selectors/content.js
- src/renderer/scss/component/_media.scss
Suggested subscriptions weren't being loaded due to an issue with lazy loading. Now you have to manually pass in `lazyLoad` to the `CategoryList` component for it to work.
> fix: suggested subscriptions not being fetched from lazy load bug

- src/renderer/analytics.js
- src/renderer/component/wunderbar/index.js
- src/renderer/redux/actions/publish.js
- src/renderer/scss/component/_navigation.scss
Should have used `analytics` from the beginning.
> Respect "do not track" setting for search/publish events

- CHANGELOG.md
- src/renderer/scss/component/_button.scss
Issue Number: 2270
Inverse buttons on hover in dark mode can be difficult to read.
Inverse buttons on hover in dark mode now have a higher contrasting background color to improve readability.
> Fix #2270 - Dark mode inverse button css

- package.json
- src/main/Daemon.js
- src/main/index.js
- src/renderer/component/channelTile/view.jsx
- src/renderer/component/fileDownloadLink/view.jsx
- src/renderer/component/fileViewer/view.jsx
- src/renderer/component/splash/view.jsx
- src/renderer/page/show/index.js
- src/renderer/page/show/view.jsx
- src/renderer/redux/actions/app.js
- src/renderer/redux/actions/content.js
- yarn.lock
Includes new shutdown procedure for SDK and a few other fixes around file handling and resolving own channels from file page. Will update changelog shortly..
> 0.32 SDK support + other fixes

- package.json
- src/renderer/component/common/form-components/form-field.jsx
- src/renderer/component/fileListSearch/index.js
- src/renderer/component/fileListSearch/view.jsx
- src/renderer/component/fileTile/view.jsx
- src/renderer/component/searchOptions/index.js
- src/renderer/component/searchOptions/view.jsx
- src/renderer/component/wunderbar/index.js
- src/renderer/component/wunderbar/view.jsx
- src/renderer/constants/icons.js
- src/renderer/page/search/index.js
- src/renderer/page/search/view.jsx
- src/renderer/scss/component/_button.scss
- src/renderer/scss/component/_form-field.scss
- src/renderer/scss/component/_media.scss
- src/renderer/scss/component/_search.scss
- src/renderer/scss/init/_gui.scss
- src/renderer/scss/init/_mixins.scss
- src/renderer/store.js
- yarn.lock
- Adds filters for search
- Removes `resultCount` from settings reducer, not it lives in search
> feat: search filters

- package.json
- src/renderer/component/channelTile/view.jsx
- src/renderer/component/common/form-components/form-field.jsx
- src/renderer/component/fileActions/view.jsx
- src/renderer/component/fileList/view.jsx
- src/renderer/component/inviteNew/view.jsx
- src/renderer/component/publishForm/internal/license-type.jsx
- src/renderer/component/publishForm/internal/name-help-text.jsx
- src/renderer/component/publishForm/view.jsx
- src/renderer/component/searchOptions/view.jsx
- src/renderer/component/selectChannel/view.jsx
- src/renderer/component/transactionList/view.jsx
- src/renderer/component/userHistory/view.jsx
- src/renderer/component/userHistoryItem/view.jsx
- src/renderer/component/walletSendTip/view.jsx
- src/renderer/modal/modalRemoveFile/view.jsx
- src/renderer/modal/modalRewardCode/view.jsx
- src/renderer/page/channel/view.jsx
- src/renderer/page/help/view.jsx
- src/renderer/page/settings/view.jsx
- src/renderer/scss/component/_button.scss
- src/renderer/scss/component/_channel.scss
- src/renderer/scss/component/_form-field.scss
- src/renderer/scss/component/_header.scss
- src/renderer/scss/component/_media.scss
- src/renderer/scss/init/_gui.scss
- yarn.lock
Not as bad as it looks, mostly ensuring all inputs have a `name` attribute so labels work as expected.
Minor alignment changes
> ui cleanup

- package.json
- webpack.base.config.js
- yarn.lock
> Prune packages

- src/ui/analytics.js
We don't need an email, knowing they have one is enough
> update: remove email for mixpanel data collection

- src/ui/index.js
- webpack.base.config.js
So we can use a local instance of lbryweb api
> allow overriding the web daemon

- package.json
- src/ui/page/file/index.js
- src/ui/page/file/view.jsx
- src/ui/store.js
- yarn.lock
For https://github.com/lbryio/lbry-desktop/issues/1952
> add viewcount stats for your published content

- package.json
- src/ui/component/fileViewer/view.jsx
- src/ui/page/file/view.jsx
- src/ui/redux/actions/content.js
- yarn.lock
We don't need to, and it takes up space.
> don't call file_list on web

- src/ui/component/errorBoundary/view.jsx
Dependent on https://github.com/lbryio/internal-apis/pull/826
> report errors through internal-apis

- .eslintrc.json
- src/ui/component/common/file-selector.jsx
- src/ui/component/common/unsupported-on-web.jsx
- src/ui/component/fileViewer/internal/player.jsx
- src/ui/component/publishForm/view.jsx
- src/ui/modal/modalRouter/view.jsx
- src/ui/page/report/view.jsx
- src/ui/page/settings/view.jsx
- webpack.web.config.js
A few messages for unsupported pages and file types
> add unsupported messages

- webpack.electron.config.js
> add IS_WEB global for electron build

- src/ui/component/fileViewer/internal/player.jsx
Needs testing, the only real change was removing the 300 ms timeout. I think the new version of chrome handles videos better.
> fix video stutters on desktop

- src/ui/analytics.js
Still in debug mode to see if this actually works once it's deployed
> add google analytics

- src/ui/component/firstRun/view.jsx
- src/ui/page/help/view.jsx
- src/ui/page/rewards/view.jsx
- src/ui/page/settings/view.jsx
- src/ui/page/transactionHistory/view.jsx
Change copy + add unsupported message on Rewards/Transactions.
> lbry.tv minor edits

- src/ui/page/transactionHistory/view.jsx
Transaction lists are now a consistent size.
Issue Number: #2431
> makes transaction lists consistent

- src/ui/component/wunderbar/index.js
- src/ui/component/wunderbar/view.jsx
Enables a showSnackBar that was previously erroring.
> displays snackbar instead of greenscreen on bad url

- src/ui/component/socialShare/view.jsx
share url previously encoded for all shares now only encoded for facebook and twitter
> only percent-encodes share urls for twitter and facebook

- flow-typed/publish.js
- src/ui/redux/actions/publish.js
> add replace to publish flags

- CHANGELOG.md
- src/ui/component/subscribeSuggested/view.jsx
- src/ui/redux/selectors/subscriptions.js
- src/ui/util/shuffleArray.js
If you have a better way to making sure the page doesn't render, you can try that..this worked for me.
> feat: shuffle suggested

- package.json
- src/ui/component/channelContent/view.jsx
- src/ui/component/common/form-components/form-field.jsx
- src/ui/component/common/paginate.jsx
- src/ui/component/fileViewer/internal/player.jsx
- src/ui/component/navigationHistory/view.jsx
- src/ui/component/navigationHistoryRecent/view.jsx
- src/ui/component/publishForm/view.jsx
- src/ui/component/transactionList/internal/transaction-list-item.jsx
- src/ui/component/transactionList/view.jsx
- src/ui/component/transactionListRecent/view.jsx
- src/ui/component/userVerify/view.jsx
- src/ui/component/walletBalance/view.jsx
- src/ui/page/settings/view.jsx
- src/ui/page/show/view.jsx
- src/ui/scss/component/_button.scss
- src/ui/scss/component/_card.scss
- src/ui/scss/component/_form-field.scss
- src/ui/scss/component/_markdown-editor.scss
- src/ui/scss/component/_media.scss
- src/ui/scss/component/_placeholder.scss
- src/ui/scss/component/_search.scss
- src/ui/scss/component/_table.scss
- src/ui/scss/init/_gui.scss
- src/ui/scss/init/_mixins.scss
- src/ui/scss/init/_vars.scss
- Style consistency with inputs/cards to match new button styles
- More noticeable hover effect on cards/tiles
- Channels with only one page are now being fetched correctly
> General fixes

- .gitignore
- .tx/config
- src/ui/i18n/index.js
> I18n fixes

- src/ui/component/viewers/videoViewer.jsx
They won't be tracked for pilot program on api side. Will merge once green (where's that plugin when you need it?)
Issue Number:
> Add back lbry.tv view analytics

- src/ui/component/channelAbout/view.jsx
- src/ui/component/common/markdown-preview-internal.jsx
- src/ui/component/externalLink/view.jsx
- src/ui/scss/component/_media.scss
- Render Markdown in channel descriptions #2506
- Missing external links on channel page #2519
- Channel description word cutoff #2485
> Minor fixes for channel-about page

- src/ui/component/router/view.jsx
open.lbry.com/?discover would fail
Issue Number:
> fix ?discover navigation

- src/ui/component/viewers/videoViewer.jsx
- src/ui/index.jsx
> update api url

- package.json
- src/ui/index.jsx
Reverts lbryio/lbry-desktop#2528
> Revert "app uses auth token header"

- src/ui/component/userVerify/view.jsx
Since we've moved away from speaking with users in the channel, I've reworded the page to reflect what they would see.
> Reword Verification Page to reflect changes

- src/ui/component/externalLink/view.jsx
- src/ui/component/fileDownloadLink/index.js
- src/ui/component/fileDownloadLink/view.jsx
- src/ui/component/wunderbar/index.js
- src/ui/modal/modalAutoGenerateThumbnail/view.jsx
- src/ui/modal/modalOpenExternalResource/view.jsx
- src/ui/util/uri.js
Issue Number: #2583 #2549 
no more displays warning message when opening files on owned claims and lbry related links.
> Minor fixes

- package.json
- src/ui/component/claimListDiscover/view.jsx
- src/ui/component/claimUri/index.js
- src/ui/component/claimUri/view.jsx
- src/ui/page/channel/view.jsx
- src/ui/page/file/index.js
- src/ui/page/file/view.jsx
- src/ui/scss/component/_channel.scss
- src/ui/scss/component/_claim-list.scss
- src/ui/scss/component/_main.scss
- src/ui/scss/component/_media.scss
- static/locales/en.json
- yarn.lock
- a couple overflow fixes
- infinite scroll not resetting when changing filters
> use short_url for channels and files and a couple fixes

- src/ui/component/commentCreate/view.jsx
- src/ui/page/file/view.jsx
- src/ui/scss/component/_badge.scss
- src/ui/scss/component/_card.scss
- static/locales/en.json
not much to see here, though this does use `markdown-preview` perhaps inappropriately
> comment intro

- src/ui/component/cardVerify/view.jsx
- src/ui/component/userEmailNew/view.jsx
- src/ui/component/userVerify/view.jsx
- src/ui/page/auth/view.jsx
- src/ui/page/rewards/view.jsx
- src/ui/scss/component/menu-button.scss
- static/locales/en.json
- static/locales/id.json
- Fixed the issue where you would be redirected back to the auth page before verifying your email
- Changed some of the language to be more clear.
> improve email collection experience (slightly)

- src/ui/component/page/view.jsx
- src/ui/modal/modalAutoUpdateConfirm/view.jsx
- src/ui/modal/modalAutoUpdateDownloaded/view.jsx
- static/locales/en.json
- [x ] Code style update (formatting)
Issue Number:#2290
> fix #2290: Update => Upgrade

- src/ui/modal/modalRemoveFile/view.jsx
- src/ui/util/use-persisted-state.js
- static/locales/en.json
- [ x] Bugfix
- [ x] Feature
Issue Number:#2132
> fix #2132: Remember ModalRemoveFile check boxes

- package.json
- src/ui/component/claimPreview/index.js
- src/ui/component/claimPreview/view.jsx
- src/ui/index.jsx
- src/ui/reducers.js
Filters out discovery previews based on file list_filtered api.
> Filter preview

- package.json
- yarn.lock
This hash supports filtering.
Disregard if another fixes branch covers this.
> updates lbryinc hash for filtering 

- src/ui/component/comment/view.jsx
- src/ui/component/commentsList/view.jsx
- src/ui/scss/component/_comments.scss
adds channel link
adds support for newline
better handles long channel names
> improves comment display

- src/ui/page/search/view.jsx
> Add loading animation to search page

- src/ui/analytics.js
- src/ui/component/app/view.jsx
- src/ui/component/tagsSelect/view.jsx
- src/ui/page/tags/view.jsx
~Still need to test this, I believe a setting needs to change in GA so we can see this events.~
Working. Merging so we can start getting data asap
> send ga event for tag follow/unfollow and also for user id

- package.json
- src/ui/component/channelEdit/view.jsx
- src/ui/component/tagsSelect/view.jsx
- static/locales/en.json
depends on https://github.com/lbryio/lbry-redux/pull/168
> adds tags to channelUpdate

- src/ui/i18n/index.js
Seems to work locally when building.
> Fix language setting

- src/platforms/web/server.js
- static/index.html
Issue Number: #2410
Shared `lbry.tv` links are plain.
Shared `lbry.tv` links are enriched with metadata to make them more appealing to scrollers.
> Dynamic meta tags for content

- src/ui/component/claimPreview/view.jsx
- src/ui/component/previewLink/view.jsx
- src/ui/scss/component/_markdown-preview.scss
- static/locales/en.json
Claim preview in description not working #2656
> Fix claim preview on description (markdown)

- src/ui/component/claimTags/view.jsx
- src/ui/component/comment/view.jsx
- src/ui/component/expandable/view.jsx
- src/ui/scss/component/_expandable.scss
comments are only expandable if larger than 120 rect.height
expandable checks the useRect ref height before inserting itself
Originally I implemented the useRect in the Comment component but it seems to work contained in Expandable.
For now, I commented out Expandable border-bottom style - I don't think expandable should be in charge of that sort of thing.
> comments and expandable changes

- package.json
- src/ui/analytics.js
- src/ui/component/blockButton/index.js
- src/ui/component/blockButton/view.jsx
- src/ui/component/channelContent/index.js
- src/ui/component/channelContent/view.jsx
- src/ui/component/channelThumbnail/view.jsx
- src/ui/component/claimList/view.jsx
- src/ui/component/claimListDiscover/index.js
- src/ui/component/claimListDiscover/view.jsx
- src/ui/component/claimPreview/index.js
- src/ui/component/claimPreview/view.jsx
- src/ui/component/common/icon-custom.jsx
- src/ui/component/router/view.jsx
- src/ui/component/subscribeButton/view.jsx
- src/ui/constants/icons.js
- src/ui/constants/pages.js
- src/ui/page/channel/index.js
- src/ui/page/channel/view.jsx
- src/ui/page/file/view.jsx
- src/ui/page/listBlocked/index.js
- src/ui/page/listBlocked/view.jsx
- src/ui/page/settings/index.js
- src/ui/page/settings/view.jsx
- src/ui/reducers.js
- src/ui/scss/component/_channel.scss
- src/ui/scss/component/_claim-list.scss
- src/ui/store.js
- yarn.lock
Users can block channels and visit their blocked channels through settings.
Images on blocked channels are obscured
channel ids are filtered in discovery claim search
> Channel filter mm

- src/platforms/web/fs.js
- src/ui/component/app/index.js
- src/ui/component/app/view.jsx
- webpack.web.config.js
Also fixes the web build after we moved the publish code to lbry-redux
> Send auth token to lbry.tv once email is verified

- src/ui/scss/component/_markdown-preview.scss
Markdown formatting incorrect in some tables #2712
> Fix table display issue

- static/locales/en.json
- static/locales/pl.json
> Fix typos "Rewawrds" to "rewards"

- src/ui/component/claimListDiscover/view.jsx
Provides links to trending/everyone and discover channels if followed channels is selected when no channels are followed
> Emptystate for channels you follow

- static/locales/id.json
> fixed typos

- package.json
- src/ui/modal/modalAutoGenerateThumbnail/index.js
- src/ui/modal/modalConfirmThumbnailUpload/index.js
Thumbnail upload was failing because `path` wasn't being passed in
> [patch] fix: thumbnail upload

- src/ui/component/blockButton/index.js
- src/ui/component/blockButton/view.jsx
Issue Number:
users can block their own channels using block button
does not show up block button for channels owned by users
> do not show block button on own channels

- src/ui/component/claimListDiscover/view.jsx
- src/ui/i18n/index.js
> I18n trending fix

- package.json
- src/platforms/electron/createWindow.js
- static/locales/en.json
- yarn.lock
Not sure where that xhr in the yarn lock came from.
> Fixes cold app starts with querystrings

- src/ui/component/channelContent/view.jsx
- src/ui/component/claimLink/view.jsx
- src/ui/component/claimPreview/view.jsx
- src/ui/page/channel/index.js
- src/ui/page/channel/view.jsx
- src/ui/page/show/view.jsx
Adds awareness to the channel page and also makes the channel level check on the file page.
Fixes: https://github.com/lbryio/lbry-desktop/issues/2802
> feat: channel level blacklisting

- src/ui/redux/actions/content.js
fixes: https://github.com/lbryio/lbry-desktop/issues/2797
> fix: instant purchase on 0.1 or less LBC fee

- src/ui/page/channel/index.js
- src/ui/page/channel/view.jsx
fixes: https://github.com/lbryio/lbry-desktop/issues/1397
> feat: add tip/supports to channels

- src/ui/redux/actions/subscriptions.js
> fix: sub autodownloads

- src/ui/component/router/view.jsx
- src/ui/page/fourOhFour/index.js
- src/ui/page/fourOhFour/view.jsx
- static/locales/en.json
WIP? It was suggested to add <FileRender /> with our 404 URL.
> 404 Page beta

- src/ui/component/selectThumbnail/index.js
- src/ui/component/selectThumbnail/view.jsx
Issue Number: #2531
video needs to be selected in order to take a new snapshot
video snapshot is enabled without selecting the video file
I tackled this once with #2543 which turned out to be troublesome (sorry about the trouble) I think this one is quite the fix.
> support thumbnail section from video on edits

- src/ui/component/publishForm/view.jsx
- src/ui/component/tagsSearch/view.jsx
Issue Number: #2798 
new tags get added without being trimmed off spaces
tags search input gets trimmed yet allows multiple spaces between words
> fix blank tags when tags search field is empty

- src/ui/page/listBlocked/view.jsx
> format string for translation

- src/ui/component/rewardLink/view.jsx
> semi crude reward display fix

- src/ui/component/fileViewer/view.jsx
> fix: don't popout for images

- src/ui/page/settings/view.jsx
> fix: add support setting to web

- src/ui/component/app/index.js
- src/ui/component/app/view.jsx
- src/ui/component/header/index.js
- src/ui/component/header/view.jsx
- src/ui/scss/component/_snack-bar.scss
very slight improvement instead of having it under the header
> move upgrade message to bottom right of screen

- package.json
- src/ui/component/common/paginate.jsx
- src/ui/component/router/view.jsx
- src/ui/page/fileListDownloaded/index.js
- src/ui/page/fileListDownloaded/view.jsx
- src/ui/page/fileListPublished/index.js
- src/ui/page/fileListPublished/view.jsx
- static/app-strings.json
- yarn.lock
responds to https://github.com/lbryio/lbry-desktop/pull/2914
> Pagination hell rebase

- package.json
- src/ui/page/channel/index.js
- src/ui/page/channel/view.jsx
- src/ui/page/file/view.jsx
- src/ui/scss/component/_channel.scss
- static/app-strings.json
- yarn.lock
> feat: sub counts on own channels

- src/ui/component/rewardListClaimed/view.jsx
> i18n change

- src/ui/component/videoDuration/view.jsx
Was going to rename the component, but not important for now.
> fix: audio duration

- src/ui/component/header/view.jsx
- src/ui/redux/actions/settings.js
- src/ui/redux/reducers/settings.js
Fixed calls for translation system. For header it's fixed Light/Dark theme option (now it translates to Jasny/Ciemny) , and also fixes light/dark option in settings menu.
> Theme setting translation fix

- src/ui/page/account/view.jsx
Issue Number: [#2024](https://github.com/lbryio/lbry-desktop/issues/2024)
`Props` was improperly used as the type for the function signature even though there is no declared type of Props.
`any` is used in its place as a proper flow type for props in this case
> fixes flow error on account/view page

- src/ui/scss/component/_main.scss
this should ensure that pages are always full height, giving the full dragging area for the file viewer, even on short pages
> Full view height

- src/ui/redux/reducers/settings.js
> Added Turkish language

- src/platforms/web/server.js
- [x ] Other - Please describe: Area Viewer
Issue Number: #2824
Added summary twitter image card as issues no #2824 said and also Added fb app id like LBRY.com repository on basic.php
> fix og image and added fbapp id like on LBRY.com

- src/ui/component/channelEdit/view.jsx
- static/app-strings.json
> Fix channel edit cancel

- static/app-strings.json
removes characters that were causing translations to not work
> remove evil symbols

- CONTRIBUTING.md
A long document on Contributing
Table of Contents for easier navigation
> Add Table of Contents in CONTRIBUTING.md

- CHANGELOG.md
Issue Number:
This is a PR for updating the CHANGELOG for my other PR, #2959
> Update CHANGELOG.md to include #2959

- src/ui/component/publishText/view.jsx
Fixed calls for translation strings
No catching string
Now strings load in json file
> Fixed calls for Simple/Advance editor option

- src/platforms/web/server.js
- static/index-web.html
> Metadata fixes

- src/platforms/electron/index.js
- src/ui/component/fileViewerInitiator/view.jsx
- src/ui/component/wunderbar/internal/autocomplete.jsx
- src/ui/redux/actions/file.js
- src/ui/util/query-params.js
> feat: minor code refactor

- src/ui/component/fileActions/view.jsx
New route: https://lbry.com/dmca/116d62d14d8efc311e1f8a9de92dcbc17deb259a
> Fix report button to use new route

- src/ui/component/fileViewerInitiator/view.jsx
> chore: minor tweak

- src/ui/component/claimList/view.jsx
- src/ui/scss/component/_search.scss
Was the wrong color after changing the background-color
> fix: loading indicator on claimList

- .tx/config
- src/ui/modal/modalWalletEncrypt/view.jsx
- static/app-strings.json
> make "I Understand" acknowledgement work for i18n case

- src/ui/component/comment/view.jsx
Comment message renders as plain text.
- Markdown formatting (bold / italic text, links, blockquotes...)
- Channel mentions
- Preview lbry urls
> Markdown preview for comments

- src/ui/scss/component/_markdown-preview.scss
-  Code tag not formatting content on markdown preview #3027
- Add inline code styles
- Add dark theme for code tag ( code blocks / inline code )
> Fix inline code styles and formatting on mardown preview

- CHANGELOG.md
- src/ui/util/remark-lbry.js
- static/app-strings.json
- Markdown rendering issues with lbry:// previews #2928
> Fix markdown rendering issues with lbry urls

- src/ui/component/fileDetails/view.jsx
- src/ui/component/splash/view.jsx
- src/ui/component/tagsSelect/view.jsx
- src/ui/component/youtubeTransferStatus/view.jsx
- src/ui/index.jsx
- src/ui/redux/actions/content.js
- src/ui/redux/actions/subscriptions.js
- src/ui/scss/component/_file-render.scss
- src/ui/scss/init/_gui.scss
- src/ui/util/detect-typing.js
> Fix typos on code comments

- src/platforms/web/server.js
- src/ui/component/claimPreview/view.jsx
- src/ui/page/show/view.jsx
> fixes #2877 and #2841

- CHANGELOG.md
- src/ui/component/claimLink/view.jsx
- src/ui/scss/component/_button.scss
Missing tooltip on channel mention #3036
> Add missing tooltip on channel links

- build/afterSignHook.js
- electron-builder.json
- package.json
- yarn.lock
> forgot to merge this into master

- CHANGELOG.md
- src/ui/component/fileViewer/view.jsx
- src/ui/util/full-screen.js
Fix gap between video player and background #3025
> Fix gap between video player and background 

- README.md
> Added Direct Download Badge for Windows, MacOS and Linux

- src/ui/component/common/form-components/form-field-price.jsx
Issue Number: https://github.com/lbryio/lbry-desktop/issues/1674
`form-field-price` number input changes value on scroll when focused
`form-field-price` no longer changes number value by scroll wheel when focused
I didnt take either of the suggestions in the PR to use a tooltip with key bind `ctrl` and mouse wheel or confirmation alert because I found the user experience to be a little odd with that.  However, if it is desired let me know and I will implement that instead.
> Added prevent default to formfield price onWheel

- src/ui/analytics.js
- src/ui/component/selectChannel/view.jsx
- src/ui/redux/actions/publish.js
Depends on https://github.com/lbryio/internal-apis/pull/1053
> removes redundant logPublish calls

- src/ui/page/settings/view.jsx
- static/app-strings.json
I would expect labels to be consistent across the app, so I'm adding missed full stops.
> added missing dots for labels to be consistent across the app

- README.md
Documentation: Added Logo at Center, Text-Center Alignment,URL addition in Readme.md
Issue Number:
Just Simple Text was Written
Added new Formatting in the documentation, added logo at the center, as well as center alignment of text including the addition of new 33 lines of code
> Documentation: Important changes in Readme.md

- src/ui/constants/search.js
- src/ui/page/channel/view.jsx
> Content search onchange now triggers search.

- src/platforms/web/server.js
Issue Number: #2449 
Right now, if you go to the url beta.lbry.tv/lbry://name the app will crash.
Redirected to the valid url beta.lbry.tv/name
> Redirected to the valid url

- config.js
- src/ui/component/app/index.js
- src/ui/component/app/view.jsx
- src/ui/component/userSignIn/view.jsx
- src/ui/redux/actions/app.js
- src/ui/util/lbrytv.js
- src/ui/util/saved-passwords.js
- webpack.base.config.js
- webpack.web.config.js
Still requires more testing I would say. It is currently deployed to `dev.lbry.tv`.
> Sync on lbry.tv

- static/app-strings.json
Removes invalid closing bracket from the app-strings file
> Fixes breaking app-strings json file

- src/ui/component/walletSendTip/view.jsx
Issue Number: #2024
Flow error in the modified file.
Flow success in the file.
> Fixed flow error in walletSendTip/view.jsx

- src/ui/component/publishForm/view.jsx
- src/ui/component/tagsSearch/view.jsx
- src/ui/component/tagsSelect/view.jsx
- src/ui/util/set-operations.js
- static/app-strings.json
OnSelect now takes an array of tag objects to solve multi tag update race contition.
https://github.com/lbryio/lbry-desktop/issues/3073 re: comma-separated tags
https://github.com/lbryio/lbry-desktop/issues/3054 re: suggesting followed tags
https://github.com/lbryio/lbry-desktop/issues/2983 re: not recommending tags already chosen
> solves 3 issues with tags

- README.md
- src/platforms/electron/index.js
- src/platforms/electron/startSandbox.js
- src/platforms/web/stubs.js
> Multiple minor edits

- CHANGELOG.md
- CONTRIBUTING.md
> Minor spelling errors corrected

- src/ui/component/header/index.js
- src/ui/component/header/view.jsx
- src/ui/redux/actions/app.js
- src/ui/util/saved-passwords.js
A few reports that the current fix was pretty confusing.
> fix: only log users out with "x"/"lbry" button click when they are on the password prompt

- src/ui/component/settingLanguage/view.jsx
french (fr), slovak (sk), turkish (tr), and chinese (zh)
Issue Number:
https://github.com/lbryio/lbry-desktop/issues/3170
> Added new languages

- package.json
- src/platforms/electron/unpackByOutpoint.js
- src/ui/redux/actions/content.js
- static/app-strings.json
- yarn.lock
Reverts lbryio/lbry-desktop#3179
> Revert "maint: support 0.45 SDK"

- src/platforms/web/server.js
@seanyesmunt this is some copy changes for #3176 which I assigned to you
> part of revised meta tags (#3176)

- src/ui/component/channelEdit/view.jsx
this page isn't that bad and this message detracts from using it
> remove channel edit notice

- ui/scss/init/_type.scss
this was not tested, but may improve page paint speed a bit https://web.dev/font-display
> do not block text rendering while loading fonts

- electron/index.js
placing a file named upgradeDisabled in 
`/opt/LBRY/resources/static/` disables updates
> feat: disable app updates when file exists in /static

- package.json
- static/app-strings.json
- ui/component/channelEdit/view.jsx
- ui/component/claimList/view.jsx
- ui/component/claimListDiscover/view.jsx
- ui/component/publishName/view.jsx
- ui/component/walletSendTip/view.jsx
- ui/constants/claim.js
- yarn.lock
- improve claim search failure
- minimum bid amounts
- fix vanity url on publish takeover
> fix: SDK bump + small fixes

- ui/component/fileViewer/view.jsx
- ui/scss/component/_content.scss
- ui/scss/component/_file-render.scss
- ui/scss/init/_vars.scss
this will always fix the player to fit in the browser viewport
I was unable to test on floating player due to separate bug with floating player placement :/
> always fit video player

- ui/modal/modalRemoveFile/view.jsx
Addresses https://github.com/lbryio/lbry-desktop/issues/3232
> Fix file delete messaging

- ui/component/button/view.jsx
- ui/effects/use-combined-refs.js
We may be able to try putting the tooltips back in due to this change.
> fixes button hover

- ui/constants/supported_languages.js
> Added Malayalam (ml) and Serbian (sr) language

- static/app-strings.json
- ui/modal/modalFirstSubscription/index.js
- ui/modal/modalFirstSubscription/view.jsx
I thought it seemed better to inline the "Sign in to..." in the <p> text, but put "Update email preferences" next to the "Got it" button.
> update first subscription modal

- static/app-strings.json
- ui/component/channelEdit/view.jsx
- ui/component/selectThumbnail/view.jsx
- ui/modal/modalDownloading/view.jsx
To support https://lbry.com/faq/thumbnails-and-covers (should we hyperlink this on these 2 pages?)
And help: https://github.com/lbryio/lbry-desktop/issues/3113
> fix: minor copy edits

- babel.config.js
- lbrytv/package.json
- lbrytv/webpack.config.js
- package.json
- ui/component/sideBar/view.jsx
- yarn.lock
Didn't include these changes in #3267 ... 🤦‍♂
> I'm not used to working on Windows

- ui/component/webUploadList/internal/web-upload-item.jsx
- ui/component/webUploadList/view.jsx
- ui/scss/component/_claim-list.scss
- ui/scss/component/_form-field.scss
- ui/scss/component/_snack-bar.scss
- ui/scss/themes/dark.scss
> Redesign fixes

- ui/redux/reducers/settings.js
> fix auto language support

- ui/component/channelAbout/view.jsx
- ui/component/comment/view.jsx
- ui/component/fileDetails/view.jsx
- ui/component/previewLink/view.jsx
- ui/component/viewers/documentViewer.jsx
- Few major sites do this, and our entire ethos is treating our users like adults.
- Malicious claims can still be flagged and filtered
> We're adults

- CHANGELOG.md
- ui/component/channelThumbnail/view.jsx
- ui/component/comment/index.js
- ui/component/comment/view.jsx
- ui/component/commentsList/view.jsx
- ui/scss/component/_channel.scss
- ui/scss/component/_comments.scss
- ui/scss/component/_markdown-preview.scss
Adds comment thumbnails
Issue Number: #3107
No thumbnails on comments
Thumbnails on comments & `ChannelThumbnail` allows for default, anonymous thumbnails now if nothing is passed in.
> Comment thumbnails

- ui/constants/supported_languages.js
- [] Code style update (formatting)
> Sort alphabetical + new languages

- ui/component/app/view.jsx
- ui/component/youtubeWelcome/index.js
- ui/component/youtubeWelcome/view.jsx
- ui/constants/modal_types.js
- ui/modal/modalRouter/view.jsx
- ui/modal/modalYoutubeWelcome/index.js
- ui/modal/modalYoutubeWelcome/view.jsx
- ui/scss/component/_card.scss
- ui/scss/init/_gui.scss
copy TBD
https://lbryians.slack.com/archives/CMJQ4JB1N/p1575523422005200
> add youtube welcome message

- ui/scss/component/_file-render.scss
This should improve #3252 but I'm still tweaking some things. Merging this now because it fixes a lot for mobile
> always show play button when video is paused

- lbrytv/webpack.config.js
- static/app-strings.json
- ui/component/claimPreview/view.jsx
- ui/page/show/index.js
- ui/page/show/view.jsx
Fixes:  https://github.com/lbryio/lbry-desktop/issues/1719 / https://github.com/lbryio/lbry-desktop/issues/1719
Just having an issue on the file page of own content + blocked.
> fix: blocked content handling of own content

- ui/scss/themes/dark.scss
There has been a decent amount of feedback about the green we had on dark mode. People don't seem to like it. This tones it down a bit and makes it a bit more consistent.
> darker inputs on dark mode and tone down the green a bit

- ui/scss/themes/dark.scss
Reverts lbryio/lbry-desktop#3379
Guess this needs a bit more testing. Reverting while I mess around with it more
> Revert "darker inputs on dark mode and tone down the green a bit"

- static/app-strings.json
- ui/component/settingWalletServer/internal/inputRow.jsx
- ui/component/settingWalletServer/view.jsx
- ui/component/splash/view.jsx
- ui/scss/component/_form-field.scss
- ui/scss/component/section.scss
- ui/scss/init/_gui.scss
- ui/store.js
> when this is merged the wallet server selection UI will be cleaned up

- lbrytv/src/routes.js
- ui/component/embedArea/view.jsx
- ui/util/lbrytv.js
> Use custom endpoint for lbry.tv embeds

- ui/component/channelEdit/view.jsx
At least add this hint until we can fix the issue. Feel free to change the copy.
> Fix: add channel edit notice

- ui/constants/supported_languages.js
> Added Marathi (mr), Panjabi (pa), and Swedish (sv)

- ui/page/search/view.jsx
was:
my cool channel => my-coolchannel
now:
my cool channel => my-cool-channel
> replace spaces globally on publish suggest on search

- package.json
- ui/component/channelAbout/view.jsx
- ui/component/channelDiscussion/view.jsx
- ui/component/common/icon-custom.jsx
- ui/component/header/index.js
- ui/component/header/view.jsx
- ui/component/sideNavigation/view.jsx
- ui/constants/icons.js
- ui/page/channel/view.jsx
- ui/scss/component/_button.scss
- ui/scss/component/_channel.scss
- ui/scss/component/_claim-list.scss
- ui/scss/component/tabs.scss
- yarn.lock
> Clean up navigation after recent changes

- electron/index.js
- [x ] Bugfix
Issue Number: #3349
All CSS styling is incorrect. The colours, brightness and contrast of videos and images are also rendered incorrectly making them not very pleasant to look at.
See the images in #3349 for example.
The styling, videos and images are rendered correctly.
> Force color profile to render correct colors

- lbrytv/src/routes.js
- static/app-strings.json
- ui/component/button/view.jsx
- ui/component/fileActions/view.jsx
- ui/component/fileDownloadLink/index.js
- ui/component/fileDownloadLink/view.jsx
- ui/util/lbrytv.js
> enable downloads on lbry.tv

- ui/component/common/tabs.jsx
Crash on opening channel page in desktop app
> adds null check to tabsRect

- ui/component/youtubeTransferStatus/view.jsx
Could not get it to reflect locally using yarn:dev for some reason.
> Pending transfer message

- ui/component/claimList/view.jsx
- ui/component/claimListDiscover/view.jsx
- ui/component/claimPreview/index.js
- ui/component/claimPreview/view.jsx
- ui/component/fileViewerInitiator/view.jsx
- ui/effects/use-get-thumbnail.js
your rejection is requested
see a clean/fast way to get this working on desktop?
> dirty, unacceptable image rendering

- package.json
- ui/component/invited/view.jsx
- ui/component/rewardTile/view.jsx
- ui/component/sideNavigation/view.jsx
- ui/modal/modalSetReferrer/index.js
- ui/modal/modalSetReferrer/view.jsx
provide for resetting referral set error state
improve reward buttons
show setReferrer errors in modal
> improve referrals

- package.json
- ui/analytics.js
- ui/component/viewers/videoViewer/index.js
- ui/component/viewers/videoViewer/view.jsx
- yarn.lock
will send the following:
sendGaEvent('Media', 'BufferTimestamp', claimId, currentTime); 
* reports every buffering event and its timestamp
sendGaEvent('Media', 'Started', claimId, duration);
* reports how delayed the start of a video is
> send events when video buffers

- lbrytv/src/html.js
- package.json
- static/index-web.html
- ui/component/commentCreate/view.jsx
- yarn.lock
I made some improvements to the way we inject metadata to the html before serving. 
It's still pretty complex, but it's moving in the right direction. I think it's good enough for now 🤷‍♂
> Invite metadata

- static/app-strings.json
- ui/analytics.js
- ui/component/viewers/videoViewer/view.jsx
These have to be timing events in order to be useful.
> send player events as timing events

- static/app-strings.json
- ui/component/transactionListTable/internal/transaction-list-item.jsx
- [ x] Bugfix
Issue Number: https://github.com/lbryio/lbry-desktop/issues/3505
The tooltip in remove icon from transaction list item show abandon claim in his text
Now show abandon support
> edit abandon claim to abandon support

- ui/component/claimListDiscover/view.jsx
Would never hit the 2nd condition.
> fix: fix hack on New + following/tags page

- ui/redux/selectors/content.js
> make sure the app  doesn't autoplay paid content, channels, or content from blocked channels

- ui/component/router/view.jsx
- ui/page/embedWrapper/view.jsx
- ui/scss/component/_embed-player.scss
Fixes the embed link at https://lbry.com/news/210-Malabarize-se
> fix encoded urls getting 404'd

- ui/component/channelThumbnail/view.jsx
- ui/component/header/view.jsx
- ui/scss/component/_header.scss
- ui/scss/component/menu-button.scss
https://www.reddit.com/r/lbry/comments/ew7fny/accessibility_of_the_new_version/
> add aria-label and alt messages

- CHANGELOG.md
- ui/component/comment/index.js
- ui/component/comment/view.jsx
- ui/component/commentsList/index.js
- ui/component/commentsList/view.jsx
- ui/component/common/icon-custom.jsx
- ui/component/common/icon.jsx
- ui/constants/icons.js
- ui/scss/component/_comments.scss
- ui/scss/themes/dark.scss
- ui/scss/themes/light.scss
Adds the ability for users to update & delete their comments.
- Two new SVG icon are introduced of three circles aligned horizontally and vertically.
- A new modal is created for the user to confirm before deleting a comment
- Overall overhaul for the `Comment` component
This PR depends on [#259](https://github.com/lbryio/lbry-redux/pull/259) for redux to work properly.
> Adds the ability for users to update & delete comments

- ui/component/invited/view.jsx
also changed default redirect to home instead of discover
> make invite redirect to channel if appropriate

- static/app-strings.json
- ui/component/fileDownloadLink/view.jsx
works on dev
Does have a screen flash the way I implemented it, not sure if it did before.
> reenable downloads

- ui/util/context-menu.js
Issue Number: #3603 
Context menu is blocked for all platforms
Context menu is blocked only for the electron platform
Used the most up-voted solution here: https://github.com/electron/electron/issues/2288
Preview: https://spee.ch/5/lbry-context-menu
> Fixes #3603. Allow browser context menu

- .sentryclirc
- lbrytv/webpack.config.js
- package.json
- ui/analytics.js
- ui/component/errorBoundary/view.jsx
- ui/index.jsx
- ui/scss/init/_gui.scss
- webpack.base.config.js
- webpack.electron.config.js
- yarn.lock
> setup for sentry

- .sentryclirc
- lbrytv/webpack.config.js
- package.json
- ui/analytics.js
- ui/component/errorBoundary/view.jsx
- ui/index.jsx
- ui/scss/init/_gui.scss
- webpack.base.config.js
- webpack.electron.config.js
- yarn.lock
Reverts lbryio/lbry-desktop#3622
> Revert "setup for sentry"

- CHANGELOG.md
- ui/component/claimPreview/view.jsx
- ui/scss/component/_claim-list.scss
Reverts lbryio/lbry-desktop#3627
> Revert "Fixes #3200 Claim previews right-clickable"

- CHANGELOG.md
- ui/component/claimPreview/view.jsx
- ui/component/claimPreviewTile/view.jsx
- ui/scss/component/_claim-list.scss
> Revert "Fixes #3200 Claim previews right-clickable - original author (michaeltintiuc)"

- CHANGELOG.md
- ui/component/claimPreview/view.jsx
- ui/component/claimPreviewTile/view.jsx
- ui/scss/component/_claim-list.scss
> Fixes #3200 Right click claims

- ui/component/common/markdown-preview-internal.jsx
> fix lbry:// links on desktop

- ui/component/router/view.jsx
Switching to window.location was a test that didn't go to well
> switch back to withRouter for app router redirects

- lbrytv/src/html.js
- ui/component/viewers/videoViewer/index.js
- ui/component/viewers/videoViewer/view.jsx
- ?autoplay=true param
- mute on autoplay
- thumb poster on embeds (unless autoplay)
- twitter player card for audio too
> embed improvements

- package.json
- ui/scss/themes/dark.scss
- yarn.lock
> higher contrast for toggle inputs

- ui/constants/supported_languages.js
Issue Number:
https://github.com/lbryio/lbry-desktop/issues/3533
> Added Danish, Romanian, and Urdu

- ui/component/common/card.jsx
- ui/component/publishForm/view.jsx
- ui/component/userVerify/view.jsx
Could not get help text to show.
> Copy changes for first run and publish

- ui/constants/supported_languages.js
added javanesse as new language
> added javanese

- CHANGELOG.md
- ui/component/channelForm/view.jsx
- ui/component/commentCreate/view.jsx
- ui/component/selectChannel/view.jsx
Drops support for anonymous comments
> Removes ability to create comments anonymously

- package.json
adds ability to serve in production mode using "yarn run:web-server"
> add production script

- ui/component/claimListDiscover/view.jsx
- ui/page/channelsFollowingDiscover/view.jsx
- ui/page/tags/view.jsx
> add claim_type support to tags page

- CHANGELOG.md
- static/app-strings.json
- ui/component/common/help-link.jsx
- ui/component/router/view.jsx
- ui/component/walletBalance/index.js
- ui/component/walletBalance/view.jsx
- ui/page/backup/index.js
- ui/page/backup/view.jsx
- ui/page/help/view.jsx
I took what jessop had and added the second part of it
> add wallet sync message on wallet page

- ui/redux/actions/app.js
preference stored in a different shape from how settings_set expects
> properly transforms wallet server preference

- static/app-strings.json
- ui/page/settings/view.jsx
- ui/redux/actions/app.js
So some app users aren't stuck with broken preferences
> comment out broken preference sync code

- ui/component/userVerify/view.jsx
> Add "skip" card at bottom of rewards validation page

- ui/constants/supported_languages.js
based on my observation on transifex
> added more languages

- ui/scss/component/_file-render.scss
- ui/scss/component/nag.scss
Issue Number:
Nag Banner is hidden by code viewer
Nag Banner isn't hidden by code viewer
> keep nag banner on top

- ui/component/claimListDiscover/view.jsx
- ui/component/userChannelFollowIntro/view.jsx
- ui/page/channelsFollowingDiscover/view.jsx
- ui/page/discover/view.jsx
Also tried to fix some prop type issues
> hide claimList filters on channel discovery and sign in pages

- static/app-strings.json
- ui/component/claimListDiscover/view.jsx
- ui/constants/claim_search.js
add image, bodel, binary
fix duration reset/disable
> claim search options tweaks

- ui/component/publishForm/view.jsx
- ui/component/publishFormErrors/index.js
- ui/component/publishFormErrors/view.jsx
- ui/component/publishName/view.jsx
- ui/component/userFirstChannel/view.jsx
Changes channel default bid and fixes publish form errors around bid amount.
> fixes: default channel bid and publish form

- static/app-strings.json
- ui/component/publishFile/view.jsx
> suggest 720p

- ui/component/commentCreate/index.js
- ui/component/commentCreate/view.jsx
set to top channel if not already persisted
> do not set comment channel anonymous,

- ui/constants/supported_languages.js
Based on Translators LBRY Discord channel and LBRY zone on Transifex
- [ x] Feature
> Added Ukrainian to supported language

- CHANGELOG.md
- package.json
- yarn.lock
> Electron builder and SDK update

- static/app-strings.json
- ui/component/publishForm/view.jsx
- ui/component/tag/view.jsx
- ui/component/tagsSearch/view.jsx
- ui/component/tagsSelect/view.jsx
- ui/scss/component/_tags.scss
disables tag entry after 5
updates card instructions to enter up to 5
> limit tags on publishing to 5

- flow-typed/web-file.js
- static/app-strings.json
- ui/component/publishFile/view.jsx
- ui/scss/init/_gui.scss
- ui/scss/themes/dark.scss
- ui/scss/themes/light.scss
increase lbrytv limit until tv transcoding
warn about bitrate
warn about strange types
more reliably convey size limit message
update faq link for publishing
> Publish messages

- CHANGELOG.md
- package.json
> Bump version, changelog

- ui/modal/modalCommentAcknowledgement/view.jsx
Removed outdated point regarding the ability to delete/edit comments and replaced it with an at least somewhat relevant point.
Issue Number: [#3802 ](https://github.com/lbryio/lbry-desktop/issues/3802)
Comment Acknowledgement modal includes incorrect information.
Comment Acknowledgement modal now includes more relevant information, scrapping the incorrect information.
I did not make changes to the "Alpha" phrasing as I am not sure if comments are still in alpha, beta, etc.
> Updated commentAcknowledgement modal.

- ui/component/publishAdditionalOptions/view.jsx
- [x ] I have checked that this PR does not introduce a breaking change
- [ x] Feature
Issue Number: https://github.com/lbryio/lbry-desktop/issues/3698
> add finnish and kannada to publish form

- ui/page/channelsFollowingDiscover/view.jsx
- ui/page/home/view.jsx
Also updated broken links on the homepage
> Fix/add links to ClaimTilesDiscover grid sections

- ui/component/viewers/appViewer/view.jsx
Until we can better secure javascript execution in the apps.
> temporarily disable lbry-format apps

- ui/component/app/view.jsx
- ui/component/common/nag.jsx
- ui/scss/component/nag.scss
> add error nag when api performance is degraded

- ui/component/userSignIn/view.jsx
- ui/component/userVerify/view.jsx
- ui/effects/use-persisted-state.js
- ui/page/rewards/view.jsx
- yarn.lock
- If a user clicks "skip" on the rewards validation screen, don't show it again on future sign-ins
- If a user has verified their identity but still not rewards eligible, don't show the rewards validation screen on future sign-ins.
There was an issue with `usePersistedState` where when a value was set that caused the component to be un-rendered, it wouldn't actually write the value to local storage. Now it's being written right when the value is set.
> Improve reward issues on sign-in

- ui/component/userSignIn/view.jsx
- ui/component/userVerify/view.jsx
- ui/effects/use-persisted-state.js
- ui/page/rewards/view.jsx
- yarn.lock
Reverts lbryio/lbry-desktop#3809
> Revert "Improve reward issues on sign-in"

- .flowconfig
- lbrytv/setup/publish.js
- ui/component/channelEdit/index.js
- ui/component/channelEdit/view.jsx
- ui/component/common/form-components/form-field.jsx
- ui/component/header/index.js
- ui/component/header/view.jsx
- ui/component/selectAsset/view.jsx
- ui/component/walletSendTip/view.jsx
- ui/constants/modal_types.js
- ui/modal/modalRouter/view.jsx
- ui/modal/modalSendTip/index.js
- ui/modal/modalSignOut/index.js
- ui/modal/modalSignOut/view.jsx
- ui/page/channel/view.jsx
Fixes:
#3295 
#3653
#3392
#3296
> Bug roundup

- package.json
- static/app-strings.json
- ui/component/app/index.js
- ui/component/app/view.jsx
- ui/component/claimListDiscover/index.js
- ui/component/claimListDiscover/view.jsx
- ui/component/claimTilesDiscover/view.jsx
- ui/component/publishForm/view.jsx
- ui/component/tagsSearch/view.jsx
- ui/component/tagsSelect/view.jsx
- ui/component/userChannelFollowIntro/index.js
- ui/component/userChannelFollowIntro/view.jsx
- ui/component/userSignIn/view.jsx
- ui/component/userTagFollowIntro/index.js
- ui/component/userTagFollowIntro/view.jsx
- ui/constants/claim_search.js
- ui/page/channelsFollowingDiscover/view.jsx
- ui/page/discover/view.jsx
- ui/page/tagsFollowing/view.jsx
- ui/page/tagsFollowingManage/view.jsx
- ui/scss/component/_claim-search.scss
- yarn.lock
User prompted to select tags after email verified.
After tags, user can select channels to follow. 
Back button added on channels.
Tags filter added to claim search.
Still a bit janky.
> select tags before channels and filter channels by tag

- ui/component/app/view.jsx
- ui/util/fetch.js
will move this code into `lbrytv/` folder when I add the gerbil
Just adding this now because it's better than what we have
> add 10 second timeout to lbrytv status call

- static/app-strings.json
- ui/modal/modalRepost/view.jsx
- [ x] Code style update (formatting)
> Fix Wording "sucessfully" to "successfully" on LBRY Desktop App

- ui/util/lbrytv.js
- ui/util/saved-passwords.js
Reverts lbryio/lbry-desktop#3836
> Revert "Localized player urls for lbry.tv"

- .eslintrc.json
- .flowconfig
- lbrytv/component/nag-data-collection.jsx
- lbrytv/component/nag-degraded-performance.jsx
- lbrytv/effects/use-degraded-performance.js
- static/app-strings.json
- ui/component/app/view.jsx
`"degraded"` => show nag at bottom
`"down"` => show full screen gerbil
`anything else` => assume "ok"
> add gerbil when apis are down and move components into lbrytv/

- package.json
- ui/analytics.js
- ui/redux/actions/app.js
- yarn.lock
Requires https://github.com/lbryio/lbryinc/pull/85
> Pass `trending_algorithm` to GA

- package.json
- ui/component/claimList/view.jsx
- ui/component/claimListDiscover/view.jsx
- ui/component/fileActions/view.jsx
- ui/constants/claim_search.js
- ui/page/discover/index.js
- ui/page/discover/view.jsx
- yarn.lock
A few parts of this are minorly wonky but I felt like I was working with what was already there
> display repost counts on file pages, link to all reposts

- static/app-strings.json
- ui/index.jsx
Forgot to remove this when I ripped out keytar
> fix desktop login

- ui/analytics.js
- ui/index.jsx
> send a few metrics to lbrytv api

- ui/component/claimListDiscover/view.jsx
- ui/page/discover/index.js
- ui/page/discover/view.jsx
The reposted claim was never resolved before
> fix reposts page when navigating directly by url

- ui/page/home/view.jsx
> only show content for tags on the homepage

- static/app-strings.json
- ui/redux/actions/settings.js
ffmpeg find was not updating status, so seemed unavailable even when effective.
> gets status after ffmpeg find
